#!/usr/bin/env python3
"""
Translate lasagna_npcs.txt English dialogue to LATAM Spanish (informal tu).
Only translates text inside mes "...", select("..."), and npctalk "..." strings.
Preserves NPC names in brackets [Name], color codes ^RRGGBB, variables, functions, script logic.
Uses single quotes instead of double quotes inside translated strings.
"""

import re
import sys

# Build a comprehensive translation dictionary
# Key: English text, Value: Spanish translation
TRANSLATIONS = {
    # === Vigilante Ajegna (lines 23-96) ===
    "Hey, newbie! Get over here!": "Oye, novato! Ven aqui!",
    "Come on over here! Click me, quick!": "Ven aqui! Hazme clic, rapido!",
    "Huh? I doubt you're from Far-Star.": "Eh? Dudo que seas de Far-Star.",
    "I get it! You're from the New Continent, aren't you?": "Ya entiendo! Eres del Nuevo Continente, verdad?",
    "If you're planning to cross that ridge, I wouldn't recommend it.": "Si planeas cruzar esa cordillera, no te lo recomiendo.",
    "Why don't you just return to your village from here?": "Por que no regresas a tu aldea desde aqui?",
    "Oh, there you go!": "Oh, aqui estas!",
    "You can talk to others in the same way you just spoke to me.": "Puedes hablar con otros de la misma forma en que me hablaste a mi.",
    "^4d4dffBasically, you talk by left-clicking the mouse button while hovering the cursor over an NPC.": "^4d4dffBasicamente, hablas haciendo clic izquierdo con el mouse mientras pasas el cursor sobre un NPC.",
    "Left-click the mouse button to talk with an NPC, move about and attack a target.^000000": "Haz clic izquierdo para hablar con un NPC, moverte y atacar un objetivo.^000000",
    "Good work crossing over the mountain, newbie.": "Buen trabajo cruzando la montana, novato.",
    "Just like yourself, there are a bunch of people who are crossing this mountain range these days to reach the ^4d4dffNew Continent^000000.": "Al igual que tu, hay un monton de gente que esta cruzando esta cordillera estos dias para llegar al ^4d4dffNuevo Continente^000000.",
    "Honestly, I was surprised, too.": "Honestamente, yo tambien me sorprendi.",
    "I never imagined even in my wildest dreams that there would be any other continent other than ^4d4dffMidgard^000000 or ^4d4dffFar-Star,^000000 which we live in.": "Jamas imagine, ni en mis suenos mas locos, que existiria otro continente aparte de ^4d4dffMidgard^000000 o ^4d4dffFar-Star,^000000 donde vivimos.",
    "That explains the slew of Dorams, who simply wander about, in ^4d4dffLasagna^000000, which was nothing but a fishing village in the border area.": "Eso explica la cantidad de Dorams que simplemente deambulan por ^4d4dffLasagna^000000, que no era mas que un pueblo pesquero en la zona fronteriza.",
    "What's worse is that the Dorams who come from outside of Lasagna would often cause problems. This is really causing a headache for the Vigilante Corp.": "Lo peor es que los Dorams que vienen de fuera de Lasagna a menudo causan problemas. Esto le esta dando un dolor de cabeza al Cuerpo de Vigilantes.",
    "A Vigilante's job is to assist the Dorams who are in the New Continent expedition, in addition to maintaining public order, so please help.": "El trabajo de un Vigilante es ayudar a los Dorams que estan en la expedicion al Nuevo Continente, ademas de mantener el orden publico, asi que por favor ayuda.",
    "Do you see the Doram over there? He's ^4d4dffAglio^000000. He'll let you in on some useful stuff. Go meet the guy.": "Ves al Doram de alla? El es ^4d4dffAglio^000000. Te contara cosas utiles. Ve a conocerlo.",
    "I should welcome the new Dorams coming in here.": "Deberia darle la bienvenida a los nuevos Dorams que llegan aqui.",
    "^4d4dffAglio^000000 will let you in on more details. He's right over there.": "^4d4dffAglio^000000 te dara mas detalles. Esta justo por alla.",
    "Aglio is one of the very, I mean, very good Doram in the Farfalle Vigilante Corp, so watch and learn!": "Aglio es uno de los muy, digo, muy buenos Doram en el Cuerpo de Vigilantes Farfalle, asi que observa y aprende!",
    "If you have any questions, don't hesitate to ask him.": "Si tienes alguna pregunta, no dudes en preguntarle.",
    "Don't be a stranger even when you're out on the New Continent!": "No seas un extrano incluso cuando estes en el Nuevo Continente!",
    "The Lasagna Port is over that way!": "El Puerto de Lasagna esta por alla!",
    "Don't tell me you're here because you didn't know that.": "No me digas que estas aqui porque no lo sabias.",

    # === Applicant Paul (lines 98-172) ===
    "~Shrieks~ You startled me!": "~Grita~ Me asustaste!",
    "A human? Wow, what an odd-looking one!": "Un humano? Vaya, que aspecto tan extrano!",
    "So, you're that adventurer Doram, eh?": "Asi que tu eres ese Doram aventurero, eh?",
    "Hey, what do you think?": "Oye, que opinas?",
    "You agree with me about damage, right? STR comes first!": "Estas de acuerdo conmigo sobre el dano, verdad? STR va primero!",
    "You need to be on the offense to win the battle.": "Necesitas estar a la ofensiva para ganar la batalla.",
    "^4d4dffThe quickest way to boost ATK is to boost STR^000000!": "^4d4dffLa forma mas rapida de aumentar ATK es aumentar STR^000000!",
    "...Reckless attacks are of no use!": "...Los ataques temerarios no sirven de nada!",
    "No attack will work if you miss the target!": "Ningun ataque funcionara si fallas el objetivo!",
    "So, ^4d4dffyou need to boost DEX first to increase Accuracy^000000.": "Entonces, ^4d4dffnecesitas aumentar DEX primero para incrementar la Precision^000000.",
    "It doesn't matter how strong you are. You need to hit the target first!": "No importa que tan fuerte seas. Necesitas golpear al objetivo primero!",
    "I refuse to use martial arts willy-nilly as you do!": "Me niego a usar artes marciales a lo loco como tu!",
    "^4d4dffI'm using the summoning skill by boosting INT for magical attacks!^000000": "^4d4dffEstoy usando la habilidad de invocacion aumentando INT para ataques magicos!^000000",
    "Pfff! What's wrong with using the summoning skills to complement the physical skills?": "Pfff! Que tiene de malo usar las habilidades de invocacion para complementar las habilidades fisicas?",
    "Are you implying that I haven't got a clue?": "Estas insinuando que no tengo ni idea?",
    "...That's not what I meant! This cat's brains must be full of fat!": "...Eso no es lo que quise decir! El cerebro de este gato debe estar lleno de grasa!",
    "...Stop fighting, you two!": "...Dejen de pelear, ustedes dos!",
    "Hey, there. Newcomer.": "Oye, tu. Recien llegado.",
    "You can ask me if there is something you'd like to know.": "Puedes preguntarme si hay algo que te gustaria saber.",
    "He might tell you What's good about being a Vigilante, so go ahead and ask him.": "El podria decirte que tiene de bueno ser un Vigilante, asi que ve y preguntale.",
    "He'll prove that I was right, after all.": "El probara que yo tenia razon, despues de todo.",
    "So, is this all about boosting your abilities based on your competencies?": "Entonces, todo esto se trata de aumentar tus habilidades segun tus competencias?",
    "Come to think of it, there is a ^4d4dffhypnotist^000000 in the village.": "Ahora que lo pienso, hay un ^4d4dffhipnotista^000000 en la aldea.",
    "^4d4dffYou can reset skills and statuses through a hypnotist^000000. Just so you know that you can.": "^4d4dffPuedes reiniciar habilidades y estados a traves de un hipnotista^000000. Solo para que sepas que puedes.",
    "You, dimwit! Nothing beats damage! You should boost your STR first!": "Tu, tonto! Nada supera el dano! Deberias aumentar tu STR primero!",
    "You have no idea! DEX comes first if you want your attack to be successful!!": "No tienes ni idea! DEX va primero si quieres que tu ataque sea exitoso!!",

    # === Vigilante Gnocchi (lines 175-243) ===
    "Ahem! This is like a gateway to the Far-Star Continent.": "Ejem! Esto es como una puerta de entrada al Continente Far-Star.",
    "No more humans are allowed!": "No se permiten mas humanos!",
    "Do you happen to know why they are making so much noise?": "Sabes por que estan haciendo tanto ruido?",
    "So they were having an animated discussion over status.": "Asi que estaban teniendo una discusion animada sobre estados.",
    "Do you need more explanation on the status?": "Necesitas mas explicacion sobre los estados?",
    "Yes.": "Si.",
    "No.": "No.",
    "Up to level 49, the village hypnotist will reset your stats and skills.": "Hasta el nivel 49, el hipnotista de la aldea reiniciara tus stats y habilidades.",
    "This will let you practice and experiment which will help find the path that works for you.": "Esto te permitira practicar y experimentar, lo que te ayudara a encontrar el camino que funcione para ti.",
    "Press the ^4d4dffAlt+Q^000000 keys to view your physical stats.": "Presiona las teclas ^4d4dffAlt+Q^000000 para ver tus stats fisicos.",
    "Calibration is also available depending on your equipment.": "La calibracion tambien esta disponible dependiendo de tu equipo.",
    "Let me explain the statuses in detail.": "Dejame explicarte los estados en detalle.",
    "^4d4dffSTR means strength^000000. It ^4d4dffboosts physical attacks^000000.": "^4d4dffSTR significa fuerza^000000. ^4d4dffAumenta los ataques fisicos^000000.",
    "^4d4dffVIT is vitality which indicates health^000000. This is what ^4d4dffboosts your overall HP^000000.": "^4d4dffVIT es vitalidad que indica salud^000000. Es lo que ^4d4dffaumenta tu HP general^000000.",
    "^4d4dffAGI means agility^000000. It affects ^4d4dffevasion and attack speed^000000.": "^4d4dffAGI significa agilidad^000000. Afecta la ^4d4dffevasion y velocidad de ataque^000000.",
    "^4d4dffINT refers to intelligence and MATK means magical attack^000000. If your skills are centered on magic, you must boost INT first and foremost.": "^4d4dffINT se refiere a inteligencia y MATK significa ataque magico^000000. Si tus habilidades se centran en la magia, debes aumentar INT ante todo.",
    "^4d4dffDEX is related with dexterity and accuracy^000000.": "^4d4dffDEX esta relacionado con la destreza y la precision^000000.",
    "You can both quicken casting speed and boost the accuracy of your attacks.": "Puedes tanto acelerar la velocidad de casteo como aumentar la precision de tus ataques.",
    "^4d4dffLUK means luck; the more luck you have, the higher your critical hit rate (CRI) becomes^000000.": "^4d4dffLUK significa suerte; mientras mas suerte tengas, mayor sera tu tasa de golpe critico (CRI)^000000.",
    "It also means you can dodge an enemy's attack more easily.": "Tambien significa que puedes esquivar el ataque de un enemigo mas facilmente.",
    "If you want to boost your physical attacks, focus on STR. If what you want is magical attacks, go for INT. Got it?": "Si quieres aumentar tus ataques fisicos, enfocate en STR. Si lo que quieres son ataques magicos, ve por INT. Entendido?",
    "DEX is highly crucial in the early stages because it is what boosts Accuracy.": "DEX es muy importante en las etapas tempranas porque es lo que aumenta la Precision.",
    "This can be a difficult concept to get, so you should try boosting this and that to find your own way.": "Este puede ser un concepto dificil de entender, asi que deberias intentar aumentar esto y aquello para encontrar tu propio camino.",
    "I wish you godspeed!": "Te deseo buena suerte!",

    # === Vigilante Aglio (lines 245-538) ===
    "Oh! You must be the famous strangers from the New Continent, eh?": "Oh! Ustedes deben ser los famosos extranjeros del Nuevo Continente, eh?",
    "Out-of-towner Dorams abound in this place, I definitely don't want any more of them.": "Los Dorams foraneos abundan en este lugar, definitivamente no quiero mas de ellos.",
    "Wouldn't they be surprised to see you guys?": "No se sorprenderian de verlos?",
    "Moreover, it's dangerous to cross the mountain ridge.": "Ademas, es peligroso cruzar la cordillera.",
    "This is for your own good. Just go back to where you come from.": "Es por tu propio bien. Solo regresa de donde viniste.",
    "- Hold on a second here!! -": "- Espera un momento!! -",
    "- You have too many items. -": "- Tienes demasiados objetos. -",
    "- That means you can no longer receive any items. -": "- Eso significa que ya no puedes recibir mas objetos. -",
    "- Free up some space -": "- Libera algo de espacio -",
    "- and try again. -": "- e intentalo de nuevo. -",
    "Oh, hello?": "Oh, hola?",
    "I'm Aglio. I'm going to be your attendant from this point on.": "Soy Aglio. Voy a ser tu acompanante de ahora en adelante.",
    "Consider it a privilege.": "Consideralo un privilegio.",
    "Because I'm one of the ace members of the Farfalle Vigilante Corp.": "Porque soy uno de los miembros estrella del Cuerpo de Vigilantes Farfalle.",
    "I'm sure I can be of help for just about anything.": "Estoy seguro de que puedo ayudarte con casi cualquier cosa.",
    "First off, let's see what you've got.": "Primero, veamos que tienes.",
    "Hang on. Let me check if you are properly equipped first.": "Espera. Dejame revisar si estas bien equipado primero.",
    "You don't want to fight with bare hands, now do you?": "No quieres pelear con las manos vacias, verdad?",
    "^4d4dffYou should equip your weapons.^000000": "^4d4dffDeberias equipar tus armas.^000000",
    "^4d4dffYou can use or equip an item by double-clicking it.": "^4d4dffPuedes usar o equipar un objeto haciendo doble clic en el.",
    "Open or close the item window with the shortcut key [Alt+E].": "Abre o cierra la ventana de objetos con la tecla de atajo [Alt+E].",
    "^4d4dffCheck out your equipped items easily by pressing the shortcut key [Alt+Q].": "^4d4dffRevisa tus objetos equipados facilmente presionando la tecla de atajo [Alt+Q].",
    "Simply drag the appropriate items to the area you'd like to equip.^000000": "Simplemente arrastra los objetos apropiados al area donde quieras equiparlos.^000000",
    "Now that we've checked your weapons, why don't we take a look at a target to hunt?": "Ahora que revisamos tus armas, por que no echamos un vistazo a un objetivo para cazar?",
    "Do you see those ^4d4dffEggring^000000 wandering around over there?": "Ves esos ^4d4dffEggring^000000 deambulando por alla?",
    "They may look dumb but they can be a real pain in the butt. They will pick up and eat anything they come across.": "Pueden parecer tontos pero pueden ser un verdadero dolor de cabeza. Recogen y comen cualquier cosa que encuentren.",
    "They are a dime a dozen around here, so they're a great target for the novice Dorams to test their worth on.": "Hay un monton de ellos por aqui, asi que son un gran objetivo para que los Dorams novatos demuestren su valor.",
    "Go ahead and get rid of some ^4d4dffEggring^000000, will you? ^4d4dffThree^000000 should do for now.": "Adelante, elimina algunos ^4d4dffEggring^000000, si? ^4d4dffTres^000000 deberian ser suficientes por ahora.",
    "You have accepted a quest from an NPC.": "Has aceptado una mision de un NPC.",
    "^4d4dffCheck out the quest details by pressing the shortcut key [Alt+U],^000000 or through the Quest icon found in the menu tray.^000000": "^4d4dffRevisa los detalles de la mision presionando la tecla de atajo [Alt+U],^000000 o a traves del icono de Mision en la bandeja del menu.^000000",
    "Alright, to warm up, go and eliminate ^4d4dffthree Eggrings^000000.": "Bien, para calentar, ve y elimina ^4d4dfftres Eggrings^000000.",
    "What do they look like? You'll see just by glancing at them right away. You can't miss them!": "Como se ven? Los veras con solo echarles un vistazo. No puedes no verlos!",
    "They abound around here. Go get them, tiger!": "Abundan por aqui. Ve por ellos, tigre!",
    "Whoa, you're good!": "Vaya, eres bueno!",
    "I should've seen that in you because crossing the mountains is never easy.": "Deberia haberlo visto en ti porque cruzar las montanas nunca es facil.",
    "I believe you can do very well, even in a new location.": "Creo que puedes hacerlo muy bien, incluso en un lugar nuevo.",
    "Here, take this.": "Toma, ten esto.",
    "I brought some snacks for you.": "Te traje unos bocadillos.",
    "It's cool apple juice!": "Es un jugo de manzana frio!",
    "Click the 'Item' icon in the basic information window found in the upper left-hand side to open the item window.": "Haz clic en el icono de 'Objeto' en la ventana de informacion basica en la parte superior izquierda para abrir la ventana de objetos.",
    "The item window comes with four tabs.": "La ventana de objetos tiene cuatro pestanas.",
    "Items are automatically placed into the Item, Gear and Etc tabs, depending on their type.": "Los objetos se colocan automaticamente en las pestanas Objeto, Equipo y Etc, segun su tipo.",
    "To use or equip an item, ^4d4dffdouble-click that item^000000, or": "Para usar o equipar un objeto, ^4d4dffhaz doble clic en ese objeto^000000, o",
    "^4d4dffdrag it to the Equipment window^000000 to use.": "^4d4dffarrastralo a la ventana de Equipo^000000 para usarlo.",
    "Or, simply drag the appropriate items to the area you'd like to equip.^000000": "O simplemente arrastra los objetos apropiados al area donde quieras equiparlos.^000000",
    "If you want to ^4d4dffsee a detailed description for each item, right-click that item.^000000": "Si quieres ^4d4dffver una descripcion detallada de cada objeto, haz clic derecho en ese objeto.^000000",
    "This shows the detailed description of the selected item.": "Esto muestra la descripcion detallada del objeto seleccionado.",
    "^4d4dffRight-click an item to view its detailed description.^000000": "^4d4dffHaz clic derecho en un objeto para ver su descripcion detallada.^000000",
    "^4d4dffIf a player wishes, they can use the social options such as Booking, Party, or Guild. Here, they join a party or request transactions.^000000": "^4d4dffSi un jugador lo desea, puede usar las opciones sociales como Reserva, Grupo o Gremio. Aqui pueden unirse a un grupo o solicitar transacciones.^000000",
    "Well, then. ^4d4dffGo ahead and drink the apple juice that I gave you.^000000": "Bien, entonces. ^4d4dffAdelante, bebe el jugo de manzana que te di.^000000",
    "How do you like it? It's cool, sweet, and just good, right?": "Que te parecio? Esta frio, dulce y simplemente bueno, verdad?",
    "I would've given you more if I had any, but...no.": "Te hubiera dado mas si tuviera, pero...no.",
    "Oh, right! I'll give you this, too.": "Oh, cierto! Te dare esto tambien.",
    "It'll restore your stamina if you take it when you're tired.": "Restaurara tu energia si lo tomas cuando estes cansado.",
    "Also, I'll give you a new staff.": "Tambien te dare un nuevo baculo.",
    "It should be better than that sprout you brought with you.": "Deberia ser mejor que ese brote que trajiste contigo.",
    "Now you know how to equip an item because I already explained it to you, don't you?": "Ahora sabes como equipar un objeto porque ya te lo explique, verdad?",
    "I'll direct you to the village, now.": "Te dirigire a la aldea ahora.",
    "....Aglioooooo!!": "....Aglioooooo!!",
    "Oh, my days! You startled me!": "Ay, cielos! Me asustaste!",
    "What's up?": "Que pasa?",
    "Oh, you're the youngest kitten of the tool merchant!": "Oh, eres el gatito mas joven del comerciante de herramientas!",
    "it's dangerous around here. What brought you all this way?": "Es peligroso por aqui. Que te trajo hasta aca?",
    "Oh, actually...I lost it!": "Oh, en realidad...lo perdi!",
    "There was a box!": "Habia una caja!",
    "I was supposed to give it to Haru.": "Se suponia que debia darsela a Haru.",
    "I was just trying to hang out for a while, but I fell down!": "Solo estaba tratando de pasear un rato, pero me cai!",
    "Please find it, Aglio!": "Por favor encuentrala, Aglio!",
    "Or, I'm going to be in trouble!": "O voy a estar en problemas!",
    "So, you were running an errand to deliver a box to Healer Haru.": "Entonces, estabas haciendo un mandado para entregar una caja a la Sanadora Haru.",
    "But you fell down while hanging out for a while and lost the box. Is that it?": "Pero te caiste mientras paseabas un rato y perdiste la caja. Es eso?",
    "Yes, sir!": "Si, senor!",
    "You're so good at summing it up!": "Eres muy bueno resumiendo!",
    "Alright. You just return to your village.": "Bien. Tu solo regresa a tu aldea.",
    "I'll see what I can do. You return home and wait.": "Vere que puedo hacer. Regresa a casa y espera.",
    "One more thing. Just drop that habit of acting like you're naive in front of the strangers!": "Una cosa mas. Deja esa costumbre de actuar como si fueras ingenuo frente a los extranjeros!",
    "Come on...I'm the cutest, youngest kitten from Lasagna!": "Vamos...soy el gatito mas lindo y joven de Lasagna!",
    "Anyway, I hope you help me by finding that box. Please.": "De todos modos, espero que me ayudes encontrando esa caja. Por favor.",
    "You know that I love you, don't you?": "Sabes que te quiero, verdad?",
    "Just go, already!": "Ya vete!",
    ".....": ".....",
    "........~Sighs deeply~...": "........~Suspira profundamente~...",
    "Well, there's no choice, then.": "Bueno, no hay opcion entonces.",
    "I think you can step up and handle it this time.": "Creo que puedes dar un paso al frente y encargarte esta vez.",
    "it's a relief to have a competent Doram with me.": "Es un alivio tener a un Doram competente conmigo.",
    "My guess is that an ^4d4dffEggring must've eaten that box.^000000": "Mi suposicion es que un ^4d4dffEggring debe haberse comido esa caja.^000000",
    "Keep hunting Eggrings until you find that box...": "Sigue cazando Eggrings hasta que encuentres esa caja...",
    "Let's go!": "Vamos!",
    "^4d4dffYou accepted a new quest from Vigilante Aglio.": "^4d4dffAceptaste una nueva mision de Vigilante Aglio.",
    "Check out the details of the quest in the Quest Information Window.": "Revisa los detalles de la mision en la Ventana de Informacion de Misiones.",
    "Press the ^4d4dffAlt + U^000000 shortcut key to open the Quest Information Window.": "Presiona la tecla de atajo ^4d4dffAlt + U^000000 para abrir la Ventana de Informacion de Misiones.",
    "You must remember Eggrings, you've hunted them before, haven't you?": "Debes recordar a los Eggrings, los has cazado antes, no?",
    "They are easily spotted around here.": "Son faciles de encontrar por aqui.",
    "I have no idea which Eggring swallowed the box, but, you'll find it once you start hunting them.": "No tengo idea de cual Eggring se trago la caja, pero la encontraras una vez que empieces a cazarlos.",
    "Well, then. I'm counting on you.": "Bueno, entonces. Cuento contigo.",
    "Ohh...! This is the box!": "Ohh...! Esta es la caja!",
    "You can bring this when you visit the village!": "Puedes llevar esto cuando visites la aldea!",
    "^4d4dffWhen you arrive in the village, find the tool shop first and deliver this box.^000000": "^4d4dffCuando llegues a la aldea, encuentra la tienda de herramientas primero y entrega esta caja.^000000",
    "I'll let you know how to reach the village.": "Te dire como llegar a la aldea.",
    "Follow the arrows that just appeared on the ground.": "Sigue las flechas que acaban de aparecer en el suelo.",
    "^4d4dffSometimes NPCs will help you find your destination through the Navigation tool.": "^4d4dffA veces los NPCs te ayudaran a encontrar tu destino a traves de la herramienta de Navegacion.",
    "Links can be created if there is a need for it. If you see the [Target], click it for pathfinding.^000000": "Se pueden crear enlaces si es necesario. Si ves el [Objetivo], haz clic para buscar el camino.^000000",
    "^4d4dffCall up the Navigation panel by clicking the appropriate menu icon.": "^4d4dffAbre el panel de Navegacion haciendo clic en el icono de menu correspondiente.",
    "Search for the target, set the goal, and click Pathfinding.": "Busca el objetivo, establece la meta y haz clic en Buscar Camino.",
    "Arrows will be generated pointing toward the location of the target.^000000": "Se generaran flechas apuntando hacia la ubicacion del objetivo.^000000",
    "What's in front of you is Lasagna, the harbor village.": "Lo que tienes enfrente es Lasagna, la aldea portuaria.",
    "You should bring that box to the tool shop first, right?": "Deberias llevar esa caja a la tienda de herramientas primero, verdad?",
    "I'll be right behind you!": "Estare justo detras de ti!",
    "Don't worry about me. Just keep going.": "No te preocupes por mi. Solo sigue adelante.",
    "Haven't you left for Midgard yet?": "Aun no has partido hacia Midgard?",
    "Well, problems do occur at the harbor from time to time, but I thought it wouldn't be an issue for you.": "Bueno, los problemas ocurren en el puerto de vez en cuando, pero pense que no seria un problema para ti.",

    # === Sloth (lines 542-647) ===
    "Hmm...You look energetic.": "Hmm...Te ves energico.",
    "You see, I have an upset stomach.": "Veras, tengo el estomago revuelto.",
    "The weather is sunny and warm, but...": "El clima esta soleado y calido, pero...",
    "I think I'm having a very bad day...": "Creo que estoy teniendo un dia muy malo...",
    "I should pluck all the Red Grass in this herb field...": "Deberia arrancar toda la Red Grass de este campo de hierbas...",
    "But I'm pleasantly full in this fine sunny weather...": "Pero estoy agradablemente lleno en este buen clima soleado...",
    "And there's a good breeze blowing...": "Y hay una buena brisa soplando...",
    "I don't think I can ever drag myself up.": "No creo que pueda levantarme jamas.",
    "But I'm supposed to pluck the Red Grass...": "Pero se supone que debo arrancar la Red Grass...",
    "If you do it I'll give you anchovies, okay?": "Si lo haces te dare anchoas, esta bien?",
    "I'll pluck the Red Grass for you.": "Arrancare la Red Grass por ti.",
    "Move your butt, you lazy sloth!": "Mueve tu trasero, flojo perezoso!",
    "^4d4dffPluck 3 Red Grass and then collect 2 Red Herbs^000000 around here!": "^4d4dffArranca 3 Red Grass y luego recolecta 2 Red Herbs^000000 por aqui!",
    "This may be of great help to you!": "Esto puede ser de gran ayuda para ti!",
    "I'll rest here to make my upset stomach feel better.": "Descansare aqui para que mi estomago revuelto se sienta mejor.",
    "Meeow....": "Meeow....",
    "....Meeowww....": "....Meeowww....",
    "What I want isn't too much.": "Lo que quiero no es demasiado.",
    "Just ^4d4dffpluck the Red Grass and collect 2 Red Herbs^000000 around here. That's all.": "Solo ^4d4dffarranca la Red Grass y recolecta 2 Red Herbs^000000 por aqui. Eso es todo.",
    "They grow too fast and keep growing no matter how many times I pluck them. I've had it...": "Crecen demasiado rapido y siguen creciendo sin importar cuantas veces las arranque. Ya me canse...",
    "Oh...This aroma!": "Oh...Este aroma!",
    "You plucked the Red Herbs just right.": "Arrancaste las Red Herbs justo como debia ser.",
    "I'll munch on them like twigs and digest them just like that. Meow!": "Las masticare como ramitas y las digerire asi nomas. Meow!",
    "I'll give you the left-over herbs as a reward.": "Te dare las hierbas sobrantes como recompensa.",
    "Chew them up and ^4d4dffyour HP will be restored.^000000": "Masticalas y ^4d4dfftu HP se restaurara.^000000",
    "If you ask Haru, she'll tell you how to turn them into a potion with more effects.": "Si le preguntas a Haru, te dira como convertirlas en una pocion con mas efectos.",
    "Anyway, I'm the cat who knows how to return the favor.": "De todos modos, soy el gato que sabe como devolver el favor.",
    "This is for you.": "Esto es para ti.",
    "Stay out of trouble, now.": "No te metas en problemas, vale?",
    "I'm feeling... so tired...": "Me siento... tan cansado...",
    "~Growling~": "~Gruuunido~",
    "Hey, there! Get over here for a minute!": "Oye, tu! Ven aqui un momento!",

    # === Well-known Troublemaker (lines 649-819) ===
    "What brought you all the way up here, human?": "Que te trajo hasta aqui arriba, humano?",
    "Be gone! Be gone, meeow!": "Fuera! Fuera, meeow!",
    "This is like a gateway. It cannot and should not be tainted by humans!": "Esto es como una puerta de entrada. No puede ni debe ser contaminada por humanos!",
    "Hey, buddy!": "Oye, amigo!",
    "Nyo-hoho! Nyo-hoho! You look so hectic. Where are you going?": "Nyo-hoho! Nyo-hoho! Te ves muy agitado. A donde vas?",
    "To me, you look like a newbie adventurer who has just crossed the mountain ridge, meeow.": "Para mi, pareces un aventurero novato que acaba de cruzar la cordillera, meeow.",
    "Aren't you too weak to handle the Dorams in Lasagna?": "No eres demasiado debil para lidiar con los Dorams de Lasagna?",
    "Do you even know how to use skills?": "Sabes siquiera como usar habilidades?",
    "To me, you look like a greenhorn who's simply acting out.": "Para mi, pareces un novaton que simplemente esta actuando.",
    "I'm a better fighter than you are!": "Soy mejor peleador que tu!",
    "Whoa, is that so?": "Vaya, es asi?",
    "Nyo-ho! Nyo-ho! How dare you disrespect me?": "Nyo-ho! Nyo-ho! Como te atreves a faltarme al respeto?",
    "How about making a bet with me?": "Que tal si hacemos una apuesta?",
    "I'll give you 10 full minutes while you hunt ^4d4dff3 Leaf Lunatics and 2 Grass Fabres^000000 around here!": "Te dare 10 minutos completos para que caces ^4d4dff3 Leaf Lunatics y 2 Grass Fabres^000000 por aqui!",
    "If you show me what you're made of, I'll get out of your way.": "Si me demuestras de que estas hecho, me quitare de tu camino.",
    "Accept.": "Aceptar.",
    "Decline.": "Rechazar.",
    "You've got 10 minutes. No more, no less!": "Tienes 10 minutos. Ni mas, ni menos!",
    "^4d4dff3 Leaf Lunatics and 2 Grass Fabres!^000000": "^4d4dff3 Leaf Lunatics y 2 Grass Fabres!^000000",
    "Are you running away?!": "Te estas escapando?!",
    "No adventurer with a faint heart ever survived on the New Continent!": "Ningun aventurero cobarde sobrevivio en el Nuevo Continente!",
    "Eliminate ^4d4dff3 Leaf Lunatics and 2 Grass Fabres^000000 swarming around here within ^4d4dff10 minutes^000000!": "Elimina ^4d4dff3 Leaf Lunatics y 2 Grass Fabres^000000 que pululan por aqui en ^4d4dff10 minutos^000000!",
    "Nyo-hoho!! Nyo-hoho!!": "Nyo-hoho!! Nyo-hoho!!",
    "Was it too tough for you to handle?": "Fue demasiado dificil para ti?",
    "What do you think? Want to give it another try?": "Que opinas? Quieres intentarlo de nuevo?",
    "Was it too hard for you?": "Fue muy dificil para ti?",
    "Are you using your ^4d4dffskills^000000 well while hunting?": "Estas usando bien tus ^4d4dffhabilidades^000000 mientras cazas?",
    "You can ^4d4dffbring up the Skill Tree by pressing the [Alt+S] shortcut key or clicking the corresponding skill icon.^000000": "Puedes ^4d4dffabrir el Arbol de Habilidades presionando la tecla de atajo [Alt+S] o haciendo clic en el icono de habilidad correspondiente.^000000",
    "Setup the skill you'd like to use so that you can use it while in battle.": "Configura la habilidad que quieras usar para poder usarla durante la batalla.",
    "^4d4dffSkills that are activated manually ^000000 can be ^4d4dffplaced on the quickbar^000000 for fast use.": "^4d4dffLas habilidades que se activan manualmente ^000000 se pueden ^4d4dffcolocar en la barra rapida^000000 para uso rapido.",
    "...Now you know how to use skills.": "...Ahora sabes como usar habilidades.",
    "So, what are you going to do?": "Entonces, que vas a hacer?",
    "Try again.": "Intentar de nuevo.",
    "I'll quit right now!": "Lo dejo ahora mismo!",
    "You have moxie and I like that!": "Tienes agallas y eso me gusta!",
    "Alright, then. Give it another go!": "Muy bien, entonces. Intentalo otra vez!",
    "How can you hope to survive the New Continent with that weak mindset?": "Como esperas sobrevivir en el Nuevo Continente con esa mentalidad debil?",
    "Nyo-hoho! Nyo-hoho! I'm the strongest Doram in this domain!": "Nyo-hoho! Nyo-hoho! Soy el Doram mas fuerte de este dominio!",
    "Hmm...You are good.": "Hmm...Eres bueno.",
    "I feel challenged whenever I stumble upon a competent Doram such as you.": "Me siento retado cada vez que me encuentro con un Doram competente como tu.",
    "Time is already up! Nyo-hoho!!": "El tiempo ya se acabo! Nyo-hoho!!",
    "So that again proves that I'm the best in this domain!": "Eso demuestra otra vez que soy el mejor de este dominio!",
    "You finished the job on a high note so I'd like to help you in return.": "Terminaste el trabajo de manera excelente asi que me gustaria ayudarte a cambio.",
    "By the way, do you know what a ^4d4dffSkill Tree^000000 is?": "Por cierto, sabes que es un ^4d4dffArbol de Habilidades^000000?",
    "Did I teach you about that?": "Te ensene sobre eso?",
    "Do you remember anything about it?": "Recuerdas algo al respecto?",
    "...Now you know how to use skills.\nYou should thank me. Nyo-hoho!": "...Ahora sabes como usar habilidades.\nDeberias agradecerme. Nyo-hoho!",
    "You should thank me. Nyo-hoho!": "Deberias agradecerme. Nyo-hoho!",
    "Do you need to be enlightened again?": "Necesitas que te iluminen de nuevo?",
    "There's nothing special about life in this world.": "No hay nada especial sobre la vida en este mundo.",
    "You'd better make yourself familiar with the skill tree. It is accessed when you click the Skill icon.": "Sera mejor que te familiarices con el arbol de habilidades. Se accede haciendo clic en el icono de Habilidad.",
    "Battle Dorams are specialized in summoning.": "Los Dorams de batalla se especializan en invocacion.",
    "Focus on using the summoning skills so that you can win battles.": "Enfocate en usar las habilidades de invocacion para poder ganar batallas.",
    "Meeow?? Is this another out-of-towner Doram that I haven't met before?": "Meeow?? Es este otro Doram foraneo que no he conocido antes?",
    "You! You're picking a fight with another innocent passerby?": "Tu! Estas buscando pelea con otro transeuntes inocente?",
    "Picking a fight? This is what we call training!": "Buscar pelea? A esto le llamamos entrenamiento!",
    "Shut your mouth! You're joining the Vigilante Corp the moment you return to the village, got it?": "Cierra la boca! Te uniras al Cuerpo de Vigilantes en cuanto regreses a la aldea, entendido?",
    "Well, uh...I'm...uh...I'm free-spirited! That's all!": "Bueno, eh...Yo...eh...Soy de espiritu libre! Eso es todo!",
    "You're just full of it.": "Estas lleno de fanfarronerias.",

    # === Kid/Tool Merchant (lines 825-1000) ===
    "This is it!!": "Esta es!!",
    "The kitten hoisted the box given to him up high, screaming out in joy": "El gatito levanto la caja que le dieron bien alto, gritando de alegria",
    "Wait. This box looks familiar...": "Espera. Esta caja me resulta familiar...",
    "Hey! Isn't this the box that I told you to deliver to Haru?": "Oye! No es esta la caja que te dije que le entregaras a Haru?",
    "~Gulps~": "~Traga saliva~",
    "I'm leaving! Right now!": "Me voy! Ahora mismo!",
    "Thank you for finding the box!": "Gracias por encontrar la caja!",
    "...Wow, that was fast.": "...Vaya, eso fue rapido.",
    "Anyway, thank you for finding the box.": "De todos modos, gracias por encontrar la caja.",
    "If you have the time, sit down and talk with me.": "Si tienes tiempo, sientate y habla conmigo.",
    "Why is he taking so long...?": "Por que se tarda tanto...?",
    "I'm worried.": "Estoy preocupado.",
    "Is there anything that troubles you?": "Hay algo que te preocupe?",
    "No, it's nothing.": "No, no es nada.",
    "I'm not one of the Dorams who would randomly give up on their errands!": "No soy de los Dorams que abandonarian sus mandados asi nomas!",
    "The little Doram starts whining, secretly being conscious of the adult Doram next to him.": "El pequeno Doram empieza a quejarse, siendo secretamente consciente del Doram adulto a su lado.",
    "I was told you're headed to the New Continent.": "Me dijeron que te diriges al Nuevo Continente.",
    "I want to go there myself, too!": "Yo tambien quiero ir alla!",
    "You're too young! Just join the Vigilante Corp.": "Eres muy joven! Solo unete al Cuerpo de Vigilantes.",
    "You must be here to apply for the expedition to the New Continent.": "Debes estar aqui para inscribirte en la expedicion al Nuevo Continente.",
    "It looks like my son caused some trouble for you.": "Parece que mi hijo te causo algunos problemas.",
    "Thank you for your help.": "Gracias por tu ayuda.",
    "This is not much, but please take it. It's a token of my appreciation.": "Esto no es mucho, pero por favor aceptalo. Es una muestra de mi agradecimiento.",
    "I also gave you ^4d4dffa new set of clothes^000000 so that you can change out of your dirty ones.": "Tambien te di ^4d4dffun nuevo conjunto de ropa^000000 para que te cambies la sucia.",
    "You can find other tool merchants like me in each village.": "Puedes encontrar otros comerciantes de herramientas como yo en cada aldea.",
    "You can buy and sell the items through those merchants.": "Puedes comprar y vender objetos a traves de esos comerciantes.",
    "Ask ^4d4dffHealer Haru about the Combination Kit^000000 and she'll help you use it effectively.": "Preguntale a ^4d4dffla Sanadora Haru sobre el Kit de Combinacion^000000 y ella te ayudara a usarlo eficazmente.",
    "Just take this with you.": "Solo lleva esto contigo.",
    "If you want to dispose of any items, you should see me.": "Si quieres deshacerte de algun objeto, deberias verme.",
    "Do you understand?": "Entiendes?",
    "^4d4dffHealer Haru's house^000000 is straight ^4d4dffto the east^000000 from here.": "^4d4dffLa casa de la Sanadora Haru^000000 esta derecho ^4d4dffhacia el este^000000 desde aqui.",
    "Plants and grasses are packed in front of her house because she's busy testing medicinal herbs.": "Las plantas y hierbas estan amontonadas frente a su casa porque esta ocupada probando hierbas medicinales.",
    "^4d4dffIt's the house where lots of flowerpots are aligned.^000000 You can't miss it.": "^4d4dffEs la casa donde hay muchas macetas alineadas.^000000 No puedes no verla.",
    "Haru is a very smart girl, so every sick person goes to her place.": "Haru es una chica muy inteligente, asi que toda persona enferma va a su lugar.",
    "You're about to go on a journey and she's going to be a lot of help.": "Estas a punto de emprender un viaje y ella te sera de mucha ayuda.",
    "Be sure to meet her.": "Asegurate de conocerla.",
    "Is there anything you need?": "Hay algo que necesites?",
    "Welcome.": "Bienvenido.",
    "Buy an item.": "Comprar un objeto.",
    "Sell your belongings.": "Vender tus pertenencias.",
    "Do you need anything? I have basic potions, traps, magnifiers...You name it!": "Necesitas algo? Tengo pociones basicas, trampas, lupas...Lo que quieras!",
    "Good thinking! I knew you would. you'd better sell away items that you no longer need!": "Buena idea! Sabia que lo harias. Sera mejor que vendas los objetos que ya no necesitas!",

    # === Healer Haru (lines 1002-1224) ===
    "I see a lot of out-of-towners these days.": "Veo muchos foraneos estos dias.",
    "What do you need?": "Que necesitas?",
    "Show her the Combination Kit.": "Mostrarle el Kit de Combinacion.",
    "What's up?": "Que pasa?",
    "Somebody, help me!": "Alguien, ayudame!",
    "About First Aid": "Sobre Primeros Auxilios",
    "About Medical Botany": "Sobre Botanica Medicinal",
    "Oh, no...": "Oh, no...",
    "It's going to be fine.": "Va a estar bien.",
    "Oh, dear...": "Oh, cielos...",
    "Does it hurt a lot?": "Te duele mucho?",
    "You need 5,000 Zeny to heal it all. Do you want me to do it?": "Necesitas 5,000 Zeny para curarlo todo. Quieres que lo haga?",
    "Say yes.": "Decir que si.",
    "It's too expensive.": "Es demasiado caro.",
    "Take your time and get some rest.": "Tomate tu tiempo y descansa un poco.",
    "Thank you for using our service.": "Gracias por usar nuestro servicio.",
    "You already know what First Aid is...": "Ya sabes que son los Primeros Auxilios...",
    "Please. I don't have all day.": "Por favor. No tengo todo el dia.",
    "Oh, you'd like to learn about First Aid! How admirable of you!": "Oh, te gustaria aprender sobre Primeros Auxilios! Que admirable de tu parte!",
    "First Aid is a skill converting your SP into HP in an emergency.": "Primeros Auxilios es una habilidad que convierte tu SP en HP en una emergencia.",
    "The healing amount can be minimal...": "La cantidad de curacion puede ser minima...",
    "But you can at least avoid getting stunned by a critical hit.": "Pero al menos puedes evitar quedar aturdido por un golpe critico.",
    "Click the ^4d4dffSkill^000000 button to open the Skill Window.": "Haz clic en el boton ^4d4dffHabilidad^000000 para abrir la Ventana de Habilidades.",
    "FYI, the shortcut key is ^4d4dffAlt+S^000000.": "Para tu informacion, la tecla de atajo es ^4d4dffAlt+S^000000.",
    "Well, then. I'll let you in on something juicy while I'm at it.": "Bueno, entonces. Te contare algo interesante ya que estamos.",
    "Press the ^4d4dffF12 key^000000, will you?": "Presiona la tecla ^4d4dffF12^000000, si?",
    "Surprise! It brings up the shortcut key window where nine small slots are arranged in a row.": "Sorpresa! Abre la ventana de teclas de atajo donde hay nueve pequenas ranuras en fila.",
    "Drag the corner area in the right-hand side of the shortcut key window to view other pages.": "Arrastra el area de la esquina en el lado derecho de la ventana de atajos para ver otras paginas.",
    "It's easy to use. ^4d4dffEach slot corresponds to the keys from F1 through F9.^000000": "Es facil de usar. ^4d4dffCada ranura corresponde a las teclas de F1 a F9.^000000",
    "Drag your skill or item to use in the slot and press the corresponding key to activate it instantly.": "Arrastra tu habilidad u objeto a la ranura y presiona la tecla correspondiente para activarlo al instante.",
    "^4d4dffTo place an item or skill icon to use, drag it to the shortcut key slot.^000000": "^4d4dffPara colocar un icono de objeto o habilidad, arrastralo a la ranura de tecla de atajo.^000000",
    "^4d4dffTo use or equip an item or equipment registered in the slot, press the key that corresponds to each slot from F1 to F9.^000000": "^4d4dffPara usar o equipar un objeto o equipo registrado en la ranura, presiona la tecla que corresponda a cada ranura de F1 a F9.^000000",
    "^4d4dffIn the shortcut key settings, you can select the corresponding shortcut keys as you desire.^000000": "^4d4dffEn la configuracion de teclas de atajo, puedes seleccionar las teclas de atajo correspondientes como desees.^000000",
    "^4d4dffPlace an item and/or skill that you often use for quick usage.^000000": "^4d4dffColoca un objeto y/o habilidad que uses frecuentemente para un uso rapido.^000000",
    "Well, now. Open the Skill Window and place the First Aid skill in a shortcut key slot to use.": "Bien. Abre la Ventana de Habilidades y coloca la habilidad de Primeros Auxilios en una ranura de tecla de atajo.",
    "It's going to be a lot easier to use it.": "Sera mucho mas facil usarla.",
    "Oh, so you're here to learn the potion combination?": "Oh, entonces estas aqui para aprender la combinacion de pociones?",
    "Then, you need a combination scroll first.": "Entonces, necesitas un pergamino de combinacion primero.",
    "Above all, the most important out of all the combination items should be a potion.": "Sobre todo, lo mas importante de todos los objetos de combinacion deberia ser una pocion.",
    "Have you ever seen the grass growing in the field while you're traveling?": "Has visto alguna vez el pasto creciendo en el campo mientras viajas?",
    "^4d4dffRed Grass, Blue Grass, Green Grass, White Grass...^000000etc...": "^4d4dffRed Grass, Blue Grass, Green Grass, White Grass...^000000etc...",
    "You can obtain herbs from these grasses.": "Puedes obtener hierbas de estos pastos.",
    "Each herb is a good source to be processed into various kinds of medicine.": "Cada hierba es una buena fuente para ser procesada en varios tipos de medicina.",
    "Red Herbs are running out.": "Las Red Herbs se estan acabando.",
    "I think you should go pick some now.": "Creo que deberias ir a recoger algunas ahora.",
    "The herbs are growing in the entrance of the village. Did you see them?": "Las hierbas estan creciendo en la entrada de la aldea. Las viste?",
    "^4d4dffGo and collect 1 Red Herb in the entrance of the village.^000000 This should be a good practice.": "^4d4dffVe y recolecta 1 Red Herb en la entrada de la aldea.^000000 Esta deberia ser una buena practica.",
    "Come on. Hurry!": "Vamos. Apurate!",
    "Hey, there. Newbie Doram. Talk to me.": "Oye, tu. Doram novato. Habla conmigo.",
    "You've got them, perfect.": "Los conseguiste, perfecto.",
    "This ^4d4dffherb is effective even when eaten as it is, but, it is far more effective when it is made into a potion.^000000": "Esta ^4d4dffhierba es efectiva incluso cuando se come asi, pero es mucho mas efectiva cuando se convierte en pocion.^000000",
    "Effects vary for the herbs, depending on their colors.": "Los efectos varian para las hierbas, dependiendo de sus colores.",
    "^4d4dffGreen Herbs are known for detoxification.^000000": "^4d4dffLas Green Herbs son conocidas por la desintoxicacion.^000000",
    "^4d4dff Blue Herbs restore SP^000000.": "^4d4dff Las Blue Herbs restauran SP^000000.",
    "Anything else?": "Algo mas?",
    "Well, now. Your HP is being restored as the Red Herb does it's work.": "Bueno. Tu HP se esta restaurando mientras la Red Herb hace su trabajo.",
    "Press juice out of it and put them in a bottle...": "Exprime el jugo y ponlo en una botella...",
    "This is what we call a potion that you can take anytime, anywhere!": "Esto es lo que llamamos una pocion que puedes tomar en cualquier momento y lugar!",
    "This is for you on this special encounter.": "Esto es para ti en este encuentro especial.",
    "Prepare the materials written in the combination scroll.": "Prepara los materiales escritos en el pergamino de combinacion.",
    "Then, ^4d4dffuse the Combination Kit or cooking utensils^000000 to make an item you want.": "Entonces, ^4d4dffusa el Kit de Combinacion o utensilios de cocina^000000 para hacer el objeto que quieras.",
    "You can also make various other types of tools, other than potions, with the materials you pick up, so use them well.": "Tambien puedes hacer varios otros tipos de herramientas, aparte de pociones, con los materiales que recojas, asi que usalos bien.",
    "I gave you Red Herbs and apples.": "Te di Red Herbs y manzanas.",
    "So give it a try and craft something with the Combination Kit.": "Asi que intentalo y fabrica algo con el Kit de Combinacion.",
    "Here's the directions. To read the combination scroll,": "Aqui estan las instrucciones. Para leer el pergamino de combinacion,",
    "^4d4dffRight-click the scroll,^000000 and then, click the ^4d4dffbook-shaped icon^000000 found in the description window.": "^4d4dffHaz clic derecho en el pergamino,^000000 y luego, haz clic en el ^4d4dfficono con forma de libro^000000 en la ventana de descripcion.",
    "Oh! Here you are!": "Oh! Aqui estas!",
    "There is a place near the entrance of the village where herbs grow.": "Hay un lugar cerca de la entrada de la aldea donde crecen hierbas.",
    "^4d4dffBeat the Red Grass and get 1 Red Herb^000000.": "^4d4dffGolpea la Red Grass y obtiene 1 Red Herb^000000.",
    "You should know what the herbs look like.": "Deberias saber como se ven las hierbas.",
    "I've given you all the details about the basics of medicinal botany.": "Te he dado todos los detalles sobre los basicos de la botanica medicinal.",
    "By the way, there is ^4d4dffShining Grass^000000 in this world.": "Por cierto, hay ^4d4dffShining Grass^000000 en este mundo.",
    "You have no idea what kind of herb the Shining Grass will produce.": "No tienes idea de que tipo de hierba producira la Shining Grass.",
    "I was lucky enough to obtain Igdrasil's Fruit once.": "Tuve la suerte de obtener Igdrasil's Fruit una vez.",
    "Rumor has it that, among humans, ^4d4dffAlchemist^000000, ^4d4dffCreator^000000, or the upper-level ^4d4dffGeneric^000000": "Se rumorea que, entre los humanos, ^4d4dffAlchemist^000000, ^4d4dffCreator^000000, o el nivel superior ^4d4dffGeneric^000000",
    "are highly specialized in crafting potions.": "estan altamente especializados en fabricar pociones.",
    "If you happen to meet a human in the Midgard Continent, why don't you ask them?": "Si llegas a conocer a un humano en el Continente Midgard, por que no les preguntas?",

    # === Hypnotist (lines 1226-1281) ===
    "Oh! So you're that famous human everyone is talking about!": "Oh! Asi que tu eres ese humano famoso del que todos hablan!",
    "But why is your hair uneven?": "Pero por que tu cabello esta desparejo?",
    "Have you come down with a skin disease or something?": "Te dio alguna enfermedad de la piel o algo?",
    "This healer next to me is really good. You should ask her to take a look at it!": "Esta sanadora a mi lado es muy buena. Deberias pedirle que te revise!",
    "You're really big and that type of poor hair just doesn't go well with you...": "Eres realmente grande y ese tipo de cabello pobre no te queda bien...",
    "It must've been a lot of work.": "Debe haber sido mucho trabajo.",
    "I'm casting hypnosis on the young lads for their future.": "Estoy lanzando hipnosis a los jovenes para su futuro.",
    "You must have been over with wandering by now.": "Ya debes haber terminado de deambular a estas alturas.",
    "If you don't like a skill you just learned, I can reset it for you.": "Si no te gusta una habilidad que acabas de aprender, puedo reiniciarla por ti.",
    "^4d4dffUp to level 49, your skills and status can be reset anytime you want.^000000": "^4d4dffHasta el nivel 49, tus habilidades y estados se pueden reiniciar cuando quieras.^000000",
    "Reset the status.": "Reiniciar los estados.",
    "Reset the skill.": "Reiniciar las habilidades.",
    "Your items can be lost, so be sure to make yourself weigh ^FF00000^000000.": "Tus objetos se pueden perder, asi que asegurate de que tu peso sea ^FF00000^000000.",
    "The Cat Paw Commerce Group is responsible for the warehouse, so leave your items to them.": "El Grupo Comercial Cat Paw es responsable del almacen, asi que dejales tus objetos.",
    "Your status has been reset successfully!": "Tus estados se han reiniciado exitosamente!",
    "I don't do it for the experienced. So you should figure out your own status well beforehand.": "No lo hago para los experimentados. Asi que deberias decidir bien tus estados de antemano.",
    "Your skill has been reset successfully!": "Tus habilidades se han reiniciado exitosamente!",
    "I reset skills and statuses without charge only when your level stays at 49 or below.": "Reinicio habilidades y estados sin costo solo cuando tu nivel es 49 o menos.",
    "Before that, I advise you to practice with many skills in diverse ways, to help you decide what you like.": "Antes de eso, te aconsejo practicar con muchas habilidades de diversas formas, para ayudarte a decidir que te gusta.",

    # === Vigilante Aglio#doram09 (lines 1283-1297) ===
    "I was looking for you at the tool shop and they said you headed here.": "Te estaba buscando en la tienda de herramientas y me dijeron que viniste aqui.",
    "First off, we should meet up with our leader to make decisions about the schedule.": "Primero, debemos reunirnos con nuestro lider para tomar decisiones sobre el horario.",
    "We'd better head to the square.": "Sera mejor que vayamos a la plaza.",
    "I think you can find another Vigilante like myself in the square...": "Creo que puedes encontrar otro Vigilante como yo en la plaza...",

    # === Con-Chliina Crewman (lines 1347-1377) ===
    "Here are the shrimps, carrots and catnip!": "Aqui estan los camarones, zanahorias y hierba gatera!",
    "Buy": "Comprar",
    "Sell": "Vender",
    "Cancel": "Cancelar",
    "Come back again soon!": "Vuelve pronto!",
    "From the continent of Midgard to Far-Star!": "Del continente de Midgard a Far-Star!",
    "I see.": "Ya veo.",
    "Not enough? How about checking how much he has?": "No es suficiente? Que tal si revisas cuanto tienes?",

    # === Vigilante Penne (lines 1378-1450) ===
    "Hiya! Isn't it delightful to see the Farfalle Vigilante even here?": "Hola! No es genial ver al Vigilante Farfalle incluso aqui?",
    "By the way, how's your settlement in this land coming along?": "Por cierto, como va tu asentamiento en esta tierra?",
    "Have you been to ^4d4dffProntera^000000 or ^4d4dffPayon^000000 near here?": "Has estado en ^4d4dffProntera^000000 o ^4d4dffPayon^000000 cerca de aqui?",
    "There is a Paradise Group you might want to visit.": "Hay un Grupo Paraiso que quizas quieras visitar.",
    "It doesn't hurt to go visit there.": "No esta de mas ir a visitarlos.",
    "Humans always intrigue me with their peculiar look.": "Los humanos siempre me intrigan con su aspecto peculiar.",
    "Like a big, hairless cat!": "Como un gato grande y sin pelo!",
    "Me? Let me explain. I'm the proud member of the Farfalle Vigilante from the great Far-Star Continent.": "Yo? Dejame explicarte. Soy el orgulloso miembro del Vigilante Farfalle del gran Continente Far-Star.",
    "Far-Star Continent?": "Continente Far-Star?",
    "Farfalle Vigilante?": "Vigilante Farfalle?",
    "Are you from the Cat Paw Commerce Group?": "Eres del Grupo Comercial Cat Paw?",
    "There are more continents other than Midgard.": "Hay mas continentes aparte de Midgard.",
    "The land we crossed from is called Far-Star.": "La tierra de donde cruzamos se llama Far-Star.",
    "Well, we're no different because we thought there was only the Far-Star Continent under the sun.": "Bueno, no somos diferentes porque pensabamos que solo existia el Continente Far-Star bajo el sol.",
    "The world sure is wide...": "El mundo si que es grande...",
    "So, do you see this ribbon that goes perfectly well with this cool uniform?": "Entonces, ves esta cinta que combina perfectamente con este uniforme genial?",
    "(Show the below-neck area.)": "(Muestra el area debajo del cuello.)",
    "This is the symbol of our Farfalle Vigilante.": "Este es el simbolo de nuestro Vigilante Farfalle.",
    "We are the legendary Vigilante Corp that protects Lasagna!": "Somos el legendario Cuerpo de Vigilantes que protege Lasagna!",
    "You have no idea how cool our leader Peperoncino can be...": "No tienes idea de lo genial que puede ser nuestro lider Peperoncino...",
    "We do all kinds of chores from handling the urchins at the port to maintaining the security of the village.": "Hacemos todo tipo de tareas, desde manejar a los pilluelos del puerto hasta mantener la seguridad de la aldea.",
    "Moreover, you can come to this...Mid...Midgur...Midgar...": "Ademas, puedes venir a este...Mid...Midgur...Midgar...",
    "Anyway! You're allowed to come here only when the Farfalle Vigilante accepts.": "En fin! Solo se te permite venir aqui cuando el Vigilante Farfalle lo acepte.",
    "This proud cat is getting really talkative...": "Este gato orgulloso se esta poniendo muy hablador...",
    "Huh? Are you just passing by?": "Eh? Solo estas de paso?",
    "No, That's not it!!": "No, eso no es!!",
    "The Cat Paw Commerce Group is led by Captain Tomei-Tomas!": "El Grupo Comercial Cat Paw esta liderado por el Capitan Tomei-Tomas!",
    "I'm with the Farfalle Vigilante commanded by Leader Peperoncino!": "Estoy con el Vigilante Farfalle comandado por el Lider Peperoncino!",
    "Oh, my days! So you haven't even been to Lasagna, have you?": "Ay, cielos! Asi que ni siquiera has estado en Lasagna, verdad?",
    "Our great Captain Gamberri ventured here in person!": "Nuestro gran Capitan Gamberri se aventuro aqui en persona!",
    "We are gracious enough to give humans like you a chance to go to the land of Lasagna.": "Somos lo suficientemente amables para darles a humanos como tu la oportunidad de ir a la tierra de Lasagna.",
    "Before long, this Midgur...Midgarr...?? This land will soon be controlled by us, the Dorams!": "Pronto, este Midgur...Midgarr...?? Esta tierra pronto sera controlada por nosotros, los Dorams!",
    "You'd better earn our favor. If you do, we might give you a job to clean anchovies in Lasagna!": "Sera mejor que te ganes nuestro favor. Si lo haces, podriamos darte un trabajo limpiando anchoas en Lasagna!",

    # === Various NPCs (lines 1452-2000) ===
    "We trim your beards. We comb your tails. Be sure to groom yourselves before setting out to the new world.": "Recortamos sus barbas. Peinamos sus colas. Asegurense de asearse antes de partir al nuevo mundo.",
    "There's a hair designer in downtown, so make sure you drop by.": "Hay un disenador de cabello en el centro, asi que asegurate de pasar por ahi.",
    "This is a pub but also an adventurers' club where adventurers stop by. They come from all over the place and share their stories as well as find companions for adventures.": "Este es un bar pero tambien un club de aventureros donde los aventureros se detienen. Vienen de todas partes y comparten sus historias y encuentran companeros para aventuras.",
    "These days, many people come to seek information before heading off to the new world.": "Hoy en dia, mucha gente viene a buscar informacion antes de partir al nuevo mundo.",
    "About ten years ago, it was a conciliating place to rehab hoodlum dorams and recruit them as vigilantes. Before that, rough sailors came to relax after a hard day's work.": "Hace unos diez anos, era un lugar conciliador para rehabilitar dorams delincuentes y reclutarlos como vigilantes. Antes de eso, marineros rudos venian a relajarse despues de un duro dia de trabajo.",
    "Chief Peperoncino and Captain Gamberry first met here as well. The three became sworn brothers and became legends after their endeavors proved to be successful.": "El Jefe Peperoncino y el Capitan Gamberry se conocieron aqui tambien. Los tres se convirtieron en hermanos jurados y se volvieron leyendas despues de que sus esfuerzos resultaron exitosos.",
    "So people who wish to succeed or adventurers who wish to become just like them come here a lot.": "Asi que la gente que desea tener exito o aventureros que desean ser como ellos vienen aqui mucho.",
    "Did you decide what you'll have?": "Ya decidiste que vas a pedir?",
    "Everyone orders kaluna milk here because of the oven resolution by Peperoncino, Gamberry, and Thomas. But Pub-Oven's real specialty menu is the fish cake.": "Todos piden leche kaluna aqui por la resolucion del horno de Peperoncino, Gamberry y Thomas. Pero la verdadera especialidad de Pub-Oven es el pastel de pescado.",
    "Fish cake is a white fish fillet mashed with boiled beans that is shaped and fried. It's really delicious but no one asks for it.": "El pastel de pescado es un filete de pescado blanco machacado con frijoles hervidos que se moldea y se frie. Es realmente delicioso pero nadie lo pide.",
    "So we don't even have the ingredients prepared these days. When there's an order once in a while, we run to the fish store to buy a cod and start cooking then.": "Asi que ni siquiera tenemos los ingredientes preparados estos dias. Cuando hay un pedido de vez en cuando, corremos a la pescaderia a comprar un bacalao y empezamos a cocinar.",
    "Oh, It's really good...": "Oh, es realmente bueno...",
    "Every life in this world comes with a property.": "Toda vida en este mundo viene con una propiedad.",
    "There are numerous kinds of elements from neutral to four major natural elements, alongside the holy and dark elements.": "Hay numerosos tipos de elementos, desde neutro hasta los cuatro elementos naturales principales, junto con los elementos sagrado y oscuro.",
    "Most representative elements are the natural ones.": "Los elementos mas representativos son los naturales.",
    "Put simply, these are the elements of Water, Wind, Earth, and Fire.": "En pocas palabras, estos son los elementos de Agua, Viento, Tierra y Fuego.",
    "Besides, there are elements of Undead, Holiness and Darkness.": "Ademas, hay elementos de No-Muerto, Sagrado y Oscuridad.",
    "Each element is intertwined with each other. So be smart and use the opposing elements.": "Cada elemento esta entrelazado con los demas. Asi que se inteligente y usa los elementos opuestos.",
    "That way, you can get the upper hand of a battle.": "De esa manera, puedes obtener la ventaja en una batalla.",
    "Let me give you a brief example on their correlation.": "Dejame darte un breve ejemplo de su correlacion.",
    "Fire element is highly resistant to Earth element.": "El elemento Fuego es altamente resistente al elemento Tierra.",
    "Meanwhile, Earth element definitely outperforms Wind element.": "Mientras tanto, el elemento Tierra definitivamente supera al elemento Viento.",
    "Wind element beats Water element.": "El elemento Viento vence al elemento Agua.",
    "Yet, Water element defeats Fire element.": "Sin embargo, el elemento Agua derrota al elemento Fuego.",
    "Holy element and Dark element directly oppose each other, and you should keep that in mind.": "Los elementos Sagrado y Oscuro se oponen directamente, y deberias tenerlo en cuenta.",
    "Other than that, there are also Neutral and Undead elements. You'll soon know what they are about.": "Aparte de eso, tambien hay elementos Neutro y No-Muerto. Pronto sabras de que se tratan.",
    "You will have to see it for yourself.": "Tendras que verlo por ti mismo.",
    "Earth element defeats Wind element.": "El elemento Tierra derrota al elemento Viento.",
    "Water element is superior to Fire element.": "El elemento Agua es superior al elemento Fuego.",
    "Wind element outperforms Water element.": "El elemento Viento supera al elemento Agua.",
    "Fire element beats Earth element.": "El elemento Fuego vence al elemento Tierra.",
    "Holy element and Dark element are in stark contrast to each other.": "Los elementos Sagrado y Oscuro estan en fuerte contraste entre si.",

    # === Cat Paw Service (lines 1540-1684) ===
    "Hey, little fellow!": "Oye, amiguito!",
    "Are you headed to the Midgard Continent?": "Te diriges al Continente Midgard?",
    "Then, you'd better listen to me!": "Entonces, sera mejor que me escuches!",
    "Like our Cat Paw Commerce Group, there are other groups who provide the ^4d4dffLocation sharing service^000000 and the ^4d4dffWarehouse service^000000.": "Como nuestro Grupo Comercial Cat Paw, hay otros grupos que proporcionan el ^4d4dffservicio de Compartir Ubicacion^000000 y el ^4d4dffservicio de Almacen^000000.",
    "They are: ^4d4dffKafra^000000 and ^4d4dffZonda^000000.": "Son: ^4d4dffKafra^000000 y ^4d4dffZonda^000000.",
    "Of course, don't forget about the Cat Paw Commerce Group!": "Por supuesto, no te olvides del Grupo Comercial Cat Paw!",
    "^4d4dffLocation sharing^000000 is to save the location for you to return to.": "^4d4dffCompartir Ubicacion^000000 es para guardar la ubicacion a la que puedes regresar.",
    "If you fall down due to fatigue during an adventure, you should return to the village. That's what you can do with this service.": "Si caes por fatiga durante una aventura, deberias regresar a la aldea. Eso es lo que puedes hacer con este servicio.",
    "Use the ^4d4dffButterfly Wings^000000 item to fly straight to that location.": "Usa el objeto ^4d4dffButterfly Wings^000000 para volar directo a esa ubicacion.",
    "Most of the locations shared are the safe village or city.": "La mayoria de las ubicaciones compartidas son la aldea o ciudad segura.",
    "The ^4d4dffWarehouse service^000000 is also similar.": "El ^4d4dffservicio de Almacen^000000 tambien es similar.",
    "You pay a little service fee to deposit your items safely.": "Pagas una pequena tarifa de servicio para depositar tus objetos de forma segura.",
    "You can't just carry around every item with you, can you?": "No puedes cargar cada objeto contigo, verdad?",
    "This is where the warehouse comes in handy.": "Aqui es donde el almacen resulta util.",
    "You can deposit and take out your item in the warehouse anytime, anywhere if you pay the service fee!": "Puedes depositar y sacar tus objetos del almacen en cualquier momento y lugar si pagas la tarifa de servicio!",
    "Now do you get it?": "Ahora lo entiendes?",
    "Oh, do you want me to explain it again?": "Oh, quieres que te lo explique de nuevo?",
    "No.": "No.",
    "Please.": "Por favor.",
    "Then, what do you want me to help you with?": "Entonces, en que quieres que te ayude?",
    "Come on! Welcome!": "Vamos! Bienvenido!",
    "What do you want me to help you?": "En que quieres que te ayude?",
    "Location sharing service": "Servicio de Compartir Ubicacion",
    "Warehouse service": "Servicio de Almacen",
    "Quit.": "Salir.",
    "Saved, meow!": "Guardado, meow!",
    "I'm sorry, but...": "Lo siento, pero...",
    "You should learn the new basic skill first.": "Deberias aprender la nueva habilidad basica primero.",
    "Go and learn the skill if you want to use the warehouse.": "Ve y aprende la habilidad si quieres usar el almacen.",
    "You should learn some basic skills first if you want to use the warehouse.": "Deberias aprender algunas habilidades basicas primero si quieres usar el almacen.",
    "Go and learn the skills until you reach the level to use the warehouse.": "Ve y aprende las habilidades hasta que alcances el nivel para usar el almacen.",
    "I believe it should be ^4d4dffbasic level 6^000000 for humans.": "Creo que deberia ser ^4d4dffnivel basico 6^000000 para humanos.",
    "If you don't have cheese, I'll gladly take Zeny.": "Si no tienes queso, con gusto aceptare Zeny.",
    "The Warehouse Service costs 50 Zeny.": "El Servicio de Almacen cuesta 50 Zeny.",
    "I'll get the warehouse open.": "Abrire el almacen.",
    "Come back again!": "Vuelve pronto!",
    "Come again then.": "Vuelve entonces.",
    "Meow! Hey, a new friend! I've got a story to tell you. You don't want to miss this!": "Meow! Oye, un nuevo amigo! Tengo una historia que contarte. No te la quieras perder!",

    # === Emergency Patient / misc NPCs ===
    "S-someone help me... Dorams, they're so cute I'm going to die...": "A-alguien ayudeme... Los Dorams, son tan lindos que me voy a morir...",
    "Go for a chance to win a cruise trip and annual salary of one hundred million with a price of three anchovies! Chances are in favor of those who don't doubt!": "Participa por la oportunidad de ganar un viaje en crucero y un salario anual de cien millones con un precio de tres anchoas! Las oportunidades favorecen a quienes no dudan!",
    "Vigilantes! Over here! there's someone here tricking people to get on board!": "Vigilantes! Aqui! hay alguien aqui enganando a la gente para que se suba a bordo!",
    "Blah! No luck here!": "Bah! Aqui no hay suerte!",
    "I heard that there are illegal anchovy boats tricking people to get on board these days. It's a scary world. The vigilantes have their eyes wide open to catch them.": "Escuche que hay barcos de anchoas ilegales enganando a la gente para que se suba a bordo estos dias. Es un mundo aterrador. Los vigilantes tienen los ojos bien abiertos para atraparlos.",
    "We wish you a pleasant day on Con-Chliina!": "Les deseamos un dia agradable en Con-Chliina!",
    "Hello, adventurer!": "Hola, aventurero!",
    "I assist those who finished their training from Farfalle Vigilantes with boarding on Con-Chliina.": "Ayudo a quienes terminaron su entrenamiento con los Vigilantes Farfalle a abordar el Con-Chliina.",
    "Those heading to the new world should follow the red yarn and go to the ^0000cddock^000000.": "Los que se dirigen al nuevo mundo deben seguir el hilo rojo e ir al ^0000cdmuelle^000000.",
    "Please check to see if you have the boarding pass with you before boarding!": "Por favor verifica si tienes el pase de abordaje contigo antes de abordar!",
    "Please don't miss the announcement about the details of Con-Chliina!": "Por favor no te pierdas el anuncio sobre los detalles de Con-Chliina!",
    "Moo -": "Muu -",
    "Moo - Moo -": "Muu - Muu -",
    "Bba -": "Bba -",
    "^4d4dffPress the F12 key and it will bring up the shortcut key slots.^000000": "^4d4dffPresiona la tecla F12 y se abriran las ranuras de teclas de atajo.^000000",
    "^4d4dffTo prepare an item or skill icon to use, drag it to the shortcut key slot.": "^4d4dffPara preparar un icono de objeto o habilidad para usar, arrastralo a la ranura de tecla de atajo.",
    "^4d4dffTo use or equip an item or equipment registered in the slot, press the key that corresponds to each slot from F1 to F9.": "^4d4dffPara usar o equipar un objeto o equipo registrado en la ranura, presiona la tecla correspondiente a cada ranura de F1 a F9.",
    "^4d4dffIn the shortcut key settings, you can select the corresponding shortcut key as you desire.": "^4d4dffEn la configuracion de teclas de atajo, puedes seleccionar la tecla de atajo correspondiente como desees.",
    "^4d4dffPrepare an item and/or skill that you often use for faster use.": "^4d4dffPrepara un objeto y/o habilidad que uses frecuentemente para un uso mas rapido.",
    "F12! F12!": "F12! F12!",
    "Red yarn will take you to the place you want to go, and the yellow road will take you home. don't forget. If you get lost, follow the red yarn.": "El hilo rojo te llevara al lugar donde quieres ir, y el camino amarillo te llevara a casa. No lo olvides. Si te pierdes, sigue el hilo rojo.",
    "Follow this yellow cheese road and you'll reach my hometown. I want to go back there one day.": "Sigue este camino de queso amarillo y llegaras a mi pueblo natal. Quiero volver alli algun dia.",
    "I'm the boss of this playground-": "Soy el jefe de este parque-",
    "Whew, you little kids... You guys are too young for me.": "Uf, ninos chiquitos... Son demasiado jovenes para mi.",
    "There are one ten two ten three ten yarn balls... So many!": "Hay una decena dos decenas tres decenas de ovillos de lana... Tantos!",
    "Anyone who wants to ride the seesaw- come here-": "Quien quiera subirse al subibajon- venga aqui-",
    "Why Isn't this rolling- Make it roll-": "Por que no rueda esto- Haganlo rodar-",
    "Is this the famous Pub-Oven?": "Es este el famoso Pub-Oven?",
    "Stop looking around like a hillbilly!": "Deja de mirar a todos lados como un pueblerino!",
    "Wow! Look at this! Would this be the place where all three of them sat down?": "Guau! Mira esto! Sera este el lugar donde los tres se sentaron?",
    "Geesh! You're just screaming that you're a hillbilly!": "Uy! Estas gritando que eres un pueblerino!",
    "Since we're here, Let's make an oven resolution!": "Ya que estamos aqui, hagamos una resolucion de horno!",
    "That's why we went through the trouble to come here! Just like Peperoncino, Thomas, and Gamberry, we'll unite and become successful!": "Por eso nos tomamos la molestia de venir aqui! Igual que Peperoncino, Thomas y Gamberry, nos uniremos y seremos exitosos!",
    "Boss! Three glasses of kaluna milk shaken hard, please! And egg yolk on top!": "Jefe! Tres vasos de leche kaluna bien agitados, por favor! Y yema de huevo encima!",
    "Oh, this is embarrassing! How many times do I have to tell you that everyone here has it stirred?!": "Ay, que verguenza! Cuantas veces tengo que decirte que aqui todos la piden revuelta?!",
    "Stirred or shaken, who cares as long as It's tasty?": "Revuelta o agitada, que importa mientras sea sabrosa?",
    "don't let people notice that you're from out of town!": "No dejes que la gente note que eres de fuera!",
    "Who cares if it shows?! Apparently, there Aren't too many Lasagna natives here.": "Que importa si se nota?! Al parecer, no hay muchos nativos de Lasagna aqui.",
    "Yeah, Let's just enjoy ourselves since we're here. I'll try not to let it show too much.": "Si, solo disfrutemos ya que estamos aqui. Intentare que no se note mucho.",
    "Yeah, yeah. I won't show it.": "Si, si. No lo mostrare.",
    "Three glasses of kaluna milk. Here you go.": "Tres vasos de leche kaluna. Aqui tienen.",
    "Finally!": "Por fin!",
    "Let's all make a toast. Hold the glasses high!": "Hagamos un brindis. Levanten los vasos!",
    "We weren't born on the same day, but Let's all die on the same day!": "No nacimos el mismo dia, pero muramos todos el mismo dia!",
    "Why mention death?": "Por que mencionar la muerte?",
    "Then one for all! All for one!": "Entonces uno para todos! Todos para uno!",
    "......": "......",
    "Cheesy...": "Cursi...",
    "Since I've come all the way here, I should try the kaluna milk!": "Ya que vine hasta aca, deberia probar la leche kaluna!",
    "Don't be so loud! Everyone is looking!": "No seas tan ruidoso! Todos estan mirando!",
    "You know, you're the one who's louder.": "Sabes, tu eres el mas ruidoso.",
    "Right, right.": "Si, si.",
    "Befitting to its fame, this place is packed with people.": "Acorde a su fama, este lugar esta lleno de gente.",
    "Always right-click when it comes to information! Right-click a human, item and cat to know more about them!": "Siempre haz clic derecho cuando se trate de informacion! Haz clic derecho en un humano, objeto y gato para saber mas sobre ellos!",
    "Ha- ppi- ness-": "Fe- li- ci- dad-",
    "We're full, so there's only one thing to do. Sleep.": "Estamos llenos, asi que solo queda una cosa por hacer. Dormir.",
    "Have you ever seen the crazy seagull nearby the south bridge over there? It was hopping like crazy. What's going on?": "Has visto alguna vez a la gaviota loca cerca del puente sur por alla? Estaba saltando como loca. Que esta pasando?",
    "Humans say their weapons become stronger through refinement. What's refinement anyway?": "Los humanos dicen que sus armas se hacen mas fuertes a traves del refinamiento. Que es el refinamiento de todas formas?",
    "DEX (Dexterity) is about accuracy and casting speed.": "DEX (Destreza) se trata de precision y velocidad de casteo.",
    "Double-click a consumable item to use.": "Haz doble clic en un objeto consumible para usarlo.",
    "You can't recover naturally if the items you carry exceed 50% of your max weight amount.": "No puedes recuperarte naturalmente si los objetos que cargas exceden el 50% de tu peso maximo.",
    "Kaluna milk should be stirred. With many wanders flocking around here lately, there's been an increase in those who shake it. But That's how kids drink it, Isn't?": "La leche kaluna se debe revolver. Con tantos viajeros llegando por aqui ultimamente, ha aumentado los que la agitan. Pero asi es como la toman los ninos, no?",
    "Kaluna milk should be shaken. You have to shake it to taste the delicate flavor produced when adequately fermented kaluna is mixed with milk.": "La leche kaluna se debe agitar. Tienes que agitarla para saborear el delicado sabor que se produce cuando la kaluna adecuadamente fermentada se mezcla con la leche.",
    "If you run into a problem, ask them for help. You know, the twins in the vigilante corps. Aglio... Ali... Ol...": "Si tienes algun problema, pideles ayuda. Ya sabes, los gemelos del cuerpo de vigilantes. Aglio... Ali... Ol...",
    "Right! They're Aglio and Oligo!": "Cierto! Son Aglio y Oligo!",
    "Aglio and Oligo!": "Aglio y Oligo!",
    "Hey, That's not it... No...": "Oye, eso no es... No...",
    "No?": "No?",
    "They're Aglio and Olio. Not Aglio and Oligo. You made them sound like a sugar.": "Son Aglio y Olio. No Aglio y Oligo. Los hiciste sonar como un azucar.",
    "They're Aglio and Olio.": "Son Aglio y Olio.",
    "Whichever.": "Da igual.",
    "It's dangerous to put yourself out into the world. Take these tri-colored anchovies.": "Es peligroso aventurarse al mundo. Toma estas anchoas tricolor.",
    "It's dangerous to put yourself out into the world.": "Es peligroso aventurarse al mundo.",
    "Everyone keep away! I'm dangerous. Krahh! How long can the tri-colored anchovies hold off?!": "Todos alejense! Soy peligroso. Krahh! Cuanto tiempo pueden resistir las anchoas tricolor?!",
    "Everyone keep away! I'm dangerous.": "Todos alejense! Soy peligroso.",
    "I'm... finished... You go ahead...": "Estoy... acabado... Tu sigue adelante...",
    "Kah... The poltergeist that had been sleeping inside my bag is raging!": "Kah... El poltergeist que dormia dentro de mi bolsa esta furioso!",
    "Good! This should be enough to keep me from getting snubbed in the new world.": "Bien! Esto deberia ser suficiente para evitar que me desprecien en el nuevo mundo.",
    "We're thoroughly prepared all right!": "Estamos bien preparados!",

    # === Fettuccina (lines 2000-2013) ===
    "I've worked here for a while, but I'm still the youngest so I do all the dishes.": "He trabajado aqui un tiempo, pero sigo siendo el mas joven asi que lavo todos los platos.",
    "A glass before sailing out, a glass on land after a long voyage, a glass for everyone who came from out of town to make an oven resolution, a glass for every regular customers, a glass for everyone who drinks because others drink it..": "Un vaso antes de zarpar, un vaso en tierra despues de un largo viaje, un vaso para todos los que vinieron de fuera a hacer una resolucion de horno, un vaso para cada cliente habitual, un vaso para todos los que beben porque otros beben..",
    "So basically, It's beyond your imagination how many glasses I have to wash each day. Not only that, I have to listen to vigilance corps and merchants' low-ranking dorams whine, and counsel rookie adventurers.": "Basicamente, esta mas alla de tu imaginacion cuantos vasos tengo que lavar cada dia. No solo eso, tengo que escuchar las quejas de los dorams de bajo rango del cuerpo de vigilantes y comerciantes, y aconsejar a aventureros novatos.",
    "Really, 24 hours are too short. We should hire one more person!": "En serio, 24 horas son muy pocas. Deberiamos contratar a una persona mas!",

    # === Chara Family (lines 2015-2411) ===
    "Father, mother. Please come back home safely.": "Padre, madre. Por favor regresen a casa sanos y salvos.",
    "(He's making something, mumbling.)": "(Esta haciendo algo, murmurando.)",
    "Craft Amulet": "Fabricar Amuleto",
    "About the Family": "Sobre la Familia",
    "...My parents keep going out into the dangerous areas. I'm still a child to help them, so what I do is to make these amulets for them.": "...Mis padres siguen saliendo a las areas peligrosas. Todavia soy un nino para ayudarlos, asi que lo que hago es hacerles estos amuletos.",
    "What if some bad news reach us even if I try hard making these amulets for their safety?": "Que pasa si nos llegan malas noticias aunque me esfuerce haciendo estos amuletos para su seguridad?",
    "I get startled each time some mail arrives...": "Me asusto cada vez que llega un correo...",
    "Whatever happened to our parents? ~Bursting into crying~": "Que les paso a nuestros padres? ~Se pone a llorar~",
    "Well, then. I'll be your dad!!": "Bueno, entonces. Yo sere tu papa!!",
    "~Keeps crying uncontrollably~ No way!! Mom!! Dad!!": "~Sigue llorando sin control~ No puede ser!! Mama!! Papa!!",
    "Both will be totally fine and return to us soon. So quit it! Did you really have to make him cry, huh?!": "Ambos estaran perfectamente bien y regresaran pronto. Ya basta! De verdad tenias que hacerlo llorar, eh?!",
    "- Yota became disheartened and started making another amulet, quietly. -": "- Yota se desanimo y empezo a hacer otro amuleto, en silencio. -",
    "...Do you have someone you're close to and whom you wish for their wellness?": "...Tienes a alguien cercano a quien le desees bienestar?",
    "If you want an amulet, you can exchange it with the Doram tokens. I have a bunch of amulets with me.": "Si quieres un amuleto, puedes intercambiarlo con los tokens Doram. Tengo un monton de amuletos conmigo.",
    "Low-grade Horse Mackerel Amulet": "Amuleto de Jurel de Baja Calidad",
    "Low-grade Leaf Amulet": "Amuleto de Hoja de Baja Calidad",
    "Low-grade Rabbit Amulet": "Amuleto de Conejo de Baja Calidad",
    "Shining Twig Charm": "Amuleto de Ramita Brillante",
    "Fresh Tuna Amulet": "Amuleto de Atun Fresco",
    "Plump Earthworm Amulet": "Amuleto de Lombriz Gordita",
    "Did...did I misspeak, or what?": "Yo...dije algo malo, o que?",
    "I'm not an expert but I did my best.": "No soy un experto pero hice mi mejor esfuerzo.",
    "I'm sorry. My sister will get pretty mad if I don't sell it for the proper money. Will you come back with 10 Doram Tokens?": "Lo siento. Mi hermana se enojara mucho si no lo vendo por el precio justo. Volveras con 10 Doram Tokens?",
    "Thanks you. I hope my amulet will be of good use to you...": "Gracias. Espero que mi amuleto te sea de buen uso...",
    "Exchange": "Intercambiar",
    "~Whirring~": "~Zumbido~",
    "Here is Jogi, the bomber from Lasagna!": "Aqui esta Jogi, el bombardero de Lasagna!",
    "Drop your weapons and surrender!": "Suelta tus armas y rindete!",
    "Act as if you surrender.": "Actuar como si te rindieras.",
    "Ignore him.": "Ignorarlo.",
    "~Makes a whiffing sound~": "~Hace un sonido de soplido~",
    "~Thumping sound~": "~Sonido de golpe~",
    "Huh? Where do you think you're going?": "Eh? A donde crees que vas?",
    "Wahaha! Another victory for me! What a rewarding day!": "Wahaha! Otra victoria para mi! Que dia tan gratificante!",
    "What should we do next?": "Que hacemos ahora?",
    "Exchange tokens for a weapon.": "Intercambiar tokens por un arma.",
    "My sister told me my parents are warriors! They left for a huge adventure!!": "Mi hermana me dijo que mis padres son guerreros! Se fueron a una gran aventura!!",
    "I'll join the Militia and become great like my parents!": "Me unire a la Milicia y sere grandioso como mis padres!",
    "I'm still too young to join the Militia, but, I'm positive that I can be the ace of the band once I join it because I'm committed to training myself.": "Todavia soy muy joven para unirme a la Milicia, pero estoy seguro de que puedo ser el as del grupo una vez que me una porque estoy comprometido a entrenarme.",
    "My family members are very lazy. Unless I train them based on my strong belief, they can never become warriors.": "Los miembros de mi familia son muy flojos. A menos que los entrene basandome en mi fuerte creencia, nunca podran ser guerreros.",
    "Most notoriously, my elder and younger brother can be a real pain in my neck!": "Los mas notorios son mi hermano mayor y menor que pueden ser un verdadero dolor de cabeza!",
    "Dandi! Today's training is to <put 10 earthworms on the head!> Get over here!": "Dandi! El entrenamiento de hoy es <ponerse 10 lombrices en la cabeza!> Ven aqui!",
    "~Bursting into crying~ Goma Chara!!": "~Se pone a llorar~ Goma Chara!!",
    "That's it?": "Eso es todo?",
    "Search again.": "Buscar de nuevo.",
    "Stop.": "Parar.",
    "~Giggles~ We should see each other more often!": "~Risitas~ Deberiamos vernos mas seguido!",
    "Yay!! Thanks a mil!": "Yay!! Mil gracias!",
    "Can I look for something else?": "Puedo buscar algo mas?",
    "~Scoffs~ Alright, then.": "~Bufido~ Muy bien, entonces.",
    "~Shrieks~ Hi...Hiya...": "~Grito~ Ho...Hola...",
    "You really startled me...I thought it was Jogi.": "De verdad me asustaste...Pense que era Jogi.",
    "Exchange tokens for armor.": "Intercambiar tokens por armadura.",
    "She gets angry easily but makes new clothes for me, saying I deserve pretty ones.": "Se enoja facilmente pero me hace ropa nueva, diciendo que merezco ropa bonita.",
    "I like her...": "Me agrada...",
    "My brothers can be pretty mean. So I try my best to obey what Dandi tells me to.": "Mis hermanos pueden ser bastante malos. Asi que hago mi mejor esfuerzo para obedecer lo que Dandi me dice.",
    "Still, Yota would never show his smiles, while Jogi would bring me hideous stuff like an earthworm, saying I should be tougher. ~Makes a sobbing sound~": "Aun asi, Yota nunca muestra sus sonrisas, mientras que Jogi me trae cosas horrorosas como lombrices, diciendo que deberia ser mas fuerte. ~Hace un sonido de sollozo~",
    "What's more, Jogi keeps wandering near the forest, saying He's going for the Militia. Mom said it's dangerous...": "Ademas, Jogi sigue deambulando cerca del bosque, diciendo que va por la Milicia. Mama dijo que es peligroso...",
    "What if a monster takes my brother away? That monster's gotta hurt a lot...": "Que pasa si un monstruo se lleva a mi hermano? Ese monstruo debe doler mucho...",
    "Do you happen to have any piece of armor to spare for my brother? Would you give it to me? I'll pay for it...": "De casualidad tienes alguna pieza de armadura de sobra para mi hermano? Me la darias? La pagare...",
    "Do you mind if I search you to see the items you have with you?": "Te importa si te reviso para ver los objetos que tienes contigo?",
    "...I think That's just it. Should I look over it again, or stop right here?": "...Creo que eso es todo. Deberia revisarlo de nuevo, o paramos aqui?",
    "I know. I searched into your inventory too much. Sorry...": "Lo se. Revise demasiado tu inventario. Perdon...",
    "Thank you.": "Gracias.",
    "Can I look for something else?\n": "Puedo buscar algo mas?\n",
    "Alright...Thank you for your...help, I guess...": "Bien...Gracias por tu...ayuda, supongo...",
    "I'm Goma Chara, the eldest daughter of the Charas. These brats are who quicken my ageing process...": "Soy Goma Chara, la hija mayor de los Chara. Estos mocosos son los que aceleran mi envejecimiento...",
    "If you happen to have the amulet that my brother Yota made, I can polish it for you.": "Si tienes el amuleto que mi hermano Yota hizo, puedo pulirlo por ti.",
    "Upgrade Amulet": "Mejorar Amuleto",
    "My father was a born seaman so went out into the sea a long time ago, saying he'll catch the world's largest tuna.": "Mi padre era un marinero nato asi que se fue al mar hace mucho tiempo, diciendo que atraparia el atun mas grande del mundo.",
    "My mother can be a collector so she would go into the deepmost side of the forest, looking for the odd fruits. She would come and go even before I know it.": "Mi madre puede ser una coleccionista asi que se adentraria en lo mas profundo del bosque, buscando frutas extranas. Iba y venia antes de que me diera cuenta.",
    "So taking care of these bratty brothers has become my responsibility! I wonder why I was born the eldest! I've almost had it!": "Asi que cuidar a estos hermanos malcriados se ha convertido en mi responsabilidad! Me pregunto por que naci la mayor! Ya casi no aguanto!",
    "Yota! Tidy up your place after making amulets! Pick up the scales of horse mackerels there. Oh, my days...": "Yota! Ordena tu lugar despues de hacer amuletos! Recoge las escamas de jurel de ahi. Ay, cielos...",
    "Jogi, Dandi is about to burst into crying. Please behave yourself, will you?": "Jogi, Dandi esta a punto de ponerse a llorar. Por favor comportate, si?",
    "~Signs deeply~ My head is spinning!": "~Suspira profundamente~ Me da vueltas la cabeza!",
    "I'm sorry but our chit-chat ends here. Time flies when you're busy taking care of little brothers.": "Lo siento pero nuestra charla termina aqui. El tiempo vuela cuando estas ocupada cuidando hermanitos.",
    "Yota often makes quality amulets, but he still needs more polishing.": "Yota a menudo hace amuletos de calidad, pero todavia necesita mas pulido.",
    "If he pays attention to details, his amulets will be even greater. But he just doesn't care.": "Si pusiera atencion a los detalles, sus amuletos serian aun mejores. Pero simplemente no le importa.",
    "Polish the Horse Mackerel Amulet.": "Pulir el Amuleto de Jurel.",
    "Polish the Leaf Amulet.": "Pulir el Amuleto de Hoja.",
    "Polish the Rabbit Amulet.": "Pulir el Amuleto de Conejo.",
    "This amulet is already perfect!": "Este amuleto ya es perfecto!",
    "Show me your amulet, will you? I can't seem to find it in your inventory.": "Muestrame tu amuleto, si? No puedo encontrarlo en tu inventario.",
    "...I knew this was going to happen again. Worse, this one must require a lot more time to polish!": "...Sabia que esto iba a pasar de nuevo. Peor, este debe requerir mucho mas tiempo para pulir!",
    "Upgrade": "Mejorar",
    "As you please.": "Como quieras.",
    "Insufficient materials, can not be repaired free.": "Materiales insuficientes, no se puede reparar gratis.",
    "The inside of this amulet seems pretty tough.": "El interior de este amuleto parece bastante duro.",
    "But my dexterity is tougher. Tada! Put my brother's amulet to good use.": "Pero mi destreza es mas dura. Tadan! Dale buen uso al amuleto de mi hermano.",

    # === Shepherd / Daily Quests (lines 2413-) ===
    "Hey cows- eat a lot and relax a lot- I'll sing you a song-": "Oye vacas- coman mucho y relajense mucho- les cantare una cancion-",
    "I'm sorry to say this when you're working so hard to help us, but how about searching for some other work? I think It's a shame to let your skills go to waste.": "Lamento decir esto cuando te esfuerzas tanto por ayudarnos, pero que tal si buscas otro trabajo? Creo que es una lastima desperdiciar tus habilidades.",
    "I heard that honey collect is in need of help, so you should go see ^4D4DFF[Florin]^000000. Thank you for helping us.": "Escuche que la recoleccion de miel necesita ayuda, asi que deberias ir a ver a ^4D4DFF[Florin]^000000. Gracias por ayudarnos.",
    "I heard that Prok needs some help right now. Why don't you go see ^4D4DFF[Prok]^000000? Thank you for helping us.": "Escuche que Prok necesita algo de ayuda ahora. Por que no vas a ver a ^4D4DFF[Prok]^000000? Gracias por ayudarnos.",
    "Speaking of which, ^4D4DFF[Fisher]^000000 said he needed some help. Would you like to give it a try? Thank you for helping us.": "Hablando de eso, ^4D4DFF[Fisher]^000000 dijo que necesitaba algo de ayuda. Te gustaria intentarlo? Gracias por ayudarnos.",
    "^4D4DFF[Sleepy meow]^000000, who lives over there at the mouth of the cave where basilisks live, is desperately seeking for a strong individual. Perhaps you should give it a try for the experience. Thank you for helping us.": "^4D4DFF[Sleepy meow]^000000, que vive alla en la entrada de la cueva donde viven los basiliscos, busca desesperadamente a alguien fuerte. Quizas deberias intentarlo por la experiencia. Gracias por ayudarnos.",
    "Taking a ship from the ^4D4DFF[dock]^000000 in search of a bigger adventure is also a good idea. Thank you for helping us.": "Tomar un barco desde el ^4D4DFF[muelle]^000000 en busca de una aventura mas grande tambien es buena idea. Gracias por ayudarnos.",
    "Thank you. Now our cows can enjoy delicious meal.": "Gracias. Ahora nuestras vacas pueden disfrutar una deliciosa comida.",
    "But you seem too skilled to do this kind of work. There are many other jobs that require physical strength, so perhaps you should go seek them.": "Pero pareces demasiado habil para este tipo de trabajo. Hay muchos otros trabajos que requieren fuerza fisica, asi que quizas deberias ir a buscarlos.",
    "Not today. Maybe tomorrow? Let me see... Who said needed some help?": "Hoy no. Quizas manana? Dejame ver... Quien dijo que necesitaba ayuda?",
    "Hello, are you the person who's here to help us? Then you can start now.": "Hola, eres la persona que vino a ayudarnos? Entonces puedes empezar ahora.",
    "What is going on?": "Que esta pasando?",
    "I'm not working.": "No voy a trabajar.",
    "Work? That's out of the blue. No, I won't do it!": "Trabajar? Eso es de la nada. No, no lo hare!",
    "If you need help, then you should at least tell me what I should do.": "Si necesitas ayuda, entonces al menos deberias decirme que debo hacer.",
    "Oh, didn't the Chef tell you? I'm sorry, most people come here after hearing the details from him.": "Oh, el Chef no te lo dijo? Lo siento, la mayoria de la gente viene aqui despues de escuchar los detalles de el.",
    "Those Grass Fabres and Leaf Lunatics are eating away the entire grass. But they shouldn't because they're leaving my cute cows here with no food.": "Esos Grass Fabres y Leaf Lunatics se estan comiendo todo el pasto. Pero no deberian porque dejan a mis lindas vacas sin comida.",
    "Our cows have nothing to eat then.": "Entonces nuestras vacas no tienen nada que comer.",
    "If our cows can't eat grass, then we can't milk them. If we have no fresh milk, then we can't make kaluna milk.": "Si nuestras vacas no pueden comer pasto, no podemos ordenarlas. Si no tenemos leche fresca, no podemos hacer leche kaluna.",
    "And... Oh, I don't even want to imagine after that.": "Y... Oh, ni siquiera quiero imaginar despues de eso.",
}

def translate_file(input_path, output_path):
    """Read the input file and translate all dialogue strings."""
    with open(input_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    translated_count = 0
    untranslated = set()

    output_lines = []
    for line_num, line in enumerate(lines, 1):
        new_line = line

        # Process mes "..." strings
        # Pattern: mes "...";
        mes_matches = list(re.finditer(r'(mes\s+")(.*?)(";)', line))
        if mes_matches:
            for match in reversed(mes_matches):  # reverse to maintain positions
                text = match.group(2)
                # Skip empty strings, NPC names in brackets, and strings that are just variables
                if not text or text.startswith('[') or text.startswith('!- Notice -!') or text.startswith('!- Aviso -!'):
                    if text == '!- Notice -!':
                        new_line = new_line[:match.start(2)] + '!- Aviso -!' + new_line[match.end(2):]
                        translated_count += 1
                    continue

                # Check for translation
                if text in TRANSLATIONS:
                    translated = TRANSLATIONS[text]
                    # Replace double quotes with single quotes in translation
                    translated = translated.replace('"', "'")
                    new_line = new_line[:match.start(2)] + translated + new_line[match.end(2):]
                    translated_count += 1
                else:
                    # Check if it contains only variables/code or NPC name brackets
                    if not re.match(r'^\[.*\]$', text) and not re.match(r'^[\s.]*$', text):
                        # Check if it has actual English text (not just codes/vars)
                        clean = re.sub(r'\^[0-9a-fA-F]{6}', '', text)
                        clean = re.sub(r'\^000000', '', clean)
                        if re.search(r'[a-zA-Z]{3,}', clean):
                            untranslated.add(text[:80])

        # Process select("...") strings - find the select() call and translate each option
        select_full = re.search(r'select\((.*)\)', new_line)
        if select_full:
            content = select_full.group(1)
            option_matches = list(re.finditer(r'"(.*?)"', content))
            if option_matches:
                for opt_match in reversed(option_matches):
                    opt_text = opt_match.group(1)
                    if opt_text in TRANSLATIONS:
                        translated = TRANSLATIONS[opt_text].replace('"', "'")
                        abs_start = select_full.start(1) + opt_match.start(1)
                        abs_end = select_full.start(1) + opt_match.end(1)
                        new_line = new_line[:abs_start] + translated + new_line[abs_end:]
                        translated_count += 1

        # Process npctalk "..." strings
        npctalk_matches = list(re.finditer(r'(npctalk\s+")(.*?)(")', line))
        if npctalk_matches:
            for match in reversed(npctalk_matches):
                text = match.group(2)
                if text in TRANSLATIONS:
                    translated = TRANSLATIONS[text].replace('"', "'")
                    new_line = new_line[:match.start(2)] + translated + new_line[match.end(2):]
                    translated_count += 1
                elif text and re.search(r'[a-zA-Z]{3,}', text):
                    untranslated.add("npctalk: " + text[:80])

        output_lines.append(new_line)

    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.writelines(output_lines)

    print(f"Translated {translated_count} strings")
    print(f"Untranslated unique strings: {len(untranslated)}")
    if untranslated:
        print("\nSample untranslated (first 30):")
        for i, s in enumerate(sorted(untranslated)):
            if i >= 30:
                break
            print(f"  {s}")

if __name__ == '__main__':
    input_file = 'lasagna_npcs.txt'
    output_file = 'lasagna_npcs_translated.txt'
    translate_file(input_file, output_file)
