#!/usr/bin/env python3
"""
Translate academy.txt English dialogue to LATAM Spanish (informal 'tu').
Only translates text inside mes "...", select("..."), npctalk "...", and mapannounce ... "..." strings.
Preserves NPC names in brackets [Name], color codes ^RRGGBB, variables, functions, script logic.
"""

import re
import sys

# Build a comprehensive translation dictionary
# Key: exact English string content (inside quotes), Value: Spanish translation
TRANSLATIONS = {
    # mapannounce strings (already done in file, but keeping for reference)
    "[Tip] You can move to the desired point by clicking the ground with the left mouse button.":
        "[Consejo] Puedes moverte al punto deseado haciendo clic en el suelo con el boton izquierdo del mouse.",
    "[Tip] While holding down the right mouse button, drag to rotate the screen.":
        "[Consejo] Mientras mantienes presionado el boton derecho del mouse, arrastra para rotar la pantalla.",
    "[Tip] You can leave through the bluish warp gate.":
        "[Consejo] Puedes salir a traves del portal de teletransporte azulado.",
    "[Tip] Leave this area to continue.":
        "[Consejo] Sal de esta area para continuar.",

    # npctalk strings
    "Urgh... please... help me...":
        "Urgh... por favor... ayudame...",
    "In order to talk with me.. click my body..":
        "Para hablar conmigo.. haz clic en mi cuerpo..",

    # Wounded Swordsman
    "Wow! Thanks a lot!": "Wow! Muchas gracias!",
    "I don't know how this happened to our ship": "No se como le paso esto a nuestro barco",
    "but we should go to see the captain.": "pero deberiamos ir a ver al capitan.",
    "... ohh, it seems my body is too injured.": "... ohh, parece que mi cuerpo esta muy herido.",
    "Maybe you can go without me?": "Tal vez puedas ir sin mi?",
    "^4d4dff!- Information -!^000000": "^4d4dff!- Informacion -!^000000",
    "NPC Quest Received.": "Quest de NPC recibida.",
    "Luckily the water has not entered the ship.": "Por suerte el agua no ha entrado al barco.",
    "I will wait here, you should go see the captain.": "Esperare aqui, tu deberias ir a ver al capitan.",
    "I'm fine! I'm fine!": "Estoy bien! Estoy bien!",
    "Don't worry about me, you should really go to the captain!": "No te preocupes por mi, de verdad ve con el capitan!",
    "^4d4dffQuestinfo Shortcut is Alt + U^000000": "^4d4dffEl atajo de Questinfo es Alt + U^000000",
    "You can check your quest status there anytime.": "Puedes revisar el estado de tus quests ahi en cualquier momento.",

    # Captain Carocc (Ship)
    "There are still people in the cabins?!": "Todavia hay gente en las cabinas?!",
    "At least you are safe.": "Al menos tu estas a salvo.",
    "Are you alright?": "Estas bien?",
    "I'm alright, but others need help.": "Estoy bien, pero otros necesitan ayuda.",
    "I think I am the last?": "Creo que soy el ultimo?",
    "There are more people left?": "Hay mas gente ahi?",
    "I will send a rescue team to them.": "Enviare un equipo de rescate por ellos.",
    "Thank you for your report.": "Gracias por tu reporte.",
    "Alright, that's good.": "Bien, que bueno.",
    "The storm came unexpectedly but I never thought it would hit us that hard.": "La tormenta llego de repente pero nunca pense que nos golpearia tan fuerte.",
    "At least most people made it to safety.": "Al menos la mayoria llego a un lugar seguro.",
    "Look at the trees there, ^4d4dfffollow them to the southwest^000000 to find a new ship.": "Mira los arboles de alla, ^4d4dffsiguelos hacia el suroeste^000000 para encontrar un nuevo barco.",
    "The ship will take you to ^4d4dffIzlude^000000, our original destination.": "El barco te llevara a ^4d4dffIzlude^000000, nuestro destino original.",
    "Ah! Speaking of it, those ^4d4dffPorings^000000 on this island drop several materials we could use for repairs.": "Ah! Hablando de eso, esos ^4d4dffPorings^000000 en esta isla sueltan varios materiales que podriamos usar para reparaciones.",
    "^4d4dffKill the Porings and bring 2 Lumbers to the southern crew^000000.": "^4d4dffMata a los Porings y lleva 2 Lumber a la tripulacion del sur^000000.",
    "It is a hard task, but you look tough enough.": "Es una tarea dificil, pero te ves lo suficientemente fuerte.",
    "Speaking of Porings, you have to equip your gears.": "Hablando de Porings, tienes que equipar tu equipo.",
    "You should have a ^4d4dffweapon and an armor^000000 equipped.": "Deberias tener ^4d4dffun arma y una armadura^000000 equipadas.",
    "!- Information -!": "!- Informacion -!",
    "^4d4dffYou can equip gear or use items by simply double clicking them.": "^4d4dffPuedes equipar equipo o usar items simplemente haciendo doble clic en ellos.",
    "The item window can be opened by pressing Alt + E or using the menu button.^000000": "La ventana de items se puede abrir presionando Alt + E o usando el boton del menu.^000000",
    "^4d4dffEquipped Items can be seen by pressing Alt + Q.": "^4d4dffLos items equipados se pueden ver presionando Alt + Q.",
    "Either double click or drag & drop to equip or unequip them.^000000": "Haz doble clic o arrastra y suelta para equipar o desequipar.^000000",
    "Did you check all your equipment?": "Revisaste todo tu equipo?",
    "^4d4dffSkill distribution^000000 should be done.": "La ^4d4dffdistribucion de skills^000000 deberia estar hecha.",
    "For a smooth battle, you have to distribute your abilities properly.": "Para una batalla fluida, tienes que distribuir tus habilidades correctamente.",
    "^4d4dffIf you want to increase your strength, you need to raise Str^000000. ^4d4dffIf you want to increase your hit, you must raise Dex^000000.": "^4d4dffSi quieres aumentar tu fuerza, necesitas subir Str^000000. ^4d4dffSi quieres aumentar tu precision, debes subir Dex^000000.",
    "^4d4dffThe Ship^000000 is anchored in the southwest. It will take you to Izlude.": "^4d4dffEl Barco^000000 esta anclado en el suroeste. Te llevara a Izlude.",
    "Don't forget to ^4d4dffget some Lumber^000000 for the ship.": "No olvides ^4d4dffconseguir algo de Lumber^000000 para el barco.",
    "Don't forget to raise your ^4d4dffskills^000000.": "No olvides subir tus ^4d4dffskills^000000.",
    "Everything is ready to sail over to Izlude.": "Todo esta listo para zarpar hacia Izlude.",
    "The ship is located at the south-western part of the island.": "El barco esta ubicado en la parte suroeste de la isla.",
    "! - Information -!": "! - Informacion -!",
    "^4d4dffYou get a stats bonus for every level you raise.": "^4d4dffObtienes un bonus de stats por cada nivel que subas.",
    "The status window can be opened and closed with the shortcut Alt + A^000000.": "La ventana de estado se puede abrir y cerrar con el atajo Alt + A^000000.",
    "^4d4dffPlease properly allocate the stats you need to battle^000000.": "^4d4dffPor favor asigna correctamente los stats que necesitas para combatir^000000.",
    "Kill Porings and bring the Lumber to the crew.": "Mata Porings y lleva el Lumber a la tripulacion.",
    "Good luck!": "Buena suerte!",

    # Lumin
    "Had a good dream?": "Tuviste un buen sueno?",
    "Soon, we will get to Izlude. And you can talk to other people like you just talked to me.": "Pronto llegaremos a Izlude. Y podras hablar con otras personas como acabas de hablar conmigo.",
    "I think that guy over there lost his memory. I gave him a new name.": "Creo que ese chico de alla perdio la memoria. Le di un nuevo nombre.",
    "Many youngsters visit the ^4d4dffRune-Midgarts Kingdom^000000 to chase their dreams.": "Muchos jovenes visitan el ^4d4dffRune-Midgarts Kingdom^000000 para perseguir sus suenos.",
    "Izlude is a satellite city of Prontera, the capital of the Rune-Midgarts Kingdom.": "Izlude es una ciudad satelite de Prontera, la capital del Rune-Midgarts Kingdom.",
    "Izlude always welcomes young adventurers like you who have just started their journey through the world.": "Izlude siempre da la bienvenida a jovenes aventureros como tu que acaban de comenzar su viaje por el mundo.",
    "You are one of them, of course.": "Tu eres uno de ellos, por supuesto.",
    "I would like to tell you more stories, but it's time to get ready for arrival.": "Me gustaria contarte mas historias, pero es hora de prepararse para la llegada.",
    "There is an academy in Izlude for newcomers like yourself.": "Hay una academia en Izlude para los recien llegados como tu.",
    "Let me give you more details later. See you back at the harbor deck.": "Dejame darte mas detalles despues. Nos vemos en la cubierta del puerto.",
    "To get off this ship, you should enter the ^4d4dffShining Portal^000000 over there.": "Para bajar de este barco, debes entrar al ^4d4dffPortal Brillante^000000 de alla.",
    "All transportation is made through the portals.": "Todo el transporte se hace a traves de los portales.",
    "Yes.": "Si.",
    "Oh boy.": "Oh vaya.",
    "What a cute reaction.": "Que reaccion tan tierna.",
    "Should I introduce myself?', 'My name is ~!": "Deberia presentarme?', 'Mi nombre es ~!",
    "I am " : "Soy ",
    "....So?": "....Y?",
    "- Lu just walked away with a cynical look on his face.": "- Lu se fue con una mirada cinica en su rostro.",
    "Looks like... he has a shy personality.": "Parece que... tiene una personalidad timida.",
    "When you go to Izlude, will you check on him?": "Cuando vayas a Izlude, podrias ver como esta?",
    "From now on I'll be sailing the ship around the island.": "De ahora en adelante estare navegando el barco alrededor de la isla.",
    "Let's go, shall we?": "Vamos, si?",

    # Sailor
    "These Porings stole my materials to repair the ship. Can you help me to get them back?": "Estos Porings robaron mis materiales para reparar el barco. Puedes ayudarme a recuperarlos?",
    "There are plenty of Porings on this island.": "Hay muchos Porings en esta isla.",
    "I would really appreciate it if you help me.": "Te agradeceria mucho si me ayudas.",
    "I am not allowed to set foot on this island.": "No tengo permitido pisar esta isla.",
    "That's why I ask for your help~": "Por eso te pido tu ayuda~",
    "Unbelievable, perfect! Any chance you want to join my crew?": "Increible, perfecto! Hay alguna posibilidad de que quieras unirte a mi tripulacion?",
    "Enough talking!!": "Suficiente charla!!",
    "Come on, we're ready to set sail!": "Vamos, estamos listos para zarpar!",
    "Thank you so much!": "Muchas gracias!",
    "If you want to sail with us to Izlude, jump on board!": "Si quieres navegar con nosotros a Izlude, sube a bordo!",
    "Oh, and take these ^4d4dffMagnifiers^000000.": "Oh, y toma estos ^4d4dffMagnifiers^000000.",
    "When you hunt monsters you can find ^4d4dffunidentified items^000000.": "Cuando cazas monstruos puedes encontrar ^4d4dffitems sin identificar^000000.",
    "Using a Magnifier will identify the item.": "Usar un Magnifier identificara el item.",
    "Maybe you already have some unidentified items from your fights with those Porings?": "Tal vez ya tengas algunos items sin identificar de tus peleas con esos Porings?",
    "The ship is heading to Izlude soon~!": "El barco se dirige a Izlude pronto~!",
    "I'll let you know when we set sail~!": "Te avisare cuando zarpemos~!",

    # Captain Carocc (Izlude)
    "Why are you here at the wharf?": "Que haces aqui en el muelle?",
    "I guess you are doing well at the academy.": "Supongo que te va bien en la academia.",
    "I'm going to be docking and reparing the ship here for a while.": "Voy a estar atracando y reparando el barco aqui por un tiempo.",
    "I will be taking the same route I tried before.": "Tomare la misma ruta que intente antes.",
    "Hmm? You must be a student of the Criatura Academy?": "Hmm? Debes ser un estudiante de la Criatura Academy?",
    "Were you on my ship?": "Estabas en mi barco?",
    "Hmm I can't remember.": "Hmm no puedo recordar.",
    "Well, anything is fine.": "Bueno, lo que sea esta bien.",
    "Shall I go easy on you since you said you were a student of the Academy?": "Deberia ser amable contigo ya que dices que eres estudiante de la Academia?",
    "I am still the captain of the ship, regardless.": "Sigo siendo el capitan del barco, de todas formas.",
    "I plan on taking off as soon as the repairs are complete.": "Planeo zarpar tan pronto como las reparaciones esten completas.",
    "The route will open with ^4d4dffPharos Lighthouse^000000 by then.": "La ruta se abrira con ^4d4dffPharos Lighthouse^000000 para entonces.",
    "This is Izlude.": "Esta es Izlude.",
    "The best city for you to take wings to your dreams.": "La mejor ciudad para que le des alas a tus suenos.",
    "Although I don't have any particular feelings for you,": "Aunque no tengo sentimientos particulares por ti,",
    "I've seen a lot of young people like you, while operating the ship.": "He visto a muchos jovenes como tu, mientras operaba el barco.",
    "There were those among them who succeeded and failed and went back after being unable to adjust.": "Hubo quienes tuvieron exito y quienes fracasaron y regresaron sin poder adaptarse.",
    "I want you to have a successful start with this place.": "Quiero que tengas un comienzo exitoso en este lugar.",
    "Did you know this?": "Sabias esto?",
    "Izlude has a new Institute for budding adventurers like you!": "Izlude tiene un nuevo Instituto para aventureros novatos como tu!",
    "You mean the Academy?": "Te refieres a la Academia?",
    "Yes! It's called the ^4d4dffRoyal Criatura Academy^000000.": "Si! Se llama la ^4d4dffRoyal Criatura Academy^000000.",
    "Founded by the Rune-Midgarts lineage to help out new adventurers.": "Fundada por el linaje de Rune-Midgarts para ayudar a nuevos aventureros.",
    "A friend of mine works there, so I'll give you the introduction to him.": "Un amigo mio trabaja ahi, asi que te dare una introduccion con el.",
    "He could make a lot of things easier for you.": "El podria hacer muchas cosas mas faciles para ti.",
    "He usually talks to new adventurers near the entrance of the academy.": "El suele hablar con nuevos aventureros cerca de la entrada de la academia.",
    "Go and meet him there.": "Ve y conocelo ahi.",
    "His name is ^4d4dffHun^000000": "Su nombre es ^4d4dffHun^000000",
    "I will mark his spot on the map so go to see him.": "Marcare su ubicacion en el mapa, asi que ve a verlo.",
    "The ^4d4dffMini map can be seen on the right top of the screen.": "El ^4d4dffMini mapa se puede ver en la parte superior derecha de la pantalla.",
    "You can zoom in with +, zoom out with -. The waypoint from the NPC will be marked on it. ^000000": "Puedes acercar con +, alejar con -. El punto de referencia del NPC se marcara en el. ^000000",
    "Received a Quest from ^4d4dffCaptain Carocc.": "Quest recibida de ^4d4dffCaptain Carocc.",
    "The quest content can be checked from the quest window.": "El contenido de la quest se puede verificar desde la ventana de quests.",
    "Quest window can be opened by pressing ^4d4dffAlt + u^000000 keys together.": "La ventana de quests se puede abrir presionando las teclas ^4d4dffAlt + u^000000 juntas.",
    "If you need more help with the map, press <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> here": "Si necesitas mas ayuda con el mapa, presiona <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> aqui",
    "Yes, the part that says 'Hun'.": "Si, la parte que dice 'Hun'.",
    "^4d4dffThe icon during talk <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> means a link to navigation directions.": "^4d4dffEl icono durante la charla <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> significa un enlace a direcciones de navegacion.",
    "If you press info after selecting a task in the objectives^4d4dff,": "Si presionas info despues de seleccionar una tarea en los objetivos^4d4dff,",
    "an arrow pointing to the location of the objective will pop up along with the navigation help.": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion.",
    "Anyway, my friend will help you register with the academy": "De todas formas, mi amigo te ayudara a registrarte en la academia",
    "I hope it can help you for your future.": "Espero que pueda ayudarte para tu futuro.",
    "I know who you're talking about.": "Se de quien hablas.",
    "Then there's no worry.": "Entonces no hay de que preocuparse.",
    "He'll introduce you to the academy.": "El te presentara la academia.",
    "OK. I will show you the direction. You try it again.": "OK. Te mostrare la direccion. Intentalo de nuevo.",
    "By the way, did I tell you his name? His name is ^4d4dffHun^000000": "Por cierto, te dije su nombre? Su nombre es ^4d4dffHun^000000",
    "^4d4dff Mini map can be seen on the right top of the screen.": "^4d4dff El Mini mapa se puede ver en la parte superior derecha de la pantalla.",
    "Yes, the part that says [Hun].": "Si, la parte que dice [Hun].",
    "^4d4dff the icon during talk <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> means": "^4d4dff el icono durante la charla <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> significa",
    "a link to navigation directions.": "un enlace a direcciones de navegacion.",
    "an arrow pointing to the location of the objective will pop up along with navigation help": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion",
    "an arrow pointing to the location of the objective will pop up along with navigation help.": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion.",
    "I hope it will help you out in your journey": "Espero que te ayude en tu viaje",
    "I hope it will help you out in your journey.": "Espero que te ayude en tu viaje.",
    "Anyway, my friend will help you register with the academy.": "De todas formas, mi amigo te ayudara a registrarte en la academia.",
    "If you want, you can step forward to the world right away.": "Si quieres, puedes avanzar al mundo de inmediato.",
    "However, I recommend you visit the Academy first.": "Sin embargo, te recomiendo visitar la Academia primero.",
    "The world is a lonely place to be alone.": "El mundo es un lugar solitario para estar solo.",
    "The Academy has people you can make as lifetime companions.": "La Academia tiene personas que puedes hacer companeros de por vida.",
    "The Academy has people you could make into lifetime companions.": "La Academia tiene personas que podrias hacer companeros de por vida.",
    "My friend Hun will be around the academy entrance.": "Mi amigo Hun estara cerca de la entrada de la academia.",
    "If you don't know the way I'll point it out to you again.": "Si no conoces el camino te lo indicare de nuevo.",
    "Yes, the part that says ''Hun''.": "Si, la parte que dice ''Hun''.",
    "Still being dilligent?": "Sigues siendo diligente?",
    "I've been busy, also.": "Yo tambien he estado ocupado.",
    "I was reparing the ship.": "Estaba reparando el barco.",
    "I'll be taking off as soon as the repairs are complete.": "Zarpare tan pronto como las reparaciones esten completas.",
    "At that time, the sailing route to ^4d4dffPharos lighthouse ^000000will be opened.": "En ese momento, la ruta de navegacion hacia ^4d4dffPharos lighthouse ^000000sera abierta.",
    "Be excited for it.": "Esperalo con emocion.",
    "Hello?": "Hola?",
    "Is it your first time on Izlude?": "Es tu primera vez en Izlude?",
    "Hello?', 'Let me get on the ship!', 'I don't know what to do.": "Hola?', 'Dejame subir al barco!', 'No se que hacer.",
    "You look strong and able!": "Te ves fuerte y capaz!",
    "I like able people like you!": "Me gusta la gente capaz como tu!",
    "Always be healthy and strong as you are now.": "Siempre estate sano y fuerte como estas ahora.",
    "I usually travel to ^4d4dffPharos Lighthouse^000000.": "Normalmente viajo a ^4d4dffPharos Lighthouse^000000.",
    "But I'm resting up due to some problems.": "Pero estoy descansando debido a algunos problemas.",
    "If it's Alberta or Byalan Island, talk to the next sailor.": "Si es Alberta o Byalan Island, habla con el siguiente marinero.",
    "Hmm? You said you didn't know what to do.": "Hmm? Dijiste que no sabias que hacer.",
    "Since you're at Izlude, why don't you visit ^4d4dffCriatura Academy^000000?": "Ya que estas en Izlude, por que no visitas ^4d4dffCriatura Academy^000000?",
    "Izlude has the Institute for budding adventurers like you": "Izlude tiene el Instituto para aventureros novatos como tu",
    "He ususally talks to new adventurers near the entrance of an academy.": "El suele hablar con nuevos aventureros cerca de la entrada de la academia.",
    "Go and meet him personally.": "Ve y conocelo personalmente.",
    "I will mark his location on the map so go to see him.": "Marcare su ubicacion en el mapa, asi que ve a verlo.",
    "Contents of your Quest can be monitored on the Quest information window.": "El contenido de tu Quest se puede revisar en la ventana de informacion de Quests.",
    "Quest window can be opened by pressing the ^4d4dffAlt + u^000000 key.": "La ventana de Quest se puede abrir presionando la tecla ^4d4dffAlt + u^000000.",
    "Ah, it's you.": "Ah, eres tu.",
    "This guy has also decided to register at Criatura Academy.": "Este chico tambien decidio registrarse en Criatura Academy.",
    "This might be a good destiny for you. Hope you and him can be good friends.": "Este podria ser un buen destino para ti. Espero que tu y el puedan ser buenos amigos.",
    "My friend <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> will be around the academy entrance.": "Mi amigo <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> estara cerca de la entrada de la academia.",
    "then, Good luck!": "entonces, Buena suerte!",
    "Oh, We meet again.": "Oh, nos vemos de nuevo.",
    "Do you by any chance need a ship?": "De casualidad necesitas un barco?",
    "I usually travel to the port in Paros.": "Normalmente viajo al puerto en Paros.",
    "If you need to go to Paros later, come see me.": "Si necesitas ir a Paros despues, ven a verme.",
    "It's been a while!": "Ha pasado un tiempo!",
    "Looking at your expression, you must be doing well.": "Mirando tu expresion, te debe estar yendo bien.",
    "Take me to Pharos Lighthouse', 'To Alberta', 'Talk": "Llevame a Pharos Lighthouse', 'A Alberta', 'Hablar",
    "Do you want to go to Pharos Lighthouse on the southern coast of Morocc?": "Quieres ir a Pharos Lighthouse en la costa sur de Morocc?",
    "The fee is 2800 zeny. I have a crew that needs payment so this fee is non-negotiable.": "La tarifa es 2800 zeny. Tengo una tripulacion que necesita pago asi que esta tarifa no es negociable.",
    "To Pharos Lighthouse!', 'Cancel": "A Pharos Lighthouse!', 'Cancelar",
    "Let us travel with the wing in our hair.": "Viajemos con el viento en nuestro cabello.",
    "Sorry but you are short of the boarding fee.": "Lo siento pero te falta dinero para la tarifa de embarque.",
    "I need 2800z to operate.": "Necesito 2800z para operar.",
    "OK.": "OK.",
    "Do you know this, by the way?": "Sabias esto, por cierto?",
    "^4d4dffThere's a Rogue hideout at Pharos Lighthouse^000000.": "^4d4dffHay un escondite de Rogues en Pharos Lighthouse^000000.",
    "You already knew this?": "Ya lo sabias?",
    "I thought you knew that I only go to Pharos?": "Pense que sabias que solo voy a Pharos?",
    "Ask the sailor over there, he's the one that goes there frequently.": "Preguntale al marinero de alla, el es quien va ahi frecuentemente.",
    "There are plenty of other ships that travel to Alberta and Byalan Islands.": "Hay muchos otros barcos que viajan a Alberta y Byalan Islands.",
    "Hmm. I'm content with the well being of you and other adventurers who passed me by.": "Hmm. Estoy contento con el bienestar tuyo y de otros aventureros que pasaron por aqui.",
    "Lumin must be doing well too.": "Lumin tambien debe estar bien.",
    "I wonder why you feel like my own child even though we've only met from the sea.": "Me pregunto por que siento que eres como mi propio hijo aunque solo nos conocimos en el mar.",
    "I am Carocc, the caption of this ship.": "Soy Carocc, el capitan de este barco.",
    "Do you need a ship?": "Necesitas un barco?",
    "Pharos Lighthouse - 2800z', 'Don't need it.": "Pharos Lighthouse - 2800z', 'No lo necesito.",
    "Let us travel with the wind in our hair.": "Viajemos con el viento en nuestro cabello.",
    "Then use it next time.": "Entonces usalo la proxima vez.",

    # Criatura Academy Staff (Hun)
    "Quest cannot be continued due to the overfilled inventory.": "La quest no puede continuar debido al inventario lleno.",
    "Continue the quest after organizing the inventory.": "Continua la quest despues de organizar el inventario.",
    "Oh.. you must be the adventurer Carocc was talking about.": "Oh.. debes ser el aventurero del que Carocc hablaba.",
    "I don't know where your homeland is but Midgard is a good place to start your life's journey.": "No se de donde vienes pero Midgard es un buen lugar para comenzar el viaje de tu vida.",
    "It's a good sight to see new adventurers start their journey.": "Es agradable ver a nuevos aventureros comenzar su viaje.",
    "You must be tired. Need a drink?": "Debes estar cansado. Necesitas algo de beber?",
    "You can open the Item window by clicking on the 'item' icon on top left portion of the screen.": "Puedes abrir la ventana de Items haciendo clic en el icono de 'item' en la parte superior izquierda de la pantalla.",
    "The items are automatically catagorized by 'consumables' 'equipment' 'etcetera' and 'personal' suitable for each use.": "Los items se categorizan automaticamente en 'consumibles' 'equipo' 'etcetera' y 'personal' segun su uso.",
    "It will do the automatic sorting per indiviaul useage to": "Hara la clasificacion automatica por uso individual",
    "Either ^4d4dffdouble click on the item^000000 you intend to use": "Haz ^4d4dffdoble clic en el item^000000 que quieras usar",
    "or drag it onto^4d4dff the equipment window and use it^000000": "o arrastarlo a^4d4dff la ventana de equipo y usarlo^000000",
    "^4d4dffItems can be used or equipped with simply double-clicking.": "^4d4dffLos items se pueden usar o equipar simplemente con doble clic.",
    "Item window can be opened with shortcut key Alt+E": "La ventana de items se puede abrir con el atajo Alt+E",
    "^4d4dff Equipped items can be checked with Alt+ Q": "^4d4dff Los items equipados se pueden revisar con Alt+ Q",
    "Items can also be dragged onto the location where you wish to equip it.": "Los items tambien se pueden arrastrar a la ubicacion donde deseas equiparlos.",
    "For detailed info on individual items^4d4dff, right click ^000000on that item.": "Para info detallada de items individuales^4d4dff, haz clic derecho ^000000en ese item.",
    "You can check the detailed info on the item.": "Puedes revisar la info detallada del item.",
    "^4d4dffRight-clicking on the item icon^4d4dff  brings up detailed info on the item.": "^4d4dffHacer clic derecho en el icono del item^4d4dff  muestra la info detallada del item.",
    "^4d4dffWhen you select other players, you can trade, party up with them with the community window that pops up.": "^4d4dffCuando seleccionas a otros jugadores, puedes comerciar, hacer party con ellos con la ventana de comunidad que aparece.",
    "Ok now ^4d4dffdrink the apple juice that I gave you^000000.": "Ok ahora ^4d4dfftoma el jugo de manzana que te di^000000.",
    "Hey there.": "Hola.",
    "Rest up for a bit.": "Descansa un poco.",
    "It's joyous to see new adventurers starting out.": "Es alegre ver a nuevos aventureros comenzando.",
    "You want something to drink while you are resting?": "Quieres algo de beber mientras descansas?",
    "Right clicking on the item icon ^4d4dffon the basic item window at the upper left corner brings up the detailed info on the item": "Hacer clic derecho en el icono del item ^4d4dffen la ventana basica de items en la esquina superior izquierda muestra la info detallada del item",
    "For detailed info on individual items^4d4dff, right-click ^000000on the item.": "Para info detallada de items individuales^4d4dff, haz clic derecho ^000000en el item.",
    "Right clicking on the item icon ^4d4dffbrings up the detailed info on the item": "Hacer clic derecho en el icono del item ^4d4dffmuestra la info detallada del item",
    "When you select on other players^4d4dff you can trade, party up with them with the community window that pops up.": "Cuando seleccionas a otros jugadores^4d4dff puedes comerciar, hacer party con ellos con la ventana de comunidad que aparece.",
    "Consume the apple juice that I gave you in your inventory.": "Consume el jugo de manzana que te di en tu inventario.",
    "Then we'll talk.": "Luego hablamos.",
    "How's the taste?": "Que tal el sabor?",
    "Pretty good-taste of sweet and sour, right? It might not be much but it also has healing properties.": "Bastante buen sabor agridulce, verdad? Puede que no sea mucho pero tambien tiene propiedades curativas.",
    "I want to give you more but that was the last of it": "Quisiera darte mas pero eso fue lo ultimo",
    "Anyways here's some potions. They'll come in handy when you start fighting.": "De todas formas aqui hay algunas pociones. Te seran utiles cuando empieces a pelear.",
    "Criatura Academy is a good place to build up experience for the future.": "Criatura Academy es un buen lugar para acumular experiencia para el futuro.",
    "And I'm not just saying this because I work here.": "Y no lo digo solo porque trabajo aqui.",
    "I'm for real... haha": "En serio... jaja",
    "What do you plan to do from now on?": "Que planeas hacer de ahora en adelante?",
    "Have you found a place to stay?": "Has encontrado un lugar donde quedarte?",
    "I need help with that', 'Anything will do really.', 'Don't worry.": "Necesito ayuda con eso', 'Cualquier cosa esta bien.', 'No te preocupes.",
    "But still, though.": "Pero aun asi.",
    "It's tough to be out alone in a new place.": "Es dificil estar solo en un lugar nuevo.",
    "That's why Criatura Academy is there.": "Por eso esta Criatura Academy.",
    "Carocc sent you to me probably for the same reason.": "Carocc te envio conmigo probablemente por la misma razon.",
    "Even though I'm just a work-hand here, I could show you around.": "Aunque solo soy un trabajador aqui, podria mostrarte el lugar.",
    "If you follow this road up to north, you can see": "Si sigues este camino hacia el norte, puedes ver",
    "Anybody can enroll, so take advantage of it.": "Cualquiera puede inscribirse, asi que aprovechalo.",
    "Sorry to interrupt.": "Disculpa la interrupcion.",
    "But ^4d4dffif you need location info, please ask me.^000000": "Pero ^4d4dffsi necesitas informacion de ubicaciones, preguntame a mi.^000000",
    "Hun's information has limits": "La informacion de Hun tiene limites",
    "Hun's information has limits.": "La informacion de Hun tiene limites.",
    "How optimistic of you.": "Que optimista eres.",
    "If you need help, feel free to visit Criatura Academy any time.": "Si necesitas ayuda, sientete libre de visitar Criatura Academy en cualquier momento.",
    "There's no requirement or payment to enroll so it would be a great help to you.": "No hay requisito ni pago para inscribirse asi que te seria de gran ayuda.",
    "When you go through this way to the north, you'll find": "Cuando vayas por este camino hacia el norte, encontraras",
    "If there are more adventurers like you, the future will be brighter.": "Si hay mas aventureros como tu, el futuro sera mas brillante.",
    "Hahahaha.": "Jajajaja.",
    "You already have a plan laid out?": "Ya tienes un plan?",
    "Well prepared.": "Bien preparado.",
    "But just in case, if you are curious about the Criatura Academy, make a visit.": "Pero por si acaso, si tienes curiosidad sobre Criatura Academy, dale una visita.",
    "What is well, is well- isn't it?": "Lo que esta bien, esta bien- no?",
    "You are correct.": "Tienes razon.",
    "Preperation is the key.": "La preparacion es la clave.",
    "It's you..": "Eres tu..",
    "I'm not saying this just because I work here.": "No lo digo solo porque trabajo aqui.",
    "For real... hahahaha": "En serio... jajajaja",
    "The Royal Criatura Academy was founded to help budding adventurers on their initial journey.": "La Royal Criatura Academy fue fundada para ayudar a aventureros novatos en su viaje inicial.",
    "Although I'm but a work-hand here, it makes me happy to see students graduate here and become fine members of society.": "Aunque solo soy un trabajador aqui, me hace feliz ver a los estudiantes graduarse y convertirse en buenos miembros de la sociedad.",

    # Information Staff
    "Quest cannot be continued due to the invenory being full.": "La quest no puede continuar debido a que el inventario esta lleno.",
    "Please try it again after re-organizing your items.": "Por favor intentalo de nuevo despues de reorganizar tus items.",
    "Hi, how are you?": "Hola, como estas?",
    "I am in charge of navigation directions for Izlude's key locations": "Estoy a cargo de las direcciones de navegacion para las ubicaciones clave de Izlude",
    "I wish to propose a simple game along with the navigation, would that be ok?": "Quisiera proponerte un juego simple junto con la navegacion, estaria bien?",
    "Sure, let's play!', 'I already know them all.": "Claro, juguemos!', 'Ya los conozco todos.",
    "First of all, how to check the mini-map.": "Primero que nada, como revisar el mini-mapa.",
    "You can check your location through the mini-map at the top right of the screen": "Puedes revisar tu ubicacion a traves del mini-mapa en la parte superior derecha de la pantalla",
    "If you receive information on a town or a city, a waypoint ^4d4dff+^000000 can be marked on the map.": "Si recibes informacion sobre un pueblo o ciudad, un punto de referencia ^4d4dff+^000000 se puede marcar en el mapa.",
    "Press ^4d4dff[Ctrl] and [ ~ ] on your keyboard and you can see the world map^000000.": "Presiona ^4d4dff[Ctrl] y [ ~ ] en tu teclado y podras ver el mapa mundial^000000.",
    "Through the ^4d4dffworld map you can check the location of you, your party members and the level of monsters in the area.^000000": "A traves del ^4d4dffmapa mundial puedes revisar tu ubicacion, la de los miembros de tu party y el nivel de los monstruos en el area.^000000",
    "This is useful info to remember.": "Esta es informacion util para recordar.",
    "Now then, should we play a simple game?": "Ahora bien, jugamos un juego simple?",
    "I will ^4d4dffmark three specific locations on the mini-map.^000000": "Voy a ^4d4dffmarcar tres ubicaciones especificas en el mini-mapa.^000000",
    "Please ^4d4dffvisit those locations ^000000using the waypoints as reference.": "Por favor ^4d4dffvisita esas ubicaciones ^000000usando los puntos de referencia.",
    "Think of it as a treasure hunt and go.": "Piensalo como una busqueda del tesoro y ve.",
    "I've hidden some useful items there.": "He escondido algunos items utiles ahi.",
    "Vist me again after going by all three locations.": "Visitame de nuevo despues de pasar por las tres ubicaciones.",
    "I will check up on it.": "Lo verificare.",
    "Ah, there' somebody who started out right before you!": "Ah, hay alguien que empezo justo antes que tu!",
    "If you don't hurry that person will take all the items!": "Si no te apuras esa persona tomara todos los items!",
    "So, run!": "Asi que, corre!",
    "Do you need information on all the locations of Izlude?": "Necesitas informacion sobre todas las ubicaciones de Izlude?",
    "By clicking on the introduced ^B9062F[base camp name]^000000, I will offer you guidance so follow the ^B9062FRed Arrows^000000.": "Al hacer clic en el ^B9062F[nombre de base]^000000 indicado, te ofrecere guia asi que sigue las ^B9062FFlechas Rojas^000000.",
    "[ Main facilities ]', '[ Guide & Helper ]', 'Mini map marking removal', 'End Conversation": "[ Instalaciones principales ]', '[ Guia y Ayudante ]', 'Eliminar marcas del mini mapa', 'Terminar conversacion",
    "[ Criatura Academy ]', '[ Wharf ]', '[ Airship (International) ]', '[ Arena ]', '[ Shop ]', '[ Swordman Guild ]', '[ Enchant Association ]', '[ Blacksmith's Workshop ]', 'Go back to the previous menu": "[ Criatura Academy ]', '[ Muelle ]', '[ Aeronave (Internacional) ]', '[ Arena ]', '[ Tienda ]', '[ Swordman Guild ]', '[ Enchant Association ]', '[ Blacksmith's Workshop ]', 'Volver al menu anterior",
    "If you are the first time adventurer,": "Si eres un aventurero primerizo,",
    "can offer a lot of info and help.": "puede ofrecerte mucha informacion y ayuda.",
    "Do you need additonal directions?": "Necesitas direcciones adicionales?",
    "Do you need additional directions?": "Necesitas direcciones adicionales?",
    "Through the <NAVI>[Wharf]<INFO>izlude,197,205,</INFO></NAVI> in the north east,": "A traves del <NAVI>[Muelle]<INFO>izlude,197,205,</INFO></NAVI> en el noreste,",
    "^8B4513Alberta^000000 or ^8B4513the Byalan Island^000000 can be visted.": "^8B4513Alberta^000000 o ^8B4513Byalan Island^000000 se puede visitar.",
    "you can go.": "puedes ir.",
    "Byalan Island is the scary place with ^8B4513Izlude dungeon^000000 in it.": "Byalan Island es el lugar aterrador con ^8B4513Izlude dungeon^000000 dentro.",
    "To the southeast, the <NAVI>[Airship]<INFO>izlude,206,75,</INFO></NAVI>": "Al sureste, la <NAVI>[Aeronave]<INFO>izlude,206,75,</INFO></NAVI>",
    "will be connected with the Capital of the republic of Schwarzwald -^8B4513 Juno^000000, and": "estara conectada con la Capital de la republica de Schwarzwald -^8B4513 Juno^000000, y",
    "The capital of the Arunapeltsdom -^8B4513 Rachel ^000000.": "La capital de Arunapeltsdom -^8B4513 Rachel ^000000.",
    "The <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> located in the east": "La <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> ubicada en el este",
    "is for testing your battle ability.": "es para probar tu habilidad de combate.",
    "It's an excellent place.": "Es un lugar excelente.",
    "I will mark the location on the mini map.": "Marcare la ubicacion en el mini mapa.",
    "I will mark the location of the": "Marcare la ubicacion del/de la",
    "on the mini map.": "en el mini mapa.",
    "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> is the place to manage the job transfer to a swordman.": "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> es el lugar para gestionar el cambio de trabajo a swordman.",
    "I will mark the location of the swordman guild on the mini map.": "Marcare la ubicacion del swordman guild en el mini mapa.",
    "[ Eden Group Teleporter ]', '[ Kafra Employee ]', '[ Mesmerizer ]', '[ Wedding Secretary ]', '[ Mercenary Guild Official ]', '[ Taming Merchant ]', 'Go back to the previous menu": "[ Eden Group Teleporter ]', '[ Empleada Kafra ]', '[ Mesmerizer ]', '[ Secretaria de Bodas ]', '[ Oficial del Mercenary Guild ]', '[ Taming Merchant ]', 'Volver al menu anterior",
    "For now, I will mark the location of the": "Por ahora, marcare la ubicacion del/de la",
}

def translate_line(line):
    """Translate a single line, only modifying text inside mes/select/npctalk/mapannounce strings."""
    stripped = line.strip()

    # Skip comments and empty lines
    if stripped.startswith('//') or not stripped:
        return line

    # For each translatable string in our dictionary, do direct replacement
    for eng, spa in TRANSLATIONS.items():
        if eng in line:
            line = line.replace(eng, spa)

    return line

def main():
    input_file = r"D:\Xponzy Network\Ragnarok-Server\rathena\npc\re\jobs\novice\academy.txt"

    with open(input_file, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    # Apply translations
    for eng, spa in TRANSLATIONS.items():
        content = content.replace(eng, spa)

    # Verify line count preserved
    with open(input_file, 'r', encoding='utf-8', errors='replace') as f:
        original_lines = len(f.readlines())

    new_lines = len(content.split('\n'))

    if original_lines != new_lines:
        print(f"WARNING: Line count changed from {original_lines} to {new_lines}")
        sys.exit(1)

    with open(input_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Translation complete. Lines: {new_lines}")

if __name__ == '__main__':
    main()
