import os

base = "D:/Xponzy Network/Ragnarok-Server/rathena/npc/re/instances/"

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    count = 0
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            count += 1
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Translated {os.path.basename(filepath)}: {count} replacements applied")

# ============== SARAH AND FENRIR ==============
sarah_reps = [
    ('mes "- You may proceed after reaching level 145 or over -";', 'mes "- Puedes continuar despues de alcanzar el nivel 145 o superior -";'),
    ('mes "I would say I am Professor Bernhard, the best weapons researcher in Schwarzwald.";', 'mes "Me presento, soy el Profesor Bernhard, el mejor investigador de armas en Schwarzwald.";'),
    ('mes "After endless research I have created various weapons, but I felt something was missing so I found the ancient texts.";', 'mes "Despues de una investigacion interminable he creado varias armas, pero sentia que algo faltaba asi que encontre los textos antiguos.";'),
    ('mes "I found out about the Dimensional Device during my research.";', 'mes "Descubri el Dispositivo Dimensional durante mi investigacion.";'),
    ('mes "I also realized that relics from the glorious past were also needed to create more powerful and superior weapons.";', 'mes "Tambien me di cuenta de que se necesitaban reliquias del glorioso pasado para crear armas mas poderosas y superiores.";'),
    ('mes "That is why..I need you..";', 'mes "Por eso..te necesito..";'),
    ('mes "A longing for accomplishing a powerful weapon as a genuine professor!";', 'mes "Un anhelo de lograr un arma poderosa como un verdadero profesor!";'),
    ('mes "In order to accomplish that, we need shards of Gigantes that once appeared in the past battle of Fenrir and Sarah.";', 'mes "Para lograr eso, necesitamos fragmentos de Gigantes que alguna vez aparecieron en la batalla pasada de Fenrir y Sarah.";'),
    ('mes "I cannot leave my post.";', 'mes "No puedo abandonar mi puesto.";'),
    ('mes "I need a warrior who can bring me the shards instead..";', 'mes "Necesito un guerrero que pueda traerme los fragmentos..";'),
    ('mes "You seem capable.";', 'mes "Pareces capaz.";'),
    ('mes "I will continue discussing this further with your party leader rather than with you.";', 'mes "Continuare discutiendo esto con tu lider de grupo en lugar de contigo.";'),
    ('mes "I need a warrior who can bring me the shard of Gigantes instead..";', 'mes "Necesito un guerrero que pueda traerme los fragmentos de Gigantes..";'),
    ('mes "What do you think?";', 'mes "Que piensas?";'),
    ('mes "Would you go to the past and bring me back the shards of Gigantes?";', 'mes "Irias al pasado y me traerias los fragmentos de Gigantes?";'),
    ('mes "I will make sure to compensate you sufficiently.";', 'mes "Me asegurare de compensarte suficientemente.";'),
    ('select( "No", "Yes" )', 'select( "No", "Si" )'),
    ('mes "Visit me again if you change your mind.";', 'mes "Visitame de nuevo si cambias de opinion.";'),
    ('mes "I set the Dimensional Device to Glast Heim of the past, where Fenrir and Sarah once fought.";', 'mes "Configure el Dispositivo Dimensional hacia el Glast Heim del pasado, donde Fenrir y Sarah alguna vez lucharon.";'),
    ("mes \"The operating time isn't long so hurry up and come back.\";", 'mes "El tiempo de operacion no es largo, asi que apurate y regresa.";'),
    ('mes "Did you successfully bring back the shards of Gigantes?";', 'mes "Trajiste exitosamente los fragmentos de Gigantes?";'),
    ('mes "You probably faced a lot of danger so thank you for the effort.";', 'mes "Probablemente enfrentaste muchos peligros, asi que gracias por el esfuerzo.";'),
    ("mes \"I don't expect to receive the shards for nothing when you have risked your life for them!\";", 'mes "No espero recibir los fragmentos gratis cuando has arriesgado tu vida por ellos!";'),
    ('mes "I will give you a useful looking earring from the relics I have happened to have obtained during my previous research.";', 'mes "Te dare un arete util de las reliquias que obtuve durante mi investigacion anterior.";'),
    ('mes "- The left earring of Sarah -";', 'mes "- El arete izquierdo de Sarah -";'),
    ('mes "Usable for Heal 1Lv";', 'mes "Utilizable para Heal 1Lv";'),
    ('mes "- The right earring of Sarah -";', 'mes "- El arete derecho de Sarah -";'),
    ('mes "Usable for Teleport 1Lv";', 'mes "Utilizable para Teleport 1Lv";'),
    ('"The left earring of Sarah", "The right earring of Sarah"', '"El arete izquierdo de Sarah", "El arete derecho de Sarah"'),
    ('mes "If you hand the shards of Gigantes to my chief assistant, I will make sure the earrings will be correspondingly great through an enchantment.";', 'mes "Si le entregas los fragmentos de Gigantes a mi asistente principal, me asegurare de que los aretes sean geniales a traves de un encantamiento.";'),
    ('mes "The more shards of Gigantes are collected, the better.";', 'mes "Mientras mas fragmentos de Gigantes se recolecten, mejor.";'),
    ("mes \"However, there isn't a stable supply of energy needed to work the Dimensional Device.\";", 'mes "Sin embargo, no hay un suministro estable de energia necesaria para operar el Dispositivo Dimensional.";'),
    ('mes "Come back and find me after one week has passed for the supply of Dimensional Device energy.";', 'mes "Regresa y buscame despues de que pase una semana para el suministro de energia del Dispositivo Dimensional.";'),
    ('mes "I need you to find shards of Gigantes again.";', 'mes "Necesito que encuentres fragmentos de Gigantes de nuevo.";'),
    ('mes "We lack the shards of Gigantes in order to make powerful weapons.";', 'mes "Nos faltan fragmentos de Gigantes para hacer armas poderosas.";'),
    ('mes "Because a lot of energy is needed to open a dimension device, come back and find me when the energy has accumulated.";', 'mes "Se necesita mucha energia para abrir un dispositivo dimensional, regresa y buscame cuando la energia se haya acumulado.";'),
    ('mes "I have been waiting.";', 'mes "He estado esperando.";'),
    ('mes "How is everything going?";', 'mes "Como va todo?";'),
    ('mes "While you were gone I have succeeded in accumulating dimensional energy.";', 'mes "Mientras estabas fuera, logre acumular energia dimensional.";'),
    ('mes "We can open the dimension device again.";', 'mes "Podemos abrir el dispositivo dimensional de nuevo.";'),
    ('mes "Because I cannot leave my post, ";', 'mes "Porque no puedo abandonar mi puesto, ";'),
    ('mes "I need a warrior who can bring me the shards instead.";', 'mes "Necesito un guerrero que pueda traerme los fragmentos.";'),
    ('mes "I think you can assist me once again..";', 'mes "Creo que puedes ayudarme una vez mas..";'),
    ('mes "There, all the preparations are finished.";', 'mes "Listo, todos los preparativos estan terminados.";'),
    ('mes "Can you go back in time again and bring me the shards of Gigantes?";', 'mes "Puedes regresar en el tiempo de nuevo y traerme los fragmentos de Gigantes?";'),
    ('mes "I set the Dimensional Device to Glast Heim of the past, where Fenrir and Sarah once were.";', 'mes "Configure el Dispositivo Dimensional hacia el Glast Heim del pasado, donde Fenrir y Sarah alguna vez estuvieron.";'),
    ("mes \"It won't last long so hurry up and come back.\";", 'mes "No durara mucho, asi que apurate y regresa.";'),
    ('mes "- You must be level 145 or over";', 'mes "- Debes ser nivel 145 o superior";'),
    ('mes "It seems entry is possible. -";', 'mes "Parece que la entrada es posible. -";'),
    ('mes "- The Dimensional Device has closed.";', 'mes "- El Dispositivo Dimensional se ha cerrado.";'),
    ('mes "It seems entry is not possible. -";', 'mes "Parece que la entrada no es posible. -";'),
    ('select( "Do not enter the device.", "Enter the time device" )', 'select( "No entrar al dispositivo.", "Entrar al dispositivo temporal" )'),
    ('mes "- It seems the Dimensional Device ";', 'mes "- Parece que el Dispositivo Dimensional ";'),
    ('mes "will contort space time -";', 'mes "distorsionara el espacio tiempo -";'),
    ('mes "- There is a damp presence. -";', 'mes "- Hay una presencia humeda. -";'),
    ('mes "An unknown error occurred.";', 'mes "Ocurrio un error desconocido.";'),
    ('mes "Memorial Dungeon " + .@md_name$ + " does not exist.";', 'mes "La Mazmorra Memorial " + .@md_name$ + " no existe.";'),
    ('mes "The party leader has not created the Memorial Dungeon.";', 'mes "El lider del grupo no ha creado la Mazmorra Memorial.";'),
    ('mes "Only party members can enter the Memorial Dungeon.";', 'mes "Solo los miembros del grupo pueden entrar a la Mazmorra Memorial.";'),
    # Assistant Professor dialogue
    ("mes \"I've heard about you from the professor.\";", 'mes "He oido hablar de ti por parte del profesor.";'),
    ('mes "The professor has told me to sufficiently compensate you for risking your life and bringing the shards of Gigantes.";', 'mes "El profesor me dijo que te compensara suficientemente por arriesgar tu vida y traer los fragmentos de Gigantes.";'),
    ('select( "Enchant earring.", "Purchase earring", "Exit conversation" )', 'select( "Encantar arete.", "Comprar arete", "Salir de la conversacion" )'),
    ("mes \"Sarah's earrings we have discovered at the archaeological site must certainly have great potential.\";", 'mes "Los aretes de Sarah que descubrimos en el sitio arqueologico deben tener un gran potencial.";'),
    ('select( "Enchant Sarah\'s earrings", "Initialize enchantment on Sarah\'s earrings", "Exit conversation" )', 'select( "Encantar los aretes de Sarah", "Inicializar encantamiento en los aretes de Sarah", "Salir de la conversacion" )'),
    ('mes "2 enchantments are possible on one earring.";', 'mes "2 encantamientos son posibles en un arete.";'),
    ('mes "Which earring do you wish to enchant?";', 'mes "Que arete deseas encantar?";'),
    ('select( "The left earring of Sarah", "The right earring of Sarah", "Quit" )', 'select( "El arete izquierdo de Sarah", "El arete derecho de Sarah", "Salir" )'),
    ('mes "If you want an enchantment ";', 'mes "Si quieres un encantamiento ";'),
    ("mes \"on Sarah's earrings, \";", 'mes "en los aretes de Sarah, ";'),
    ('mes "come and find me again.";', 'mes "ven y buscame de nuevo.";'),
    ('mes "You must equip the item to make enchantment possible.";', 'mes "Debes equipar el objeto para hacer posible el encantamiento.";'),
    ('mes "Which column do you wish to enchant?";', 'mes "Que columna deseas encantar?";'),
    ('select( "Left column", "Right column" )', 'select( "Columna izquierda", "Columna derecha" )'),
    ('mes "If you wish to enchant, you must equip Sarah\'s " + .@sarah_earring$ + " earring.";', 'mes "Si deseas encantar, debes equipar el arete " + .@sarah_earring$ + " de Sarah.";'),
    ('mes "A fully enchanted earring of Sarah cannot be enchanted any further.";', 'mes "Un arete de Sarah completamente encantado no puede ser encantado mas.";'),
    ("mes \"Sarah's Earring is currently in a state of enchantment in slot 4.\";", 'mes "El Arete de Sarah actualmente tiene un encantamiento en el slot 4.";'),
    ("mes \"Sarah's Earring is currently in a state without enchantment.\";", 'mes "El Arete de Sarah actualmente esta sin encantamiento.";'),
    ('mes "Which ability do you want as an enchantment on slot " + .@slot + "?";', 'mes "Que habilidad quieres como encantamiento en el slot " + .@slot + "?";'),
    ('select( "CRI or Critical", "Expert archer or Bleed", "Conservation or MATK", "Delay Attack or Delay Skill" )', 'select( "CRI o Critical", "Arquero experto o Sangrado", "Conservacion o MATK", "Delay Attack o Delay Skill" )'),
    ('mes "Selected for CRI or Critical Enchantment slot " + .@slot + ".";', 'mes "Seleccionado para encantamiento CRI o Critical en slot " + .@slot + ".";'),
    ('mes "Selected for Expert Archer or Bleed Enchantment slot " + .@slot + ".";', 'mes "Seleccionado para encantamiento Arquero Experto o Sangrado en slot " + .@slot + ".";'),
    ('mes "Selected for Conservation or MATK Enchantment slot " + .@slot + ".";', 'mes "Seleccionado para encantamiento Conservacion o MATK en slot " + .@slot + ".";'),
    ('mes "Selected for Delay Attack or Delay Skill Enchantment slot " + .@slot + ".";', 'mes "Seleccionado para encantamiento Delay Attack o Delay Skill en slot " + .@slot + ".";'),
    ('mes "4 shards of Gigantes is required for one enchantment.";', 'mes "Se requieren 4 fragmentos de Gigantes para un encantamiento.";'),
    ('mes "Because enchantment is a high risk process, there is risk of Sarah\'s earring being destroyed.";', 'mes "El encantamiento es un proceso de alto riesgo, existe el riesgo de que el arete de Sarah sea destruido.";'),
    ('mes "Do you still want to do it?";', 'mes "Aun quieres hacerlo?";'),
    ('mes "Please speak to me again after making a clear decision!";', 'mes "Habla conmigo de nuevo despues de tomar una decision clara!";'),
    ('mes "There are not enough shards of Gigantes.";', 'mes "No hay suficientes fragmentos de Gigantes.";'),
    ('mes "4 shards of Gigantes is required to do one enchantment.";', 'mes "Se requieren 4 fragmentos de Gigantes para hacer un encantamiento.";'),
    ('mes "Good. I will start the enchantment!";', 'mes "Bien. Comenzare el encantamiento!";'),
    ('mes "I wish you luck~!";', 'mes "Te deseo suerte~!";'),
    ('mes "Sadly... it is..";', 'mes "Tristemente... fue..";'),
    ('mes "destroyed...";', 'mes "destruido...";'),
    ('mes "Whew.. ";', 'mes "Uf.. ";'),
    ('mes "enchantment is not an easy task..";', 'mes "el encantamiento no es una tarea facil..";'),
    ('mes "Enchantment completed!";', 'mes "Encantamiento completado!";'),
    ('mes "Which earring do you wish to initialize?";', 'mes "Que arete deseas inicializar?";'),
    ("mes \"If you want to initialize an enchantment on Sarah's earrings, come and find me again.\";", 'mes "Si quieres inicializar un encantamiento en los aretes de Sarah, ven y buscame de nuevo.";'),
    ("mes \"On Sarah's earring. 1 shard of Gigantes is required to initialize the enchantment..\";", 'mes "En el arete de Sarah. Se requiere 1 fragmento de Gigantes para inicializar el encantamiento..";'),
    ('mes "You will need them in order for initialization to take place.";', 'mes "Los necesitaras para que la inicializacion se lleve a cabo.";'),
    ('mes "You must equip the item to make initialization possible.";', 'mes "Debes equipar el objeto para hacer posible la inicializacion.";'),
    ("mes \"Which column's earring do you wish to initialize?\";", 'mes "En que columna deseas inicializar el arete?";'),
    ('mes "To initialize an enchantment, the relevant column must be equipped with gear.";', 'mes "Para inicializar un encantamiento, la columna correspondiente debe estar equipada.";'),
    ("mes \"To initialize an enchantment, the relevant column must be equipped with Sarah's earring.\";", 'mes "Para inicializar un encantamiento, la columna correspondiente debe estar equipada con el arete de Sarah.";'),
    ("mes \"Sarah's earring without an enchantment cannot be initialized.\";", 'mes "El arete de Sarah sin encantamiento no puede ser inicializado.";'),
    ('mes "You have selected Sarah\'s " + .@sarah_earring$ + " earring on the " + .@column$ + " column.";', 'mes "Has seleccionado el arete " + .@sarah_earring$ + " de Sarah en la columna " + .@column$ + ".";'),
    ('mes "It is impossible to restore abilities that are gone after initialization.";', 'mes "Es imposible restaurar habilidades que se pierden despues de la inicializacion.";'),
    ('mes "Do you still want to proceed?";', 'mes "Aun quieres continuar?";'),
    ('mes "Yes sir. Initialization will start.";', 'mes "Si senor. La inicializacion comenzara.";'),
    ('mes "Initialization completed.";', 'mes "Inicializacion completada.";'),
    ('mes "Please find me if you need me.";', 'mes "Buscame si me necesitas.";'),
    ("mes \"If you want an enchantment on Sarah's earrings, come and find me again.\";", 'mes "Si quieres un encantamiento en los aretes de Sarah, ven y buscame de nuevo.";'),
    ('mes "Related to Glast Heim, this is an unique and rare earring found during an excavation with the professor.";', 'mes "Relacionado con Glast Heim, este es un arete unico y raro encontrado durante una excavacion con el profesor.";'),
    ('mes "I think this has been worn by Sarah in the past and seems to have a great ability to draw out potential strength.";', 'mes "Creo que fue usado por Sarah en el pasado y parece tener una gran capacidad para sacar fuerza potencial.";'),
    ('mes "I will specially trade it for 1 shard since you are the warrior who brought shards of Gigantes for the professor\'s work.";', 'mes "Lo intercambiare especialmente por 1 fragmento ya que eres el guerrero que trajo fragmentos de Gigantes para el trabajo del profesor.";'),
    ('mes "Which one do you wish?";', 'mes "Cual deseas?";'),
    ('select( "The left earring of Sarah", "The right earring of Sarah", "Exit conversation" )', 'select( "El arete izquierdo de Sarah", "El arete derecho de Sarah", "Salir de la conversacion" )'),
    ('mes "You will need them for me to trade with you.";', 'mes "Los necesitaras para que pueda intercambiar contigo.";'),
    ('mes "Professor Bernhard is the professor I respect the most.";', 'mes "El Profesor Bernhard es el profesor que mas respeto.";'),
    ('mes "Do you have someone you respect?";', 'mes "Tienes a alguien que respetes?";'),
    ('mes "You arrived safely!";', 'mes "Llegaste a salvo!";'),
    ('mes "The dangerous situation";', 'mes "La situacion peligrosa";'),
    ('mes "had me worried.";', 'mes "me tenia preocupado.";'),
    ('mes "It was difficult and dangerous work";', 'mes "Fue un trabajo dificil y peligroso";'),
    ('mes "so I am grateful for your help.";', 'mes "asi que estoy agradecido por tu ayuda.";'),
    ('mes "I feel we will meet again";', 'mes "Siento que nos volveremos a ver";'),
    ('mes "but perhaps it is just my imagination?";', 'mes "pero quizas es solo mi imaginacion?";'),
    ('mes "Mm.. that would be nice.";', 'mes "Mm.. eso estaria bien.";'),
    ('mes "We worked well together";', 'mes "Trabajamos bien juntos";'),
    ('mes "so I hope we will meet again.";', 'mes "asi que espero que nos veamos de nuevo.";'),
    ('mes "And watch for Sarah,";', 'mes "Y cuidado con Sarah,";'),
    ('mes "harm can come your way as well.";', 'mes "el peligro tambien puede venir hacia ti.";'),
    # npctalk/unittalk - all Sarah/Fenrir combat and dialogue strings
    ('" : Huh? Somebody there? Hello~ You must be a traveler."', '" : Eh? Alguien ahi? Hola~ Debes ser un viajero."'),
    ('"Fenrith Fenrir: This is strange.. I don\'t recall Glast Heim castle being filled with such a dark presence.."', '"Fenrith Fenrir: Esto es extrano.. No recuerdo que el castillo de Glast Heim estuviera lleno de una presencia tan oscura.."'),
    ('"Fenrith Fenrir: Greetings can come later! Careful! It seems somebody has summoned a monster!"', '"Fenrith Fenrir: Los saludos pueden esperar! Cuidado! Parece que alguien ha invocado un monstruo!"'),
    ('" : What are these things?"', '" : Que son estas cosas?"'),
    ('"Fenrith Fenrir: Buy me some time while I cast magic! I will handle this!"', '"Fenrith Fenrir: Gana algo de tiempo mientras lanzo magia! Yo me encargare!"'),
    ('"Fenrith Fenrir: Wrath of the true sky."', '"Fenrith Fenrir: Ira del verdadero cielo."'),
    ('"Fenrith Fenrir: Thunderbolt that may split the earth!"', '"Fenrith Fenrir: Rayo que puede partir la tierra!"'),
    ('"Fenrith Fenrir: Fall before me now!"', '"Fenrith Fenrir: Caigan ante mi ahora!"'),
    ('"Fenrith Fenrir: Glast Heim, once the cathedral for the Asgard gods.."', '"Fenrith Fenrir: Glast Heim, alguna vez la catedral de los dioses de Asgard.."'),
    ('"Fenrith Fenrir: Now it has completely become a habitat for monsters.."', '"Fenrith Fenrir: Ahora se ha convertido completamente en un habitat para monstruos.."'),
    ('"Fenrith Fenrir: Wait.. Come to think of it, something is strange.."', '"Fenrith Fenrir: Espera.. Ahora que lo pienso, algo es extrano.."'),
    ('"Fenrith Fenrir: Galions are the monsters that habit this vicinity.."', '"Fenrith Fenrir: Los Galions son los monstruos que habitan esta zona.."'),
    ('"Fenrith Fenrir: By the way, I know it was sudden but thank you for helping."', '"Fenrith Fenrir: Por cierto, se que fue repentino pero gracias por ayudar."'),
    ('"Fenrith Fenrir: Anyway, who are you?"', '"Fenrith Fenrir: De todos modos, quien eres?"'),
    ('" : Ah.. that is...."', '" : Ah.. eso es...."'),
    ('" : .. I am a traveler who wanders around the world!"', '" : .. Soy un viajero que recorre el mundo!"'),
    ('"Fenrith Fenrir: Is that so..? I see.. I guess it does not matter."', '"Fenrith Fenrir: Es asi..? Ya veo.. Supongo que no importa."'),
    ('"Fenrith Fenrir: This place seems quite dangerous now. It is not too late to turn back."', '"Fenrith Fenrir: Este lugar parece bastante peligroso ahora. No es tarde para regresar."'),
    ('"Fenrith Fenrir: There is an object I need to find. I need to hurry before it is too late."', '"Fenrith Fenrir: Hay un objeto que necesito encontrar. Debo darme prisa antes de que sea tarde."'),
    ('"Fenrith Fenrir: Perhaps you can help me..."', '"Fenrith Fenrir: Quizas puedas ayudarme..."'),
    ('"Fenrith Fenrir: No.. Then thank you! I hope we can meet again later!"', '"Fenrith Fenrir: No.. Entonces gracias! Espero que nos veamos de nuevo!"'),
    ('" : Did that.. person.. really happen to be.. the.. Fenrir..? No way.. probably not.."', '" : Esa.. persona.. realmente fue.. el.. Fenrir..? No puede ser.. probablemente no.."'),
    ('"Sarah Irene: Impressive Fenrith Fenrir, you cleverly escaped"', '"Sarah Irene: Impresionante Fenrith Fenrir, escapaste astutamente"'),
    ('"Sarah Irene: Mm.. today I will make you stand down"', '"Sarah Irene: Mm.. hoy te hare rendirte"'),
    ('"Fenrith Fenrir: Today I hope to end our ill fated relationship."', '"Fenrith Fenrir: Hoy espero terminar nuestra relacion de mal destino."'),
    ('"Sarah Irene: However, do not think this is the end"', '"Sarah Irene: Sin embargo, no pienses que esto es el final"'),
    ('"Sarah Irene: You will surely see me again!!!"', '"Sarah Irene: Seguramente me veras de nuevo!!!"'),
    ('"Fenrith Fenrir: Mm... I look forward to it Sarah Irene.."', '"Fenrith Fenrir: Mm... Lo espero con ansias Sarah Irene.."'),
    ('"Fenrith Fenrir: You are still in Glast Heim? Why aren\'t you leaving this dangerous place?"', '"Fenrith Fenrir: Aun estas en Glast Heim? Por que no dejas este lugar peligroso?"'),
    ('" : I know it\'s dangerous but I thought it would be fun so I couldn\'t help myself.."', '" : Se que es peligroso pero pense que seria divertido y no pude evitarlo.."'),
    ('"Fenrith Fenrir: Hm.. Adventurers.."', '"Fenrith Fenrir: Hm.. Aventureros.."'),
    ('" : You don\'t have to worry~! I am fairly strong myself!"', '" : No tienes que preocuparte~! Yo tambien soy bastante fuerte!"'),
    ('"Fenrith Fenrir: Oh.. really? Do you think you can assist me then?"', '"Fenrith Fenrir: Oh.. en serio? Crees que puedes ayudarme entonces?"'),
    ('"Fenrith Fenrir: The object I am looking for is located somewhere in Glast Heim!"', '"Fenrith Fenrir: El objeto que busco esta en algun lugar de Glast Heim!"'),
    ('"Fenrith Fenrir: But others looking for the object will arrive there soon!"', '"Fenrith Fenrir: Pero otros que buscan el objeto llegaran alli pronto!"'),
    ("\"Fenrith Fenrir: This is urgent because there isn't enough time. We have to arrive there soon. 5 minutes at the latest!\"", '"Fenrith Fenrir: Esto es urgente porque no hay suficiente tiempo. Debemos llegar pronto. 5 minutos como maximo!"'),
    ('"Fenrith Fenrir: I will be waiting! If you are late I will have to go by myself!"', '"Fenrith Fenrir: Estare esperando! Si llegas tarde tendre que ir solo!"'),
    ('"Fenrith Fenrir: Alright, I will go on ahead and you decide if you are going to assist me!"', '"Fenrith Fenrir: Bien, me adelantare y tu decides si vas a ayudarme!"'),
    ('" : Hm.. what should I do..? I need shards of Gigantes as requested by Professor Bernhard.."', '" : Hm.. que deberia hacer..? Necesito fragmentos de Gigantes como solicito el Profesor Bernhard.."'),
    ('" : Should I help that person.. Or should I look for Gigantes to take the shards as requested by Professor Bernhard..?"', '" : Deberia ayudar a esa persona.. O deberia buscar Gigantes para tomar los fragmentos como solicito el Profesor Bernhard..?"'),
    ('"Fenrith Fenrir: I would like your party leader to come and help me!"', '"Fenrith Fenrir: Me gustaria que tu lider de grupo venga a ayudarme!"'),
    ('"Fenrith Fenrir: You came! I was waiting!"', '"Fenrith Fenrir: Viniste! Estaba esperando!"'),
    ("\"Fenrith Fenrir: We don't have much time! We have to go search for it now! Let's go in!\"", '"Fenrith Fenrir: No tenemos mucho tiempo! Tenemos que ir a buscarlo ahora! Entremos!"'),
    ('"Fenrith Fenrir: The sword of Baldur, Sentinel Breeze... even after 1000 years.."', '"Fenrith Fenrir: La espada de Baldur, Sentinel Breeze... incluso despues de 1000 anos.."'),
    ('"Fenrith Fenrir: I can feel the evil of monsters in this place.. as if they are being controlled by someone.."', '"Fenrith Fenrir: Puedo sentir la maldad de los monstruos en este lugar.. como si estuvieran controlados por alguien.."'),
    ('"Fenrith Fenrir: Then there is someone else here other than me?"', '"Fenrith Fenrir: Entonces hay alguien mas aqui aparte de mi?"'),
    ('"Fenrith Fenrir: That will do.. Now all I have to do is use Sentinel Breeze to find Baldur\'s whereabouts.."', '"Fenrith Fenrir: Eso bastara.. Ahora solo debo usar Sentinel Breeze para encontrar el paradero de Baldur.."'),
    ('"Sarah Irene: Hehe.. I see... just as I expected."', '"Sarah Irene: Jeje.. Ya veo... justo como esperaba."'),
    ('"Sarah Irene: Was that blade the clue?"', '"Sarah Irene: Esa espada era la pista?"'),
    ('"Sarah Irene: Then, Fenrith Fenrir, that means a 1000 year old seal can be broken with it?"', '"Sarah Irene: Entonces, Fenrith Fenrir, eso significa que un sello de 1000 anos puede romperse con ella?"'),
    ('" : Could it be he was the real Fenrir?"', '" : Podria ser que el era el verdadero Fenrir?"'),
    ('"Fenrith Fenrir: Could this be.. Valkyrie! Now it is not fun anymore"', '"Fenrith Fenrir: Podria ser.. Valkyrie! Ahora ya no es divertido"'),
    ('"Sarah Irene: Belated salutations, my name is Sarah Irene, one of the 12 Valkyries of Valhalla."', '"Sarah Irene: Saludos tardios, mi nombre es Sarah Irene, una de las 12 Valkirias de Valhalla."'),
    ('"Sarah Irene: Anyway, also to achieve Freyja\'s will.. hehe.."', '"Sarah Irene: De todos modos, tambien para lograr la voluntad de Freyja.. jeje.."'),
    ('"Fenrith Fenrir: Two Gigantes! This will not be an easy fight. Help me and defeat the Gigantes!"', '"Fenrith Fenrir: Dos Gigantes! Esta no sera una pelea facil. Ayudame y derrota a los Gigantes!"'),
    ('"Sarah Irene: Go forth! Gigantes! And my loyal monsters!"', '"Sarah Irene: Adelante! Gigantes! Y mis leales monstruos!"'),
    ('"Fenrith Fenrir: Sarah will hide and continuously summon monsters! I will take care of that monster, you face the Gigantes!"', '"Fenrith Fenrir: Sarah se escondera e invocara monstruos! Yo me encargare de ese monstruo, tu enfrenta a los Gigantes!"'),
    ('"Fenrith Fenrir: Currents vibrating in the atmosphere! Show me your strength!"', '"Fenrith Fenrir: Corrientes vibrando en la atmosfera! Muestrame tu fuerza!"'),
    ('"Fenrith Fenrir: Devour this evil presence with the fire pit of the universe!"', '"Fenrith Fenrir: Devora esta presencia maligna con el pozo de fuego del universo!"'),
    ('"Fenrith Fenrir: Hell fire that can swallow even space! Meteor storm~!!!!!"', '"Fenrith Fenrir: Fuego infernal que puede tragar incluso el espacio! Meteor storm~!!!!!"'),
    ('"Fenrith Fenrir: Freeze the evil presence with frost wind!!!"', '"Fenrith Fenrir: Congela la presencia maligna con viento helado!!!"'),
    ('"Fenrith Fenrir: A storm that can freeze even the soul!! Storm gust~!!!!!"', '"Fenrith Fenrir: Una tormenta que puede congelar incluso el alma!! Storm gust~!!!!!"'),
    ('"Fenrith Fenrir: They are endless. I should finish this absolutely."', '"Fenrith Fenrir: Son interminables. Debo terminar esto definitivamente."'),
    ('"Fenrith Fenrir: Limitlessly distant monarch with the beautiful scarlet breath!!"', '"Fenrith Fenrir: Monarca infinitamente distante con el hermoso aliento escarlata!!"'),
    ('"Fenrith Fenrir: Where you have passed will only be filled with nothingness."', '"Fenrith Fenrir: Donde hayas pasado solo quedara el vacio."'),
    ('"Fenrith Fenrir: Power to shake the earth\'s axis! Show your grace right here and now!!!"', '"Fenrith Fenrir: Poder para sacudir el eje de la tierra! Muestra tu gracia aqui y ahora!!!"'),
    ('"Fenrith Fenrir: Alright! We have defeated a Gigantes!"', '"Fenrith Fenrir: Bien! Hemos derrotado a un Gigantes!"'),
    ('"Sarah Irene: As expected, Fenrith Fenrir, you do not yield easily!"', '"Sarah Irene: Como era de esperarse, Fenrith Fenrir, no te rindes facilmente!"'),
    ('"Fenrith Fenrir: Get away from the Sentinel Breeze immediately!"', '"Fenrith Fenrir: Alejate de la Sentinel Breeze inmediatamente!"'),
    ("\"Sarah Irene: Hehe.. I can't do that!\"", '"Sarah Irene: Jeje.. No puedo hacer eso!"'),
    ('"Sarah Irene: If you want it back come to Glast Heim Castle! I shall be waiting!"', '"Sarah Irene: Si la quieres de vuelta ven al Castillo de Glast Heim! Estare esperando!"'),
    ('"Fenrith Fenrir: We must follow quickly to retrieve the sword! I shall use a group space movement spell!"', '"Fenrith Fenrir: Debemos seguirla rapido para recuperar la espada! Usare un hechizo de movimiento espacial grupal!"'),
    ('"Fenrith Fenrir: Simultaneous large scale warp!"', '"Fenrith Fenrir: Teletransportacion a gran escala simultanea!"'),
    ('"Fenrith Fenrir: I need to go to Glast Heim Castle to retrieve the sword of Baldur."', '"Fenrith Fenrir: Necesito ir al Castillo de Glast Heim para recuperar la espada de Baldur."'),
    ('"Fenrith Fenrir: It could be difficult alone, I would gratefully accept your help."', '"Fenrith Fenrir: Podria ser dificil solo, agradeceria tu ayuda."'),
    ("\"Fenrith Fenrir: Since there isn't enough time, we can't wait long.\"", '"Fenrith Fenrir: Como no hay suficiente tiempo, no podemos esperar mucho."'),
    ('"Fenrith Fenrir: I will wait in the central castle of Glast Heim for about 5 minutes."', '"Fenrith Fenrir: Esperare en el castillo central de Glast Heim por unos 5 minutos."'),
    ('"Fenrith Fenrir: Since it is dangerous you do not have to feel obligated to help me. I will try by myself if I have to."', '"Fenrith Fenrir: Ya que es peligroso no tienes que sentirte obligado a ayudarme. Lo intentare solo si es necesario."'),
    ('"Fenrith Fenrir: Then I will go on ahead! Warp!"', '"Fenrith Fenrir: Entonces me adelantare! Warp!"'),
    ('"Fenrith Fenrir: I need to go to Glast Heim Castle to retrieve the sword of Baldur"', '"Fenrith Fenrir: Necesito ir al Castillo de Glast Heim para recuperar la espada de Baldur"'),
    ('"Fenrith Fenrir: It may be difficult alone. If you are listening I will gratefully accept your help."', '"Fenrith Fenrir: Puede ser dificil solo. Si estas escuchando agradeceria tu ayuda."'),
    ('"Fenrith Fenrir: I was waiting. Thank you for not being late."', '"Fenrith Fenrir: Estaba esperando. Gracias por no llegar tarde."'),
    ('"Fenrith Fenrir: Let us climb the castle to retrieve Sentinel Breeze! Sarah will be waiting!"', '"Fenrith Fenrir: Subamos al castillo para recuperar la Sentinel Breeze! Sarah estara esperando!"'),
    ('"Sarah Irene: It seemed like forever waiting for you~ Fenrith Fenrir."', '"Sarah Irene: Parecia una eternidad esperandote~ Fenrith Fenrir."'),
    ('"Fenrith Fenrir: No need for useless words, hand over the Sentinel Breeze now!"', '"Fenrith Fenrir: No hacen falta palabras inutiles, entrega la Sentinel Breeze ahora!"'),
    ('"Sarah Irene: Try if you can."', '"Sarah Irene: Intentalo si puedes."'),
    ('"Fenrith Fenrir: Sarah may be too difficult for you to face alone. I must face her!"', '"Fenrith Fenrir: Sarah puede ser demasiado dificil para enfrentarla solo. Debo enfrentarla yo!"'),
    ('"Fenrith Fenrir: Pure white shackles, eternal prison, make a deal with me now!"', '"Fenrith Fenrir: Cadenas blancas puras, prision eterna, haz un trato conmigo ahora!"'),
    ('"Sarah Irene: Hurk.... he.."', '"Sarah Irene: Hurk.... je.."'),
    ('"Fenrith Fenrir: I will weaken Sarah with white imprison and face her while she\'s shackled,"', '"Fenrith Fenrir: Debilitare a Sarah con white imprison y la enfrentare mientras esta encadenada,"'),
    ('"Fenrith Fenrir: you take care of the monsters she summons. I\'m counting on you."', '"Fenrith Fenrir: tu encargate de los monstruos que ella invoque. Cuento contigo."'),
    ('" : Will do. Powerful enemies make my blood boil."', '" : Lo hare. Los enemigos poderosos hacen hervir mi sangre."'),
    ('"Fenrith Fenrir: This is a strategy to attack at once and finish Sarah off while she is in critical condition. Remember, our opponent is strong."', '"Fenrith Fenrir: Esta es una estrategia para atacar de una vez y acabar con Sarah mientras esta en condicion critica. Recuerda, nuestro oponente es fuerte."'),
    ('"Sarah Irene: So your plan was to tie me up with this sort of trick?"', '"Sarah Irene: Asi que tu plan era atarme con este tipo de truco?"'),
    ('"Sarah Irene: Furthermore you borrow the assistance of such rookie adventurers..."', '"Sarah Irene: Ademas pides la ayuda de aventureros tan novatos..."'),
    ('"Sarah Irene: You need to disappear from here along with that worn out blade!!"', '"Sarah Irene: Necesitas desaparecer de aqui junto con esa espada desgastada!!"'),
    ('"Fenrith Fenrir: Lethal poison, Dark clouds, appear before me and show a most painful death!"', '"Fenrith Fenrir: Veneno letal, nubes oscuras, aparezcan ante mi y muestren la muerte mas dolorosa!"'),
    ('"Fenrith Fenrir: Go! Cloud Kill!!!!!"', '"Fenrith Fenrir: Ve! Cloud Kill!!!!!"'),
    ('"Sarah Irene: That was sudden Fenrir. Is that all you\'ve got?"', '"Sarah Irene: Eso fue repentino Fenrir. Es todo lo que tienes?"'),
    ('"Sarah Irene: Try to entertain me a little more!!"', '"Sarah Irene: Intenta entretenerme un poco mas!!"'),
    ('"Fenrith Fenrir: I speak to you who controls fire, I Fenrith, desire a fire that does not go out..."', '"Fenrith Fenrir: Te hablo a ti que controlas el fuego, yo Fenrith, deseo un fuego que no se extinga..."'),
    ('"Fenrith Fenrir: Endlessly burning conflagration, a fire that can scorch even the soul!! Appear before me now!!"', '"Fenrith Fenrir: Conflagracion que arde sin fin, un fuego que puede quemar incluso el alma!! Aparece ante mi ahora!!"'),
    ('"Sarah Irene: Oh... not bad? But not good enough!!"', '"Sarah Irene: Oh... nada mal? Pero no lo suficientemente bueno!!"'),
    ('"Fenrith Fenrir: The root of earthshaking power!! Fear the power of the earth!!!"', '"Fenrith Fenrir: La raiz del poder que sacude la tierra!! Teman el poder de la tierra!!!"'),
    ('"Fenrith Fenrir: Go forth!! Heaven\'s Drive!!!"', '"Fenrith Fenrir: Adelante!! Heaven\'s Drive!!!"'),
    ('"Sarah Irene: Why don\'t you stop your childish magic, Fenrir?"', '"Sarah Irene: Por que no detienes tu magia infantil, Fenrir?"'),
    ('"Sarah Irene: Do you think that is enough to beat me?"', '"Sarah Irene: Crees que eso es suficiente para vencerme?"'),
    ('"Fenrith Fenrir: The mercilessly cold breath of the Northern winds,"', '"Fenrith Fenrir: El aliento despiadadamente frio de los vientos del Norte,"'),
    ('"Fenrith Fenrir: Come like the silent dawn mist and freeze everything!!"', '"Fenrith Fenrir: Ven como la niebla silenciosa del amanecer y congela todo!!"'),
    ('"Fenrith Fenrir: Appear!!! Frost Misty!!!!!"', '"Fenrith Fenrir: Aparece!!! Frost Misty!!!!!"'),
    ('"Sarah Irene: Not bad but.. not even close!"', '"Sarah Irene: Nada mal pero.. ni siquiera cerca!"'),
    ('"Fenrith Fenrir: The power of doubt, a powerful force, the power of deeply hidden secrets in the mind!!!"', '"Fenrith Fenrir: El poder de la duda, una fuerza poderosa, el poder de los secretos profundamente ocultos en la mente!!!"'),
    ('"Fenrith Fenrir: Now!!! Psychic Wave!!!!"', '"Fenrith Fenrir: Ahora!!! Psychic Wave!!!!"'),
    ('"Sarah Irene: Ugh... that is no use Fenrir!"', '"Sarah Irene: Ugh... eso no sirve Fenrir!"'),
    ('"Sarah Irene: Hurk.. such an annoying magic bombardment!!"', '"Sarah Irene: Hurk.. un bombardeo magico tan molesto!!"'),
    ('"Sarah Irene: I am Sarah Irene! I will not fall so easily!!!"', '"Sarah Irene: Soy Sarah Irene! No caere tan facilmente!!!"'),
    ('"Fenrith Fenrir: True wrath of the sky, thunderbolt that may split the earth... Fall before me now!!"', '"Fenrith Fenrir: Verdadera ira del cielo, rayo que puede partir la tierra... Caigan ante mi ahora!!"'),
    ('"Fenrith Fenrir: Come now!! Thunder Storm!!!!!"', '"Fenrith Fenrir: Vengan ahora!! Thunder Storm!!!!!"'),
    ('"Sarah Irene: Ugh...you are.. stronger than I predicted Fenrir..."', '"Sarah Irene: Ugh...eres.. mas fuerte de lo que predije Fenrir..."'),
    ('"Fenrith Fenrir: Heaven\'s sword piercing the sky"', '"Fenrith Fenrir: Espada celestial perforando el cielo"'),
    ('"Fenrith Fenrir: I wish to borrow your strength for a moment!!"', '"Fenrith Fenrir: Deseo tomar prestada tu fuerza por un momento!!"'),
    ('"Fenrith Fenrir: Let fall here your extreme strength that can tear even the vacuum!!"', '"Fenrith Fenrir: Deja caer aqui tu fuerza extrema que puede rasgar incluso el vacio!!"'),
    ('"Fenrith Fenrir: Sword that can control life and death, and pierce space time!!!"', '"Fenrith Fenrir: Espada que puede controlar la vida y la muerte, y perforar el espacio tiempo!!!"'),
    ('"Fenrith Fenrir: Come out Baretis Spear!!!!!!"', '"Fenrith Fenrir: Sal Baretis Spear!!!!!!"'),
    ('"Sarah Irene: Argh!!! I will kill you all!!!!!!"', '"Sarah Irene: Argh!!! Los matare a todos!!!!!!"'),
    ('"Fenrith Fenrir: Now! I put Sarah in critical condition! You have to finish her off! Attack her quickly! Sarah is strong!"', '"Fenrith Fenrir: Ahora! Puse a Sarah en condicion critica! Tienes que acabar con ella! Atacala rapido! Sarah es fuerte!"'),
    ('"Fenrith Fenrir: Now! I put Sarah in critical condition! You have to finish her off!! Attack her quickly! Sarah is strong!"', '"Fenrith Fenrir: Ahora! Puse a Sarah en condicion critica! Tienes que acabar con ella!! Atacala rapido! Sarah es fuerte!"'),
    ('"Sarah Irene: Hurk...this.. cannot happen!!! I cannot lose!!!!!"', '"Sarah Irene: Hurk...esto.. no puede pasar!!! No puedo perder!!!!!"'),
    ('"Fenrith Fenrir: Since you may not be able to finish her off alone, I will prepare one final spell!!"', '"Fenrith Fenrir: Ya que quizas no puedas acabar con ella solo, preparare un ultimo hechizo!!"'),
    ('"Fenrith Fenrir: Sentinel Breeze! I have it in my hand!"', '"Fenrith Fenrir: Sentinel Breeze! La tengo en mi mano!"'),
    ('"Sarah Irene: Hurk...."', '"Sarah Irene: Hurk...."'),
    ('"Fenrith Fenrir: I can find Baldur with this!"', '"Fenrith Fenrir: Puedo encontrar a Baldur con esto!"'),
    ('"Sarah Irene: Not yet!!"', '"Sarah Irene: Aun no!!"'),
    ('"Sarah Irene: Hehe... You evade well like a rat."', '"Sarah Irene: Jeje... Evades bien como una rata."'),
    ('"Sarah Irene: However, I cannot let you leave with that."', '"Sarah Irene: Sin embargo, no puedo dejarte ir con eso."'),
    ('"Sarah Irene: I will blow this entire castle away! Yaah!"', '"Sarah Irene: Volare este castillo entero! Yaah!"'),
    ('"Fenrith Fenrir: She is planning to collapse this place! I must perform a large scale teleportation!!!"', '"Fenrith Fenrir: Ella planea derrumbar este lugar! Debo realizar una teletransportacion a gran escala!!!"'),
    ('"Fenrith Fenrir: Farewell Valkyrie!! I shall take the Sentinel Breeze! So long!"', '"Fenrith Fenrir: Adios Valkyrie!! Me llevare la Sentinel Breeze! Hasta luego!"'),
    ('"Fenrith Fenrir: Hehe.. You are certainly skilled but I think you have underestimated me, Valkyrie."', '"Fenrith Fenrir: Jeje.. Ciertamente eres habil pero creo que me has subestimado, Valkyrie."'),
    ('"Sarah Irene: You rather entertain me Fenrith..."', '"Sarah Irene: Mas bien me entretienes Fenrith..."'),
    ('"Sarah Irene: Did you think you can escape that easily?"', '"Sarah Irene: Pensaste que podias escapar tan facilmente?"'),
    ('"Sarah Irene: I shall turn Glast Heim into hell!!"', '"Sarah Irene: Convertire Glast Heim en un infierno!!"'),
    ("\"Fenrith Fenrir: If we don't escape now we will suffer a gruesome fate by Sarah's monsters and magic!\"", '"Fenrith Fenrir: Si no escapamos ahora sufriremos un destino espantoso por los monstruos y la magia de Sarah!"'),
    ("\"Fenrith Fenrir: Let's meet at Glast Heim entrance where we first met! If we flee that far it should be safe!\"", '"Fenrith Fenrir: Encontremonos en la entrada de Glast Heim donde nos conocimos! Si huimos hasta alla deberia ser seguro!"'),
    ('"Fenrith Fenrir: There is no time! Hurry!"', '"Fenrith Fenrir: No hay tiempo! Apurate!"'),
    ('"Sarah Irene: Absurd little thing, you think you can escape that easily?"', '"Sarah Irene: Pequena cosa absurda, crees que puedes escapar tan facilmente?"'),
    ('"Sarah Irene: My minions will make sure to kill you!!!"', '"Sarah Irene: Mis secuaces se aseguraran de matarte!!!"'),
    ('"Sarah Irene: I cannot let you escape!!"', '"Sarah Irene: No puedo dejarte escapar!!"'),
    ("\"Sarah Irene: Fenrith Fenrir.... Did you think I couldn't track you because you fled?\"", '"Sarah Irene: Fenrith Fenrir.... Pensaste que no podia rastrearte porque huiste?"'),
    ('"Sarah Irene: Bwahahahahahaha!! Glast Heim is being filled with my wrath!!"', '"Sarah Irene: Bwajajajajajaja!! Glast Heim se esta llenando con mi ira!!"'),
    ('" : The Ancient Gigantes that Professor Bernhard spoke of!!"', '" : Los Antiguos Gigantes de los que hablo el Profesor Bernhard!!"'),
]

translate_file(base + "SarahAndFenrir.txt", sarah_reps)

print("DONE - SarahAndFenrir translated!")
