import re

translations = {
    # === COMMON MESSAGES ===
    '"^3355FFWait a minute! You\'re"': '"^3355FFEspera un momento! Estas"',
    '"carrying too many items"': '"cargando demasiados items"',
    '"right now: store some of"': '"ahora mismo: guarda algunos de"',
    '"your extra things in Kafra"': '"tus items extra en el Almacen"',
    '"Storage, and then come back.^000000"': '"Kafra, y luego regresa.^000000"',

    # === LEDRION ===
    '"Hm? I\'m afraid that you\'ve"': '"Hm? Me temo que me has"',
    '"misunderstood me earlier..."': '"malinterpretado..."',
    '"You\'re not ready to see"': '"No estas listo para verme"',
    '"me until you bring enough"': '"hasta que traigas suficientes"',
    '"of your group members with you."': '"miembros de tu grupo contigo."',

    '"Ah, you\'ve brought the"': '"Ah, trajiste el"',
    '"last ticket from Rospii."': '"ultimo ticket de Rospii."',
    '"Now I\'m convinced that"': '"Ahora estoy convencido de que"',
    '"you and your group really"': '"tu y tu grupo realmente"',
    '"work well together. Good"': '"trabajan bien juntos. Buen"',
    '"job on passing the trials!"': '"trabajo pasando las pruebas!"',

    '"Your group must truly"': '"Tu grupo realmente debe"',
    '"understand the value of"': '"entender el valor del"',
    '"teamwork. And thanks to"': '"trabajo en equipo. Y gracias a"',
    '"you, I\'ve won the bet! Er, but"': '"ti, gane la apuesta! Eh, pero"',
    '"what\'s more important is you"': '"lo mas importante es que"',
    '"proving my faith in you guys."': '"demostraron mi fe en ustedes."',

    '"I\'m really proud of"': '"Estoy muy orgulloso de"',
    '"you guys for your great"': '"ustedes por su gran"',
    '"accomplishment. Here..."': '"logro. Aqui..."',
    '"You deserve a real reward!"': '"Se merecen una recompensa real!"',

    '"Well, I hope you like it!"': '"Bueno, espero que te guste!"',
    '"If you can\'t use it, then"': '"Si no puedes usarlo, entonces"',
    '"why don\'t you share it with"': '"por que no lo compartes con"',
    '"someone in your guild? Feel"': '"alguien de tu gremio? Sientete"',
    '"free to come back if you want"': '"libre de regresar si quieres"',
    '"to try my trials again, okay?"': '"intentar mis pruebas de nuevo, si?"',

    '"Once again, I\'d like to"': '"Una vez mas, me gustaria"',
    '"thank you. I\'m not sure"': '"agradecerte. No estoy seguro"',
    '"if we\'ll ever meet again,"': '"si nos volveremos a ver,"',
    '"but I\'ll be praying for you as"': '"pero rezare por ti mientras"',
    '"you go on your adventures."': '"continuas tus aventuras."',

    '"Hm? Why aren\'t your"': '"Hm? Por que no estan tus"',
    '"comrades with you?"': '"companeros contigo?"',
    '"You must bring your"': '"Debes traer a tus"',
    '"group members here to"': '"miembros de grupo aqui para"',
    '"proceed with these trials."': '"continuar con estas pruebas."',

    '"Aren\'t you supposed to"': '"No se supone que debes"',
    '"ask one a Swordman or"': '"pedirle a un miembro clase"',
    '"Mage Class member of "': '"Espadachin o Mago de "',
    '"your group to bring a ticket"': '"tu grupo que lleve un ticket"',
    '"over to Gatan right now?"': '"a Gatan ahora mismo?"',

    '"Great, you\'ve brought"': '"Genial, me trajiste"',
    '"me the eighth ticket from"': '"el octavo ticket de"',
    '"Lospii. Your group must"': '"Lospii. Tu grupo debe"',
    '"work pretty well together,"': '"trabajar muy bien juntos,"',
    '"eh? It usually isn\'t easy to"': '"eh? Normalmente no es facil"',
    '"gather people like that..."': '"reunir gente asi..."',

    '"Please keep up the good"': '"Por favor sigan con el buen"',
    '"work until you finish all"': '"trabajo hasta que terminen"',
    '"of the trials, okay? Here\'s"': '"todas las pruebas, si? Aqui"',
    '"a little reward for your"': '"hay una pequena recompensa por"',
    '"effort thus far, and the"': '"tu esfuerzo hasta ahora, y el"',
    '"nineth ticket for your guild."': '"noveno ticket para tu gremio."',

    '"Please give that ticket"': '"Por favor dale ese ticket"',
    '"to someone in your guild"': '"a alguien de tu gremio"',
    '"that\'s a Swordman or Mage"': '"que sea un personaje clase"',
    '"Class character, and tell"': '"Espadachin o Mago, y dile"',
    '"him to deliver it to Gatan."': '"que se lo entregue a Gatan."',
    '"Okay? I\'ll be seeing you."': '"De acuerdo? Nos vemos."',

    '"Hm? Aren\'t you supposed to"': '"Hm? No se supone que debes"',
    '"ask a Mage Class character"': '"pedirle a un personaje clase"',
    '"in your group to deliver"': '"Mago de tu grupo que entregue"',
    '"a ticket to Gatan?"': '"un ticket a Gatan?"',

    '"I see that you\'ve brought"': '"Veo que me trajiste"',
    '"me the fourth ticket from"': '"el cuarto ticket de"',
    '"Lospii. Good work, good work."': '"Lospii. Buen trabajo, buen trabajo."',
    '"Please hang in there, and"': '"Por favor aguanta, y"',
    '"finish all the trials we\'ve"': '"termina todas las pruebas que"',
    '"set before you guys, alright?"': '"hemos preparado para ustedes, si?"',

    '"Here\'s a little something"': '"Aqui hay algo pequeno"',
    '"to reward you for your"': '"para recompensar tus"',
    '"efforts for now. Now, please"': '"esfuerzos por ahora. Ahora, por favor"',
    '"give this ticket to a Mage"': '"dale este ticket a un personaje"',
    '"him to bring it to Gatan."': '"que se lo lleve a Gatan."',

    '"You didn\'t finish what"': '"No terminaste lo que"',
    '"I asked you to do, did you?"': '"te pedi que hicieras, verdad?"',
    '"It\'s not time for you to"': '"No es momento de que"',
    '"come to me, not yet."': '"vengas a verme, aun no."',

    '"As I mentioned earlier,"': '"Como mencione antes,"',
    '"I\'m challenging guild"': '"estoy retando a grupos de"',
    '"parties with missions"': '"gremios con misiones"',
    '"that will require "': '"que requeriran "',
    '"cooperation between"': '"cooperacion entre"',
    '"the group members."': '"los miembros del grupo."',

    '"These challenges are"': '"Estos desafios son"',
    '"something of a relay"': '"algo asi como una carrera"',
    '"race, where we\'ll ask"': '"de relevos, donde pediremos"',
    '"for an item to be passed"': '"que un item sea pasado"',
    '"to a member of a specific"': '"a un miembro de una clase"',
    '"Class to deliver for us."': '"especifica para que nos lo entregue."',

    '"Of course, we, the"': '"Por supuesto, nosotros, los"',
    '"administrators of this"': '"administradores de esta"',
    '"test, might add our own"': '"prueba, podemos agregar nuestros"',
    '"little challenges here and"': '"propios desafios aqui y"',
    '"there to see just how"': '"alla para ver que tan"',
    '"capable your group is."': '"capaz es tu grupo."',

    '"Why don\'t you give it"': '"Por que no lo intentas?"',
    '"a shot? You won\'t lose"': '"No perderas"',
    '"anything by trying our"': '"nada intentando nuestra"',
    '"test. I guarantee that"': '"prueba. Te garantizo que"',
    '"you\'ll benefit from"': '"te beneficiaras de"',
    '"our little exercise."': '"nuestro pequeno ejercicio."',

    '"Heh! Let\'s start with you!"': '"Jeh! Empecemos contigo!"',
    '"Here, take this ticket, and"': '"Toma, agarra este ticket, y"',
    '"give it to a Swordman Class"': '"daselo a un miembro clase"',
    '"member of your guild, and"': '"Espadachin de tu gremio, y"',
    '"ask him to bring it to Gatan."': '"pidele que se lo lleve a Gatan."',
    '"The relay has started~"': '"El relevo ha comenzado~"',

    '"Now, since you\'re the"': '"Ahora, ya que eres"',
    '"one that started the relay,"': '"el que inicio el relevo,"',
    '"you\'ll have to come back"': '"tendras que regresar"',
    '"to me later on. Don\'t"': '"a verme despues. No"',
    '"worry, we\'ll let you know"': '"te preocupes, te avisaremos"',
    '"once the time is right."': '"cuando sea el momento."',

    '"As leader of your"': '"Como lider de tu"',
    '"Party, you should"': '"Grupo, deberias"',
    '"always think of what"': '"siempre pensar en lo que"',
    '"would be best for all"': '"seria mejor para todos"',
    '"of your partners."': '"tus companeros."',

    '"I\'m sorry, but there\'s"': '"Lo siento, pero no hay"',
    '"nothing I can really offer"': '"nada que pueda ofrecerte..."',
    '"you... Unless you formed"': '"A menos que formes"',
    '"a Party and became its"': '"un Grupo y te conviertas en"',
    '"leader, there\'s absolutely"': '"su lider, no hay absolutamente"',
    '"nothing I can do for you..."': '"nada que pueda hacer por ti..."',

    '"Ah, pleased to make your"': '"Ah, un placer conocerte,"',
    '"acquaintance, adventurer."': '"aventurero."',
    '"I am Ledrion, a man of great"': '"Soy Ledrion, un hombre de gran"',
    '"intelligence, mystery, and"': '"inteligencia, misterio, y"',
    '"most importantly, wealth."': '"lo mas importante, riqueza."',
    '"Yes, I\'m a philanthropist."': '"Si, soy un filantropo."',

    '"I\'m always working to make"': '"Siempre estoy trabajando para hacer"',
    '"a meaningful contribution"': '"una contribucion significativa"',
    '"to all of Rune-Midgarts, which"': '"a todo Rune-Midgarts, lo que"',
    '"brings me to why I am here."': '"me trae a por que estoy aqui."',
    '"There are many adventurers like you, but we have a problem."': '"Hay muchos aventureros como tu, pero tenemos un problema."',

    '"So many adventurers have"': '"Tantos aventureros han"',
    '"chosen the ways of greed,"': '"elegido el camino de la codicia,"',
    '"and have forgotten how to"': '"y han olvidado como"',
    '"work well together with their"': '"trabajar bien junto con sus"',
    '"colleagues. Such selfishness"': '"colegas. Tal egoismo"',
    '"sickens me to no end! Ugh!"': '"me enferma sin fin! Ugh!"',

    '"I may not be an adventurer,"': '"Puede que no sea aventurero,"',
    '"but I have the money to do"': '"pero tengo el dinero para hacer"',
    '"something. I am hosting"': '"algo. Estoy organizando"',
    '"my own little challenge"': '"mi propio pequeno desafio"',
    '"to adventurers to encourage"': '"para aventureros para fomentar"',
    '"camaraderie and teamwork."': '"la camaraderia y el trabajo en equipo."',

    '"Please, I invite you to"': '"Por favor, te invito a"',
    '"give it a try! Allow me to"': '"intentarlo! Permiteme"',
    '"state some of my conditions."': '"decirte algunas de mis condiciones."',
    '"Firstly, you must be part of"': '"Primero, debes ser parte de"',
    '"a group of 6 or more members,"': '"un grupo de 6 o mas miembros,"',
    '"such as a Party or a Guild."': '"como un Grupo o un Gremio."',

    '"Secondly, only the leader"': '"Segundo, solo el lider"',
    '"of the group can begin the"': '"del grupo puede comenzar la"',
    '"first part of my challenge."': '"primera parte de mi desafio."',
    '"If you are not the leader,"': '"Si no eres el lider,"',
    '"let him know that he should"': '"hazle saber que deberia"',
    '"speak to me for the challenge."': '"hablar conmigo para el desafio."',

    '"Thirdly, you must have a"': '"Tercero, debes tener un"',
    '"Swordman Class, Mage Class,"': '"personaje clase Espadachin, Mago,"',
    '"Acolyte Class, Archer Class,"': '"Acolito, Arquero,"',
    '"Thief Class, and Merchant"': '"Ladron, y Mercader"',
    '"Class character to complete"': '"para completar"',
    '"the challenges you\'ll receive."': '"los desafios que recibiras."',

    '"Transcended characters"': '"Los personajes trascendidos"',
    '"are good too. Fourthly, all"': '"tambien sirven. Cuarto, todos"',
    '"group members must be"': '"los miembros del grupo deben"',
    '"at least Base Level 40."': '"ser al menos Nivel Base 40."',
    '"Everything else, well,"': '"Todo lo demas, bueno,"',
    '"you\'ll learn along the way."': '"lo aprenderas en el camino."',

    '"Don\'t fret, I won\'t have you"': '"No te preocupes, no te hare"',
    '"jumping through hoops for"': '"saltar obstaculos sin"',
    '"no reason at all. I\'ll provide"': '"razon alguna. Proporcionare"',
    '"plenty of rewards as an"': '"muchas recompensas como"',
    '"incentive for your group."': '"incentivo para tu grupo."',
    '"Would you like to participate?"': '"Te gustaria participar?"',

    '"Sure!:No."': '"Claro!:No."',

    '"Great! Let\'s see..."': '"Genial! Veamos..."',
    '"Well, you meet all the"': '"Bueno, cumples todos los"',
    '"requirements. It looks"': '"requisitos. Parece"',
    '"like I\'ll win the bet! Er, let"': '"que ganare la apuesta! Eh, dejame"',
    '"me give you your first"': '"darte tus primeras"',
    '"set of instructions."': '"instrucciones."',

    '"Just--^666666*Cough!*^000000"': '"Solo--^666666*Cof!*^000000"',
    '"Lemme clear my"': '"Dejame aclararme"',
    '"throat for a second..."': '"la garganta un segundo..."',

    '"That\'s great! Still,"': '"Que bien! Aun asi,"',
    '"you\'re not ready to tackle"': '"no estas listo para enfrentar"',
    '"my little challenge until"': '"mi pequeno desafio hasta que"',
    '"you fulfill all of my"': '"cumplas todas mis"',
    '"conditions. Come back"': '"condiciones. Regresa"',
    '"once you do that, alright?"': '"cuando lo hagas, de acuerdo?"',

    '"Really? Trust me, this"': '"En serio? Creeme, este"',
    '"little challenge will be"': '"pequeno desafio valdra"',
    '"worthwhile for you, and it"': '"la pena para ti, y"',
    '"would bring a greater sense"': '"traeria un mayor sentido"',
    '"of solidarity and teamwork"': '"de solidaridad y trabajo en equipo"',
    '"to Rune-Midgarts. It\'s win-win!"': '"a Rune-Midgarts. Todos ganan!"',

    # === GATAN ===
    '"Say, aren\'t you forgetting"': '"Oye, no estas olvidando"',
    '"something? Try to remember..."': '"algo? Trata de recordar..."',
    '"Earlier, you received some"': '"Antes, recibiste algunas"',
    '"instructions, didn\'t you?"': '"instrucciones, no?"',

    '"Say, I don\'t think it\'s"': '"Oye, no creo que sea"',
    '"your turn to meet up with"': '"tu turno de reunirte"',
    '"me. I think you need to ask a"': '"conmigo. Creo que necesitas pedirle a un"',
    '"Thief or Acolyte Class member"': '"miembro clase Ladron o Acolito"',
    '"of your group to bring the"': '"de tu grupo que lleve el"',
    '"tenth ticket to Bafhail."': '"decimo ticket a Bafhail."',

    '"Ah, very nice! Please"': '"Ah, muy bien! Por favor"',
    '"give this ticket to a Thief"': '"dale este ticket a un miembro"',
    '"or Acolyte Class member"': '"clase Ladron o Acolito"',
    '"of your group, and ask him"': '"de tu grupo, y pidele"',
    '"to bring it to Bafhail. Ah, and"': '"que se lo lleve a Bafhail. Ah, y"',
    '"here\'s a little reward for you~"': '"aqui hay una pequena recompensa para ti~"',

    '"Alright, get that done."': '"Bien, hazlo."',
    '"I\'ll see you around."': '"Nos vemos por ahi."',

    '"Great, you gained some"': '"Genial, ganaste algunos"',
    '"levels, just like I asked."': '"niveles, justo como te pedi."',
    '"Let me find your next--I swore"': '"Dejame encontrar tu siguiente--jure"',
    '"I left it around somewhere--"': '"que lo deje por aqui--"',
    '"and I\'ll give you your next set"': '"y te dare tu siguiente conjunto"',
    '"of instructions. Hang on..."': '"de instrucciones. Espera..."',

    '"Great, you gained a"': '"Genial, ganaste un"',
    '"level, just like I asked."': '"nivel, justo como te pedi."',

    '"Your mission is to"': '"Tu mision es"',
    '"gain 3 more Base Levels."': '"ganar 3 Niveles Base mas."',
    '"Come see me during my"': '"Ven a verme durante mis"',
    '"working hours once you"': '"horas de trabajo una vez que"',
    '"accomplish that, alright?"': '"logres eso, de acuerdo?"',
    '"gain 2 more Base Levels."': '"ganar 2 Niveles Base mas."',
    '"gain 1 more Base Level."': '"ganar 1 Nivel Base mas."',

    '"I can\'t tell you exactly"': '"No puedo decirte exactamente"',
    '"when I work, but my work"': '"cuando trabajo, pero mis horas"',
    '"hours are in the afternoon..."': '"de trabajo son en la tarde..."',
    '"Pacific Standard Time, anyway."': '"Hora Estandar del Pacifico, en todo caso."',
    '"I might not be here if you"': '"Puede que no este aqui si"',
    '"come here too late, alright?"': '"vienes muy tarde, de acuerdo?"',

    '"Oh, um... Is that...?"': '"Oh, um... Eso es...?"',
    '"That\'s a ticket from"': '"Eso es un ticket de"',
    '"Ledrion, huh? (^666666Nuts! I\'ve"': '"Ledrion, eh? (^666666Rayos! Tengo"',
    '"got to work now?^000000) It\'s nice"': '"que trabajar ahora?^000000) Es un placer"',
    '"to meet you. I\'m Gatan."': '"conocerte. Soy Gatan."',

    '"Well, now I\'ve got a little"': '"Bueno, ahora tengo una"',
    '"test for you. You ready?"': '"pequena prueba para ti. Listo?"',
    '"Your objective is to gain"': '"Tu objetivo es ganar"',
    '"more levels! Let\'s see..."': '"mas niveles! Veamos..."',
    '"What would be fair?"': '"Que seria justo?"',

    '"Actually, you\'re already"': '"En realidad, ya eres"',
    '"pretty strong. I don\'t feel"': '"bastante fuerte. Yo tampoco"',
    '"like doing much work either,"': '"tengo ganas de trabajar mucho,"',
    '"so we\'ll just say that you"': '"asi que diremos que"',
    '"finished my test, alright?"': '"terminaste mi prueba, si?"',
    '"Just don\'t tell anyone!"': '"Solo no le digas a nadie!"',

    '"Hold on a second..."': '"Espera un segundo..."',
    '"I\'m supposed to tell"': '"Se supone que debo"',
    '"you something... Give"': '"decirte algo... Dame"',
    '"me a minute, will you?"': '"un minuto, si?"',

    '"You\'re pretty strong,"': '"Eres bastante fuerte,"',
    '"but it wouldn\'t kill"': '"pero no te mataria"',
    '"you to gain 1 more"': '"ganar 1 Nivel"',
    '"Base Level. Go ahead"': '"Base mas. Adelante,"',
    '"and do that, alright?"': '"hazlo, de acuerdo?"',
    '"you to gain 2 more"': '"ganar 2 Niveles"',
    '"Base Levels. Go ahead"': '"Base mas. Adelante,"',

    '"I\'ll go ahead and take"': '"Voy a tomar"',
    '"your ticket now. Come"': '"tu ticket ahora. Regresa"',
    '"back after you finish what"': '"despues de terminar lo que"',
    '"I\'ve asked, and then we can"': '"te pedi, y luego podremos"',
    '"move on to the next part."': '"pasar a la siguiente parte."',

    '"You know, you\'d probably"': '"Sabes, probablemente te"',
    '"benefit from being just"': '"beneficiarias de ser solo"',
    '"a little bit stronger. Now"': '"un poco mas fuerte. Ahora"',
    '"go out and gain 3 Base"': '"sal y gana 3 Niveles"',
    '"Levels for me, okay?"': '"Base para mi, si?"',

    '"Ledrion, huh? It\'s nice"': '"Ledrion, eh? Es un placer"',

    '"I\'m not on shift right"': '"No estoy en turno ahora"',
    '"now, though: even I need"': '"mismo: hasta yo necesito"',
    '"to take some off time to"': '"tomarme un tiempo libre para"',
    '"avoid getting swamped with"': '"evitar ahogarme con"',
    '"work. Come back to me during"': '"trabajo. Regresa durante"',
    '"my work hours, alright?"': '"mis horas de trabajo, de acuerdo?"',

    '"when I\'m working (^666666well,"': '"cuando trabajo (^666666bueno,"',
    '"I just want to avoid working"': '"solo quiero evitar trabajar"',
    '"altogether to be honest^000000) but"': '"para ser honesto^000000) pero"',
    '"come back in the afternoon,"': '"regresa en la tarde,"',
    '"Pacific Standard Time, that is."': '"Hora Estandar del Pacifico, claro."',

    '"Did you give that ticket"': '"Le diste ese ticket"',
    '"to the Thief Class member"': '"al miembro clase Ladron"',
    '"of your group? ^666666*Yawn*^000000 If you"': '"de tu grupo? ^666666*Bostezo*^000000 Si"',
    '"wanna finish all of these"': '"quieres terminar todos estos"',
    '"challenges, then that\'s"': '"desafios, entonces eso"',
    '"what you gotta do~"': '"es lo que tienes que hacer~"',

    '"Ah, very nice!"': '"Ah, muy bien!"',
    '"Now please give this"': '"Ahora por favor dale este"',
    '"ticket to the Thief Class"': '"ticket al miembro clase"',
    '"member of the your group,"': '"Ladron de tu grupo,"',
    '"and ask him to deliver"': '"y pidele que se lo"',
    '"it to Bafhail. Easy, right?"': '"entregue a Bafhail. Facil, no?"',

    '"Here you are..."': '"Aqui tienes..."',
    '"Just a little"': '"Solo un poco"',
    '"something for"': '"de algo para"',
    '"your troubles~"': '"tus esfuerzos~"',

    '"Don\'t forget to make"': '"No olvides asegurarte"',
    '"sure that Bafhail gets"': '"de que Bafhail reciba"',
    '"that ticket from a Thief"': '"ese ticket de un personaje"',
    '"Class character in your"': '"clase Ladron de tu"',
    '"group. I\'ll see you around."': '"grupo. Nos vemos por ahi."',

    '"Nice work. I guess"': '"Buen trabajo. Supongo que"',
    '"that Ledrion really knows"': '"Ledrion realmente sabe reconocer"',
    '"good adventurers when he"': '"buenos aventureros cuando los"',
    '"sees them. Now, you mind"': '"ve. Ahora, te importa"',
    '"waiting a bit? Um, there\'s"': '"esperar un poco? Um, hay"',
    '"something I have to give you..."': '"algo que tengo que darte..."',

    '"You didn\'t forget that"': '"No olvidaste que"',
    '"you had to gain 3 more"': '"tenias que ganar 3"',
    '"Base Levels, did you?"': '"Niveles Base mas, verdad?"',
    '"Oh, and come back during"': '"Oh, y regresa durante"',
    '"my regular working hours."': '"mis horas regulares de trabajo."',
    '"Don\'t bother me when I\'m off~"': '"No me molestes cuando no trabajo~"',
    '"you had to gain 2 more"': '"tenias que ganar 2"',
    '"you had to gain 1 more"': '"tenias que ganar 1"',
    '"Base Level, did you?"': '"Nivel Base mas, verdad?"',

    '"I\'ll tell you when I work"': '"Te dire cuando trabajo"',
    '"one more time: come from"': '"una vez mas: ven de"',
    '"11 AM to 2 PM, or 12 AM to"': '"11 AM a 2 PM, o de 12 AM a"',
    '"3 AM, Pacific Standard Time."': '"3 AM, Hora Estandar del Pacifico."',
    '"Good luck to you, alright?"': '"Buena suerte, de acuerdo?"',

    '"Ledrion wanted me to give"': '"Ledrion queria que le diera"',
    '"a little test if any Swordman"': '"una pequena prueba a cualquier"',
    '"Class guys brought me a ticket,"': '"clase Espadachin que me trajera un ticket,"',
    '"and were working with a group."': '"y estuviera trabajando con un grupo."',
    '"Ready? Increasing your Base"': '"Listo? Aumentar tu Nivel"',
    '"Level will be my test for you."': '"Base sera mi prueba para ti."',

    '"I\'ll keep your ticket."': '"Me quedare con tu ticket."',
    '"When you\'re finished, please come back."': '"Cuando termines, por favor regresa."',

    '"Hate to tell you, but"': '"Odio decirtelo, pero"',
    '"I\'m not on duty right now."': '"no estoy de turno ahora."',
    '"You should really come back"': '"Realmente deberias regresar"',
    '"and talk to me during my"': '"y hablar conmigo durante mis"',
    '"work hours, okay? I need"': '"horas de trabajo, si? Necesito"',
    '"my rest from work, you know?"': '"mi descanso del trabajo, sabes?"',

    '"I\'ll tell you when I work,"': '"Te dire cuando trabajo,"',
    '"just don\'t forget: come from"': '"solo no lo olvides: ven de"',

    '"Hey, nice meeting you."': '"Oye, gusto en conocerte."',
    '"I\'m Gatan. I\'m not up to"': '"Soy Gatan. No estoy haciendo"',
    '"much, just helping out"': '"mucho, solo ayudando a"',
    '"a friend. He\'s loaded, but"': '"un amigo. Es adinerado, pero"',
    '"he\'s also a really good guy."': '"tambien es muy buena persona."',
    '"Working me to the bone, though."': '"Aunque me hace trabajar hasta los huesos."',

    '"Now I work three hours"': '"Ahora trabajo tres horas"',
    '"just before I have lunch,"': '"justo antes de almorzar,"',
    '"and three hours around"': '"y tres horas alrededor de"',
    '"midnight. Go ahead and"': '"medianoche. Ve y"',
    '"look me up around those"': '"buscame alrededor de esas"',
    '"times. A bit confusing, I know~"': '"horas. Un poco confuso, lo se~"',

    '"Say, it\'s not time for"': '"Oye, no es momento para"',
    '"you to meet up with me"': '"que te reunas conmigo"',
    '"just yet. I think you need"': '"todavia. Creo que necesitas"',
    '"to ask an Acolyte Class"': '"pedirle a un miembro clase"',
    '"member in your group to bring"': '"Acolito de tu grupo que lleve"',
    '"your sixth ticket to Bafhail."': '"tu sexto ticket a Bafhail."',
    '"give this ticket to an"': '"dale este ticket a un"',
    '"Acolyte Class member"': '"miembro clase Acolito"',

    # === BAFHAIL ===
    '"You must be confused..."': '"Debes estar confundido..."',
    '"It\'s not time for you"': '"No es momento para que"',
    '"to see me just yet."': '"me veas todavia."',
    '"Have you tried meeting"': '"Has intentado reunirte"',
    '"with any of the other guys?"': '"con alguno de los otros?"',

    '"to an Archer or Merchant"': '"a un miembro clase Arquero o"',
    '"Class member of your group?"': '"Mercader de tu grupo?"',
    '"Just a reminder in case"': '"Solo un recordatorio en caso"',
    '"you\'ve already forgotten."': '"de que ya lo hayas olvidado."',

    '"Well, it looks like you came"': '"Bueno, parece que viniste"',
    '"at the right time and brought"': '"a la hora correcta y trajiste"',
    '"everything I asked. Good work."': '"todo lo que pedi. Buen trabajo."',
    '"Please take your next ticket"': '"Por favor toma tu siguiente ticket"',
    '"and this small reward for you."': '"y esta pequena recompensa para ti."',

    '"Make sure that you give"': '"Asegurate de darle"',
    '"that ticket to an Archer"': '"ese ticket a un miembro"',
    '"or Merchant Class member"': '"clase Arquero o Mercader"',
    '"of your group, and have him"': '"de tu grupo, y que lo"',
    '"bring it to a boy named Lospii."': '"lleve a un chico llamado Lospii."',
    '"Goodbye now, and good luck~"': '"Adios, y buena suerte~"',

    '"My mission for you is"': '"Mi mision para ti es"',
    '"to bring me some items"': '"traerme algunos items"',
    '"at the right time. I\'ll only"': '"a la hora correcta. Solo"',
    '"accept your items for 3 hours"': '"aceptare tus items por 3 horas"',
    '"once the day starts, and for 3"': '"cuando comience el dia, y por 3"',
    '"hours in the middle of the day."': '"horas a la mitad del dia."',
    '"I need"': '"Necesito"',
    '"^4D4DFF20 Anolian Skins^000000, and"': '"^4D4DFF20 Anolian Skins^000000, y"',
    '"Don\'t forget now, alright?"': '"No lo olvides, de acuerdo?"',

    '"Oh, isn\'t that ticket...?"': '"Oh, no es ese ticket...?"',
    '"Ah, good, good. Judging"': '"Ah, bien, bien. A juzgar"',
    '"from your Job, Gatan must"': '"por tu Clase, Gatan debio"',
    '"have sent you, right? Nice"': '"haberte enviado, no? Gusto"',
    '"to meet you, I\'m Bafhail~"': '"en conocerte, soy Bafhail~"',
    '"Now, let\'s get to business."': '"Ahora, al grano."',
    '"My mission is"': '"Mi mision es"',
    '"for you to collect"': '"que recolectes"',
    '"Understood?"': '"Entendido?"',
    '"Alright then, if you\'ll"': '"Bien entonces, si me"',
    '"just hand me your ticket,"': '"entregas tu ticket,"',
    '"you can start gathering"': '"puedes empezar a recolectar"',
    '"those items I listed."': '"los items que mencione."',
    '"I\'ll see you later~"': '"Nos vemos luego~"',

    '"Would you mind coming "': '"Te importaria volver "',
    '"back to me later? Now"': '"a verme mas tarde? Ahora"',
    '"isn\'t the right time to talk"': '"no es el momento de hablar"',
    '"to me. I\'m available for 3"': '"conmigo. Estoy disponible por 3"',
    '"hours at the start of the day,"': '"horas al inicio del dia,"',
    '"and 3 hours in midday."': '"y 3 horas al mediodia."',

    '"Do me a favor and make"': '"Hazme un favor y asegurate"',
    '"sure that the Merchant"': '"de que el personaje clase"',
    '"Class character in your"': '"Mercader de tu"',
    '"group delivers that ticket"': '"grupo entregue ese ticket"',
    '"to Lospii. Alright, I guess"': '"a Lospii. Bueno, supongo que"',
    '"I\'ll see you later, then."': '"nos vemos despues, entonces."',

    '"Remember to bring me"': '"Recuerda traerme"',
    '"the items I requested"': '"los items que pedi"',
    '"at the right time, during"': '"a la hora correcta, durante"',
    '"the 3 hours after noon or"': '"las 3 horas despues del mediodia o"',
    '"3 hours in the early evening."': '"3 horas en la tarde temprana."',
    '"Now, I want you to bring..."': '"Ahora, quiero que traigas..."',
    '"^4D4DFF10 Leopard Claws^000000, and"': '"^4D4DFF10 Leopard Claws^000000, y"',
    '"I\'ll be waiting for you here"': '"Te estare esperando aqui"',
    '"and will accept those items"': '"y aceptare esos items"',

    '"Remember that your"': '"Recuerda que tu"',
    '"mission from me is"': '"mision de mi parte es"',
    '"to collect some items,"': '"recolectar algunos items,"',
    '"and to bring them to"': '"y traermelos"',
    '"me at the right time."': '"a la hora correcta."',
    '"I\'ll only accept your"': '"Solo aceptare tus"',
    '"items for 3 hours after"': '"items por 3 horas despues"',
    '"the day starts, and for"': '"de que comience el dia, y por"',
    '"3 hours during midday."': '"3 horas durante el mediodia."',
    '"These are the items"': '"Estos son los items"',
    '"that I want you to bring..."': '"que quiero que traigas..."',
    '"^4D4DFF10 Dokebi Horns^000000, and"': '"^4D4DFF10 Dokebi Horns^000000, y"',
    '"I\'ll be here waiting for"': '"Estare aqui esperando"',
    '"you during the hours"': '"durante las horas"',
    '"I just described, okay?"': '"que acabo de describir, si?"',

    '"Alright, let\'s get down"': '"Bien, vamos a lo"',
    '"to what you came for."': '"que viniste."',
    '"My mission is for you to"': '"Mi mision para ti es"',
    '"collect some items, and"': '"recolectar algunos items, y"',
    '"for you to bring them at"': '"que los traigas a"',
    '"the right time. Bring me..."': '"la hora correcta. Traeme..."',

    '"Would you mind coming"': '"Te importaria volver"',
    '"isn\'t the right time to"': '"no es el momento de"',
    '"talk to me. I\'m available"': '"hablar conmigo. Estoy disponible"',
    '"from 8 AM to 11 AM, and"': '"de 8 AM a 11 AM, y"',
    '"from 9 PM to 12 AM."': '"de 9 PM a 12 AM."',

    '"Oh, did you already"': '"Oh, ya entregaste"',
    '"deliver the ticket that"': '"el ticket que"',
    '"I gave you? If that\'s the"': '"te di? Si es asi,"',
    '"case, we won\'t have any"': '"no tendremos ningun"',
    '"business with each other"': '"asunto entre nosotros"',
    '"for a while, I suppose."': '"por un tiempo, supongo."',

    '"Your mission"': '"Tu mision"',
    '"is to bring me"': '"es traerme"',
    '"^4D4DFF10 Wolf Claws^000000, and"': '"^4D4DFF10 Wolf Claws^000000, y"',
    '"during hours I accept items."': '"durante las horas que acepto items."',
    '"Remember that I only"': '"Recuerda que solo"',
    '"accept items from 8 AM"': '"acepto items de 8 AM"',
    '"to 11 AM, and from 9 PM"': '"a 11 AM, y de 9 PM"',
    '"to 12 AM. That\'s Pacific"': '"a 12 AM. Eso es Hora"',
    '"Standard Time. Don\'t forget!"': '"Estandar del Pacifico. No lo olvides!"',
    '"^4D4DFF10 Porcupine Quills^000000, and"': '"^4D4DFF10 Porcupine Quills^000000, y"',

    '"Remember that I won\'t"': '"Recuerda que no"',
    '"accept your items, even"': '"aceptare tus items, aunque"',
    '"if you have everything,"': '"tengas todo,"',
    '"if you don\'t come during"': '"si no vienes durante"',
    '"the hours when I accept"': '"las horas en que acepto"',
    '"items for missions, okay?"': '"items para misiones, de acuerdo?"',

    '"Please give that"': '"Por favor dale ese"',
    '"ticket to the Archer"': '"ticket al miembro"',
    '"Class member of your"': '"clase Arquero de tu"',
    '"group, and have him"': '"grupo, y que lo"',
    '"deliver it to Lospii, okay?"': '"entregue a Lospii, si?"',
    '"Good luck on your travels~"': '"Buena suerte en tus viajes~"',

    '"...Hm? I don\'t think"': '"...Hm? No creo que"',
    '"we have any business"': '"tengamos ningun asunto"',
    '"with each other. You mind"': '"entre nosotros. Te importa"',
    '"leaving me alone? I\'m pretty"': '"dejarme solo? Estoy bastante"',
    '"busy administering a bunch"': '"ocupado administrando un monton"',
    '"of these missions for a friend."': '"de estas misiones para un amigo."',
    '"If we\'re lucky, maybe"': '"Si tenemos suerte, quizas"',
    '"you\'ll be one of those"': '"seras uno de esos"',
    '"adventurers that\'ll carry"': '"aventureros que llevaran"',
    '"out these fun little missions"': '"a cabo estas divertidas misiones"',
    '"for my friend Ledrion."': '"para mi amigo Ledrion."',

    # === LOSPII ===
    '"Hey, didn\'t you figure"': '"Oye, no te diste"',
    '"out what you need to do?"': '"cuenta de lo que tienes que hacer?"',
    '"You\'re not supposed to"': '"No deberias"',
    '"talk to me now! Mmm..."': '"hablar conmigo ahora! Mmm..."',
    '"I don\'t know who you"': '"No se con quien"',
    '"have to meet either, but..."': '"tienes que reunirte tampoco, pero..."',

    '"Hey! Did you give"': '"Oye! Le diste"',
    '"that ticket to the"': '"ese ticket al"',
    '"leader of your group"': '"lider de tu grupo"',
    '"yet? The guy that started"': '"ya? El tipo que inicio"',
    '"this whole relay thing!"': '"todo esto del relevo!"',

    '"Oh! You brought so many"': '"Oh! Trajiste tantos"',
    '"friends! One... T-two..."': '"amigos! Uno... D-dos..."',
    '"Maybe I gave you something"': '"Tal vez te di algo"',
    '"too easy to do. I didn\'t know"': '"muy facil. No sabia"',
    '"you knew this many people!"': '"que conocias a tanta gente!"',
    '"Oh well, thanks for"': '"Bueno, gracias por"',
    '"bringing everyone here."': '"traer a todos aqui."',
    '"For that, you get this"': '"Por eso, te doy este"',
    '"gift from me. Cool, huh?"': '"regalo de mi parte. Genial, no?"',

    '"Okay, now take this"': '"Bien, ahora toma este"',
    '"ticket, and give it to"': '"ticket, y daselo a"',
    '"your leader, the guy that"': '"tu lider, el tipo que"',
    '"started this whole relay"': '"inicio todo esto del"',
    '"thing. He needs to give"': '"relevo. El necesita darle"',
    '"the ticket to Ledrion, okay?"': '"el ticket a Ledrion, si?"',

    '"You\'re almost done!"': '"Ya casi terminas!"',
    '"...I think. Um, I\'m not"': '"...Creo. Um, no estoy"',
    '"really sure what will"': '"muy seguro de que"',
    '"happen next. I can only"': '"pasara despues. Solo puedo"',
    '"remember the parts I have"': '"recordar las partes que me"',
    '"to do. C\'mon! I\'m just a kid!"': '"tocan. Vamos! Solo soy un nino!"',

    '"Okay, you have to bring"': '"Bien, tienes que traerme"',
    '"me 10 of your friends when"': '"10 de tus amigos cuando"',
    '"I\'m working, okay? That\'s, uh,"': '"este trabajando, si? Eso es, eh,"',
    '"3 hours before noon, and then"': '"3 horas antes del mediodia, y luego"',
    '"another 3 hours after midnight."': '"otras 3 horas despues de medianoche."',
    '"Just only those times, okay?"': '"Solo en esos horarios, si?"',
    '"me 12 of your friends when"': '"12 de tus amigos cuando"',

    '"Hi, I\'m Lospii! Maybe"': '"Hola, soy Lospii! Quizas"',
    '"I\'m younger than you, but"': '"soy menor que tu, pero"',
    '"I\'m in charge of this mission!"': '"estoy a cargo de esta mision!"',
    '"So you have to listen, okay?"': '"Asi que tienes que escuchar, si?"',
    '"Heh heh! Don\'t be scared~"': '"Je je! No te asustes~"',

    '"I\'m working now for this"': '"Estoy trabajando ahora para esta"',
    '"mission thing so you came"': '"cosa de la mision asi que llegaste"',
    '"at a good time! Let\'s see..."': '"en buen momento! Veamos..."',
    '"I need to give you... Some"': '"Necesito darte... Alguna"',
    '"mission for you to doooo..."': '"mision para que hagaaas..."',
    '"Oh! I know! I got it!"': '"Oh! Ya se! Lo tengo!"',

    '"We\'re seeing if you"': '"Estamos viendo si"',
    '"know about teamwork, right?"': '"sabes de trabajo en equipo, no?"',
    '"Why don\'t you show me a lot"': '"Por que no me muestras muchos"',
    '"of your friends? Bring me..."': '"de tus amigos? Traeme..."',
    '"14 of them! Yes, that\'s good!"': '"14 de ellos! Si, eso esta bien!"',
    '"12 of them! Yes, that\'s good!"': '"12 de ellos! Si, eso esta bien!"',
    '"10 of them! Yes, that\'s good!"': '"10 de ellos! Si, eso esta bien!"',

    '"I need to be able to"': '"Necesito poder"',
    '"see them, you know, so"': '"verlos, sabes, para"',
    '"I know you\'re not lying"': '"saber que no me estas mintiendo."',
    '"to me. Bring them reeeally"': '"Traelos muuuy"',
    '"close so I know they\'re your"': '"cerca para saber que son tus"',
    '"friends, not some other guys."': '"amigos, no unos cualquiera."',

    '"Okay, I\'ll be right"': '"Bien, estare justo"',
    '"here! Oh! And you have"': '"aqui! Oh! Y tienes"',
    '"to come with your friends"': '"que venir con tus amigos"',
    '"while I\'m at work! That\'s"': '"mientras estoy trabajando! Eso"',
    '"important to know!"': '"es importante saberlo!"',

    '"Uh oh... I forgot"': '"Ay no... Olvide"',
    '"that I\'m not supposed"': '"que no deberia"',
    '"to be working now. Come"': '"estar trabajando ahora. Regresa"',
    '"back when I\'m working, okay?"': '"cuando este trabajando, si?"',

    '"I... I work before"': '"Yo... trabajo antes"',
    '"noon for 3 hours, and"': '"del mediodia por 3 horas, y"',
    '"then... 3 hours after"': '"luego... 3 horas despues"',
    '"midnight? Yes, those"': '"de medianoche? Si, esos"',
    '"are the times when"': '"son los horarios en que"',
    '"I\'m working!"': '"estoy trabajando!"',

    '"Huh? No, no, you\'re"': '"Eh? No, no, no deberias"',
    '"not supposed to be here!"': '"estar aqui!"',
    '"Give the eighth ticket to"': '"Dale el octavo ticket a"',
    '"your leader so he can give"': '"tu lider para que se lo de"',
    '"it to Ledrion! Your leader..."': '"a Ledrion! Tu lider..."',
    '"You know him, right?"': '"Lo conoces, verdad?"',

    '"Bring 10 of your friends"': '"Trae 10 de tus amigos"',
    '"here to me while I\'m working,"': '"aqui mientras estoy trabajando,"',
    '"okay? Umm... I work frooom..."': '"si? Umm... trabajo deeesde..."',
    '"2 PM to 5 PM, and 6 PM to 9 PM."': '"2 PM a 5 PM, y de 6 PM a 9 PM."',
    '"I think those are the times."': '"Creo que esos son los horarios."',
    '"I... I can\'t read watches..."': '"Yo... no se leer relojes..."',

    '"Umm... Did you bring"': '"Umm... Le llevaste"',
    '"the fourth ticket to your"': '"el cuarto ticket a tu"',
    '"leader yet? You know,"': '"lider ya? Ya sabes,"',
    '"the leader of the group."': '"el lider del grupo."',
    '"The one that started this"': '"El que inicio todo esto"',
    '"whole relay test thingee."': '"del relevo."',

    '"I work frooom... Uh..."': '"Trabajo deeesde... Eh..."',
    '"2 PM to 5 PM? Oh!"': '"2 PM a 5 PM? Oh!"',
    '"And also 6 PM to 9 PM."': '"Y tambien de 6 PM a 9 PM."',
    '"I think those are the"': '"Creo que esos son los"',
    '"times... I mean, clocks"': '"horarios... Digo, los relojes"',
    '"are hard to read, man!"': '"son dificiles de leer, viejo!"',

    '"Hi! I\'m Lospii!"': '"Hola! Soy Lospii!"',
    '"Hey, does it look like"': '"Oye, parece que"',
    '"I\'m at work? Ha ha!"': '"estoy trabajando? Ja ja!"',
    '"I got a job! I\'m helping"': '"Tengo trabajo! Estoy ayudando"',
    '"my friends a lot!"': '"mucho a mis amigos!"',
}

with open("npc/quests/partyrelay.txt", "r", encoding="utf-8") as f:
    content = f.read()

for eng, spa in translations.items():
    content = content.replace(eng, spa)

with open("npc/quests/partyrelay.txt", "w", encoding="utf-8") as f:
    f.write(content)

# Verify line count
lines = content.count('\n') + (1 if not content.endswith('\n') else 0)
print(f"Translation complete! Line count: {lines}")
