import sys

filepath = sys.argv[1]
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    # ALCHE_SK == 5
    ('mes "I\'m busy right now.";', 'mes "Estoy ocupado ahora.";'),
    ('mes "You didn\'t forget";', 'mes "No olvidaste";'),
    ('mes "anything did you?";', 'mes "nada, verdad?";'),
    ('mes "If not, you better";', 'mes "Si no, mejor";'),
    ('mes "get going and let";', 'mes "vete y dejame";'),
    ('mes "me do my work.";', 'mes "hacer mi trabajo.";'),
    ('select("Alright, sorry to bother you.:Can I still help you?")', 'select("Bien, disculpa la molestia.:Aun puedo ayudarte?")'),
    ('mes "Yeah, whatever.";', 'mes "Si, como sea.";'),
    ('mes "Just hurry up and leave";', 'mes "Solo apurate y vete";'),
    ('mes "so that I can concentrate.";', 'mes "para que pueda concentrarme.";'),
    ('mes "Huh? What made you";', 'mes "Eh? Que te hizo";'),
    ('mes "change your mind? Well,";', 'mes "cambiar de opinion? Bueno,";'),
    ('mes "I can\'t afford not to accept";', 'mes "no puedo darme el lujo de rechazar";'),
    ('mes "any help, so I guess that\'s";', 'mes "ninguna ayuda, asi que supongo que es";'),
    ('mes "a \\"Yes.\\" Yeah, you can help.";', 'mes "un \'Si\'. Si, puedes ayudar.";'),
    ('mes "Alright, go and get me";', 'mes "Bien, ve y consigueme";'),
    ('mes "If I weren\'t so sickly, I\'d get";', 'mes "Si no estuviera tan enfermo, las conseguiria";'),
    ('mes "them myself, but--*Cough* as";', 'mes "yo mismo, pero--*Cof* como";'),
    ('mes "you can see, I don\'t feel so well.";', 'mes "puedes ver, no me siento muy bien.";'),
    ('mes "I... I really";', 'mes "Yo... Realmente";'),
    ('mes "appreciate your";', 'mes "aprecio tu";'),
    ('mes "willingness to help";', 'mes "disposicion para ayudar";'),
    ('mes "me in my research...";', 'mes "en mi investigacion...";'),
    ('mes "I hope you get those";', 'mes "Espero que me traigas esos";'),
    ('mes "items to me as soon as";', 'mes "objetos lo antes";'),
    ('mes "you can. And don\'t flake";', 'mes "posible. Y no me";'),
    ('mes "out on me this time!";', 'mes "dejes plantado esta vez!";'),
    # Explosion + glasses scene
    ('mes "Thanks so much for";', 'mes "Muchas gracias por";'),
    ('mes "bringing me these";', 'mes "traerme estas";'),
    ('mes "Maneater Blossoms.";', 'mes "Maneater Blossoms.";'),
    ('mes "You don\'t know how";', 'mes "No sabes cuanto";'),
    ('mes "much this means to me~";', 'mes "significa esto para mi~";'),
    ('mes "Now all I have to do";', 'mes "Ahora solo tengo que";'),
    ('mes "is mix these with the";', 'mes "mezclarlas con el";'),
    ('mes "Clover extract I prepared.";', 'mes "extracto de Clover que prepare.";'),
    ('mes "Ah!";', 'mes "Ah!";'),
    ('mes "M-my face!";', 'mes "M-mi cara!";'),
    ('mes "Hey...";', 'mes "Oye...";'),
    ('mes "Are you alright?";', 'mes "Estas bien?";'),
    ('mes "That was a pretty";', 'mes "Esa fue una";'),
    ('mes "big explosion...";', 'mes "gran explosion...";'),
    ('mes "Your glasses...";', 'mes "Tus lentes...";'),
    ('mes "They\'re broken...";', 'mes "Estan rotos...";'),
    ('mes "^3355FFThe explosion destroyed";', 'mes "^3355FFLa explosion destruyo";'),
    ('mes "Pisruik\'s glasses, revealing";', 'mes "los lentes de Pisruik, revelando";'),
    ('mes "the beautiful face of a";', 'mes "el hermoso rostro de un";'),
    ('mes "gorgeous, gorgeous man.^000000";', 'mes "hombre guapisimo.^000000";'),
    ('mes "^3355FFThe explosion blew off";', 'mes "^3355FFLa explosion volo";'),
    ('mes "Pisruik\'s glasses. Without";', 'mes "los lentes de Pisruik. Sin";'),
    ('mes "them, he looks more like";', 'mes "ellos, se parece mas a";'),
    ('mes "a male model than a dorky";', 'mes "un modelo que a un nerd";'),
    ('mes "scientific researcher.^000000";', 'mes "investigador cientifico.^000000";'),
    ('mes "Holy crap!";', 'mes "Santo cielo!";'),
    ('mes "You\'re one";', 'mes "Eres un tipo";'),
    ('mes "good looking guy!";', 'mes "muy guapo!";'),
    ('mes "I c-can\'t see too";', 'mes "N-no puedo ver muy";'),
    ('mes "well without my glasses.";', 'mes "bien sin mis lentes.";'),
    ('mes "Well, at least I can tell";', 'mes "Bueno, al menos puedo ver";'),
    ('mes "that you\'re not bleeding.";', 'mes "que no estas sangrando.";'),
    ('mes "But are you alright?";', 'mes "Pero estas bien?";'),
    ('mes "Oh, I\'m fine.";', 'mes "Oh, estoy bien.";'),
    ('mes "But what are you";', 'mes "Pero que vas a";'),
    ('mes "going to do about";', 'mes "hacer con";'),
    ('mes "your glasses?";', 'mes "tus lentes?";'),
    ('mes "Shoot, you\'re right.";', 'mes "Rayos, tienes razon.";'),
    ('mes "I don\'t happen to have";', 'mes "No tengo";'),
    ('mes "an extra pair. Hey, can";', 'mes "un par extra. Oye, puedes";'),
    ('mes "you get me a pair of glasses,";', 'mes "conseguirme unos lentes,";'),
    ('mes "the same kind I used to wear?";', 'mes "del mismo tipo que usaba?";'),
    ('mes "I know it\'s too much";', 'mes "Se que es mucho";'),
    ('mes "to ask you for, but I\'m";', 'mes "pedirte, pero estoy";'),
    ('mes "almost blind without them.";', 'mes "casi ciego sin ellos.";'),
    ('mes "I can\'t do very much if I can\'t";', 'mes "No puedo hacer mucho si no";'),
    ('mes "even see. I\'m really sorry";', 'mes "puedo ni ver. Lo siento mucho";'),
    ('mes "about this, "+ strcharinfo(0) +".";', 'mes "por esto, "+ strcharinfo(0) +".";'),
    # ALCHE_SK == 6 else
    ('mes "Would you come back with";', 'mes "Podrias volver con";'),
    ('mes "so that I can finish this";', 'mes "para que pueda terminar esta";'),
    ('mes "medicine I\'m working on?";', 'mes "medicina en la que trabajo?";'),
    ('mes "Thanks, thanks, I\'ve got";', 'mes "Gracias, gracias, tengo";'),
    ('mes "to hustle with this project...";', 'mes "que apurarme con este proyecto...";'),
    # ALCHE_SK == 7/8
    ('mes "Hmmm...";', 'mes "Hmmm...";'),
    ('mes "Actually, I miscalculated";', 'mes "En realidad, calcule mal";'),
    ('mes "the number of Maneater";', 'mes "el numero de Maneater";'),
    ('mes "Blossoms that I need. Would";', 'mes "Blossoms que necesito. Podrias";'),
    ('mes "you bring me one more? Sorry, I know it\'s kind of troublesome...";', 'mes "traerme una mas? Perdon, se que es algo molesto...";'),
    ('mes "Thanks so much!";', 'mes "Muchas gracias!";'),
    ('mes "Now I finally have the";', 'mes "Ahora por fin tengo la";'),
    ('mes "exact amount of Maneater";', 'mes "cantidad exacta de Maneater";'),
    ('mes "Blossoms that I\'ll need.";', 'mes "Blossoms que necesitare.";'),
    ('mes "I\'m really sorry for putting";', 'mes "Lamento mucho haberte";'),
    ('mes "your through all this trouble.";', 'mes "causado tantas molestias.";'),
    ('mes "Finally, I begin the most";', 'mes "Finalmente, comienzo la parte";'),
    ('mes "exciting part of this project!";', 'mes "mas emocionante de este proyecto!";'),
    # ALCHE_SK == 9
    ('mes "^3355FFPisruik is holding his";', 'mes "^3355FFPisruik esta sosteniendo sus";'),
    ('mes "broken glasses, squinting";', 'mes "lentes rotos, entrecerando";'),
    ('mes "his eyes. It seems he like";', 'mes "los ojos. Parece que el";'),
    ('mes "he really does need them,";', 'mes "realmente los necesita,";'),
    ('mes "even if he looks much less";', 'mes "aunque se ve mucho menos";'),
    ('mes "dorky without them.^000000";', 'mes "nerd sin ellos.^000000";'),
    ('select("Let him try a pair of your glasses:Don\'t give him anything")', 'select("Dejar que pruebe unos de tus lentes:No darle nada")'),
    ('mes "Here, why don\'t you";', 'mes "Toma, por que no";'),
    ('mes "check I\'m carrying and";', 'mes "revisas lo que traigo y";'),
    ('mes "see if there\'s a pair of";', 'mes "ves si hay unos";'),
    ('mes "glasses that you can use?";', 'mes "lentes que puedas usar?";'),
    ('mes "Huh? Oh, is that you?";', 'mes "Eh? Oh, eres tu?";'),
    ('mes "Ah, this pair of glasses";', 'mes "Ah, estos lentes";'),
    ('mes "works! Thanks a lot, now";', 'mes "funcionan! Muchas gracias, ahora";'),
    ('mes "I can see again! Now, let";', 'mes "puedo ver otra vez! Ahora, dejame";'),
    ('mes "me check the results of the";', 'mes "revisar los resultados del";'),
    ('mes "experiment we conducted.";', 'mes "experimento que realizamos.";'),
    ('mes "Okay, the test tube wasn\'t";', 'mes "Bien, el tubo de ensayo no se";'),
    ('mes "damaged. Yes, according to";', 'mes "dano. Si, segun estas";'),
    ('mes "these readings, this medicine";', 'mes "lecturas, esta medicina";'),
    ('mes "should be fully functional!";', 'mes "deberia ser completamente funcional!";'),
    ('mes "I think it was a success!";', 'mes "Creo que fue un exito!";'),
    ('mes "Well, theoretically anyway.";', 'mes "Bueno, teoricamente al menos.";'),
    ('mes "Hmm, changing the attributes";', 'mes "Hmm, cambiar los atributos";'),
    ('mes "of the human body for certain";', 'mes "del cuerpo humano para ciertos";'),
    ('mes "effects may cause controversy";', 'mes "efectos puede causar controversia";'),
    ('mes "later, but hopefully this thing";', 'mes "despues, pero con suerte esto";'),
    ("mes \"I've invented will be used for\";", 'mes "que invente se usara para";'),
    ('mes "good. Ah, that\'s right!";', 'mes "el bien. Ah, es cierto!";'),
    ('mes "Would you like me to";', 'mes "Te gustaria que te";'),
    ('mes "teach you everything I\'ve";', 'mes "ensenara todo lo que he";'),
    ('mes "learned in my research? You";', 'mes "aprendido en mi investigacion? Deberias";'),
    ('mes "should be able to create a new";', 'mes "poder crear un nuevo";'),
    ('mes "type of potion by making use of";', 'mes "tipo de pocion usando";'),
    ('mes "the knowledge I can teach you.";', 'mes "el conocimiento que puedo ensenarte.";'),
    ('select("Sure!:No, thanks.")', 'select("Claro!:No, gracias.")'),
    # Teaching scene
    ('mes "I know I can trust you";', 'mes "Se que puedo confiar en ti";'),
    ('mes "to use this research for";', 'mes "para usar esta investigacion para";'),
    ('mes "good and noble ends. Now,";', 'mes "fines buenos y nobles. Ahora,";'),
    ('mes "please read this thesis and";', 'mes "por favor lee esta tesis y";'),
    ('mes "all of my additional notes...";', 'mes "todas mis notas adicionales...";'),
    ('mes "^3355FFPisruik thoroughly";', 'mes "^3355FFPisruik explica a fondo";'),
    ('mes "explains the properties";', 'mes "las propiedades";'),
    ('mes "of his medicine, the reaction";', 'mes "de su medicina, la reaccion";'),
    ('mes "of the human organs to it, as";', 'mes "de los organos humanos a ella, asi";'),
    ('mes "well as a few warnings about";', 'mes "como algunas advertencias sobre";'),
    ("mes \"the medicine's side effects.^000000\";", 'mes "los efectos secundarios de la medicina.^000000";'),
    ('mes "Well, you should be";', 'mes "Bueno, deberias estar";'),
    ('mes "ready to make your own";', 'mes "listo para hacer tus propias";'),
    ('mes "potions that are a variation";', 'mes "pociones que son una variacion";'),
    ('mes "of my medicine. But you\'ll";', 'mes "de mi medicina. Pero probablemente";'),
    ('mes "probably need to keep that";', 'mes "necesitaras tener esa";'),
    ('mes "thesis as a ready reference.";', 'mes "tesis como referencia.";'),
    ('mes "Hopefully, we\'ll";', 'mes "Con suerte, nos";'),
    ('mes "meet again sometime";', 'mes "veremos otra vez";'),
    ('mes "in the future. Good luck on";', 'mes "en el futuro. Buena suerte en";'),
    ('mes "your journeys, adventurer.";', 'mes "tus viajes, aventurero.";'),
    ('mes "*Cough cough* Now... What";', 'mes "*Cof cof* Ahora... Cual";'),
    ('mes "will be my next project?";', 'mes "sera mi proximo proyecto?";'),
    ('mes "Anyway, I need to be";', 'mes "En fin, necesito estar";'),
    ('mes "working on a new project";', 'mes "trabajando en un nuevo proyecto";'),
    ('mes "soon, so I suppose this is";', 'mes "pronto, asi que supongo que aqui";'),
    ('mes "where we part ways for now.";', 'mes "nos separamos por ahora.";'),
    ('mes "But I must say, it was truly";', 'mes "Pero debo decir, fue realmente";'),
    ('mes "a great pleasure to meet you...";', 'mes "un gran placer conocerte...";'),
    # Refuse to learn
    ('mes "R-Really...?";', 'mes "D-De verdad...?";'),
    ('mes "Well, if you ever change";', 'mes "Bueno, si alguna vez cambias";'),
    ('mes "your mind, feel free to come";', 'mes "de opinion, sientete libre de venir";'),
    ('mes "back for me to teach you.";', 'mes "para que te ensene.";'),
    ('mes "And it\'s no trouble at all!";', 'mes "Y no es ninguna molestia!";'),
    ('mes "I really enjoy your company...";', 'mes "Realmente disfruto tu compania...";'),
    # ALCHE_SK == 11
    ('mes "Uh oh...";', 'mes "Oh no...";'),
    ('mes "You lost the thesis";', 'mes "Perdiste la tesis";'),
    ('mes "I wrote for you? I don\'t";', 'mes "que escribi para ti? No";'),
    ('mes "have the time to write";', 'mes "tengo tiempo de escribir";'),
    ('mes "another one for you now...";', 'mes "otra para ti ahora...";'),
    ('mes "So, how have you been";', 'mes "Entonces, como te ha ido";'),
    ('mes "using the potions that";', 'mes "usando las pociones que";'),
    ("mes \"I've taught you to make?\";", 'mes "te ensene a hacer?";'),
    ('mes "Hopefully, they\'ll come";', 'mes "Con suerte, te seran";'),
    ('mes "in handy in your adventures.";', 'mes "utiles en tus aventuras.";'),
    ('mes "Huh, so copies of my";', 'mes "Huh, asi que copias de mi";'),
    ('mes "thesis are circulating";', 'mes "tesis estan circulando";'),
    ('mes "around in public? Well,";', 'mes "por ahi en publico? Bueno,";'),
    ("mes \"I'm sorry, but I don't have\";", 'mes "lo siento, pero no tengo";'),
    ('mes "time to autograph your copy...";', 'mes "tiempo para autografiar tu copia...";'),
    # Default messages
    ('mes "Mmm...?";', 'mes "Mmm...?";'),
    ('mes "Did you need anything";', 'mes "Necesitabas algo";'),
    ('mes "in particular? Though,";', 'mes "en particular? Aunque,";'),
    ("mes \"I'm afraid someone in\";", 'mes "me temo que alguien en";'),
    ('mes "my position won\'t be";', 'mes "mi posicion no sera";'),
    ('mes "much help to you.";', 'mes "de mucha ayuda para ti.";'),
    # ALCHE_SK == 10
    ('mes "So, "+ strcharinfo(0) +",";', 'mes "Entonces, "+ strcharinfo(0) +",";'),
    ('mes "teach you the results";', 'mes "ensenara los resultados";'),
    ("mes \"of the research I've''\";", 'mes "de la investigacion que he";'),
    ('mes "been conducting?";', 'mes "estado realizando?";'),
    ('select("Yes!:No, thanks.")', 'select("Si!:No, gracias.")'),
    # Narration - no glasses
    ('mes "Listen, you look so";', 'mes "Oye, te ves mucho";'),
    ('mes "much better when you\'re";', 'mes "mejor cuando no";'),
    ('mes "not wearing glasses.";', 'mes "usas lentes.";'),
    ('mes "Excuse me,";', 'mes "Disculpa,";'),
    ('mes "come again?";', 'mes "que dijiste?";'),
    ('mes "Hahahahhaha~!";', 'mes "Jajajajaja~!";'),
    ('mes "No-nothing at all!";', 'mes "Na-nada en absoluto!";'),
    # Irache NPC
    ('mes "Heh heh heh...!";', 'mes "Je je je...!";'),
    ("mes \"It's done! With this\";", 'mes "Esta listo! Con esta";'),
    ('mes "formula, I can melt any";', 'mes "formula, puedo derretir cualquier";'),
    ('mes "substance in the world!";', 'mes "sustancia en el mundo!";'),
    ('mes "Hahahaha! Nothing stands";', 'mes "Jajajaja! Nada se interpone";'),
    ('mes "between me and world domi--";', 'mes "entre yo y la domina--";'),
    ('mes "OWWWW!";', 'mes "AYYY!";'),
    ('mes "The secret formula!";', 'mes "La formula secreta!";'),
    ("mes \"It's burning through\";", 'mes "Esta quemando";'),
    ("mes \"the test tube! I've made\";", 'mes "el tubo de ensayo! La hice";'),
    ('mes "it too powerful! Confound it!";', 'mes "demasiado poderosa! Maldicion!";'),
    # Degas NPC
    ("mes \"It's such a pain working\";", 'mes "Es un fastidio trabajar";'),
    ('mes "so close to these other";', 'mes "tan cerca de estos otros";'),
    ('mes "scientists. The guy next";', 'mes "cientificos. El tipo de al";'),
    ('mes "time is always cackling";', 'mes "lado siempre se rie";'),
    ('mes "about taking over the";', 'mes "sobre conquistar el";'),
    ('mes "world and whatnot.";', 'mes "mundo y esas cosas.";'),
    ('mes "And this other geek is";', 'mes "Y este otro nerd siempre";'),
    ('mes "always coughing. Between";', 'mes "esta tosiendo. Entre";'),
    ("mes \"the two of them, it's far too\";", 'mes "los dos, hay demasiado";'),
    ('mes "noisy to focus on my research!";', 'mes "ruido para concentrarme en mi investigacion!";'),
    ('mes "If only I could work in my very own private, secret laboratory...";', 'mes "Si tan solo pudiera trabajar en mi propio laboratorio privado y secreto...";'),
    # Pile of Books
    ("mes \"^3355FFIt's simply a pile\";", 'mes "^3355FFEs simplemente una pila";'),
    ('mes "of scattered documents.";', 'mes "de documentos dispersos.";'),
    ('mes "Although it seems unorganized,";', 'mes "Aunque parece desorganizado,";'),
    ("mes \"it doesn't look like the people\";", 'mes "no parece que la gente";'),
    ('mes "here have any trouble finding^FFFFFF ^3355FF what they need when they need it.";', 'mes "de aqui tenga problemas para encontrar^FFFFFF ^3355FF lo que necesita cuando lo necesita.";'),
    # Kellasus NPC - bioeth == 13
    ('mes "Keep up the";', 'mes "Sigue con el";'),
    ('mes "good work. I get";', 'mes "buen trabajo. Tengo";'),
    ('mes "the feeling that";', 'mes "el presentimiento de que";'),
    ('mes "our future might";', 'mes "nuestro futuro podria";'),
    ('mes "be depending on you...";', 'mes "depender de ti...";'),
    # bioeth == 12
    ('mes "Alright then, I\'ll begin";', 'mes "Muy bien, comenzare";'),
    ('mes "by teaching you ^FF0000Bioethics^000000,";', 'mes "ensenandote ^FF0000Bioethics^000000,";'),
    ('mes "the fundamental skill for";', 'mes "la habilidad fundamental para";'),
    ('mes "creating Homunculi.";', 'mes "crear Homunculi.";'),
    ('mes "In order to master Bioethics,";', 'mes "Para dominar Bioethics,";'),
    ("mes \"you've got to appreciate the\";", 'mes "tienes que apreciar la";'),
    ('mes "sweetness of life and genuinely";', 'mes "dulzura de la vida y genuinamente";'),
    ('mes "care about living creatures.";', 'mes "preocuparte por los seres vivos.";'),
    ('mes "And so, you must always take";', 'mes "Y por eso, siempre debes";'),
    ('mes "care of your Homunculus.";', 'mes "cuidar de tu Homunculus.";'),
    ('mes "You must constantly check";', 'mes "Debes revisar constantemente";'),
    ('mes "to see if your Homunculus";', 'mes "si tu Homunculus";'),
    ("mes \"is tired or hungry, or if it's\";", 'mes "esta cansado o hambriento, o si";'),
    ('mes "been hurt. You must also take";', 'mes "ha sido herido. Tambien debes tomar";'),
    ("mes \"into account your Homunculus's feelings towards you, its owner.\";", 'mes "en cuenta los sentimientos de tu Homunculus hacia ti, su dueno.";'),
    ('mes "When that nurturing attitude";', 'mes "Cuando esa actitud de cuidado";'),
    ('mes "becomes second nature to you,";', 'mes "se vuelva tu segunda naturaleza,";'),
    ('mes "you will have mastered Bioethics. It sounds simple, but you can only";', 'mes "habras dominado Bioethics. Suena simple, pero solo puedes";'),
    ('mes "understand a relationship with a Homunculus through experience.";', 'mes "entender una relacion con un Homunculus a traves de la experiencia.";'),
    ('mes "Well, you should know enough";', 'mes "Bueno, ya deberias saber lo suficiente";'),
    ('mes "by now to create and care for";', 'mes "para crear y cuidar";'),
    ('mes "your own Homunculus. I trust";', 'mes "tu propio Homunculus. Confio";'),
    ('mes "that you will be responsible";', 'mes "en que seras responsable";'),
    ('mes "in your search for discoveries";', 'mes "en tu busqueda de descubrimientos";'),
    ('mes "that may benefit mankind.";', 'mes "que puedan beneficiar a la humanidad.";'),
    ('mes "Before we part";', 'mes "Antes de que nos";'),
    ('mes "ways, would you";', 'mes "separemos, me";'),
    ('mes "tell me your name?";', 'mes "dirias tu nombre?";'),
    ('mes "My name is...";', 'mes "Mi nombre es...";'),
    ('mes "" + strcharinfo(0) + ".";', 'mes "" + strcharinfo(0) + ".";'),
    ('mes "Ah...";', 'mes "Ah...";'),
    ("mes \"I'll remember that. Goodbye\";", 'mes "Lo recordare. Adios";'),
    ('mes "for now, and I hope that you";', 'mes "por ahora, y espero que";'),
    ('mes "make a great contribution to";', 'mes "hagas una gran contribucion al";'),
    ('mes "the world of Alchemy someday.";', 'mes "mundo de la Alquimia algun dia.";'),
    # bioeth == 11
    ('mes "Our viewpoints may be";', 'mes "Nuestros puntos de vista pueden ser";'),
    ("mes \"different, but I'll agree that\";", 'mes "diferentes, pero estare de acuerdo en que";'),
    ("mes \"there's too much potential in\";", 'mes "hay demasiado potencial en";'),
    ('mes "studying Homunculi that I can";', 'mes "estudiar Homunculi que ya no";'),
    ('mes "no longer ignore as a scientist";', 'mes "puedo ignorar como cientifico";'),
    ('mes "and as a humanitarian.";', 'mes "y como humanitario.";'),
    ('mes "If I teach you these skills,";', 'mes "Si te enseno estas habilidades,";'),
    ('mes "you may be treading a moral";', 'mes "puede que estes pisando una linea";'),
    ('mes "line. But I believe it should";', 'mes "moral. Pero creo que deberia";'),
    ('mes "be alright if you work to learn";', 'mes "estar bien si trabajas para aprender";'),
    ('mes "something that will benefit";', 'mes "algo que beneficie";'),
    ('mes "the greater good.";', 'mes "el bien comun.";'),
    ('mes "Does...";', 'mes "Eso...";'),
    ('mes "Does that mean";', 'mes "Eso significa";'),
    ("mes \"you'll teach me?\";", 'mes "que me enseñaras?";'),
    ("mes \"Now don't get too excited.\";", 'mes "No te emociones demasiado.";'),
    ("mes \"I'm still unsure if Homunculus\";", 'mes "Aun no estoy seguro de si el estudio";'),
    ('mes "Study should be open to all";', 'mes "de Homunculus deberia estar abierto a todos";'),
    ('mes "Alchemists, but for now,";', 'mes "los Alchemists, pero por ahora,";'),
    ('mes "I believe I can trust you.";', 'mes "creo que puedo confiar en ti.";'),
    ("mes \"However, you've got to\";", 'mes "Sin embargo, tienes que";'),
    ('mes "use the skills I teach you";', 'mes "usar las habilidades que te ensene";'),
    ('mes "to ultimately benefit other";', 'mes "para finalmente beneficiar a otras";'),
    ("mes \"people. It's not like I can force you to forget once you know how\";", 'mes "personas. No es como que pueda obligarte a olvidar una vez que sepas como";'),
    ('mes "to make Homunculi, understand?";', 'mes "hacer Homunculi, entiendes?";'),
    ('mes "Please give me a little";', 'mes "Por favor dame un poco";'),
    ('mes "time to prepare my lesson";', 'mes "de tiempo para preparar mi leccion";'),
    ("mes \"for you. It's been a very long\";", 'mes "para ti. Ha pasado mucho";'),
    ("mes \"time since I've done this...\";", 'mes "tiempo desde que hice esto...";'),
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Batch 1 done')
