import sys

filepath = sys.argv[1]
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    # Skrajjad NPC
    ("mes \"I've taught you everything\";", 'mes "Te he ensenado todo lo que";'),
    ('mes "I can about the Homunculi.";', 'mes "puedo sobre los Homunculi.";'),
    ('mes "I hope that I\'ve been of some";', 'mes "Espero haber sido de alguna";'),
    ('mes "help in your quest for knowledge and understanding of our universe.";', 'mes "ayuda en tu busqueda de conocimiento y comprension de nuestro universo.";'),
    ("mes \"If you haven't already done\";", 'mes "Si aun no lo has hecho,";'),
    ('mes "so, please visit Keshibien,";', 'mes "por favor visita a Keshibien,";'),
    ('mes "master of the Call Homunculus";', 'mes "maestro de la habilidad Call Homunculus.";'),
    ("mes \"skill. He's a kind person who's\";", 'mes "Es una persona amable que siempre";'),
    ('mes "always willing to go out of his";', 'mes "esta dispuesta a hacer un esfuerzo";'),
    ('mes "way to help young scientists.";', 'mes "extra para ayudar a jovenes cientificos.";'),
    ("mes \"Ah, you're the one\";", 'mes "Ah, tu eres el que";'),
    ('mes "who had the courage";', 'mes "tuvo el valor";'),
    ('mes "to ask Kellasus to teach";', 'mes "de pedirle a Kellasus que le ensenara";'),
    ('mes "you Alchemy. I must say";', 'mes "Alquimia. Debo decir";'),
    ('mes "that I admire your attitude,";', 'mes "que admiro tu actitud,";'),
    ('mes "young lad. Now, don\'t worry...";', 'mes "joven. Ahora, no te preocupes...";'),
    ('mes "young lass. Now, don\'t worry...";', 'mes "jovencita. Ahora, no te preocupes...";'),
    ('mes "I understand how you";', 'mes "Entiendo como";'),
    ('mes "must feel after Kellasus";', 'mes "debes sentirte despues de que Kellasus";'),
    ('mes "refused to teach you his";', 'mes "se nego a ensenarte sus";'),
    ('mes "methods, but that does not";', 'mes "metodos, pero eso no";'),
    ("mes \"mean that you'll never learn\";", 'mes "significa que nunca aprenderas";'),
    ('mes "how to create a Homunculus.";', 'mes "como crear un Homunculus.";'),
    ("mes \"I believe you'll be able to learn what you desire if you manage to\";", 'mes "Creo que podras aprender lo que deseas si logras";'),
    ('mes "train under all of the Homunculus experts. When you show how serious";', 'mes "entrenar con todos los expertos de Homunculus. Cuando demuestres lo serio";'),
    ('mes "you are about this, then Kellasus might change his mind about you.";', 'mes "que eres con esto, entonces Kellasus podria cambiar de opinion sobre ti.";'),
    ('mes "Let give teach you my";', 'mes "Dejame ensenarte mi";'),
    ('mes "Homunculus specialty,";', 'mes "especialidad de Homunculus,";'),
    ('mes "the ^FF0000Vaporize^000000 skill. Actually,";', 'mes "la habilidad ^FF0000Vaporize^000000. En realidad,";'),
    ("mes \"it's useless without Kellasus's\";", 'mes "es inutil sin la tecnica";'),
    ('mes "technique, but it should be a";', 'mes "de Kellasus, pero deberia ser un";'),
    ('mes "good enough starting point.";', 'mes "buen punto de partida.";'),
    ('mes "The Vaporize skill";', 'mes "La habilidad Vaporize";'),
    ('mes "is an Alchemist skill";', 'mes "es una habilidad de Alchemist";'),
    ('mes "that deals solely with";', 'mes "que trata unicamente con";'),
    ('mes "Homunculi. Vaporize is";', 'mes "Homunculi. Vaporize se";'),
    ('mes "mastered at Skill Level 1.";', 'mes "domina en Skill Level 1.";'),
    ('mes "This skill allows you to";', 'mes "Esta habilidad te permite";'),
    ('mes "reduce your Homunculus";', 'mes "reducir tu Homunculus";'),
    ('mes "to vapor so that it is in an";', 'mes "a vapor para que este en un";'),
    ("mes \"inert chemical state. It's\";", 'mes "estado quimico inerte. Es";'),
    ('mes "very similar to hibernation";', 'mes "muy similar a la hibernacion";'),
    ('mes "when you think about it.";', 'mes "si lo piensas bien.";'),
    ('mes "Now, if you want to";', 'mes "Ahora, si quieres";'),
    ('mes "bring back a vaporized";', 'mes "traer de vuelta a un";'),
    ('mes "Homunculus, you will need";', 'mes "Homunculus vaporizado, necesitaras";'),
    ('mes "to know the ^FF0000Call Homunculus^000000";', 'mes "conocer la habilidad ^FF0000Call Homunculus^000000";'),
    ('mes "which you can learn from";', 'mes "que puedes aprender de";'),
    ('mes "Keshibien. Just remember...";', 'mes "Keshibien. Solo recuerda...";'),
    ('mes "Homunculi are living";', 'mes "Los Homunculi son seres";'),
    ("mes \"creatures, so don't go\";", 'mes "vivos, asi que no vayas";'),
    ('mes "and vaporize and recall";', 'mes "a vaporizarlos y llamarlos";'),
    ('mes "them recklessly. That sort";', 'mes "sin cuidado. Ese tipo";'),
    ('mes "of behavior would be inhumane.";', 'mes "de comportamiento seria inhumano.";'),
    ("mes \"''Show respect for all life\";", "mes \"''Muestra respeto por todas las formas\";"),
    ("mes \"forms.'' That's the creed\";", "mes \"de vida.'' Ese es el credo\";"),
    ('mes "for the Homuculus expert.";', 'mes "del experto en Homunculus.";'),
    ('mes "Now go and find ^FF0000Keshibien^000000";', 'mes "Ahora ve y encuentra a ^FF0000Keshibien^000000";'),
    ('mes "so that he can teach you";', 'mes "para que te ensene";'),
    ('mes "the Call Homunculus skill.";', 'mes "la habilidad Call Homunculus.";'),
    ('mes "Good luck in";', 'mes "Buena suerte en";'),
    ('mes "your studies";', 'mes "tus estudios";'),
    ('mes "and I hope you";', 'mes "y espero que";'),
    ('mes "find the answers";', 'mes "encuentres las respuestas";'),
    ('mes "that you are seeking.";', 'mes "que estas buscando.";'),
    # Skrajjad default
    ('mes "Alchemy is wondrous...";', 'mes "La Alquimia es maravillosa...";'),
    ('mes "It incorporates every";', 'mes "Incorpora cada";'),
    ('mes "science and many other";', 'mes "ciencia y muchos otros";'),
    ('mes "fields of knowledge that";', 'mes "campos de conocimiento que";'),
    ("mes \"it's not enough to be jack\";", 'mes "no basta con ser aprendiz";'),
    ('mes "of all trades... No...";', 'mes "de todo... No...";'),
    ('mes "In a sense, you must";', 'mes "En cierto sentido, debes";'),
    ('mes "be a master of all trades";', 'mes "ser maestro de todo";'),
    ('mes "to be proficient in Alchemy.";', 'mes "para ser competente en Alquimia.";'),
    ("mes \"But it's incredibly rewarding to those of us who never stop asking\";", 'mes "Pero es increiblemente gratificante para los que nunca dejamos de preguntar";'),
    ('mes "how and why our world works.";', 'mes "como y por que funciona nuestro mundo.";'),
    # Keshibien NPC
    ('mes "I hope that you";', 'mes "Espero que puedas";'),
    ('mes "can make good use";', 'mes "hacer buen uso";'),
    ("mes \"of what I've taught you.\";", 'mes "de lo que te ensene.";'),
    ("mes \"I'm glad that I was able\";", 'mes "Me alegra haber podido";'),
    ('mes "to contribute something to";', 'mes "contribuir algo a";'),
    ('mes "your learning of Alchemy.";', 'mes "tu aprendizaje de la Alquimia.";'),
    ('mes "Now, the only person qualified";', 'mes "Ahora, la unica persona calificada";'),
    ('mes "to teach you the Homunculus";', 'mes "para ensenarte la habilidad Homunculus";'),
    ('mes "Resurrection skill is Brocher.";', 'mes "Resurrection es Broncher.";'),
    ("mes \"He's... He's a character, but\";", 'mes "El es... Es todo un personaje, pero";'),
    ("mes \"he's also a great teacher.\";", 'mes "tambien es un gran maestro.";'),
    ('mes "Now...";', 'mes "Ahora...";'),
    ('mes "Where could he be?";', 'mes "Donde podra estar?";'),
    ('mes "I know he likes to drink,";', 'mes "Se que le gusta beber,";'),
    ('mes "so maybe you can find him";', 'mes "asi que quizas puedas encontrarlo";'),
    ('mes "some place where they serve";', 'mes "en algun lugar donde sirvan";'),
    ('mes "alcohol in Lighthalzen?";', 'mes "alcohol en Lighthalzen?";'),
    ('mes "Oh! You must be the";', 'mes "Oh! Tu debes ser a quien";'),
    ('mes "one Skrajjad told me";', 'mes "Skrajjad me hablo";'),
    ("mes \"about. So you've come\";", 'mes "sobre. Entonces viniste";'),
    ('mes "so I can teach you the";', 'mes "para que te ensene la";'),
    ('mes "Call Homunculus skill?";', 'mes "habilidad Call Homunculus?";'),
    ("mes \"First of all, it's always\";", 'mes "Antes que nada, siempre es";'),
    ('mes "a pleasure to meet another";', 'mes "un placer conocer a otro";'),
    ("mes \"colleague. I'm Keshibien, and\";", 'mes "colega. Soy Keshibien, y";'),
    ("mes \"although I'm an expert on this\";", 'mes "aunque soy experto en esta";'),
    ("mes \"particular skill, overall I'm just a run of the mill Alchemist.\";", 'mes "habilidad en particular, en general soy un Alchemist comun y corriente.";'),
    ('mes "Anyway, the Call Homunculus";', 'mes "En fin, la habilidad Call Homunculus";'),
    ('mes "skill requires knowledge of the";', 'mes "requiere conocimiento de la";'),
    ('mes "Vaporize skill and is mastered";', 'mes "habilidad Vaporize y se domina";'),
    ('mes "at Skill Level 1. This skill allows you to summon a Homunculus.";', 'mes "en Skill Level 1. Esta habilidad te permite invocar un Homunculus.";'),
    ('mes "Pretty simple so far, right?";', 'mes "Bastante simple hasta ahora, no?";'),
    ('mes "Now, you can summon a";', 'mes "Ahora, puedes invocar un";'),
    ('mes "vaporized Homunculus if";', 'mes "Homunculus vaporizado si";'),
    ('mes "you happen to have one.";', 'mes "resulta que tienes uno.";'),
    ('mes "Otherwise, you can just";', 'mes "De lo contrario, puedes";'),
    ('mes "create one through using";', 'mes "crear uno usando";'),
    ('mes "this skill and these items...";', 'mes "esta habilidad y estos objetos...";'),
    ("mes \"Well, that's all the\";", 'mes "Bueno, esa es toda la";'),
    ('mes "technical information";', 'mes "informacion tecnica";'),
    ('mes "I have to share with you.";', 'mes "que tengo para compartir contigo.";'),
    ('mes "Always remember to treat";', 'mes "Siempre recuerda tratar";'),
    ('mes "your Homunculus well. Eh,";', 'mes "bien a tu Homunculus. Eh,";'),
    ('mes "once you summon one, anyway.";', 'mes "una vez que invoques uno, claro.";'),
    ('mes "But before you can do";', 'mes "Pero antes de que puedas hacer";'),
    ('mes "that, you need to learn";', 'mes "eso, necesitas aprender";'),
    ('mes "the techniques that only";', 'mes "las tecnicas que solo";'),
    ('mes "Kellasus can teach you.";', 'mes "Kellasus puede ensenarte.";'),
    ('mes "For now, go to ^FF0000Broncher^000000";', 'mes "Por ahora, ve con ^FF0000Broncher^000000";'),
    ('mes "and learn from him, okay?";', 'mes "y aprende de el, si?";'),
    ('mes "Broncher happens";', 'mes "Broncher resulta";'),
    ('mes "to specialize in the";', 'mes "especializarse en la";'),
    ('mes "Homunculus Resurrection";', 'mes "habilidad Homunculus Resurrection.";'),
    ('mes "skill. You should be able to";', 'mes "Deberias poder";'),
    ('mes "find him somewhere in town,";', 'mes "encontrarlo en algun lugar de la ciudad,";'),
    ("mes \"though I'm unsure where...\";", 'mes "aunque no estoy seguro donde...";'),
    ('mes "Anyway, it was really";', 'mes "En fin, fue realmente";'),
    ('mes "nice to meet you. Hopefully,";', 'mes "agradable conocerte. Con suerte,";'),
    ("mes \"you'll be able to learn how\";", 'mes "podras aprender a";'),
    ('mes "to fully use a Homunculus";', 'mes "usar completamente un Homunculus";'),
    ("mes \"someday soon. Still, you'll\";", 'mes "algun dia pronto. Aun asi, tendras";'),
    ('mes "need to convince Kellasus...";', 'mes "que convencer a Kellasus...";'),
    # Keshibien default
    ('mes "Hello there~";', 'mes "Hola~";'),
    ('mes "You must be from";', 'mes "Debes ser de";'),
    ('mes "Rune-Midgarts, right?";', 'mes "Rune-Midgarts, verdad?";'),
    ("mes \"It's nice to meet you.\";", 'mes "Es un placer conocerte.";'),
    ('mes "I hear that the";', 'mes "He escuchado que los";'),
    ('mes "Alchemists from";', 'mes "Alchemists de";'),
    ('mes "over there are pretty";', 'mes "por alla son bastante";'),
    ("mes \"skilled. I wonder if I'll\";", 'mes "habiles. Me pregunto si algun";'),
    ('mes "ever get the chance to";', 'mes "dia tendre la oportunidad de";'),
    ('mes "collaborate with any of them...";', 'mes "colaborar con alguno de ellos...";'),
    # Broncher NPC
    ("mes \"You again? Didn't I already\";", 'mes "Tu otra vez? No te ensene ya";'),
    ('mes "teach you the Homunculus";', 'mes "la habilidad Homunculus";'),
    ('mes "Resurrection skill? Come";', 'mes "Resurrection? Vamos,";'),
    ("mes \"on, there's nothing else\";", 'mes "no hay nada mas";'),
    ('mes "I can do for you. Lemme";', 'mes "que pueda hacer por ti. Dejame";'),
    ('mes "enjoy myself here...";', 'mes "disfrutar aqui...";'),
    ("mes \"If you didn't already,\";", 'mes "Si aun no lo hiciste,";'),
    ('mes "go and bother Kellasus";', 'mes "ve y molesta a Kellasus";'),
    ('mes "and get him to teach you the";', 'mes "y haz que te ensene las";'),
    ('mes "basic Homunculus techniques.";', 'mes "tecnicas basicas de Homunculus.";'),
    ("mes \"Now go away, you're sobering\";", 'mes "Ahora vete, me estas quitando";'),
    ("mes \"me up! Go on, get outta here!\";", 'mes "la borrachera! Anda, fuera de aqui!";'),
    ('mes "^333333*Hiccup!*^000000";', 'mes "^333333*Hip!*^000000";'),
    ('mes "Oh man...";', 'mes "Oh cielos...";'),
    ('mes "Oh man, this stuff";', 'mes "Oh cielos, esto";'),
    ("mes \"is great! Yeah. Yeah,\";", 'mes "esta genial! Si. Si,";'),
    ('mes "this really hits the spot.";', 'mes "esto si que pega.";'),
    ("mes \"Holy crap! Y-you're that\";", 'mes "Santo cielo! T-tu eres ese";'),
    ('mes "Alchemist that Skrajjad";', 'mes "Alchemist del que Skrajjad";'),
    ('mes "told me to expect! Wha--?";', 'mes "me dijo que esperara! Que--?";'),
    ('mes "You already visited Keshibien?";', 'mes "Ya visitaste a Keshibien?";'),
    ('mes "Crap! I thought you wouldn\'t";', 'mes "Rayos! Pense que no";'),
    ('mes "get here for another... Hour!";', 'mes "llegarias en otra... Hora!";'),
    ('mes "Oh, forget sobering.";', 'mes "Oh, olvida lo de dejar de beber.";'),
    ("mes \"I'll just teach you the\";", 'mes "Solo te ensenare la";'),
    ('mes "^FF0000Homunculus Resurrection^000000";', 'mes "habilidad ^FF0000Homunculus Resurrection^000000.";'),
    ("mes \"skill. It's one of the last\";", 'mes "Es una de las ultimas";'),
    ('mes "skills you need to learn";', 'mes "habilidades que necesitas aprender";'),
    ('mes "for Homunculi, anyway.";', 'mes "para los Homunculi, de todos modos.";'),
    ('mes "Yes, you can literally";', 'mes "Si, literalmente puedes";'),
    ('mes "bring Homunculi back";', 'mes "traer Homunculi de vuelta";'),
    ('mes "from the dead. Oh, and you";', 'mes "de la muerte. Oh, y debes";'),
    ('mes "should know that this skill is";', 'mes "saber que esta habilidad se";'),
    ('mes "mastered at Skill Level 5.";', 'mes "domina en Skill Level 5.";'),
    ('mes "To bring your";', 'mes "Para traer a tu";'),
    ('mes "Homunculus back from";', 'mes "Homunculus de vuelta de";'),
    ('mes "the dead, you just push";', 'mes "la muerte, solo presionas";'),
    ("mes \"this button, the one that's\";", 'mes "este boton, el que dice";'),
    ("mes \"labeled, ''Homunculus\";", "mes \"''Homunculus\";"),
    ("mes \"Resurrection.'' Easy, right?\";", "mes \"Resurrection.'' Facil, no?\";"),
    ("mes \"Well, lesson's over.\";", 'mes "Bueno, la leccion termino.";'),
    ('mes "You know everything you";', 'mes "Sabes todo lo que";'),
    ('mes "need to know about using";', 'mes "necesitas saber sobre usar";'),
    ('mes "Homunculus Resurrection.";', 'mes "Homunculus Resurrection.";'),
    ('mes "But you still need Kellasus";', 'mes "Pero aun necesitas que Kellasus";'),
    ('mes "to teach you the fundamentals.";', 'mes "te ensene los fundamentos.";'),
    ('mes "Without those basic";', 'mes "Sin esas tecnicas";'),
    ('mes "techiques, everything";', 'mes "basicas, todo lo que";'),
    ("mes \"you've studied from us\";", 'mes "has estudiado de nosotros";'),
    ('mes "will be for nothing. So...";', 'mes "sera en vano. Asi que...";'),
    ('mes "Lots of luck convincing";', 'mes "Mucha suerte convenciendo";'),
    ('mes "Kellasus to teach you.";', 'mes "a Kellasus de ensenarte.";'),
    ('mes "Now leave alone";', 'mes "Ahora dejame solo";'),
    ('mes "and let me enjoy";', 'mes "y dejame disfrutar";'),
    ('mes "all of this alcohol";', 'mes "todo este alcohol";'),
    ('mes "in solitude, alright?";', 'mes "en soledad, si?";'),
    # Broncher default
    ('mes "^333333*Hiccup~*^000000";', 'mes "^333333*Hip~*^000000";'),
    ('mes "Oh yeah, this is";', 'mes "Oh si, esto es";'),
    ("mes \"the stuff! I call it...\";", 'mes "lo bueno! Yo lo llamo...";'),
    ("mes \"My ''Anti-Sobriety''\";", "mes \"Mi formula\";"),
    ("mes \"formula! Can't think\";", 'mes "\'Anti-Sobriedad\'! No puedo pensar";'),
    ('mes "of a finer thing created...";', 'mes "en algo mejor que haya creado...";'),
    # Koring NPC
    ('mes "My daddy is the bestest";', 'mes "Mi papi es el mejor";'),
    ("mes \"Alchemist! He's sooooo\";", 'mes "Alchemist! Es taaaan";'),
    ('mes "smart, and I never heard";', 'mes "inteligente, y nunca lo escuche";'),
    ('mes "him be wrong before!";', 'mes "estar equivocado!";'),
    ("mes \"Daddy's been thinking\";", 'mes "Papi ha estado pensando";'),
    ("mes \"a lot lately and I don't\";", 'mes "mucho ultimamente y no";'),
    ('mes "know why. Daddy gets ";', 'mes "se por que. Papi se pone ";'),
    ("mes \"really serious when he's \";", 'mes "muy serio cuando esta ";'),
    ('mes "worried about something.";', 'mes "preocupado por algo.";'),
    ("mes \"He's always trying hard\";", 'mes "Siempre se esfuerza mucho";'),
    ('mes "to make me happy and to ";', 'mes "por hacerme feliz y ";'),
    ('mes "help me when I have problems.";', 'mes "ayudarme cuando tengo problemas.";'),
    ('mes "Like the time I was really sick...";', 'mes "Como la vez que estuve muy enfermo...";'),
    ('mes "Daddy did his best to make";', 'mes "Papi hizo lo mejor que pudo para hacer";'),
    ('mes "some medicine to help me, ";', 'mes "medicina para ayudarme, ";'),
    ('mes "and he looked all over for any";', 'mes "y busco por todas partes algun";'),
    ('mes "doctor who could cure me. For";', 'mes "doctor que pudiera curarme. Por";'),
    ('mes "a while, I was really scared,";', 'mes "un tiempo, estuve muy asustado,";'),
    ('mes "but my Daddy never gave up.";', 'mes "pero mi Papi nunca se rindio.";'),
    ('mes "He might be a little";', 'mes "Puede que este un poco";'),
    ('mes "grumpy now, but my ";', 'mes "gruñon ahora, pero mi ";'),
    ('mes "Daddy is still the best!";', 'mes "Papi sigue siendo el mejor!";'),
    ('mes "I hope he feels better soon.";', 'mes "Espero que se sienta mejor pronto.";'),
    # Koring default
    ('mes "How did my Daddy get";', 'mes "Como se volvio mi Papi";'),
    ('mes "so smart? I wish I could";', 'mes "tan inteligente? Ojala pudiera";'),
    ('mes "learn things as fast as";', 'mes "aprender cosas tan rapido como";'),
    ('mes "him so that I can be an";', 'mes "el para poder ser un";'),
    ('mes "Alchemist too when I grow up!";', 'mes "Alchemist tambien cuando crezca!";'),
    # Beninne NPC
    ("mes \"You've met my husband,\";", 'mes "Conociste a mi esposo,";'),
    ("mes \"Kellasus? He's either a\";", 'mes "Kellasus? Es un hombre";'),
    ('mes "very stubborn or determined";', 'mes "muy terco o determinado,";'),
    ('mes "man, depending on how you";', 'mes "dependiendo de como lo";'),
    ("mes \"want to look at it. Once his\";", 'mes "quieras ver. Una vez que";'),
    ("mes \"mind's made up, he won't budge!\";", 'mes "se decide, no se mueve!";'),
    ("mes \"He's a very good husband\";", 'mes "Es un muy buen esposo";'),
    ('mes "and father, but I feel like it";', 'mes "y padre, pero siento que se necesita";'),
    ('mes "takes the entire world to";', 'mes "al mundo entero para";'),
    ("mes \"change his mind once he's \";", 'mes "hacerlo cambiar de opinion una vez que ";'),
    ("mes \"convinced that he's right\";", 'mes "esta convencido de que tiene razon";'),
    ('mes "about something.";', 'mes "sobre algo.";'),
    ('mes "Of course, if you manage";', 'mes "Por supuesto, si logras";'),
    ('mes "to prove him wrong, he will";', 'mes "demostrar que esta equivocado, hara";'),
    ('mes "do everything he can to make";', 'mes "todo lo posible para";'),
    ('mes "up for it. Kellasus has been";', 'mes "compensarlo. Kellasus ha sido";'),
    ('mes "like that since I first met him.";', 'mes "asi desde que lo conoci.";'),
    ("mes \"It feels so nice to\";", 'mes "Se siente tan bien";'),
    ('mes "have someone like that";', 'mes "tener a alguien asi";'),
    ('mes "to be protective of you.";', 'mes "que te proteja.";'),
    ('mes "Kellasus loves his work,";', 'mes "Kellasus ama su trabajo,";'),
    ('mes "but he loves his family even";', 'mes "pero ama a su familia aun";'),
    ("mes \"more. Amazing, isn't it?\";", 'mes "mas. Increible, no?";'),
    # Beninne default
    ('mes "Most people think that";', 'mes "La mayoria piensa que";'),
    ("mes \"being a scientist's wife\";", 'mes "ser la esposa de un cientifico";'),
    ('mes "would be so difficult. I must";', 'mes "seria muy dificil. Debo";'),
    ('mes "be lucky that my husband is";', 'mes "tener suerte de que mi esposo sea";'),
    ('mes "such a good family man, even";', 'mes "tan buen hombre de familia, aunque";'),
    ('mes "though he may be an Alchemist.";', 'mes "sea un Alchemist.";'),
    # Nannan NPC
    ('mes "You know, I always thought that all Alchemists were bookish,";', 'mes "Sabes, siempre pense que todos los Alchemists eran ratones de biblioteca,";'),
    ('mes "scholarly types, their faces always buried in books and studying. But";', 'mes "tipos academicos, con la cara siempre metida en libros y estudiando. Pero";'),
    ("mes \"I managed to find one who doesn't fit that nerdy stereotype at all.\";", 'mes "logre encontrar uno que no encaja para nada en ese estereotipo de nerd.";'),
    ("mes \"This guy, what's-his-face,\";", 'mes "Este tipo, como-se-llame,";'),
    ('mes "Broncher, is always wasting";', 'mes "Broncher, siempre esta perdiendo";'),
    ('mes "his time drinking. I guess he discovered the secret of turning";', 'mes "su tiempo bebiendo. Supongo que descubrio el secreto de convertir";'),
    ("mes \"water into Grade A booze. But at least he's not the stuffy type.\";", 'mes "agua en licor de primera. Pero al menos no es del tipo estirado.";'),
    ("mes \"I don't know how much\";", 'mes "No se que tanta";'),
    ("mes \"help he'd be to an aspiring\";", 'mes "ayuda seria para un aspirante a";'),
    ('mes "Alchemist, but in my opinion,";', 'mes "Alchemist, pero en mi opinion,";'),
    ('mes "the man is a fully fledged";', 'mes "el hombre es un completo";'),
    ('mes "genius! At least, compared";', 'mes "genio! Al menos, comparado";'),
    ('mes "to a street guy like me...";', 'mes "con un tipo de la calle como yo...";'),
    # Alchemist NPC
    ('mes "Out of all humans,";', 'mes "De todos los humanos,";'),
    ('mes "I believe Kellasus is";', 'mes "creo que Kellasus es";'),
    ('mes "the one who has come";', 'mes "quien mas se ha";'),
    ('mes "closest to discovering";', 'mes "acercado a descubrir";'),
    ('mes "the secrets of life. He";', 'mes "los secretos de la vida. El";'),
    ('mes "never fails to amaze me...";', 'mes "nunca deja de asombrarme...";'),
    ("mes \"I'm also impressed by the\";", 'mes "Tambien me impresiona el";'),
    ("mes \"fact that he doesn't let his\";", 'mes "hecho de que no deja que su";'),
    ('mes "work keep him from being the";', 'mes "trabajo le impida ser el";'),
    ('mes "best father and husband that";', 'mes "mejor padre y esposo que";'),
    ("mes \"he can for his family. He's\";", 'mes "puede ser para su familia. Es";'),
    ('mes "an example for all of us.";', 'mes "un ejemplo para todos nosotros.";'),
    ('mes "Kellasus really is";', 'mes "Kellasus realmente es";'),
    ('mes "an amazing person.";', 'mes "una persona increible.";'),
    ("mes \"There isn't one Alchemist\";", 'mes "No hay un solo Alchemist";'),
    ("mes \"that I know who doesn't look\";", 'mes "que yo conozca que no lo";'),
    ('mes "up to him in the realms of";', 'mes "admire tanto en el ambito de";'),
    ('mes "both science and personal life.";', 'mes "la ciencia como en la vida personal.";'),
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Batch 3 done')
