import sys

filepath = sys.argv[1]
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Translation pairs (English, Spanish)
R = [
    # Hideout legend
    ('mes "- You hear a faint conversation going on inside. -";', 'mes "- Escuchas una conversacion debil adentro. -";'),
    ('mes "Once again, I have failed to";', 'mes "Una vez mas, no he logrado";'),
    ('mes "make the ^8B4513Jaty Crown^000000...";', 'mes "hacer la ^8B4513Jaty Crown^000000...";'),
    ('mes "I was sure that I could do it this time.";', 'mes "Estaba seguro de que lo lograria esta vez.";'),
    ("mes \"Why won't it work?\";", 'mes "Por que no funciona?";'),
    ('mes "The ^006400Jaty Crown^000000 has been known to have miraculous power since the time of the ancients.";', 'mes "Se sabe que la ^006400Jaty Crown^000000 tiene poder milagroso desde tiempos antiguos.";'),
    ("mes \"But it's been said only those who've earned a tribal honor\";", 'mes "Pero se dice que solo quienes han ganado un honor tribal";'),
    ('mes "would be able to use it.";', 'mes "podrian usarla.";'),
    ('mes "^0000FFKasyapa^000000!!";', 'mes "^0000FFKasyapa^000000!!";'),
    ('mes "Are you saying that even though I am the leader of our tribe, I have not yet received that honor?";', 'mes "Estas diciendo que aunque soy el lider de nuestra tribu, aun no he recibido ese honor?";'),
    ('mes "Calm down ^0000FFChief Paiko^000000...";', 'mes "Calmate ^0000FFChief Paiko^000000...";'),
    ('mes "As the Great and Powerful Chief, you should be more than enough to qualify.";', 'mes "Como el Gran y Poderoso Jefe, deberias ser mas que suficiente para calificar.";'),
    ("mes \"In my younger years I could have easily solved the problem but this old man's mind cannot figure out what's missing.\";", 'mes "En mis anos jovenes podria haber resuelto el problema facilmente pero la mente de este viejo no puede descifrar que falta.";'),
    ("mes \"The conversation trails off and you don't hear any more.\";", 'mes "La conversacion se desvanece y no escuchas nada mas.";'),
    ('mes "Kasyapa and Chief Paiko begin talking as you are about to leave...";', 'mes "Kasyapa y Chief Paiko comienzan a hablar cuando estas a punto de irte...";'),
    ('mes "I am unsure of what is missing but that traveler could be big help in creating the ^006400Jaty Crown^000000.";', 'mes "No estoy seguro de que falta pero ese viajero podria ser de gran ayuda para crear la ^006400Jaty Crown^000000.";'),
    ('mes "Of this I am certain.";', 'mes "De esto estoy seguro.";'),
    ('mes "The reason is...";', 'mes "La razon es...";'),
    ('mes "What is the reason?";', 'mes "Cual es la razon?";'),
    ('mes "This ^8B4513Cendrawasih Feather^000000 was owned by our first tribe leader when the crown was originally created.";', 'mes "Esta ^8B4513Cendrawasih Feather^000000 le pertenecia a nuestro primer lider tribal cuando la corona fue creada originalmente.";'),
    ('mes "It was stored as a treasured heirloom of our tribe.";', 'mes "Fue guardada como una reliquia preciada de nuestra tribu.";'),
    ("mes \"But when the traveler came near, this feather started to shine, and I kept thinking that this is not just a coincidence.\";", 'mes "Pero cuando el viajero se acerco, esta pluma comenzo a brillar, y sigo pensando que no es solo una coincidencia.";'),
    ('mes "This person will be the key to assisting us to make the crown.";', 'mes "Esta persona sera la clave para ayudarnos a hacer la corona.";'),
    ('mes "Could it happen for sure?";', 'mes "Podria pasar de verdad?";'),
    ('mes "If so, I will give everything";', 'mes "Si es asi, dare todo";'),
    ('mes "to support them...";', 'mes "para apoyarlos...";'),
    # Sage Kasyapa
    ('mes "Ah, a stranger to our land.";', 'mes "Ah, un extranjero en nuestra tierra.";'),
    ('mes "Are you lost?";', 'mes "Estas perdido?";'),
    ('mes "I hope you did not encounter much danger on your journey here.";', 'mes "Espero que no hayas encontrado mucho peligro en tu viaje hasta aqui.";'),
    ('mes "Your earnest expression tells me";', 'mes "Tu expresion sincera me dice";'),
    ('mes "that you have something to say";', 'mes "que tienes algo que decir";'),
    ('mes "you might as well tell me what it is.";', 'mes "asi que mejor dime que es.";'),
    ('select("I overheard talk about a crown?:Just looking for the gift shop.")', 'select("Escuche hablar sobre una corona?:Solo busco la tienda de regalos.")'),
    ('mes "Really?";', 'mes "En serio?";'),
    ('mes "It looked as if your eyes";', 'mes "Parecia que tus ojos";'),
    ('mes "wanted to say something.";', 'mes "querian decir algo.";'),
    ('mes "Oh, you heard about the crown, eh?";', 'mes "Oh, escuchaste sobre la corona, eh?";'),
    ("mes \"Ah, this old man's got loose lips\";", 'mes "Ah, este viejo tiene la boca floja";'),
    ('mes "we should have used a little more discretion...";', 'mes "debimos haber sido un poco mas discretos...";'),
    ('select("Anything I can do to help?");', 'select("Hay algo en que pueda ayudar?");'),
    ('mes "I can see in your eyes";', 'mes "Puedo ver en tus ojos";'),
    ('mes "that you are a trustworthy sort... but...";', 'mes "que eres de fiar... pero...";'),
    ('mes "There is a brief twinkling of light ^0000FFKasyapa^000000 all of sudden seems to be taken aback.";', 'mes "Hay un breve destello de luz y ^0000FFKasyapa^000000 de repente parece sorprendido.";'),
    ('mes "Ah, the feather......!";', 'mes "Ah, la pluma......!";'),
    ("mes \"Instead of talking to me, why don't you talk to our tribe's leader, ^0000FFPaiko^000000.\";", 'mes "En vez de hablar conmigo, por que no hablas con el lider de nuestra tribu, ^0000FFPaiko^000000.";'),
    ("mes \"Instead of talking to me, why don't you talk to our tribe's leader, ^0000FFChief Paiko^000000.\";", 'mes "En vez de hablar conmigo, por que no hablas con el lider de nuestra tribu, ^0000FFChief Paiko^000000.";'),
    ("mes \"If that's what Chief ^0000FFPaiko^000000 wants\";", 'mes "Si eso es lo que Chief ^0000FFPaiko^000000 quiere";'),
    ("mes \"I don't have any more to say.\";", 'mes "no tengo nada mas que decir.";'),
    ('mes "Hmm....";', 'mes "Hmm....";'),
    ('mes "but...... this....";', 'mes "pero...... esto....";'),
    ('mes "Never mind, please have a good trip.";', 'mes "Olvidalo, que tengas un buen viaje.";'),
    ("mes \"I've been waiting for you traveler.\";", 'mes "Te he estado esperando, viajero.";'),
    ("mes \"Our tribe's leader has a favor\";", 'mes "El lider de nuestra tribu tiene un favor";'),
    ('mes "to ask of you.";', 'mes "que pedirte.";'),
    ('mes "Please talk to Chief ^0000FFPaiko^000000.";', 'mes "Por favor habla con Chief ^0000FFPaiko^000000.";'),
    ('mes "I heard you could help making a crown";', 'mes "Escuche que podrias ayudar a hacer una corona";'),
    ('mes "for our tribe leader.";', 'mes "para nuestro lider tribal.";'),
    ('mes "You will certainly be";', 'mes "Ciertamente seras";'),
    ('mes "a big help to us...";', 'mes "de gran ayuda para nosotros...";'),
    ('mes "I trust my own eyes!";', 'mes "Confio en mis propios ojos!";'),
    ('mes "And also the sparkling light...";', 'mes "Y tambien la luz brillante...";'),
    ('mes "The symbol of Dayak Tribe";', 'mes "El simbolo de la Tribu Dayak";'),
    ('mes "and a famous mystical creature.";', 'mes "y una famosa criatura mistica.";'),
    ('mes "Find 15 of ^006400Cendrawasih Feather^000000";', 'mes "Encuentra 15 ^006400Cendrawasih Feather^000000";'),
    ('mes "and bring them to Chief ^0000FFPaiko^000000.";', 'mes "y traeelas a Chief ^0000FFPaiko^000000.";'),
    ('mes "With the feathers that you have brought creating a ^006400Jaty Crown^000000 is going much more smoothly.";', 'mes "Con las plumas que trajiste, la creacion de la ^006400Jaty Crown^000000 va mucho mas fluido.";'),
    ('mes "Go see Chief ^0000FFPaiko^000000.";', 'mes "Ve a ver a Chief ^0000FFPaiko^000000.";'),
    ('mes "There is something";', 'mes "Hay algo";'),
    ('mes "I wish to give to you";', 'mes "que deseo darte";'),
    ('mes "as a reward for your help.";', 'mes "como recompensa por tu ayuda.";'),
    ('mes "Please, it would honor us if you would take it.";', 'mes "Por favor, seria un honor para nosotros que lo aceptaras.";'),
    ('mes "You are carrying too much weight over the limit.";', 'mes "Estas cargando demasiado peso sobre el limite.";'),
    ('mes "I cannot get you your reward unless you reduce the amount of weighty items you are carrying.";', 'mes "No puedo darte tu recompensa a menos que reduzcas la cantidad de objetos pesados que llevas.";'),
    ('mes "You are carrying too much in your inventory.";', 'mes "Llevas demasiado en tu inventario.";'),
    ('mes "I will give you the reward once you unburden yourself and return.";', 'mes "Te dare la recompensa una vez que te aligeres y regreses.";'),
    ('mes "The reason I asked you to embark on this important mission is because of this feather.";', 'mes "La razon por la que te pedi que emprendieras esta importante mision es por esta pluma.";'),
    ('mes "Handed down from generation to generation the legendary origin of the crown is this feather...";', 'mes "Transmitida de generacion en generacion, el origen legendario de la corona es esta pluma...";'),
    ('mes "I saw this feather begin to shine when you came here.";', 'mes "Vi esta pluma comenzar a brillar cuando viniste aqui.";'),
    ('mes "I knew you were a person who";', 'mes "Supe que eras una persona que";'),
    ('mes "would endeavour to help us.";', 'mes "se esforzaria por ayudarnos.";'),
    ('mes "On behalf of my people";', 'mes "En nombre de mi pueblo";'),
    ('mes "I give my thanks.";', 'mes "doy las gracias.";'),
    ("mes \"Also, the feather you received isn't just valuable on its own, it also is an acknowledgment from our tribe.\";", 'mes "Ademas, la pluma que recibiste no solo es valiosa por si misma, tambien es un reconocimiento de nuestra tribu.";'),
    ('mes "Like ^8B4513Krakatau^000000 Volcano, when you venture into dangerous areas like that, if you display this feather, you can get help from the tribe.";', 'mes "Como el Volcan ^8B4513Krakatau^000000, cuando te aventures en areas peligrosas como esa, si muestras esta pluma, puedes obtener ayuda de la tribu.";'),
    ('mes "Anyway, I really thank you.";', 'mes "En fin, realmente te agradezco.";'),
    # Tribal Chief Paiko
    ('mes "I am the leader of this tribe";', 'mes "Soy el lider de esta tribu";'),
    ('mes "I can see you are a traveler,";', 'mes "Puedo ver que eres un viajero,";'),
    ('mes "from another land.";', 'mes "de otra tierra.";'),
    ('mes "What brings you here?";', 'mes "Que te trae por aqui?";'),
    ('select("I overheard the story by accident:I have nothing to say.")', 'select("Escuche la historia por accidente:No tengo nada que decir.")'),
    ('mes "You are wasting your time here.";', 'mes "Estas perdiendo tu tiempo aqui.";'),
    ('mes "There are many other attractions around our village.";', 'mes "Hay muchas otras atracciones alrededor de nuestra aldea.";'),
    ('mes "What do you mean?";', 'mes "A que te refieres?";'),
    ('mes "You heard the story about a crown?";', 'mes "Escuchaste la historia sobre una corona?";'),
    ('mes "You must have heard incorrectly.";', 'mes "Debes haber escuchado mal.";'),
    ('mes "I have nothing to say to you";', 'mes "No tengo nada que decirte";'),
    ('mes "regarding such things.";', 'mes "respecto a esas cosas.";'),
    ('select("Kasyapa was talking about a crown...");', 'select("Kasyapa estaba hablando de una corona...");'),
    ('mes "It seems that ^0000FFKasyapa^000000 has told you a tall tale and I appreciate your concern about our affairs.";', 'mes "Parece que ^0000FFKasyapa^000000 te conto una historia exagerada y aprecio tu preocupacion por nuestros asuntos.";'),
    ("mes \"It's not something that a stranger like you could understand so make like a tree, and get out of here.\";", 'mes "No es algo que un extranjero como tu pueda entender asi que mejor vete de aqui.";'),
    ("mes \"If it's about the crown I want you to stop asking about it.\";", 'mes "Si es sobre la corona quiero que dejes de preguntar sobre eso.";'),
    ('mes "Please leave.";', 'mes "Por favor vete.";'),
    ("mes \"I've been waiting for you, traveler\";", 'mes "Te he estado esperando, viajero";'),
    ('mes "according to sage ^0000FFKasyapa^000000";', 'mes "segun el sabio ^0000FFKasyapa^000000";'),
    ('mes "You are willing to help us make a crown for our tribe.";', 'mes "Estas dispuesto a ayudarnos a hacer una corona para nuestra tribu.";'),
    ('select("Crown-a-whatsis?");', 'select("Corona-de-que?");'),
    ('mes "The Tribe leader has the duty of making and protecting the ^006400Jaty Crown^000000 to uphold the tribe\'s pride and honor.";', 'mes "El lider tribal tiene el deber de hacer y proteger la ^006400Jaty Crown^000000 para mantener el orgullo y honor de la tribu.";'),
    ('mes "But, ever since I became the tribe leader there have been difficulties making it.";', 'mes "Pero, desde que me converti en lider tribal ha habido dificultades para hacerla.";'),
    ('mes "According to Sage ^0000FFKasyapa^000000, you can help us create a ^006400Jaty Crown^000000.";', 'mes "Segun el Sabio ^0000FFKasyapa^000000, puedes ayudarnos a crear una ^006400Jaty Crown^000000.";'),
    ('mes "Do you think you can help?";', 'mes "Crees que puedes ayudar?";'),
    ('mes "Your efforts will not go unrewarded.";', 'mes "Tus esfuerzos no quedaran sin recompensa.";'),
    ('select("Ok, I will help:I am sorry, I cannot help now.")', 'select("Ok, ayudare:Lo siento, no puedo ayudar ahora.")'),
    ("mes \"That's really sad.\";", 'mes "Eso es muy triste.";'),
    ('mes "If you ever change";', 'mes "Si alguna vez cambias";'),
    ('mes "your mind, please";', 'mes "de opinion, por favor";'),
    ('mes "come again.";', 'mes "ven de nuevo.";'),
    ('mes "I will be waiting.";', 'mes "Estare esperando.";'),
    ('mes "Many thanks to you, stranger";', 'mes "Muchas gracias, extranjero";'),
    ('mes "If Kasyapa trusts you then I know that you can help us make a";', 'mes "Si Kasyapa confia en ti entonces se que puedes ayudarnos a hacer una";'),
    ('mes "What you can do to";', 'mes "Lo que puedes hacer para";'),
    ('mes "help us is very simple.";', 'mes "ayudarnos es muy simple.";'),
    ("mes \"The symbol of the Jaty Tribe is also a famous mystical creature.\";", 'mes "El simbolo de la Tribu Jaty es tambien una famosa criatura mistica.";'),
    ('mes "Find 15 ^006400Cendrawasih Feather^000000s and bring them to me.";', 'mes "Encuentra 15 ^006400Cendrawasih Feather^000000s y traeelas.";'),
    ('mes "Our faith is in you, stranger.";', 'mes "Nuestra fe esta en ti, extranjero.";'),
    ('mes "It seems that you have yet to find the materials to make the ^006400Jaty Crown^000000.";', 'mes "Parece que aun no encuentras los materiales para hacer la ^006400Jaty Crown^000000.";'),
    ('mes "The symbol of the Dayak Tribe is also a famous mystical creature.";', 'mes "El simbolo de la Tribu Dayak es tambien una famosa criatura mistica.";'),
    ('mes "Find 15 ^006400Cendrawasih Feather^000000s and bring them to me.";', 'mes "Encuentra 15 ^006400Cendrawasih Feather^000000s y traemelas.";'),
    ("mes \"Oh! You've found all of them. Look! The feathers you have found are sparkling. Aren't they?\";", 'mes "Oh! Las encontraste todas. Mira! Las plumas que encontraste estan brillando. No es asi?";'),
    ('mes "Alright, let me begin crafting the ^006400Jaty Crown^000000 I feel that I am ready.";', 'mes "Bien, dejame comenzar a elaborar la ^006400Jaty Crown^000000, siento que estoy listo.";'),
    ('mes "Suddenly, a large noise begins to boom as you and ^0000FFPaiko^000000 are surrounded by warm and bright sparkling energy like a thousand tinkling fireflies.";', 'mes "De repente, un gran ruido comienza a retumbar mientras tu y ^0000FFPaiko^000000 son rodeados por energia calida y brillante como miles de luciernagas centelleantes.";'),
    ('mes "With your help the ^006400Jaty Crown^000000 is coming along nicely.";', 'mes "Con tu ayuda la ^006400Jaty Crown^000000 va muy bien.";'),
    ('mes "It will take some time until the task is finished so please wait a little.";', 'mes "Tomara algo de tiempo hasta que la tarea termine asi que por favor espera un poco.";'),
    ('mes "After the ^006400Jaty Crown^000000 is complete, there is a gift that I want to give to you.";', 'mes "Despues de que la ^006400Jaty Crown^000000 este completa, hay un regalo que quiero darte.";'),
    ('mes "Ah, also you should go see Sage ^0000FFKasyapa^000000 who really wants to reward you with something.";', 'mes "Ah, tambien deberias ir a ver al Sabio ^0000FFKasyapa^000000 quien realmente quiere recompensarte con algo.";'),
    ('mes "Ah, you should talk to Sage ^0000FFKasyapa^000000 who really wants to reward you with something.";', 'mes "Ah, deberias hablar con el Sabio ^0000FFKasyapa^000000 quien realmente quiere recompensarte con algo.";'),
    ('mes "With your support I am not worrying about creating the ^006400Jaty Crown^000000.";', 'mes "Con tu apoyo no me preocupo por crear la ^006400Jaty Crown^000000.";'),
    ('mes "I really appreciate it.";', 'mes "Realmente lo aprecio.";'),
    ("mes \"A delightful day like today should be celebrated. Don't you think?\";", 'mes "Un dia tan agradable como hoy deberia celebrarse. No crees?";'),
    ('mes "So I prepared to sample the special food of our tribe, called ^006400Satay^000000";', 'mes "Asi que prepare una muestra de la comida especial de nuestra tribu, llamada ^006400Satay^000000";'),
    ('mes "But, this ^006400Satay^000000 is too tasty for just the two of us to share so we would like to share it with people out in the village.";', 'mes "Pero, este ^006400Satay^000000 es demasiado sabroso para compartirlo solo entre nosotros dos, asi que nos gustaria compartirlo con la gente de la aldea.";'),
    ('mes "What do you think?";', 'mes "Que opinas?";'),
    ('mes "In order to share news that";', 'mes "Para compartir la noticia de que";'),
    ('mes "the ^006400Jaty Crown^000000 is being successfully crafted and to share the delicious ^006400Satay^000000 with our friends, I need your help.";', 'mes "la ^006400Jaty Crown^000000 se esta elaborando exitosamente y para compartir el delicioso ^006400Satay^000000 con nuestros amigos, necesito tu ayuda.";'),
    ('mes "Are you up for a short delivery job?";', 'mes "Te animas para un trabajo de entrega corto?";'),
    ('select("Of course, I can help:Sorry, I am too busy to help.")', 'select("Por supuesto, puedo ayudar:Lo siento, estoy muy ocupado para ayudar.")'),
    ('mes "I believed you would definitely help me...";', 'mes "Creia que definitivamente me ayudarias...";'),
    ("mes \"It's a little disappointing.\";", 'mes "Es un poco decepcionante.";'),
    ('mes "If you ever change your mind";', 'mes "Si alguna vez cambias de opinion";'),
    ('mes "come speak with me again.";', 'mes "ven a hablar conmigo de nuevo.";'),
    ("mes \"Oh!, I knew you'd help.\";", 'mes "Oh!, sabia que ayudarias.";'),
    ("mes \"Our tribe's warriors come to my mind before we share with anyone else.\";", 'mes "Los guerreros de nuestra tribu vienen a mi mente antes de compartir con nadie mas.";'),
    ('mes "Please share Satay with the warriors in the village.";', 'mes "Por favor comparte Satay con los guerreros de la aldea.";'),
    ('mes "For the moment I will give you 2 ^006400Satay^000000.";', 'mes "Por el momento te dare 2 ^006400Satay^000000.";'),
    ("mes \"You may be tempted by the aroma of our ^006400Satay^000000 and you may eat one but, if you eat more than that you won't be able to share the ^006400Satay^000000\";", 'mes "Puedes sentirte tentado por el aroma de nuestro ^006400Satay^000000 y puedes comer uno pero, si comes mas de eso no podras compartir el ^006400Satay^000000";'),
    ('mes "with our village friends.";', 'mes "con nuestros amigos de la aldea.";'),
    ('mes "Our tribe warriors come to my mind to deliver the food to share Satay with warriors in the village.";', 'mes "Los guerreros de nuestra tribu vienen a mi mente para entregar la comida y compartir Satay con los guerreros de la aldea.";'),
    ('mes "Ah, the next person whom I want the ^006400Satay^000000 delivered to is someone who stays across from the river, the ^0000FFTribe Manager^000000.";', 'mes "Ah, la siguiente persona a quien quiero que le entregues el ^006400Satay^000000 es alguien que vive al otro lado del rio, el ^0000FFTribe Manager^000000.";'),
    ('mes "To this end, I will give you 2 more servings of ^006400Satay^000000.";', 'mes "Para esto, te dare 2 porciones mas de ^006400Satay^000000.";'),
    ("mes \"If you are attracted by the aroma of the ^006400Satay^000000, you may eat one but, if you eat more you won't be able to share ^006400Satay^000000 with our friends.\";", 'mes "Si te atrae el aroma del ^006400Satay^000000, puedes comer uno pero, si comes mas no podras compartir ^006400Satay^000000 con nuestros amigos.";'),
    ('mes "Second person to be delivered ^006400Satay^000000 is someone who stays across the river.";', 'mes "La segunda persona a quien entregarle ^006400Satay^000000 es alguien que vive al otro lado del rio.";'),
    ('mes "That is the ^0000FFTribe Manager^000000.";', 'mes "Es el ^0000FFTribe Manager^000000.";'),
    ('mes "Please deliver it to them before it cools down.";', 'mes "Por favor entregalo antes de que se enfrie.";'),
    ('mes "Oh, you have delivered it already?";', 'mes "Oh, ya lo entregaste?";'),
    ('mes "The third person to deliver the ^006400Satay^000000 to is the ^0000FFGatekeeper of Krakatau Volcano^000000.";', 'mes "La tercera persona a quien entregar el ^006400Satay^000000 es el ^0000FFGatekeeper of Krakatau Volcano^000000.";'),
    ("mes \"I'll give you 2 more servings of ^006400Satay^000000 for this delivery.\";", 'mes "Te dare 2 porciones mas de ^006400Satay^000000 para esta entrega.";'),
    ("mes \"And just like before, don't give into the smell and try not to eat the ^006400Satay^000000.\";", 'mes "Y al igual que antes, no cedas ante el olor y trata de no comer el ^006400Satay^000000.";'),
    ('mes "Please deliver it before it cools down.";', 'mes "Por favor entregalo antes de que se enfrie.";'),
    ('mes "Oh, You have delivered it";', 'mes "Oh, lo entregaste";'),
    ('mes "Last person to deliver ^006400Satay^000000 to is the ^0000FFBorobudur Temple Manager^000000 who is on ^8B4513Dewata Island^000000.";', 'mes "La ultima persona a quien entregar ^006400Satay^000000 es el ^0000FFBorobudur Temple Manager^000000 que esta en ^8B4513Dewata Island^000000.";'),
    ('mes "I will give you 2 more ^006400Satay^000000";', 'mes "Te dare 2 mas de ^006400Satay^000000";'),
    ('mes "The last person to be delivered ^006400Satay^000000 is";', 'mes "La ultima persona a quien entregar ^006400Satay^000000 es";'),
    ('mes "^0000FFBorobudur Temple Manager^000000 who is in";', 'mes "^0000FFBorobudur Temple Manager^000000 que esta en";'),
    ('mes "Oh, you have delivered it.";', 'mes "Oh, lo entregaste.";'),
    ("mes \"You've done good work.\";", 'mes "Hiciste un buen trabajo.";'),
    ('mes "It has been a good time for all of us to share and enjoy this happy occasion together. Thank you.";', 'mes "Ha sido un buen momento para todos nosotros compartir y disfrutar esta feliz ocasion juntos. Gracias.";'),
    ('mes "While you were on the way back from delivering the ^006400Satay^000000,";', 'mes "Mientras regresabas de entregar el ^006400Satay^000000,";'),
    ('mes "the Jaty Crown has been made. Its ambience and radiance make it a truly flawless crown.";', 'mes "la Jaty Crown fue hecha. Su ambiente y resplandor la hacen una corona verdaderamente perfecta.";'),
    ('mes "Also, you brought more than enough materials so after making the ^006400Jaty Crown^000000, we were able to craft a similar one for you to keep.";', 'mes "Ademas, trajiste mas que suficientes materiales asi que despues de hacer la ^006400Jaty Crown^000000, pudimos elaborar una similar para que la conserves.";'),
    ("mes \"It's not the same as the original, but it has its own specialty. It is my reward to thank you for what you have done.\";", 'mes "No es igual a la original, pero tiene su propia especialidad. Es mi recompensa para agradecerte por lo que has hecho.";'),
    ('mes "You are carrying too much weight to receive your reward.";', 'mes "Llevas demasiado peso para recibir tu recompensa.";'),
    ('mes "Please reduce your carried weight and come back again.";', 'mes "Por favor reduce tu peso y regresa.";'),
    ("mes \"Made with our tribe's secret marinade try the ^006400Satay^000000.\";", 'mes "Hecho con la marinada secreta de nuestra tribu, prueba el ^006400Satay^000000.";'),
    ("mes \"It was made with all our heart, especially for you, but don't forget to share it with friends.\";", 'mes "Fue hecho con todo nuestro corazon, especialmente para ti, pero no olvides compartirlo con amigos.";'),
    ('mes "Whatever you do in the future, I wish for you to have a life which is full of fortune and joy.";', 'mes "Hagas lo que hagas en el futuro, deseo que tengas una vida llena de fortuna y alegria.";'),
    ('mes "As Chief of the ^8B4513Jaty Tribe^000000, I wish you the best of luck!!";', 'mes "Como Jefe de la ^8B4513Jaty Tribe^000000, te deseo la mejor de las suertes!!";'),
    ('mes "It seems that you have yet to deliver the ^006400Satay^000000.";', 'mes "Parece que aun no has entregado el ^006400Satay^000000.";'),
    ('mes "Did you run into any problems?";', 'mes "Te encontraste con algun problema?";'),
    ("mes \"Haven't you delivered the ^006400Satay^000000 yet?\";", 'mes "Aun no has entregado el ^006400Satay^000000?";'),
    ('mes "Anything go wrong?";', 'mes "Algo salio mal?";'),
    ('select("I ate them all.:Deliver to whom.:Nothing.")', 'select("Me los comi todos.:Entregar a quien.:Nada.")'),
    ("mes \"Huh... so you couldn't resist yourself, eh?\";", 'mes "Huh... asi que no pudiste resistirte, eh?";'),
    ("mes \"Don't blame yourself too much. It is difficult to resist the ^006400Satay^000000's addicting aroma.\";", 'mes "No te culpes demasiado. Es dificil resistir el aroma adictivo del ^006400Satay^000000.";'),
    ("mes \"Our tribe is short on food supplies so we can't give out more of our ^006400Satay^000000, but there's a rumor that the restaurant owner in Dewata Island is making and selling their own ^006400Satay^000000.\";", 'mes "Nuestra tribu tiene escasez de alimentos asi que no podemos dar mas de nuestro ^006400Satay^000000, pero hay un rumor de que el dueno del restaurante en Dewata Island esta haciendo y vendiendo su propio ^006400Satay^000000.";'),
    ("mes \"It is not as tasty as our tribe's recipe, but this is an urgent task so just find it and deliver it.\";", 'mes "No es tan sabroso como la receta de nuestra tribu, pero es una tarea urgente asi que solo encuentralo y entregalo.";'),
    ('mes "Alright! Deliver it right now!";', 'mes "Muy bien! Entregalo ahora mismo!";'),
    # Jaty Tribe Warrior
    ('mes "We revere strength and bravery.";', 'mes "Reverenciamos la fuerza y la valentia.";'),
    ('mes "We are ^FF0000Jaty^000000 Tribe.";', 'mes "Somos la Tribu ^FF0000Jaty^000000.";'),
    ('mes "My trained eyes see that";', 'mes "Mis ojos entrenados ven que";'),
    ('mes "you seem about to say something.";', 'mes "pareces estar a punto de decir algo.";'),
    ('mes "Speak, and state your business.";', 'mes "Habla, y di tu asunto.";'),
    ("mes \"I've heard about your\";", 'mes "He escuchado de tus";'),
    ('mes "helpful deeds...";', 'mes "buenas acciones...";'),
    ('mes "As a representative of my tribe";', 'mes "Como representante de mi tribu";'),
    ('mes "I express my thanks to you.";', 'mes "te expreso mis agradecimientos.";'),
    ('mes "Also, thank you for the ^006400Satay^000000";', 'mes "Ademas, gracias por el ^006400Satay^000000";'),
    ('mes "My mouth is already watering thank you.";', 'mes "Ya se me hace agua la boca, gracias.";'),
    ('mes "There is something I would like to share with you regarding our tribe.";', 'mes "Hay algo que me gustaria compartir contigo sobre nuestra tribu.";'),
    ("mes \"Unlike the ancient times when our tribe's warriors fought and shed their blood the world has become more peaceful nowadays but our tribe's territory has shrunk drastically.\";", 'mes "A diferencia de los tiempos antiguos cuando los guerreros de nuestra tribu peleaban y derramaban su sangre, el mundo se ha vuelto mas pacifico pero el territorio de nuestra tribu se ha reducido drasticamente.";'),
    ("mes \"Nevertheless we will continue keeping the warrior tradition of our tribe alive and we will preserve the pride we have earned through the sacrifice of those past warriors.\";", 'mes "Sin embargo seguiremos manteniendo viva la tradicion guerrera de nuestra tribu y preservaremos el orgullo que hemos ganado a traves del sacrificio de esos guerreros pasados.";'),
    ('mes "I hope that your perseverance and pride remain with you in your travels.";', 'mes "Espero que tu perseverancia y orgullo te acompanen en tus viajes.";'),
    # Tribe Manager
    ('mes "Keeping our culture and tradition is very important.";', 'mes "Mantener nuestra cultura y tradicion es muy importante.";'),
    ('mes "Although it is a little boring...";', 'mes "Aunque es un poco aburrido...";'),
    ('mes "It seems to me that you have something";', 'mes "Me parece que tienes algo";'),
    ("mes \"to say, don't you?\";", 'mes "que decir, no es asi?";'),
    ("mes \"I didn't know that there was\";", 'mes "No sabia que habia";'),
    ('mes "such an effort being put forth";', 'mes "tanto esfuerzo siendo realizado";'),
    ('mes "and that you took a key role in the effort...";', 'mes "y que tu tomaste un papel clave en el esfuerzo...";'),
    ('mes "You are the hero of the^8B4513Jaty Tribe^000000.";', 'mes "Eres el heroe de la ^8B4513Jaty Tribe^000000.";'),
    ('mes "Wow~ the savory scent of";', 'mes "Wow~ el delicioso aroma de";'),
    ('mes "delicious homemade ^006400Satay^000000!!";', 'mes "un delicioso ^006400Satay^000000 casero!!";'),
    ('mes "Thank you for the meal.";', 'mes "Gracias por la comida.";'),
    ('mes "Please give my regards";', 'mes "Por favor da mis saludos";'),
    ('mes "to our Tribe Leader.";', 'mes "a nuestro Lider Tribal.";'),
    ('mes "There are few contacts between";', 'mes "Hay pocos contactos entre";'),
    ('mes "^8B4513Dewata Island^000000 and ^8B4513Jaty tribe^000000.";', 'mes "^8B4513Dewata Island^000000 y la ^8B4513Jaty tribe^000000.";'),
    ('mes "We used to have a stronger bond";', 'mes "Soliamos tener un lazo mas fuerte";'),
    ('mes "in older times.";', 'mes "en tiempos pasados.";'),
    ('mes "But with new culture and foreigners flowing in";', 'mes "Pero con nueva cultura y extranjeros llegando";'),
    ('mes "^8B4513Dewata Island^000000 has became a tourist attraction and we have lost touch with them.";', 'mes "^8B4513Dewata Island^000000 se ha convertido en una atraccion turistica y hemos perdido contacto con ellos.";'),
    ("mes \"The tourist attraction has expanded continuously but the reason it hasn't influenced us here is due to this small temple which I am managing.\";", 'mes "La atraccion turistica se ha expandido continuamente pero la razon por la que no nos ha influenciado aqui es gracias a este pequeno templo que estoy administrando.";'),
    ("mes \"I couldn't let our tradition fade away like that easily.\";", 'mes "No podia dejar que nuestra tradicion se desvaneciera tan facilmente.";'),
    ('mes "I hope keeping our tradition and culture alive lets people know how important these things are to us.";', 'mes "Espero que mantener vivas nuestra tradicion y cultura le haga saber a la gente lo importantes que son estas cosas para nosotros.";'),
    ('mes "From now on, I hope people from ^8B4513Dewata Island^000000 and ^8B4513Jaty Tribe^000000 can get along and interact more often.";', 'mes "De ahora en adelante, espero que la gente de ^8B4513Dewata Island^000000 y la ^8B4513Jaty Tribe^000000 puedan llevarse bien e interactuar mas seguido.";'),
    # Gatekeeper of Krakatau
    ('mes "^8B4513Krakatau Volcano^000000 is";', 'mes "El Volcan ^8B4513Krakatau^000000 es";'),
    ('mes "a very dangerous area";', 'mes "un area muy peligrosa";'),
    ('mes "I cannot allow anyone to go in there.";', 'mes "No puedo permitir que nadie entre ahi.";'),
    ("select(\"Allow me through:I don't want to go in\"+.@menu$)", "select(\"Dejame pasar:No quiero entrar\"+.@menu$)"),
    ("mes \"so I can't allow you in\";", 'mes "asi que no puedo dejarte entrar";'),
    ('mes "unless you qualify for entry.";', 'mes "a menos que califiques para la entrada.";'),
    ('mes "You are the traveler who was acknowledged by tribe leader as a friend of the tribe and received a ^006400Shining Cendrawasih Feather^000000.";', 'mes "Eres el viajero que fue reconocido por el lider tribal como amigo de la tribu y recibio una ^006400Shining Cendrawasih Feather^000000.";'),
    ('mes "Well, I will let you pass but ^8B4513Krakatau Volcano^000000 is dangerous so please take care.";', 'mes "Bueno, te dejare pasar pero el Volcan ^8B4513Krakatau^000000 es peligroso asi que ten cuidado.";'),
    ('mes "You have chosen wisely.";', 'mes "Has elegido sabiamente.";'),
    ('mes "an extremely dangerous area.";', 'mes "un area extremadamente peligrosa.";'),
    ("mes \"Oh! I didn't know about that!\";", 'mes "Oh! No sabia eso!";'),
    ('mes "This is some of the best news";', 'mes "Esta es una de las mejores noticias";'),
    ('mes "I have heard recently.";', 'mes "que he escuchado recientemente.";'),
    ('mes "Um, what is this wonderful smell?";', 'mes "Um, que es este olor maravilloso?";'),
    ("mes \"Of course, it's our ^006400Satay^000000!\";", 'mes "Por supuesto, es nuestro ^006400Satay^000000!";'),
    ('mes "I was slightly hungry";', 'mes "Tenia un poco de hambre";'),
    ('mes "so this should fill me up.";', 'mes "asi que esto deberia llenarme.";'),
    ('mes "Since you came all the way here";', 'mes "Ya que viniste hasta aqui";'),
    ('mes "I will share you an interesting story.";', 'mes "te compartire una historia interesante.";'),
    ('mes "It has become a lost tradition in recent years but until 10 or more years ago in order to become a ^8B4513Jaty Tribe^000000 warrior you had to climb Krakatau Volcano to prove your endurance.";', 'mes "Se ha convertido en una tradicion perdida en anos recientes pero hasta hace 10 o mas anos para convertirse en guerrero de la ^8B4513Jaty Tribe^000000 tenias que escalar el Volcan Krakatau para probar tu resistencia.";'),
    ('mes "The eyes of those warriors were anxious yet determined before going up ^8B4513Krakatau Volcano^000000.";', 'mes "Los ojos de esos guerreros estaban ansiosos pero determinados antes de subir el Volcan ^8B4513Krakatau^000000.";'),
    ('mes "I still cannot forget that look in their eyes I feel a little bit the same emotion from you Adventurer.";', 'mes "Aun no puedo olvidar esa mirada en sus ojos, siento un poco la misma emocion viniendo de ti, Aventurero.";'),
    ('mes "I want you to live long and prosper.";', 'mes "Quiero que vivas largo y prosperes.";'),
    ('mes "Be healthy and safe, traveler so you can live to tell the tale of your adventures.";', 'mes "Se saludable y ten cuidado, viajero, para que puedas vivir para contar la historia de tus aventuras.";'),
    ('mes "Want to go back";', 'mes "Quieres regresar";'),
    ('mes "to Dewata?";', 'mes "a Dewata?";'),
    ('select("Yes:No")', 'select("Si:No")'),
    ('mes "a dangerous place.";', 'mes "un lugar peligroso.";'),
    ('mes "You should go back now.";', 'mes "Deberias regresar ahora.";'),
    # Borobudur Temple Manager
    ('mes "The weather today is so beautiful.";', 'mes "El clima de hoy es tan hermoso.";'),
    ('mes "By the way, do you have";', 'mes "Por cierto, tienes";'),
    ('mes "something to tell me...?";', 'mes "algo que decirme...?";'),
    ('mes "I never knew such a thing had happened.";', 'mes "Nunca supe que tal cosa habia pasado.";'),
    ('mes "If you had told me in advance, I could have helped at least a little bit.";', 'mes "Si me hubieras dicho de antemano, podria haber ayudado al menos un poco.";'),
    ('mes "Still things have gone well with your help.";', 'mes "Aun asi las cosas han ido bien con tu ayuda.";'),
    ('mes "Ah, it is the ^006400Satay^00000 that I sampled when the tribe invited me some time ago.";', 'mes "Ah, es el ^006400Satay^00000 que probe cuando la tribu me invito hace algun tiempo.";'),
    ('mes "Good~~ This is the same taste I remember.";', 'mes "Bueno~~ Es el mismo sabor que recuerdo.";'),
    ('mes "To give my thanks I will pass along a story that may interest you";', 'mes "Para dar mis agradecimientos te contare una historia que puede interesarte";'),
    ('mes "Legend tells of a strange bird called ^FF0000Garuda^000000.";', 'mes "La leyenda habla de un pajaro extrano llamado ^FF0000Garuda^000000.";'),
    ('mes "It has the torso, arms and legs of a human but has the head and beak of an eagle.";', 'mes "Tiene el torso, brazos y piernas de un humano pero tiene la cabeza y pico de un aguila.";'),
    ('mes "The Story of this bird describes it helping the gods exterminate wicked demons and snakes.";', 'mes "La historia de este pajaro describe como ayudo a los dioses a exterminar demonios malvados y serpientes.";'),
    ('mes "The tale has been passed down from generation to generation.";', 'mes "El cuento ha sido transmitido de generacion en generacion.";'),
    ("mes \"Quite interesting, isn't it?\";", 'mes "Bastante interesante, no?";'),
    ('mes "I am sure in the village of the ^8B4513Jaty Tribe^000000 there are many legendary stories.";', 'mes "Estoy seguro de que en la aldea de la ^8B4513Jaty Tribe^000000 hay muchas historias legendarias.";'),
    ('mes "When I get to meet the Chief, I will hear many such stories for sure.";', 'mes "Cuando pueda reunirme con el Jefe, escuchare muchas de esas historias de seguro.";'),
    ('mes "I am not certain of when we will cross paths again but I hope we will meet again someday.";', 'mes "No estoy seguro de cuando nos cruzaremos de nuevo pero espero que nos encontremos algun dia.";'),
    ('mes "I wish you a pleasant journey, young traveler.";', 'mes "Te deseo un viaje placentero, joven viajero.";'),
    # Memo NPC - Help Out the Old Man
    ("mes \"Why are you carrying so much? Doesn't that hurt your back?\";", 'mes "Por que llevas tanto? No te duele la espalda?";'),
    ('mes "Is it a trend for youngsters to carry heavy things?";', 'mes "Es tendencia de los jovenes cargar cosas pesadas?";'),
    ('mes "Will you help me again tomorrow?";', 'mes "Me ayudaras otra vez manana?";'),
    ('mes "Poby still has a back pain.";', 'mes "Poby todavia tiene dolor de espalda.";'),
    ("mes \"Backaches don't just go away after one day.\";", 'mes "Los dolores de espalda no se van despues de un dia.";'),
    ('mes "Dewata is always crowded but today is quiet.";', 'mes "Dewata siempre esta llena pero hoy esta tranquila.";'),
    ("mes \"Oh god! We don't have a message from the Jaty tribe yet.\";", 'mes "Dios mio! Aun no tenemos un mensaje de la tribu Jaty.";'),
    ("mes \"They have never broken a promise for 10 years, I do not know the reason. What's happening?\";", 'mes "Nunca han roto una promesa en 10 anos, no se la razon. Que esta pasando?";'),
    ('mes "I might spoil all the liquid if it is going on like this.";', 'mes "Podria echar a perder todo el liquido si esto sigue asi.";'),
    ("mes \"What should I do? I still don't have any news from the Jaty tribe.\";", 'mes "Que deberia hacer? Aun no tengo noticias de la tribu Jaty.";'),
    ('mes "Oh no~ All the liquid is going to spoil...";', 'mes "Oh no~ Todo el liquido se va a echar a perder...";'),
    ('select("What happened?");', 'select("Que paso?");'),
    ('mes "Who are you?";', 'mes "Quien eres?";'),
    ('mes "You are an adventurer, right?";', 'mes "Eres un aventurero, verdad?";'),
    ('mes "As you can see from the jars around me, I am making ^0000FFtraditional wine^000000 for a living.";', 'mes "Como puedes ver por las jarras a mi alrededor, me gano la vida haciendo ^0000FFvino tradicional^000000.";'),
    ('mes "Everyone knows about this, so ^0000FFDewata island^000000 attracts many tourists.";', 'mes "Todos saben de esto, asi que ^0000FFDewata island^000000 atrae muchos turistas.";'),
    ('mes "Especially this traditional wine, which has been made for four generations! But ^FF0000Ark^000000 is short of supply.";', 'mes "Especialmente este vino tradicional, que se ha hecho por cuatro generaciones! Pero ^FF0000Ark^000000 tiene escasez.";'),
    ('mes "Ark needs ^0000FFPalm Oils^000000, made from Oil Palm Fruit.";', 'mes "Ark necesita ^0000FFPalm Oils^000000, hechos de Oil Palm Fruit.";'),
    ("mes \"Unfortunately, we haven't been getting ^0000FFPalm Oil^000000 from the Jaty tribe village lately.\";", 'mes "Desafortunadamente, no hemos estado recibiendo ^0000FFPalm Oil^000000 de la aldea de la tribu Jaty ultimamente.";'),
    ("mes \"The ingredients might be useless if it is delivered too late.\";", 'mes "Los ingredientes podrian ser inutiles si se entregan demasiado tarde.";'),
    ('select("Sounds like a big problem.");', 'select("Suena como un gran problema.");'),
    ("mes \"It is more of a problem than you think. Sales are credit, but if we do not make due today, we'll lose the credit, the ingredients, and the tourists who do not get the Ark. So it's quite damaging.\";", 'mes "Es mas problema de lo que crees. Las ventas son a credito, pero si no producimos hoy, perderemos el credito, los ingredientes, y los turistas que no obtienen el Ark. Asi que es bastante danino.";'),
    ('mes "Ah, right! Are you busy now?";', 'mes "Ah, cierto! Estas ocupado ahora?";'),
    ('select("Sorry, I am busy.:No, I am not busy.")', 'select("Lo siento, estoy ocupado.:No, no estoy ocupado.")'),
    ('mes "Hmm, I have no choice.";', 'mes "Hmm, no tengo opcion.";'),
    ("mes \"You don't care that others are in trouble. What has this world come to?\";", 'mes "No te importa que otros esten en problemas. A que ha llegado este mundo?";'),
    ("mes \"That's good to hear.\";", 'mes "Que bueno escuchar eso.";'),
    ('mes "So since you are wandering here...";', 'mes "Entonces ya que andas por aqui...";'),
    ("mes \"Do you mind if I ask you a favor~? Actually I have to visit the Jaty Tribe, but this unmatured ^FF0000Ark^000000 won't let me leave.\";", 'mes "Te importaria si te pido un favor~? De hecho tengo que visitar a la Tribu Jaty, pero este ^FF0000Ark^000000 sin madurar no me deja irme.";'),
    ('mes "Will you go to Jaty village and ask ^0000FFLero^000000 what happened?";', 'mes "Irias a la aldea Jaty a preguntarle a ^0000FFLero^000000 que paso?";'),
    ('mes "This guy has never broken a promise for 10 years, so he must have a really good reason not to come.";', 'mes "Este tipo nunca ha roto una promesa en 10 anos, asi que debe tener una muy buena razon para no venir.";'),
    ('mes "Find the best oil master.";', 'mes "Encuentra al mejor maestro aceitero.";'),
    ('mes "His name again is ^0000FFLero^000000.";', 'mes "Su nombre de nuevo es ^0000FFLero^000000.";'),
    ('mes "So, what did Lero say?";', 'mes "Entonces, que dijo Lero?";'),
    ("mes \"You didn't find out what happened?\";", 'mes "No averiguaste que paso?";'),
    ('mes "Find the best oil master. His name is ^0000FFLero^000000.";', 'mes "Encuentra al mejor maestro aceitero. Su nombre es ^0000FFLero^000000.";'),
    ('select("Palm tree... became.");', 'select("El palmeral... se convirtio.");'),
    ('mes "- You explain the situation to Mr. Memo -";', 'mes "- Le explicas la situacion al Sr. Memo -";'),
    ('mes "Lero said sorry?";', 'mes "Lero dijo lo siento?";'),
    ("mes \"Hmm, it's okay.\";", 'mes "Hmm, esta bien.";'),
    ("mes \"That must be ^0000FFPoby^000000. If he has been hurt, that's why there wasn't any message. Lero actually cares about him a lot...\";", 'mes "Ese debe ser ^0000FFPoby^000000. Si fue herido, por eso no hubo ningun mensaje. Lero realmente se preocupa mucho por el...";'),
    ('mes "He might be troublesome, but please visit the Jaty village. Lero must complete the oil.";', 'mes "Puede que sea problematico, pero por favor visita la aldea Jaty. Lero debe completar el aceite.";'),
    ('mes "If it is not, wait there and bring ^FF000030 bottles of oil^000000 to me.";', 'mes "Si no es asi, espera ahi y traeme ^FF000030 botellas de aceite^000000.";'),
    ("mes \"Oh, didn't I tell you to bring 30 bottles of oil? Did you forget?\";", 'mes "Oh, no te dije que trajeras 30 botellas de aceite? Se te olvido?";'),
    ('mes "Go back to Lero and get more, he will give you more if it was your mistake.";', 'mes "Regresa con Lero y consigue mas, el te dara mas si fue tu error.";'),
    ('mes "You brought the oil. Good job, and thank you.";', 'mes "Trajiste el aceite. Buen trabajo, y gracias.";'),
    ('mes "Excuse me, but I have an urgent matter to attend to. Can you wait for a while and talk to me when I\'m done?";', 'mes "Disculpa, pero tengo un asunto urgente que atender. Puedes esperar un rato y hablarme cuando termine?";'),
    ('mes "- Memo is making an ark. -";', 'mes "- Memo esta haciendo un ark. -";'),
    ('mes "Did I make you wait too long?";', 'mes "Te hice esperar demasiado?";'),
    ('mes "My family has been making Arks for four generations.";', 'mes "Mi familia ha hecho Arks por cuatro generaciones.";'),
    ("mes \"Grandfather had a hard living since he didn't get many good sales.\";", 'mes "El abuelo tuvo una vida dificil ya que no tenia muchas buenas ventas.";'),
    ('mes "Dewata island people do not drink much in the hot weather.";', 'mes "La gente de Dewata island no bebe mucho en el clima caluroso.";'),
    ('mes "When I was young, Dewata developed as a tourist attraction and that\'s when the ^FF00FFtour package^000000 Ark started selling well.";', 'mes "Cuando era joven, Dewata se desarrollo como atraccion turistica y fue cuando el Ark de ^FF00FFpaquete turistico^000000 empezo a venderse bien.";'),
    ('mes "Good liquid needs fresh oil. I was able to make liquid for ten years and deliver it all on time.";', 'mes "Un buen liquido necesita aceite fresco. Pude hacer liquido por diez anos y entregarlo todo a tiempo.";'),
    ("mes \"Because today's oil has not arrived on time, I think I might have a hard time.\";", 'mes "Porque el aceite de hoy no ha llegado a tiempo, creo que podria tener problemas.";'),
    ('mes "You helped me to make the liquid correctly.";', 'mes "Me ayudaste a hacer el liquido correctamente.";'),
    ("mes \"This proverb ^0000FF'Mengatakan mudah, mengerjakan susah.'^000000 means it is easy to say something but hard to do anything.\";", "mes \"Este proverbio ^0000FF'Mengatakan mudah, mengerjakan susah.'^000000 significa que es facil decir algo pero dificil hacer algo.\";"),
    ("mes \"In other words, it's easy to say that we'll help others but it's hard to actually do the action.\";", 'mes "En otras palabras, es facil decir que ayudaremos a otros pero es dificil realmente hacerlo.";'),
    ("mes \"You really did a great job. I like you because you are different from today's youngins.\";", 'mes "Realmente hiciste un gran trabajo. Me agradas porque eres diferente a los jovenes de hoy.";'),
    ('mes "Will you help me with my work from time to time?";', 'mes "Me ayudaras con mi trabajo de vez en cuando?";'),
    ('mes "I will pay you for what you do for me.";', 'mes "Te pagare por lo que hagas por mi.";'),
    ('mes strcharinfo(0)+", to what do I owe the pleasure?";', 'mes strcharinfo(0)+", a que debo el placer?";'),
    ('select("Just came by to say hello.:I will help you.")', 'select("Solo vine a saludar.:Te ayudare.")'),
    ('mes "I guess you are busy.";', 'mes "Supongo que estas ocupado.";'),
    ("mes \"If possible, will you get the oil from Lero? I will appreciate it...\";", 'mes "Si es posible, podrias conseguir el aceite de Lero? Lo apreciaria...";'),
    ("mes \"Thank you. I know that you're busy and helping me can be a chore.\";", 'mes "Gracias. Se que estas ocupado y ayudarme puede ser una molestia.";'),
    ('mes "Can you help Lero and bring back palm tree oil...?";', 'mes "Puedes ayudar a Lero y traer aceite de palmera...?";'),
    ("mes \"You haven't brought enough oil.\";", 'mes "No has traido suficiente aceite.";'),
    ("mes \"Poby owes me a few things, he'll give you some.\";", 'mes "Poby me debe algunas cosas, el te dara un poco.";'),
    ('mes "Oh you brought the oil, good job.";', 'mes "Oh trajiste el aceite, buen trabajo.";'),
    ("mes \"You must've had a hard time bringing the oil so here take this drink.\";", 'mes "Debiste haber tenido problemas trayendo el aceite asi que toma esta bebida.";'),
    ('mes "Ark is famous for tourists, a guy bought many bottles by himself.";', 'mes "Ark es famoso entre turistas, un tipo compro muchas botellas el solo.";'),
    ("mes \"Worrying that he'll drink alone? Too much drink always becomes poisonous.\";", 'mes "Preocupado de que beba solo? Demasiada bebida siempre se vuelve veneno.";'),
    ('mes "The sun always rises in the East. The well known laziness wakes up early in the morning.";', 'mes "El sol siempre sale por el Este. La conocida pereza madruga.";'),
    ('mes "Does he come to reality? He is good but lazy.";', 'mes "Vuelve a la realidad? Es bueno pero flojo.";'),
    ('mes "The first blow is half the battle.";', 'mes "El primer golpe es la mitad de la batalla.";'),
    ("mes \"I think that you're destined to do great things.\";", 'mes "Creo que estas destinado a hacer grandes cosas.";'),
    ("mes \"There's a man saying blow hot and cold, it seems that a word is easy but it is not.\";", 'mes "Hay un dicho de soplar caliente y frio, parece que una palabra es facil pero no lo es.";'),
    ('mes "I believe that you will hold true to your promise.";', 'mes "Creo que mantendras tu promesa.";'),
    ('mes "I want you to help me this time.";', 'mes "Quiero que me ayudes esta vez.";'),
    ('mes "Poby still has back pains and it will take some days for him to recover.";', 'mes "Poby aun tiene dolor de espalda y tomara algunos dias para que se recupere.";'),
    ('mes "Dewata island is always crowded but today is quiet.";', 'mes "Dewata island siempre esta llena pero hoy esta tranquila.";'),
    # Lero NPC
    ("mes \"You're carrying too many things...\";", 'mes "Llevas demasiadas cosas...";'),
    ("mes \"Oh no! I have so many orders and I'm running out of ingredients.\";", 'mes "Oh no! Tengo tantos pedidos y me estoy quedando sin ingredientes.";'),
    ("mes \"Not yet? What's going on, Poby? Where did he go?\";", 'mes "Aun no? Que esta pasando, Poby? A donde fue?";'),
    ('select("Excuse me, but are you Lero?");', 'select("Disculpa, pero eres Lero?");'),
    ("mes \"When Poby gets back here, I'm gonna give him a beating he'll never forget!\";", 'mes "Cuando Poby regrese aqui, le dare una paliza que nunca olvidara!";'),
    ('mes "- Lero seems pretty mad at someone and ignores you -";', 'mes "- Lero parece bastante enojado con alguien y te ignora -";'),
    ('mes "Oops. Who are you?";', 'mes "Ups. Quien eres?";'),
    ('select("Memo sent me here.");', 'select("Memo me envio aqui.");'),
    ('mes "Ah, right! I forgot about Memo because the workers who gather nuts have not come yet. Sorry.";', 'mes "Ah, cierto! Me olvide de Memo porque los trabajadores que recolectan nueces aun no han llegado. Lo siento.";'),
    ("mes \"To make fresh palm oils, I need fresh Palm Oil Fruit. Then I'll be able to get more fresh oil from its fresh fruit.\";", 'mes "Para hacer aceites de palma frescos, necesito Palm Oil Fruit frescas. Entonces podre obtener mas aceite fresco de sus frutos frescos.";'),
    ('mes "Between you and me, Mr. Memo is so fussy that he will not use any unfresh oil.";', 'mes "Entre tu y yo, el Sr. Memo es tan quisquilloso que no usara aceite que no sea fresco.";'),
    ("mes \"To make fresh oil, he always sends the workers to palm tree forest, but... the guys sent at dawn have not come back yet.\";", 'mes "Para hacer aceite fresco, siempre envia trabajadores al bosque de palmeras, pero... los que envio al amanecer aun no regresan.";'),
    ('mes "First, I thought that he was lazy and it made me very uneasy.";', 'mes "Al principio, pense que era flojo y eso me ponia muy inquieto.";'),
    ('mes "Can you find the workers in the palm forest?";', 'mes "Puedes encontrar a los trabajadores en el bosque de palmeras?";'),
    ('select("Yes, I will find them.");', 'select("Si, los encontrare.");'),
    ('mes "Thank you so much.";', 'mes "Muchas gracias.";'),
    ('mes "Find Poby.";', 'mes "Encuentra a Poby.";'),
    ('mes "Poby might in ^0000FFPalm Forest^000000. The crop is best at the southern part of the forest.";', 'mes "Poby podria estar en ^0000FFPalm Forest^000000. La cosecha es mejor en la parte sur del bosque.";'),
    ('mes "Did you find Poby?";', 'mes "Encontraste a Poby?";'),
    ("mes \"Oh, you haven't visited the east of ^0000FFPalm Forest^000000 yet. I'm pretty worried.\";", 'mes "Oh, aun no has visitado el este de ^0000FFPalm Forest^000000. Estoy bastante preocupado.";'),
    ("mes \"You're back... and... Poby...\";", 'mes "Regresaste... y... Poby...";'),
    ('mes "How is Poby?";', 'mes "Como esta Poby?";'),
    ('select("Poby.....");', 'select("Poby.....");'),
    ("mes \"Ah! I didn't know that. I always tell Poby ^0000FF'Kemarau setahun rusak sehari.'^000000\";", "mes \"Ah! No lo sabia. Siempre le digo a Poby ^0000FF'Kemarau setahun rusak sehari.'^000000\";"),
    ("mes \"He climbed the tree without any safety equipment, so he might've fallen down and gotten injured.\";", 'mes "Escalo el arbol sin equipo de seguridad, asi que podria haberse caido y lastimado.";'),
    ("mes \"Hmm... Sorry I couldn't get the Palm Oil right now.\";", 'mes "Hmm... Lo siento, no pude obtener el Palm Oil ahora.";'),
    ('mes "Will you deliver the message to Mr. Memo that it is impossible to get the oil due do to a lack of ingredients?";', 'mes "Le llevaras el mensaje al Sr. Memo de que es imposible obtener el aceite debido a la falta de ingredientes?";'),
    ('mes "No artisans can create anything without ingredients.";', 'mes "Ningun artesano puede crear nada sin ingredientes.";'),
    ("select(\"Why don't I get the ingredients?\");", 'select("Por que no consigo yo los ingredientes?");'),
    ('mes "Ah, that can be a good way, but it will be hard to gather nuts as a starter.";', 'mes "Ah, esa puede ser una buena idea, pero sera dificil recolectar nueces siendo principiante.";'),
    ('mes "Hmm!!!";', 'mes "Hmm!!!";'),
    ('mes "I have a good idea.";', 'mes "Tengo una buena idea.";'),
    ('mes "You can ask Poby about the best method of gathering nuts where you met him in the forest. He should be able to teach you the technique.";', 'mes "Puedes preguntarle a Poby sobre el mejor metodo para recolectar nueces donde lo encontraste en el bosque. El deberia poder ensenarte la tecnica.";'),
    ('mes "Although he is lazy and rather careless, he is the best worker.";', 'mes "Aunque es flojo y bastante descuidado, es el mejor trabajador.";'),
    ('mes "Did you gather the nuts already?";', 'mes "Ya recolectaste las nueces?";'),
    ('mes "One, two...";', 'mes "Una, dos...";'),
    ("mes \"This isn't the number I ordered from Poby.\";", 'mes "Este no es el numero que le pedi a Poby.";'),
    ("mes \"It's going to be difficult if it is delayed more, so hurry up and bring me 60.\";", 'mes "Va a ser dificil si se retrasa mas, asi que apurate y traeme 60.";'),
    ('mes "One, two, three, four, . . . .";', 'mes "Una, dos, tres, cuatro, . . . .";'),
    ('mes "60 pieces of nuts, exactly. I will press the oil right now.";', 'mes "60 piezas de nueces, exacto. Prensare el aceite ahora mismo.";'),
    ('mes "It takes some time, so go back to Mr. Memo and tell him the situation. Also tell him that I\'m sorry for the delay.";', 'mes "Toma algo de tiempo, asi que regresa con el Sr. Memo y cuentale la situacion. Tambien dile que lamento la demora.";'),
    ('mes "You are carrying too much right now to continue.";', 'mes "Llevas demasiado encima ahora para continuar.";'),
    ("mes \"You've come at the right time. I just finished making the palm tree oil.\";", 'mes "Llegaste justo a tiempo. Acabo de terminar de hacer el aceite de palmera.";'),
    ('mes "It is heavier than you might think, so be careful when carrying it.";', 'mes "Es mas pesado de lo que piensas, asi que ten cuidado al cargarlo.";'),
    ("mes \"Oh, tell Mr. Memo that I'm sorry for the late delivery, and explain that it wasn't my fault.\";", 'mes "Oh, dile al Sr. Memo que lamento la entrega tardia, y explica que no fue mi culpa.";'),
    ('mes "I clearly remembered giving you 30 bottles of palm tree oil, did you lose it all?";', 'mes "Recuerdo claramente haberte dado 30 botellas de aceite de palmera, las perdiste todas?";'),
    ("select(\"Sorry, it's my fault...\");", 'select("Lo siento, fue mi culpa...");'),
    ('mes "This is the palm tree oil which was in short supply. Be careful please. It was really hard to get this...";', 'mes "Este es el aceite de palmera que estaba escaso. Ten cuidado por favor. Fue muy dificil conseguirlo...";'),
    ('mes "What did Mr. Memo say?";', 'mes "Que dijo el Sr. Memo?";'),
    ('mes "Ah... I understand...";', 'mes "Ah... Entiendo...";'),
    ("mes \"What happened? I didn't get a memo from Mr. Memo that he was going to send someone here.\";", 'mes "Que paso? No recibi un aviso del Sr. Memo de que iba a enviar a alguien aqui.";'),
    ("mes \"Hey, I've been waiting for you. I didn't know that Poby's injury would make my life so difficult.\";", 'mes "Oye, te he estado esperando. No sabia que la lesion de Poby haria mi vida tan dificil.";'),
    ("mes \"I'm ashamed to ask you this, but can you bring ^0000FF\"+(20+(.@quest*10))+\" pieces of oil palm nuts^000000 please?\";", 'mes "Me da pena pedirte esto, pero puedes traer ^0000FF"+(20+(.@quest*10))+" piezas de nueces de palma^000000 por favor?";'),
    ('mes "Once you bring the oil palm nuts, Mr. Memo will exchange them with oil.";', 'mes "Una vez que traigas las nueces de palma, el Sr. Memo las cambiara por aceite.";'),
    ('mes "Once you bring the "+.@i[0]+" pieces of oil palm nuts, Mr. Memo will exchange them with oil.";', 'mes "Una vez que traigas las "+.@i[0]+" piezas de nueces de palma, el Sr. Memo las cambiara por aceite.";'),
    ("mes \"You're carrying too much right now to continue.\";", 'mes "Llevas demasiado encima ahora para continuar.";'),
    ('mes "Exactly "+.@i[0]+" pieces of oil palm nuts. Let you exchange them with oil right now.";', 'mes "Exactamente "+.@i[0]+" piezas de nueces de palma. Dejame cambiarlas por aceite ahora mismo.";'),
    ('mes "As I told you before, it is heavier than you might think, so be careful when carrying this.";', 'mes "Como te dije antes, es mas pesado de lo que piensas, asi que ten cuidado al cargarlo.";'),
    ("mes \"What's going on with Poby...? Why hasn't he come back...?\";", 'mes "Que pasa con Poby...? Por que no ha regresado...?";'),
    ('mes "- Seems that he is waiting for someone-";', 'mes "- Parece que esta esperando a alguien -";'),
    # Poby NPC
    ('mes "Why are you carrying so much?";', 'mes "Por que llevas tanto?";'),
    ("mes \"You're going to regret it if you are carrying so much.\";", 'mes "Te vas a arrepentir si llevas tanto.";'),
    ('mes "Ah~ backache...";', 'mes "Ah~ dolor de espalda...";'),
    ('select("Are you Poby?");', 'select("Eres Poby?");'),
    ("mes \"I do not know you, but\";", 'mes "No te conozco, pero";'),
    ('mes "are you a fan of mine?";', 'mes "eres fan mio?";'),
    ("mes \"I'm Poby, the best fruit hunter in the Jaty tribe.\";", 'mes "Soy Poby, el mejor cazador de frutas de la tribu Jaty.";'),
    ('mes "You here for my autograph?";', 'mes "Vienes por mi autografo?";'),
    ('select("Lero made me come here.");', 'select("Lero me hizo venir aqui.");'),
    ("mes \"Ah! Mr. Lero made you come here. I can't move because I hurt my back while climbing a tree.\";", 'mes "Ah! El Sr. Lero te hizo venir. No me puedo mover porque me lastime la espalda escalando un arbol.";'),
    ("mes \"And I've still never had a girlfriend...\";", 'mes "Y todavia nunca he tenido novia...";'),
    ('mes "Ah! Sorry. Tell Mr. Lero that I will go back if I can find a way to move.";', 'mes "Ah! Lo siento. Dile al Sr. Lero que volvere si encuentro la forma de moverme.";'),
    ("mes \"I can't move at all 'cuz of this backache...\";", 'mes "No me puedo mover por este dolor de espalda...";'),
    ('mes "Oh!! You\'re-- Let me guess...";', 'mes "Oh!! Tu eres-- Dejame adivinar...";'),
    ("mes \"...you're back! You plan to catch ^0000FFPalm Oil Fruit^000000 instead of me, right?\";", 'mes "...regresaste! Planeas atrapar ^0000FFPalm Oil Fruit^000000 en mi lugar, verdad?";'),
    ("mes \"It is hard for beginners to catch the fruit like me. No it's impossible.\";", 'mes "Es dificil para principiantes atrapar la fruta como yo. No, es imposible.";'),
    ("mes \"Masters usually climb the tree to catch the fruit, but you're a beginner...\";", 'mes "Los maestros usualmente escalan el arbol para atrapar la fruta, pero eres principiante...";'),
    ("mes \"It's easiest for beginners to shake or kick the tree. It might be dangerous, so remember to wear a ^0000FFSafety Helmet^000000.\";", 'mes "Lo mas facil para principiantes es sacudir o patear el arbol. Puede ser peligroso, asi que recuerda usar un ^0000FFSafety Helmet^000000.";'),
    ('mes "Ok! Gather ^FF000060^0000FF ^0000FFPalm Oil Fruit^000000 and bring that amount to Mr. Lero.";', 'mes "Ok! Recolecta ^FF000060^0000FF ^0000FFPalm Oil Fruit^000000 y lleva esa cantidad al Sr. Lero.";'),
    ('mes "Oh! "+strcharinfo(0)+", we meet again. What\'s going on?";', 'mes "Oh! "+strcharinfo(0)+", nos vemos de nuevo. Que pasa?";'),
    ('mes "Good work! Be careful while delivering them~";', 'mes "Buen trabajo! Ten cuidado al entregarlas~";'),
    ('mes "- You explain the situation. -";', 'mes "- Le explicas la situacion. -";'),
    ('mes "Right... I owed Memo\'s grandfather. Wait, I hid some oil around here.";', 'mes "Cierto... Le debia al abuelo de Memo. Espera, escondi algo de aceite por aqui.";'),
    ('mes "I have some, but you seem to have too much stuff with you.";', 'mes "Tengo algo, pero pareces tener demasiadas cosas contigo.";'),
    ('mes "- rummaging... rummaging... -";', 'mes "- buscando... buscando... -";'),
    ("mes \"Ah! Here is another one. Take care not to lose it again. And keep it a secret from Mr. Lero.\";", 'mes "Ah! Aqui hay otro. Ten cuidado de no perderlo otra vez. Y guardalo en secreto del Sr. Lero.";'),
    ('mes "Please~ "+strcharinfo(0)+".";', 'mes "Por favor~ "+strcharinfo(0)+".";'),
    ("select(\"Why'd you come here?:I want to know how to get fruit.\")", 'select("Por que viniste aqui?:Quiero saber como obtener fruta.")'),
    ("mes \"I'm taking a walk because I think it will make my back ache less.\";", 'mes "Estoy caminando porque creo que hara que me duela menos la espalda.";'),
    ("mes \"It's easiest for beginners to shake or kick the tree.\";", 'mes "Lo mas facil para principiantes es sacudir o patear el arbol.";'),
    ('mes "It might be dangerous, so always wear a ^0000FFSafety Helmet^000000.";', 'mes "Puede ser peligroso, asi que siempre usa un ^0000FFSafety Helmet^000000.";'),
    ("mes \"Ah~ my freakin' back is killing me.\";", 'mes "Ah~ mi maldita espalda me esta matando.";'),
    ('mes "You got all the fruits. Bring them to Mr. Lero.";', 'mes "Conseguiste todas las frutas. Llevalas al Sr. Lero.";'),
    ('mes "Gather ^FF000060 ^0000FFPalm Oil Fruit^000000 and bring them to Mr. Lero.";', 'mes "Recolecta ^FF000060 ^0000FFPalm Oil Fruit^000000 y llevalas al Sr. Lero.";'),
    # Palm Tree
    ('mes "You are carrying too much.";', 'mes "Llevas demasiado.";'),
    ("mes \"There's a palm tree\";", 'mes "Hay una palmera";'),
    ('mes "facing the cool wind.";', 'mes "frente al viento fresco.";'),
    ('mes "The palm tree denies";', 'mes "La palmera rechaza";'),
    ('mes "your greedy hands.";', 'mes "tus manos codiciosas.";'),
    ("mes \"There's a palm tree with fruits and flowers hanging from its branches.\";", 'mes "Hay una palmera con frutas y flores colgando de sus ramas.";'),
    ('mes "Be sure to wear a Safety Helmet while trying to pick the fruit.";', 'mes "Asegurate de usar un Safety Helmet mientras intentas recoger la fruta.";'),
    ("mes \"There's a palm tree.\";", 'mes "Hay una palmera.";'),
    ('mes "You can kick or shake it.";', 'mes "Puedes patearla o sacudirla.";'),
    ('mes "What do you want to do?";', 'mes "Que quieres hacer?";'),
    ('select("Shake the tree:Kick the tree")', 'select("Sacudir el arbol:Patear el arbol")'),
    ('mes "You shake the palm tree.";', 'mes "Sacudes la palmera.";'),
    ('mes "You kick the palm tree swiftly with all you might.";', 'mes "Pateas la palmera rapidamente con toda tu fuerza.";'),
    ('mes "a ^FF0000stone^000000 falls out.";', 'mes "una ^FF0000stone^000000 cae.";'),
    ('mes "a ^FF0000Great Leaf^000000 falls out.";', 'mes "una ^FF0000Great Leaf^000000 cae.";'),
    ('mes "a ^FF0000Worm Peeling^000000 falls out.";', 'mes "un ^FF0000Worm Peeling^000000 cae.";'),
    ('mes "an ^0000FFOil Palm Fruit^000000 falls out.";', 'mes "un ^0000FFOil Palm Fruit^000000 cae.";'),
    ("mes \"something falls on your head, but since you're wearing a Safety Helmet you're safe and sound.\";", 'mes "algo cae en tu cabeza, pero como llevas un Safety Helmet estas sano y salvo.";'),
    ('mes "something smashes down on your head, right where that soft spot is, $#*@! that\'s a one in a million shot.";', 'mes "algo te cae en la cabeza, justo donde esta la parte blanda, $#*@! eso es un tiro en un millon.";'),
    ('mes "tons of ^0000FFOil Palm Fruit^000000 crashes down from the tree.";', 'mes "toneladas de ^0000FFOil Palm Fruit^000000 caen del arbol.";'),
    ('mes "but nothing happens.";', 'mes "pero nada pasa.";'),
    # Gatti - Traditional Weapon
    ('mes "- Hold it right there!! -";', 'mes "- Alto ahi!! -";'),
    ("mes \"- You're carrying too many items and don't have enough inventory space to receive any rewards. -\";", 'mes "- Llevas demasiados objetos y no tienes suficiente espacio en el inventario para recibir recompensas. -";'),
    ('mes "- Please make more inventory space available and come back to take this challenge. -";', 'mes "- Por favor libera mas espacio en el inventario y regresa para tomar este desafio. -";'),
    ('mes "Where in the hell am I? Everybody here is avoiding me.";', 'mes "Donde rayos estoy? Todos aqui me estan evitando.";'),
    ('mes "Hey there, young "+((Sex == SEX_MALE)?"man":"lady")+"~ Are you from around here?";', 'mes "Oye, joven "+((Sex == SEX_MALE)?"hombre":"dama")+"~ Eres de por aqui?";'),
    ("select(\"No, I'm not.\");", 'select("No, no lo soy.");'),
    ("mes \"I'd like to ask\";", 'mes "Me gustaria hacerte";'),
    ('mes "you a question.";', 'mes "una pregunta.";'),
    ('mes "Where is this place?";', 'mes "Donde es este lugar?";'),
    ('mes "- He seems to be asking for the Island name. -";', 'mes "- Parece estar preguntando por el nombre de la Isla. -";'),
    ("mes \"It's called \"+ .@island_name$ +\". What's wrong?\";", 'mes "Se llama "+ .@island_name$ +". Que pasa?";'),
    ("mes \"This is Dewata Island? You're sure this is Dewata Island?\";", 'mes "Esta es Dewata Island? Estas seguro de que es Dewata Island?";'),
    ('mes "Hahahahahahahahaha...!!!";', 'mes "Jajajajajajajaja...!!!";'),
    ('mes "- The old man started to laugh like a crazy person after hearing the name of the Island. You decide to ask a little bit later. -";', 'mes "- El viejo comenzo a reirse como loco despues de escuchar el nombre de la Isla. Decides preguntar mas tarde. -";'),
    ('mes "Is that so... "+ .@island_name$ +"? "+ .@island_name$ +"... "+ .@island_name$ +"... "+ .@island_name$ +"...";', 'mes "Es asi... "+ .@island_name$ +"? "+ .@island_name$ +"... "+ .@island_name$ +"... "+ .@island_name$ +"...";'),
    ('mes "- The old man gave a deep sigh of resignation and continued speaking. -";', 'mes "- El viejo dio un profundo suspiro de resignacion y continuo hablando. -";'),
    ("mes \"Damn... My plan is ruined. I invested all my fortunes to get there, but I failed. I can't do anything now, my boat has been wrecked.\";", 'mes "Rayos... Mi plan esta arruinado. Inverti toda mi fortuna para llegar ahi, pero falle. No puedo hacer nada ahora, mi barco fue destruido.";'),
    ('mes "- The old man starts to cry. -";', 'mes "- El viejo comienza a llorar. -";'),
    ('mes "- Feeling awkward, you quickly leave. -";', 'mes "- Sintiendote incomodo, te vas rapidamente. -";'),
    ('select("Well... Sir...");', 'select("Bueno... Senor...");'),
    ('mes "Cough... cough...";', 'mes "Cof... cof...";'),
    ('mes "Oh... Sorry~ Sorry. I was so happy that I finally arrived at Dewata Island.";', 'mes "Oh... Perdon~ Perdon. Estaba tan feliz de que finalmente llegue a Dewata Island.";'),
    ('mes "This is not a short story. Oh! I have to introduce myself first. I am Mastersmith Gatti, also an Adventurer.";', 'mes "Esta no es una historia corta. Oh! Primero debo presentarme. Soy el Herrero Maestro Gatti, tambien un Aventurero.";'),
    ("mes \"I found a mysterious Weapon blueprint, but I don't remember exactly when I acquired it.\";", 'mes "Encontre un misterioso plano de Arma, pero no recuerdo exactamente cuando lo consegui.";'),
    ('mes "Weapon Blueprint?";', 'mes "Plano de Arma?";'),
    ('mes "Yes! I traveled all around to find the materials for the weapon, but...";', 'mes "Si! Viaje por todos lados para encontrar los materiales para el arma, pero...";'),
    ('mes "But?";', 'mes "Pero?";'),
    ("mes \"I couldn't find the last material anywhere.\";", 'mes "No pude encontrar el ultimo material en ningun lado.";'),
    ('mes "I was about to give up, but there was some fine print on the blueprint saying that it could be found on the Dewata Island.";', 'mes "Estaba a punto de rendirme, pero habia unas letras pequenas en el plano diciendo que se podia encontrar en Dewata Island.";'),
    ("mes \"I don't know why somebody put such an important thing in fine print. Anyway, after reading that, I invested all my fortunes to find that Island.\";", 'mes "No se por que alguien puso algo tan importante en letra chica. En fin, despues de leer eso, inverti toda mi fortuna para encontrar esa Isla.";'),
    ('mes "Oh... Is that so?";', 'mes "Oh... Es asi?";'),
    ('mes "This island is strange. I arrived here a week ago, and everybody here has been avoiding me.";', 'mes "Esta isla es extrana. Llegue aqui hace una semana, y todos aqui me han estado evitando.";'),
    ('mes "Last week was so hard, but you saved me by telling me this is Dewata Island.";', 'mes "La semana pasada fue tan dificil, pero me salvaste al decirme que esta es Dewata Island.";'),
    ('mes "Thank you for telling me, and thank you for passing here at just the right time.";', 'mes "Gracias por decirme, y gracias por pasar aqui justo en el momento correcto.";'),
    ('mes "Uh... No problem.";', 'mes "Eh... No hay problema.";'),
    ("mes \"Well... There was a little problem of my ship getting wrecked, but that's neither here nor there.\";", 'mes "Bueno... Hubo un pequeno problema con mi barco siendo destruido, pero eso es otra cosa.";'),
    ('mes "Now that I found out this is Dewata Island, I should find the material for this great weapon.";', 'mes "Ahora que descubri que esta es Dewata Island, deberia encontrar el material para esta gran arma.";'),
    ('mes "Ah! the material that I am looking for is Comodo Leather.";', 'mes "Ah! El material que estoy buscando es Comodo Leather.";'),
    ('mes "Comodo Leather?";', 'mes "Comodo Leather?";'),
    ("mes \"Yes. In the blueprint, it's written that only the recognized few of the Dewata Natives are worthy enough to fight against the Comodo Dragon.\";", 'mes "Si. En el plano, esta escrito que solo los pocos reconocidos de los Nativos de Dewata son dignos de pelear contra el Comodo Dragon.";'),
    ("mes \"In order to fight the Comodo Dragon, you have to get recognized by the natives. I assume it'll be hard to get the recognition.\";", 'mes "Para pelear contra el Comodo Dragon, tienes que ser reconocido por los nativos. Supongo que sera dificil obtener el reconocimiento.";'),
    ('mes "Of course, it must be...";', 'mes "Por supuesto, debe ser...";'),
    ("mes \"Let me ask you a favor. If you get the recognition first, please don't forget to visit me.\";", 'mes "Dejame pedirte un favor. Si obtienes el reconocimiento primero, por favor no olvides visitarme.";'),
    ('mes "Lady, you possess a strong energy.";', 'mes "Dama, posees una energia fuerte.";'),
    ('mes "You possess a strong energy.";', 'mes "Posees una energia fuerte.";'),
    ('mes "Have you seen a monster called a Comodo Dragon on this Island?";', 'mes "Has visto un monstruo llamado Comodo Dragon en esta Isla?";'),
    ('select("Yes, I have.");', 'select("Si, lo he visto.");'),
    ('mes "Oh! Really?";', 'mes "Oh! En serio?";'),
    ("mes \"I'm so lucky to have met you. This is going so well.\";", 'mes "Que suerte haberte conocido. Esto va muy bien.";'),
    ('mes "Would you please help me?";', 'mes "Me ayudarias por favor?";'),
    ('mes "The weapon material that I was looking for is ^0000FFComodo Leather^000000. Bring me 100 of them, and I will make you a fancy weapon.";', 'mes "El material de arma que buscaba es ^0000FFComodo Leather^000000. Traeme 100 y te hare un arma elegante.";'),
    ('mes "I heard Comodo Dragons are very powerful monsters. Please be careful.";', 'mes "Escuche que los Comodo Dragons son monstruos muy poderosos. Ten cuidado por favor.";'),
    ('mes "Did you get recognized by the natives?";', 'mes "Fuiste reconocido por los nativos?";'),
    ("mes \"I guess not yet. I'm asking around everywhere, but I couldn't find a way to get recognized from natives. I don't know when I could finish making this weapon.\";", 'mes "Supongo que aun no. Estoy preguntando por todas partes, pero no pude encontrar la forma de ser reconocido por los nativos. No se cuando podre terminar de hacer esta arma.";'),
    ("mes \"If you get the recognition before me, please DON'T forget to visit me.\";", 'mes "Si obtienes el reconocimiento antes que yo, por favor NO olvides visitarme.";'),
    ('mes "So, did you get recognized by the natives?";', 'mes "Entonces, fuiste reconocido por los nativos?";'),
    ('mes "Oh yes! Finally.";', 'mes "Oh si! Por fin.";'),
    ('mes "Lady, you also possess a strong energy.";', 'mes "Dama, tu tambien posees una energia fuerte.";'),
    ('mes "You also possess a strong energy.";', 'mes "Tu tambien posees una energia fuerte.";'),
    ('mes "Did you finally get the recognition from natives?";', 'mes "Finalmente obtuviste el reconocimiento de los nativos?";'),
    ('select("Yes.");', 'select("Si.");'),
    ('mes "Oh! Just as I expected!";', 'mes "Oh! Justo como esperaba!";'),
    ('mes "I was so lucky to meet you. Everything is going so well.";', 'mes "Tuve tanta suerte de conocerte. Todo va muy bien.";'),
    ('mes "I know I have no right to ask you for this, but meeting like this is a destiny...";', 'mes "Se que no tengo derecho a pedirte esto, pero encontrarnos asi es destino...";'),
    ('mes "- Gatti mumbles. -";', 'mes "- Gatti murmura. -";'),
    ('mes "The weapon material that I so longed for is ^0000FFComodo Leather^000000. Please get me 100 of them.";', 'mes "El material de arma que tanto anhelaba es ^0000FFComodo Leather^000000. Por favor consigueme 100.";'),
    ("mes \"I'm so eager to make the weapon in the weapon blueprint.\";", 'mes "Estoy tan ansioso por hacer el arma del plano.";'),
    ('mes "Please, before my passion fades out.";', 'mes "Por favor, antes de que mi pasion se desvanezca.";'),
    ('mes "Oh! And Comodo Dragon is a very powerful monster, so please be careful.";', 'mes "Oh! Y el Comodo Dragon es un monstruo muy poderoso, asi que ten cuidado por favor.";'),
    ('mes "By the looks of your walk, you must have brought me 100 Comodo Leather. Hand it over to me.";', 'mes "Por tu forma de caminar, debes haberme traido 100 Comodo Leather. Damalos.";'),
    ('mes "- Gatti takes the Comodo Leather from you. -";', 'mes "- Gatti toma el Comodo Leather de ti. -";'),
    ('mes "So, that is the Comodo Leather. But not enough.";', 'mes "Entonces, ese es el Comodo Leather. Pero no es suficiente.";'),
    ("mes \"I know I'm asking you a favor, but I need 100 of them.\";", 'mes "Se que te estoy pidiendo un favor, pero necesito 100.";'),
    ("mes \"Please be careful because Comodo Dragon is very powerful monster. And don't forget to bring me 100 Comodo Leather on your way back.\";", 'mes "Ten cuidado porque el Comodo Dragon es un monstruo muy poderoso. Y no olvides traerme 100 Comodo Leather de regreso.";'),
    ('mes "Oh~ Look at this. How resilient... So soft.";', 'mes "Oh~ Mira esto. Que resistente... Tan suave.";'),
    ('mes "Comodo Leather is the best material ever.";', 'mes "Comodo Leather es el mejor material de todos.";'),
    ('mes "Yes, how should I process this?";', 'mes "Si, como deberia procesar esto?";'),
    ('mes "Hmm... Like this?";', 'mes "Hmm... Asi?";'),
    ('mes "Or like that? Yes! This is the way!";', 'mes "O asi? Si! Este es el camino!";'),
    ('mes "- Mastersmith Gatti is enjoying to process the Leathers you\'ve brought to make the weapon. -";', 'mes "- El Herrero Maestro Gatti esta disfrutando procesar los Cueros que trajiste para hacer el arma. -";'),
    ('mes "- You should wait a little while. -";', 'mes "- Deberias esperar un poco. -";'),
    ('mes "Well... Gatti?";', 'mes "Bueno... Gatti?";'),
    ('mes "Oh! Sorry, sorry! This leather is so interesting.";', 'mes "Oh! Perdon, perdon! Este cuero es tan interesante.";'),
    ('mes "I made a hilt out of the leather you brought me.";', 'mes "Hice una empunadura con el cuero que me trajiste.";'),
    ('mes "Hilt?";', 'mes "Empunadura?";'),
    ("mes \"You don't know what a hilt is? That's what you call the handle of a weapon.\";", 'mes "No sabes que es una empunadura? Asi se llama el mango de un arma.";'),
    ('mes "- Gatti shows a thing that looks like a handle of a weapon. -";', 'mes "- Gatti muestra algo que parece el mango de un arma. -";'),
    ("mes \"I tried making it like what's written in the blueprint, but I need more material.\";", 'mes "Trate de hacerlo como dice el plano, pero necesito mas material.";'),
    ('mes "Really?";', 'mes "En serio?";'),
    ('mes "Yes... To be frank with you, I ruined a lot of them trying different things.";', 'mes "Si... Para ser sincero, arruine muchos intentando diferentes cosas.";'),
    ('mes "I know this is a lot to ask, but can you get me 100 more Comodo Leather, 20 Steel, and 10 Oridecon?";', 'mes "Se que es mucho pedir, pero puedes conseguirme 100 Comodo Leather mas, 20 Steel y 10 Oridecon?";'),
    ("mes \"I'll make you a best weapon ever.\";", 'mes "Te hare la mejor arma de todas.";'),
    ("mes \"Oh! I almost forgot. Don't forget to bring the hilt that I just made you.\";", 'mes "Oh! Casi lo olvido. No olvides traer la empunadura que te acabo de hacer.";'),
    ('mes "A weapon must have a handle.";', 'mes "Un arma debe tener un mango.";'),
    ('mes "You brought all the material already?";', 'mes "Ya trajiste todo el material?";'),
    ('mes "You were also curious about the finished weapon? Haha.";', 'mes "Tu tambien tenias curiosidad por el arma terminada? Jaja.";'),
    ("mes \"Hmm... I need more of those. If my ship didn't get wrecked, I could made it on my own, but...\";", 'mes "Hmm... Necesito mas de eso. Si mi barco no se hubiera destruido, podria haberlo hecho yo solo, pero...";'),
    ('mes "- Gatti mumbles to himself. -";', 'mes "- Gatti murmura para si mismo. -";'),
    ('mes "100 Comodo Leather, 20 Steel, and 10 Oridecon are what I need.";', 'mes "100 Comodo Leather, 20 Steel y 10 Oridecon es lo que necesito.";'),
    ("mes \"If you bring them all, I'll make the best weapon ever.\";", 'mes "Si los traes todos, hare la mejor arma de todas.";'),
    ('mes "Great! We have enough. Wait a little.";', 'mes "Genial! Tenemos suficiente. Espera un poco.";'),
    ('mes "I finished making the weapon. This is called Caress according to the blueprint.";', 'mes "Termine de hacer el arma. Se llama Caress segun el plano.";'),
    ('mes "I keep finding new stuffs when I lay my eyes on this blueprint.";', 'mes "Sigo encontrando cosas nuevas cuando miro este plano.";'),
    ('mes "Now, I learned how to make the weapon, ask me any time if you need it.";', 'mes "Ahora, aprendi como hacer el arma, pideme cuando quieras si la necesitas.";'),
    ("mes \"You're \"+strcharinfo(0)+\",\";", 'mes "Tu eres "+strcharinfo(0)+",";'),
    ("mes \"So, how's the Caress that I made you?\";", 'mes "Entonces, que tal el Caress que te hice?";'),
    ("select(\"It's great!:I need another Caress.:Can I make it stronger?\")", 'select("Esta genial!:Necesito otro Caress.:Puedo hacerlo mas fuerte?")'),
    ("mes \"Yes, yes of course it's great.\";", 'mes "Si, si por supuesto que esta genial.";'),
    ('mes "I made that weapon so it should be good.";', 'mes "Yo hice esa arma asi que deberia ser buena.";'),
    ("mes \"You only have a Hilt. You'll need to bring me 10 Oridecon, 20 Steel, and 70 Comodo Leather.\";", 'mes "Solo tienes una empunadura. Necesitaras traerme 10 Oridecon, 20 Steel y 70 Comodo Leather.";'),
    ("mes \"If you bring them, I'll make a brand new Caress.\";", 'mes "Si los traes, te hare un Caress nuevo.";'),
    ('mes "You have all the materials. Wait just a little.";', 'mes "Tienes todos los materiales. Espera un momentito.";'),
    ('mes "Here is the Caress! Ask me any time.";', 'mes "Aqui esta el Caress! Pideme cuando quieras.";'),
    ('mes "You want me to make one more Caress for you? In that case I need a Hilt. 50 Comodo Leather, and 1 Log. These are what I need to make a Hilt.";', 'mes "Quieres que haga otro Caress para ti? En ese caso necesito una empunadura. 50 Comodo Leather y 1 Log. Eso es lo que necesito para hacer una empunadura.";'),
    ("mes \"You brought the material for the Hilt. I'll make it right away.\";", 'mes "Trajiste el material para la empunadura. Lo hare enseguida.";'),
    ('mes "Put this here, and process it like this...";', 'mes "Pon esto aqui, y procesalo asi...";'),
    ("mes \"Here you go. I can make a Caress if you bring me 10 Oridecon, 20 Steel, and 70 Comodo Leather.\";", 'mes "Aqui tienes. Puedo hacer un Caress si me traes 10 Oridecon, 20 Steel y 70 Comodo Leather.";'),
    ("mes \"So, you want to reinforce your weapon? The weapon gets broken from time to time during the process, but it doesn't happen that often.\";", 'mes "Entonces, quieres reforzar tu arma? El arma se rompe de vez en cuando durante el proceso, pero no pasa tan seguido.";'),
    ('select("Please reinforce the weapon.:May be next time.")', 'select("Por favor refuerza el arma.:Quizas la proxima vez.")'),
    ('mes "Whenever you want to reinforce the Caress, just bring me the Caress and 100,000 zeny.";', 'mes "Cuando quieras reforzar el Caress, solo traeme el Caress y 100,000 zeny.";'),
    ("mes \"If you want to do it, I'll have to tell you some cautionary things before reinforcing the Caress.\";", 'mes "Si quieres hacerlo, tendre que decirte algunas precauciones antes de reforzar el Caress.";'),
    ('mes "^FF0000First!^009977 I need 1 Caress and 100,000 zeny to reinforce the Caress. As you know, I don\'t have any money right now because my ship got wrecked.^000000";', 'mes "^FF0000Primero!^009977 Necesito 1 Caress y 100,000 zeny para reforzar el Caress. Como sabes, no tengo dinero ahora porque mi barco fue destruido.^000000";'),
    ("mes \"^FF0000Second!^009977 If you have a Caress that is refined or inserted with cards in your inventory which you don't want to reinforce, it could get destroyed or it's upgrades can get changed during the reinforcing process.\";", 'mes "^FF0000Segundo!^009977 Si tienes un Caress refinado o con cartas en tu inventario que no quieras reforzar, podria destruirse o sus mejoras pueden cambiar durante el proceso de refuerzo.";'),
    ("mes \"If you don't want that to happen, put the refined Caress elsewhere before the reinforcing.^000000\";", 'mes "Si no quieres que eso pase, pon el Caress refinado en otro lugar antes del refuerzo.^000000";'),
    ('mes "^FF0000Third!^009977 Sometimes reinforcing fails. The weapon doesn\'t get destroyed every time you fail. However you should know that the weapon gets destroyed from time to time if you fail.^000000";', 'mes "^FF0000Tercero!^009977 A veces el refuerzo falla. El arma no se destruye cada vez que fallas. Sin embargo debes saber que el arma se destruye de vez en cuando si fallas.^000000";'),
    ('select("Please reinforce the weapon.:Maybe next time.")', 'select("Por favor refuerza el arma.:Quizas la proxima vez.")'),
    ("mes \"You don't have all the materials. It's impossible to reinforce if you don't have them all. If you want to reinforce, bring 100,000 zeny and 1 Caress.\";", 'mes "No tienes todos los materiales. Es imposible reforzar si no los tienes todos. Si quieres reforzar, trae 100,000 zeny y 1 Caress.";'),
    ('mes "Oh my~~ Almost succeeded... But failed. Sorry, sorry...";', 'mes "Ay~~ Casi lo logro... Pero fallo. Perdon, perdon...";'),
    ('mes "Reinforcing the Caress has been successful. See you later.";', 'mes "El refuerzo del Caress fue exitoso. Nos vemos.";'),
    ('mes "... ... ... ...";', 'mes "... ... ... ...";'),
    ('mes "... .... ...";', 'mes "... .... ...";'),
    ('mes ".... .... .... ....";', 'mes ".... .... .... ....";'),
    ('mes ".... .... ....";', 'mes ".... .... ....";'),
    ('mes "... ... ... ... ...";', 'mes "... ... ... ... ...";'),
    ('mes "... ... ...";', 'mes "... ... ...";'),
    ('mes "... ...";', 'mes "... ...";'),
    ('mes "... ... ... ...";', 'mes "... ... ... ...";'),
    ('mes "- There is error in the quest. -";', 'mes "- Hay un error en la quest. -";'),
    ('mes "- Memo is making an ark. -";', 'mes "- Memo esta haciendo un ark. -";'),
    ('mes "Who are you?";', 'mes "Quien eres?";'),
]

for old, new in R:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Dewata translation done')
