import sys

filepath = sys.argv[1]
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    # bioeth == 10
    ('mes "^333333*Sigh*^000000";', 'mes "^333333*Suspiro*^000000";'),
    ("mes \"I'm so confused...\";", 'mes "Estoy tan confundido...";'),
    ("mes \"There's no denying that\";", 'mes "No se puede negar que";'),
    ('mes "everything you said is right.";', 'mes "todo lo que dijiste es correcto.";'),
    ("mes \"But now I don't know what\";", 'mes "Pero ahora no se que";'),
    ('mes "I should believe...";', 'mes "deberia creer...";'),
    # bioeth == 9
    ('mes "Have you come to";', 'mes "Has venido a";'),
    ('mes "ask me again to teach";', 'mes "pedirme otra vez que te ensene";'),
    ('mes "you Homunculus skills?";', 'mes "habilidades de Homunculus?";'),
    ("mes \"You're awfully persistent,\";", 'mes "Eres terriblemente persistente,";'),
    ('mes "but I suppose that might be";', 'mes "pero supongo que asi fue";'),
    ('mes "how you became an Alchemist...";', 'mes "como te convertiste en Alchemist...";'),
    ('mes "Well, I sort of came";', 'mes "Bueno, algo asi vine";'),
    ('mes "here to ask about that.";', 'mes "a preguntar sobre eso.";'),
    ('mes "But first, I heard a rumor";', 'mes "Pero primero, escuche un rumor";'),
    ('mes "that your son was really";', 'mes "de que tu hijo estuvo muy";'),
    ('mes "sick for a while...";', 'mes "enfermo por un tiempo...";'),
    ("mes \"Y-yes. It's really\";", 'mes "S-si. Es realmente";'),
    ('mes "difficult for me to";', 'mes "dificil para mi";'),
    ('mes "talk about that time.";', 'mes "hablar de ese tiempo.";'),
    ('mes "The thought of losing";', 'mes "El pensamiento de perder";'),
    ('mes "my boy is too much to bear.";', 'mes "a mi hijo es demasiado.";'),
    ('mes "He means the world to me...";', 'mes "El significa el mundo para mi...";'),
    ('mes "I was so desperate to";', 'mes "Estaba tan desesperado por";'),
    ('mes "keep my boy alive that";', 'mes "mantener a mi hijo con vida que";'),
    ('mes "I would have sold my soul";', 'mes "hubiera vendido mi alma";'),
    ("mes \"without any regret. I'm more\";", 'mes "sin ningun arrepentimiento. Estoy mas";'),
    ('mes "than willing to sacrifice my";', 'mes "que dispuesto a sacrificar mi";'),
    ('mes "own life for his sake.";', 'mes "propia vida por su bien.";'),
    ('mes "Luckily, my son";', 'mes "Afortunadamente, mi hijo";'),
    ('mes "recovered from his";', 'mes "se recupero de su";'),
    ('mes "disease and he is very";', 'mes "enfermedad y esta muy";'),
    ('mes "healthy nowadays. But";', 'mes "saludable hoy en dia. Pero";'),
    ('mes "why are you reminding";', 'mes "por que me estas recordando";'),
    ('mes "me of something like this?";', 'mes "algo como esto?";'),
    ("mes \"You're right that the creation\";", 'mes "Tienes razon en que la creacion";'),
    ('mes "of Homunculi brings up a moral";', 'mes "de Homunculi plantea un problema";'),
    ('mes "issue. But instead of morals,";', 'mes "moral. Pero en vez de moralidad,";'),
    ('mes "I want to appeal to your sense";', 'mes "quiero apelar a tu sentido";'),
    ('mes "of humanitarianism if I can.";', 'mes "humanitario si puedo.";'),
    ("mes \"I don't follow.\";", 'mes "No entiendo.";'),
    ('mes "What exactly";', 'mes "Que exactamente";'),
    ('mes "do you mean by";', 'mes "quieres decir con";'),
    ('mes "humanitarianism?";', 'mes "humanitarismo?";'),
    ('mes "I believe that the";', 'mes "Creo que el";'),
    ('mes "study of Homunculi";', 'mes "estudio de Homunculi";'),
    ('mes "could help us discover";', 'mes "podria ayudarnos a descubrir";'),
    ('mes "the secret of life. There";', 'mes "el secreto de la vida. Hay";'),
    ('mes "is just too much";', 'mes "demasiado";'),
    ('mes "potential to do good to ignore.";', 'mes "potencial para hacer el bien como para ignorarlo.";'),
    ("mes \"I'm not interested in\";", 'mes "No estoy interesado en";'),
    ('mes "creating new creatures or";', 'mes "crear nuevas criaturas o";'),
    ('mes "playing God. What I do want";', 'mes "jugar a ser Dios. Lo que quiero";'),
    ('mes "is the knowledge to cure people";', 'mes "es el conocimiento para curar a la gente";'),
    ('mes "regardless of the disease. No";', 'mes "sin importar la enfermedad. No";'),
    ('mes "matter how desperate it may be.";', 'mes "importa cuan desesperada sea.";'),
    ('mes "It may be immoral to";', 'mes "Puede ser inmoral";'),
    ('mes "create experimental life";', 'mes "crear formas de vida";'),
    ('mes "forms and to sacrifice them,";', 'mes "experimentales y sacrificarlas,";'),
    ("mes \"but I'm willing to do that for\";", 'mes "pero estoy dispuesto a hacerlo por";'),
    ('mes "the people who may need";', 'mes "las personas que puedan necesitar";'),
    ('mes "that cure I might discover...";', 'mes "esa cura que podria descubrir...";'),
    ('mes "When your son was";', 'mes "Cuando tu hijo estaba";'),
    ('mes "sick, you were willing";', 'mes "enfermo, estabas dispuesto";'),
    ('mes "to make sacrifices to see";', 'mes "a hacer sacrificios para ver";'),
    ('mes "that he recover. But still,";', 'mes "que se recuperara. Pero aun asi,";'),
    ('mes "there are other people in the";', 'mes "hay otras personas en el";'),
    ('mes "world with worse ailments...";', 'mes "mundo con peores males...";'),
    ('mes "I want to study";', 'mes "Quiero estudiar";'),
    ('mes "Homunculi because";', 'mes "Homunculi porque";'),
    ("mes \"there's a chance that\";", 'mes "hay una posibilidad de que";'),
    ('mes "I might be able to bring";', 'mes "pueda llevar";'),
    ("mes \"hope to someone's\";", 'mes "esperanza a la situacion";'),
    ('mes "hopeless situation...";', 'mes "desesperada de alguien...";'),
    ("mes \"I've never...\";", 'mes "Yo nunca...";'),
    ('mes "I never thought...";', 'mes "Nunca pense...";'),
    ("mes \"I'm sorry. I need\";", 'mes "Lo siento. Necesito";'),
    ('mes "some time alone...";', 'mes "un tiempo a solas...";'),
    # bioeth == 8
    ('mes "Although I admit that";', 'mes "Aunque admito que";'),
    ("mes \"you're capabile of learning\";", 'mes "eres capaz de aprender";'),
    ('mes "what I might be able to teach";', 'mes "lo que podria ensenarte";'),
    ("mes \"you about Homunculi, I can't\";", 'mes "sobre Homunculi, no puedo";'),
    ("mes \"in good conscience do it. I'm\";", 'mes "en buena conciencia hacerlo.";'),
    ('mes "sorry, but please give up.";', 'mes "Lo siento, pero por favor desiste.";'),
    # bioeth == 7
    ('mes "How many times must I tell";', 'mes "Cuantas veces debo decirte?";'),
    ("mes \"you? I'm sorry, but I can't teach you anything related to Homunculi.\";", 'mes "Lo siento, pero no puedo ensenarte nada relacionado con Homunculi.";'),
    ('mes "It especially bothers me that you know nothing at all about them...";', 'mes "Me molesta especialmente que no sepas nada en absoluto sobre ellos...";'),
    ('mes "But while I was gone,";', 'mes "Pero mientras estuve fuera,";'),
    ('mes "I spent so much time";', 'mes "pase mucho tiempo";'),
    ('mes "studying about Homunculi";', 'mes "estudiando sobre Homunculi";'),
    ('mes "from these Alchemy experts.";', 'mes "con estos expertos en Alquimia.";'),
    ("mes \"I guarantee that I'm qualified\";", 'mes "Te garantizo que estoy calificado";'),
    ('mes "to learn the fundamentals!";', 'mes "para aprender los fundamentos!";'),
    ('mes "Experts...? Ah, you mean";', 'mes "Expertos...? Ah, te refieres a";'),
    ('mes "Skrajjad, Keshibien and";', 'mes "Skrajjad, Keshibien y";'),
    ('mes "Broncher. My old colleages.";', 'mes "Broncher. Mis viejos colegas.";'),
    ("mes \"Alright. But I'll be the judge\";", 'mes "Bien. Pero yo sere el juez";'),
    ('mes "of whether or not you learned";', 'mes "de si aprendiste o no";'),
    ('mes "anything about Homunculi.";', 'mes "algo sobre Homunculi.";'),
    ("mes \"I'm going to give you\";", 'mes "Te voy a hacer";'),
    ('mes "several questions, so";', 'mes "varias preguntas, asi que";'),
    ('mes "I hope you answer all";', 'mes "espero que respondas todas";'),
    ('mes "of these correctly.";', 'mes "correctamente.";'),
    ('mes "Are you ready?";', 'mes "Estas listo?";'),
    ('mes "First question.";', 'mes "Primera pregunta.";'),
    ('mes "What skill, mastered";', 'mes "Que habilidad, dominada";'),
    ('mes "at Skill Level 1, allows";', 'mes "en Skill Level 1, permite";'),
    ('mes "the caster to retreat a";', 'mes "al usuario retirar a un";'),
    ('mes "Homunculus, putting it in";', 'mes "Homunculus, poniendolo en";'),
    ('mes "an inert state of hibernation?";', 'mes "un estado inerte de hibernacion?";'),
    ('mes "Hmm, not bad. So you\'ve";', 'mes "Hmm, nada mal. Asi que has";'),
    ('mes "been studying. Now, the second";', 'mes "estado estudiando. Ahora, la segunda";'),
    ('mes "question. What is the item, whose name indicates a very early stage";', 'mes "pregunta. Cual es el objeto, cuyo nombre indica una etapa muy temprana";'),
    ('mes "of Homunculus development, used for the Call Homunculus skill?";', 'mes "del desarrollo de Homunculus, usado para la habilidad Call Homunculus?";'),
    ('mes "Huh. You got that one";', 'mes "Huh. Esa tambien la";'),
    ('mes "right too. Alright, third";', 'mes "respondiste bien. Bien, tercera";'),
    ('mes "question. What is the";', 'mes "pregunta. Cual es el";'),
    ('mes "name of the skill, mastered";', 'mes "nombre de la habilidad, dominada";'),
    ('mes "at Skill Level 5, which allows";', 'mes "en Skill Level 5, que te permite";'),
    ('mes "you to resurrect Homunculi?";', 'mes "resucitar Homunculi?";'),
    ('mes "So you have been putting";', 'mes "Asi que has estado poniendo";'),
    ('mes "a lot of effort in studying";', 'mes "mucho esfuerzo en estudiar";'),
    ('mes "this. I really admire your";', 'mes "esto. Realmente admiro tu";'),
    ('mes "dedication and it looks like";', 'mes "dedicacion y parece que";'),
    ("mes \"you've got the potential to\";", 'mes "tienes el potencial para";'),
    ('mes "be a really great Alchemist.";', 'mes "ser un gran Alchemist.";'),
    ("mes \"Still, even though you're\";", 'mes "Aun asi, aunque estes";'),
    ('mes "qualified to learn all the";', 'mes "calificado para aprender todas las";'),
    ('mes "Homunculus skills, I choose";', 'mes "habilidades de Homunculus, elijo";'),
    ('mes "not to teach them based on";', 'mes "no ensenarlas basado en";'),
    ('mes "my own personal principles.";', 'mes "mis propios principios personales.";'),
    ('mes "Nothing can change my mind.";', 'mes "Nada puede cambiar mi opinion.";'),
    ("mes \"I admit that I'm proud\";", 'mes "Admito que estoy orgulloso";'),
    ("mes \"of the progress you've\";", 'mes "del progreso que has";'),
    ("mes \"made, but I just can't\";", 'mes "hecho, pero simplemente no puedo";'),
    ('mes "bring myself to be a part";', 'mes "obligarme a ser parte";'),
    ('mes "of what I believe to be an";', 'mes "de lo que creo que es un";'),
    ('mes "abuse of the gift of life.";', 'mes "abuso del regalo de la vida.";'),
    ("mes \"There's just so much\";", 'mes "Hay demasiado";'),
    ("mes \"risk! I don't think I can\";", 'mes "riesgo! No creo que pueda";'),
    ('mes "bear to be responsible for";', 'mes "soportar ser responsable de";'),
    ('mes "any of the consequences that";', 'mes "cualquiera de las consecuencias que";'),
    ('mes "may come with the existence";', 'mes "puedan venir con la existencia";'),
    ('mes "of artificially created life.";', 'mes "de vida creada artificialmente.";'),
    # Failed answers
    ("mes \"I'm disappointed...\";", 'mes "Estoy decepcionado...";'),
    ('mes "I really thought you";', 'mes "Realmente pense que";'),
    ('mes "had learned everything";', 'mes "habias aprendido todo";'),
    ('mes "you could about Homunculi,";', 'mes "lo posible sobre Homunculi,";'),
    ('mes "but it looks like there are a";', 'mes "pero parece que hay algunos";'),
    ('mes "few gaps in your knowledge.";', 'mes "vacios en tu conocimiento.";'),
    ("mes \"Hmm... It looks like\";", 'mes "Hmm... Parece que";'),
    ("mes \"you still haven't learned\";", 'mes "aun no has aprendido";'),
    ('mes "enough about Homunculi.";', 'mes "suficiente sobre Homunculi.";'),
    ('mes "Even if I wanted to teach";', 'mes "Aunque quisiera ensenarte,";'),
    ("mes \"you, it looks like you're\";", 'mes "parece que aun no";'),
    ('mes "not quite ready to learn...";', 'mes "estas listo para aprender...";'),
    ("mes \"You'd be able to get\";", 'mes "Podrias responder";'),
    ('mes "the first question right";', 'mes "la primera pregunta bien";'),
    ('mes "if you were really serious";', 'mes "si realmente estuvieras serio";'),
    ('mes "about studying Homunculi.";', 'mes "sobre estudiar Homunculi.";'),
    ("mes \"You'd better just give up and\";", 'mes "Mejor rindete y";'),
    ('mes "find a new alchemic interest.";', 'mes "busca un nuevo interes alquimico.";'),
    # bioeth > 3
    ("mes \"I'm sorry, but\";", 'mes "Lo siento, pero";'),
    ('mes "I refuse to teach";', 'mes "me niego a ensenarte";'),
    ('mes "you anything related";', 'mes "nada relacionado";'),
    ('mes "to the Homunculus skills.";', 'mes "con las habilidades de Homunculus.";'),
    ('mes "I should feel insulted that";', 'mes "Deberia sentirme insultado de que";'),
    ('mes "you asked me, but once there";', 'mes "me lo pidieras, pero hubo un";'),
    ('mes "was a time when I was more";', 'mes "tiempo en que yo era mas";'),
    ('mes "like you, so I can understand";', 'mes "como tu, asi que puedo entender";'),
    ('mes "how you feel. However, my";', 'mes "como te sientes. Sin embargo, mis";'),
    ('mes "views are much different now...";', 'mes "puntos de vista son muy diferentes ahora...";'),
    # bioeth == 3
    ('mes "Oh, hello, what";', 'mes "Oh, hola, que";'),
    ('mes "brings you this way?";', 'mes "te trae por aqui?";'),
    ('mes "As your senior in the";', 'mes "Como tu superior en el";'),
    ('mes "field of Alchemy, I can";', 'mes "campo de la Alquimia, puedo";'),
    ("mes \"give you some advice if you're stumped by a particular problem...\";", 'mes "darte algunos consejos si estas atascado con algun problema en particular...";'),
    ('select("Teach me the Homunculus Skills.:No, nothing.")', 'select("Ensename las habilidades de Homunculus.:No, nada.")'),
    ('mes "I want you to";', 'mes "Quiero que me";'),
    ('mes "teach me how to";', 'mes "ensenes como";'),
    ('mes "create a Homunculus.";', 'mes "crear un Homunculus.";'),
    ('mes "...";', 'mes "...";'),
    ('mes "Come again?";', 'mes "Como dijiste?";'),
    ("mes \"I don't think I heard\";", 'mes "No creo haber escuchado";'),
    ('mes "what you said quite right.";', 'mes "bien lo que dijiste.";'),
    ('mes "I said...";', 'mes "Dije...";'),
    ('mes "I want you to";', 'mes "Quiero que me";'),
    ('mes "teach me the skills";', 'mes "ensenes las habilidades";'),
    ('mes "for Homunculus creation.";', 'mes "para la creacion de Homunculus.";'),
    ('mes "After all of my talk...";', 'mes "Despues de todo lo que dije...";'),
    ('mes "My warnings about knowledge";', 'mes "Mis advertencias sobre conocimiento";'),
    ('mes "that should be forbidden to";', 'mes "que deberia ser prohibido para";'),
    ('mes "Alchemists, you want to go";', 'mes "los Alchemists, quieres ir";'),
    ('mes "and create a Homunculus?!";', 'mes "y crear un Homunculus?!";'),
    ('mes "Perhaps I never should";', 'mes "Quizas nunca deberia";'),
    ("mes \"have mentioned that subject.\";", 'mes "haber mencionado ese tema.";'),
    ("mes \"But I still don't understand why you would suddenly want to \";", 'mes "Pero aun no entiendo por que de repente querrias ";'),
    ("mes \"learn those skills. Yes, it's\";", 'mes "aprender esas habilidades. Si, es";'),
    ('mes "true that I could teach you...";', 'mes "cierto que podria ensenarte...";'),
    ('mes "But I refuse to pass down";', 'mes "Pero me niego a transmitir";'),
    ('mes "my knowledge of Homunculi";', 'mes "mi conocimiento de Homunculi";'),
    ('mes "to anyone for any reason.";', 'mes "a nadie por ninguna razon.";'),
    ('mes "Surely, you must know that";', 'mes "Seguramente, ya debes saber eso";'),
    ("mes \"by now. I'm stupefied that you\";", 'mes "a estas alturas. Estoy atonito de que";'),
    ('mes "even had the audacity to ask!";', 'mes "hayas tenido la audacia de preguntar!";'),
    ('mes "No? Well, I suppose";', 'mes "No? Bueno, supongo que";'),
    ('mes "learning something on";', 'mes "aprender algo por";'),
    ("mes \"your own is good, but\";", 'mes "tu cuenta esta bien, pero";'),
    ("mes \"sometimes it's good to ask\";", 'mes "a veces es bueno pedir";'),
    ('mes "for help from those who are";', 'mes "ayuda a los que son";'),
    ('mes "more experienced than you.";', 'mes "mas experimentados que tu.";'),
    # bioeth == 2
    ("mes \"Ah, you've returned...\";", 'mes "Ah, has regresado...";'),
    ('mes "Now, you must be wondering";', 'mes "Ahora, debes estar preguntandote";'),
    ('mes "why I have been warning you";', 'mes "por que te he estado advirtiendo";'),
    ('mes "about the dangers of using";', 'mes "sobre los peligros de usar";'),
    ('mes "Alchemy to obtain knowledge";', 'mes "la Alquimia para obtener conocimiento";'),
    ('mes "that should be forbidden.";', 'mes "que deberia ser prohibido.";'),
    ('mes "It is better that you know now";', 'mes "Es mejor que lo sepas ahora";'),
    ('mes "than to find out later and not";', 'mes "a que lo descubras despues y no";'),
    ('mes "be prepared. There is a skill";', 'mes "estes preparado. Hay una habilidad";'),
    ('mes "in Alchemy that transgresses";', 'mes "en la Alquimia que transgrede";'),
    ('mes "the natural laws by creating";', 'mes "las leyes naturales al crear";'),
    ('mes "life not intended by God.";', 'mes "vida no prevista por Dios.";'),
    ('mes "It is an extremely";', 'mes "Es una habilidad";'),
    ('mes "dangerous skill that was";', 'mes "extremadamente peligrosa que fue";'),
    ('mes "developed out of human";', 'mes "desarrollada por la";'),
    ('mes "arrogance. Life is a beautiful";', 'mes "arrogancia humana. La vida es algo hermoso,";'),
    ('mes "thing, a precious gift, that";', 'mes "un regalo precioso, con el que";'),
    ('mes "we dare not tamper with.";', 'mes "no debemos atrevernos a jugar.";'),
    ('mes "My greatest shame in";', 'mes "Mi mayor verguenza en";'),
    ('mes "life is my contribution to";', 'mes "la vida es mi contribucion a";'),
    ('mes "that field of knowledge. At";', 'mes "ese campo de conocimiento. En";'),
    ('mes "that time I was young and";', 'mes "ese entonces yo era joven e";'),
    ('mes "headstrong, too proud to";', 'mes "impetuoso, demasiado orgulloso para";'),
    ('mes "admit I was playing God.";', 'mes "admitir que estaba jugando a ser Dios.";'),
    ('mes "I even went so far as to";', 'mes "Incluso llegue tan lejos como para";'),
    ('mes "become the most skilled";', 'mes "convertirme en el Alchemist";'),
    ('mes "Alchemist in the creation";', 'mes "mas habil en la creacion";'),
    ('mes "of ^FF0000Homunculi^000000. But I\'ve";', 'mes "de ^FF0000Homunculi^000000. Pero he";'),
    ("mes \"changed my ways. I don't...\";", 'mes "cambiado mis costumbres. Ya no...";'),
    ("mes \"I'll never create one again.\";", 'mes "Nunca creare uno de nuevo.";'),
    ('mes "Alchemy is an incredible";', 'mes "La Alquimia es un campo";'),
    ("mes \"field of study, and it's great\";", 'mes "de estudio increible, y es genial";'),
    ("mes \"that you've dedicated yourself\";", 'mes "que te hayas dedicado a ella,";'),
    ('mes "to it, but always remember that";', 'mes "pero siempre recuerda que";'),
    ('mes "this science has great potential for abuse, as well as for good.";', 'mes "esta ciencia tiene gran potencial para el abuso, asi como para el bien.";'),
    ('mes "I only fear that your quest";', 'mes "Solo temo que tu busqueda";'),
    ('mes "for knowledge, your insatiable";', 'mes "de conocimiento, tu insaciable";'),
    ('mes "curiosity to reveal the unknown, may lead you on the path of the";', 'mes "curiosidad por revelar lo desconocido, te lleve por el camino del";'),
    ("mes \"Homunculus. For your own sake, don't bother considering the idea.\";", 'mes "Homunculus. Por tu propio bien, no te molestes en considerar la idea.";'),
    ('mes "Remember that all life is";', 'mes "Recuerda que toda vida es";'),
    ('mes "precious. If your motives";', 'mes "preciosa. Si tus motivos";'),
    ('mes "are good, and untainted by";', 'mes "son buenos, y no estan manchados por";'),
    ('mes "the desire for fame or fortune,";', 'mes "el deseo de fama o fortuna,";'),
    ('mes "and if you work for the greater good of mankind, you\'ll be fine.";', 'mes "y si trabajas por el bien comun de la humanidad, estaras bien.";'),
    # bioeth == 1
    ("mes \"Ah, it's you again.\";", 'mes "Ah, eres tu otra vez.";'),
    ("mes \"Since you're here, let\";", 'mes "Ya que estas aqui, dejame";'),
    ('mes "me ask you a question.";', 'mes "hacerte una pregunta.";'),
    ('mes "What exactly do you";', 'mes "Que piensas exactamente";'),
    ('mes "think of Alchemy?";', 'mes "de la Alquimia?";'),
    ("mes \"Wait. Don't answer\";", 'mes "Espera. No respondas";'),
    ('mes "that. As someone more";', 'mes "eso. Como alguien mas";'),
    ('mes "experienced in this field,";', 'mes "experimentado en este campo,";'),
    ('mes "I believe that the answer";', 'mes "creo que la respuesta";'),
    ('mes "to that question is more";', 'mes "a esa pregunta es mas";'),
    ('mes "complicated than you think.";', 'mes "complicada de lo que piensas.";'),
    ('mes "Most people see Alchemists";', 'mes "La mayoria ve a los Alchemists";'),
    ('mes "as greedy scientists, assuming";', 'mes "como cientificos codiciosos, asumiendo";'),
    ('mes "that we use our skills exclusively for^FFFFFF.^000000the transmutation of gold. Of";', 'mes "que usamos nuestras habilidades exclusivamente para^FFFFFF.^000000la transmutacion de oro. Por";'),
    ('mes "course, learning how to do that";', 'mes "supuesto, aprender a hacerlo";'),
    ('mes "is part of our basic training.";', 'mes "es parte de nuestro entrenamiento basico.";'),
    ('mes "But learning transmutation";', 'mes "Pero aprender transmutacion";'),
    ('mes "is part of something bigger.";', 'mes "es parte de algo mas grande.";'),
    ('mes "All Alchemists must strive to";', 'mes "Todos los Alchemists deben esforzarse";'),
    ('mes "harness nature for the good";', 'mes "por dominar la naturaleza para el bien";'),
    ('mes "of mankind. To do this requires";', 'mes "de la humanidad. Para esto se requiere";'),
    ('mes "the study of every science.";', 'mes "el estudio de cada ciencia.";'),
    ('mes "The fields of Medicine,";', 'mes "Los campos de Medicina,";'),
    ('mes "Chemistry, Biology, Geology,";', 'mes "Quimica, Biologia, Geologia,";'),
    ('mes "Astronomy, Astrology, Geomancy,";', 'mes "Astronomia, Astrologia, Geomancia,";'),
    ('mes "Mathematics, Physics and even";', 'mes "Matematicas, Fisica e incluso";'),
    ('mes "Philosophy must all be learned";', 'mes "Filosofia deben ser aprendidos";'),
    ('mes "by the competent Alchemist.";', 'mes "por el Alchemist competente.";'),
    ("mes \"Once you've entered the\";", 'mes "Una vez que hayas entrado en";'),
    ('mes "exciting vastness of Alchemy,";', 'mes "la emocionante vastedad de la Alquimia,";'),
    ('mes "there is no turning back. Do";', 'mes "no hay vuelta atras. Haz";'),
    ('mes "your best to learn all that you";', 'mes "tu mejor esfuerzo para aprender todo lo que";'),
    ('mes "can, and never forget that you have responsibilities to mankind.";', 'mes "puedas, y nunca olvides que tienes responsabilidades con la humanidad.";'),
    # bioeth == 0 (initial)
    ("mes \"You're another\";", 'mes "Eres otro";'),
    ('mes "practitioner of";', 'mes "practicante de";'),
    ("mes \"Alchemy, aren't you?\";", 'mes "Alquimia, verdad?";'),
    ("mes \"It's been a long time\";", 'mes "Ha pasado mucho tiempo";'),
    ("mes \"since I've spoken to\";", 'mes "desde que hable con";'),
    ('mes "such a young colleague...";', 'mes "un colega tan joven...";'),
    ('mes "As your elder colleague,";', 'mes "Como tu colega mayor,";'),
    ('mes "I encourage you to focus";', 'mes "te animo a enfocarte";'),
    ('mes "on your training. Enlighten";', 'mes "en tu entrenamiento. Iluminate";'),
    ('mes "yourself and satisfy your";', 'mes "y satisface tu";'),
    ('mes "curiosity by solving the";', 'mes "curiosidad resolviendo los";'),
    ('mes "riddles of science.";', 'mes "acertijos de la ciencia.";'),
    ('mes "But heed my words...";', 'mes "Pero presta atencion a mis palabras...";'),
    ('mes "There are secrets of";', 'mes "Hay secretos de";'),
    ('mes "science that must never";', 'mes "la ciencia que nunca deben";'),
    ('mes "be discovered by humans.";', 'mes "ser descubiertos por humanos.";'),
    ('mes "Do not be so proud as to";', 'mes "No seas tan orgulloso como para";'),
    ('mes "seek out forbidden truths.";', 'mes "buscar verdades prohibidas.";'),
    ('mes "Good luck in your";', 'mes "Buena suerte en tus";'),
    ('mes "studies, and I hope";', 'mes "estudios, y espero que";'),
    ('mes "you never use your";', 'mes "nunca uses tu";'),
    ('mes "search for answers as";', 'mes "busqueda de respuestas como";'),
    ('mes "an excuse to give in to";', 'mes "una excusa para ceder a";'),
    ('mes "greed and obsession.";', 'mes "la codicia y la obsesion.";'),
    # Non-alchemist Kellasus
    ('mes "Hmm. Who decides what";', 'mes "Hmm. Quien decide que";'),
    ('mes "is right and wrong? What is";', 'mes "esta bien y que esta mal? Que";'),
    ('mes "meant to be known and what";', 'mes "estaba destinado a conocerse y que";'),
    ('mes "secrets were never intended";', 'mes "secretos nunca estuvieron destinados";'),
    ('mes "for mankind to understand?";', 'mes "a ser comprendidos por la humanidad?";'),
    ('mes "There are many who would";', 'mes "Hay muchos que estarian";'),
    ('mes "agree that God alone wields";', 'mes "de acuerdo en que solo Dios tiene";'),
    ('mes "authority over life and death.";', 'mes "autoridad sobre la vida y la muerte.";'),
    ('mes "But Alchemy does provide";', 'mes "Pero la Alquimia si provee";'),
    ('mes "a way for the audacious...";', 'mes "un camino para los audaces...";'),
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print('Batch 2 done')
