#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translate TempleOfDemonGod.txt to LATAM Spanish"""
import os
BASE = "D:/Xponzy Network/Ragnarok-Server/rathena/npc/re/instances/"
fp = os.path.join(BASE, "TempleOfDemonGod.txt")
with open(fp, 'r', encoding='utf-8') as f:
    c = f.read()

R = [
# Nidhogg entrance
('mes "This place is too dangerous for you to explore alone.";','mes "Este lugar es demasiado peligroso para que lo explores solo.";'),
('mes "Please form a party and come with your comrades.";','mes "Por favor forma un grupo y ven con tus compañeros.";'),
('mes "Only party leaders can control access to the Temple of the Demon God.";','mes "Solo los líderes de grupo pueden controlar el acceso al Templo del Dios Demonio.";'),
("mes \"It's to ensure the safety of the entire Expedition. Please let your leader talk to me instead.\";","mes \"Es para asegurar la seguridad de toda la Expedición. Por favor deja que tu líder hable conmigo.\";"),
("mes \"I'm sorry, but you can't enter this place without approval from the Commander.\";","mes \"Lo siento, pero no puedes entrar a este lugar sin la aprobación del Comandante.\";"),
('mes "You must be on the quest to subjugate the Demon God to enter this place.";','mes "Debes tener la misión de someter al Dios Demonio para entrar aquí.";'),
("mes \"Please go to Commander Hiva Agip and receive the Demon God Subjugation quest.\";","mes \"Por favor ve con el Comandante Hiva Agip y recibe la misión de Sometimiento del Dios Demonio.\";"),
("mes \"I've been waiting for you, hero-in-waiting. \";","mes \"Te estaba esperando, futuro héroe. \";"),
('mes "Let me guide you to the depth of the temple where Morroc lies in wait.";','mes "Déjame guiarte a las profundidades del templo donde Morroc espera.";'),
('mes "This tree is the spitting image of Yggdrasil.";','mes "Este árbol es la viva imagen de Yggdrasil.";'),
('mes "I just hope Morroc is not intent on what I fear most.";','mes "Solo espero que Morroc no pretenda lo que más temo.";'),
('mes "Through this tree the door is opened.";','mes "A través de este árbol se abre la puerta.";'),
('mes "I can sense that";','mes "Puedo sentir que";'),
("mes \"this tree is generating mana at certain intervals as if it's breathing.\";","mes \"este árbol está generando maná a ciertos intervalos como si respirara.\";"),
("mes \"I'm going to catch a moment between its breaths to open up a path for you. Are you ready?\";","mes \"Voy a aprovechar un momento entre sus respiraciones para abrirte un camino. ¿Estás listo?\";"),
('"Enter now."','"Entrar ahora."'),
('"Do not enter."','"No entrar."'),
('mes "Okay.";','mes "Está bien.";'),
('mes "I understand if you need time.";','mes "Entiendo si necesitas tiempo.";'),
('mes "Take your time. I can wait as long as you want me to.";','mes "Tómate tu tiempo. Puedo esperar todo lo que quieras.";'),
('mes "Just wait a while, and the entrance will open.";','mes "Solo espera un momento, y la entrada se abrirá.";'),
('mes "Enter through the tree.";','mes "Entra por el árbol.";'),
("mes \"Don't be scared, even though it's not an ordinary tree.\";","mes \"No tengas miedo, aunque no es un árbol ordinario.\";"),
('mes "You have eliminated the God of Despair!?";','mes "¡¿Has eliminado al Dios de la Desesperación?!";'),
("mes \"I can only say that his ambition was too big...\";","mes \"Solo puedo decir que su ambición era demasiado grande...\";"),
('mes "Always talk about creating a new world and becoming a god...";','mes "Siempre hablaba de crear un nuevo mundo y convertirse en un dios...";'),
("mes \"But seriously, he didn't create anything at all!\";","mes \"¡Pero en serio, no creó absolutamente nada!\";"),
('mes "Abandon the body that used to be a demon, and the appearance after rebirth is just imitating the god...";','mes "Abandonar el cuerpo que solía ser un demonio, y la apariencia después de renacer es solo una imitación del dios...";'),
('mes "The result is just what a human looks like,";','mes "El resultado es simplemente lo que parece un humano,";'),
('mes "He can\'t escape the so-called god frame,";',"mes \"No puede escapar del llamado molde de dios,\";"),
('mes "...you can only say that you are eating bad luck!";','mes "...¡solo se puede decir que tiene mala suerte!";'),
('mes "I will give you approval for the quest, and you can report to the commander.";','mes "Te daré la aprobación para la misión, y puedes reportar al comandante.";'),
('mes "Thank you!";','mes "¡Gracias!";'),
# Yggdrasil Lookalike
('mes "You touched the tree and felt a strange flow of mana.";','mes "Tocaste el árbol y sentiste un extraño flujo de maná.";'),
('mes "Perhaps the flow of mana will guide you to the depth of the temple.";','mes "Quizás el flujo de maná te guiará a las profundidades del templo.";'),
('"Enter."','"Entrar."'),
('"Quit."','"Salir."'),
('mes "No entry permission has been issued under the name of your party.";','mes "No se ha emitido permiso de entrada bajo el nombre de tu grupo.";'),
("mes \"Please let your party leader submit an entry request, and I'll open the gate to the temple.\";","mes \"Por favor deja que tu líder de grupo envíe una solicitud de entrada, y abriré la puerta del templo.\";"),
('mes "You are to comply with the rules set by the Expedition.";','mes "Debes cumplir con las reglas establecidas por la Expedición.";'),
("mes \"It's for everyone's safety.\";","mes \"Es por la seguridad de todos.\";"),
("mes \"Um...how could this happen... the flow of magic power becomes unstable,\";","mes \"Um...cómo pudo pasar esto... el flujo de poder mágico se vuelve inestable,\";"),
("mes \"It hurts my brain, this is the gap I finally made...\";","mes \"Me duele el cerebro, esta es la brecha que finalmente hice...\";"),
('mes "may not be able to enter at the moment...";','mes "puede que no se pueda entrar por el momento...";'),
('" of the party "','\" del grupo \"'),
('", is entering Temple of the Demon God."','", está entrando al Templo del Dios Demonio."'),
("mes \"Please go to Commander Hiva Agip and receive the 'Demon God Subjugation' quest.\";","mes \"Por favor ve con el Comandante Hiva Agip y recibe la misión 'Sometimiento del Dios Demonio'.\";"),
# Ahat
('mes "Welcome";','mes "Bienvenido";'),
('mes "to the Temple of the Demon God.";','mes "al Templo del Dios Demonio.";'),
("mes \"It's my honor to be your host today.\";","mes \"Es un honor ser tu anfitrión hoy.\";"),
("mes \"So, you've come.\";","mes \"Así que viniste.\";"),
("mes \"Gosh, you're so persistent.\";","mes \"Cielos, eres muy persistente.\";"),
('mes "Hah hah, are you surprised to see me here?";','mes "Ja ja, ¿te sorprende verme aquí?";'),
("mes \"Didn't you expect this at all?\";","mes \"¿No te lo esperabas?\";"),
("mes \"Why don't I introduce myself officially?\";","mes \"¿Por qué no me presento oficialmente?\";"),
("mes \"I'm Ahat, the first servant of the Demon God.\";","mes \"Soy Ahat, el primer sirviente del Dios Demonio.\";"),
('mes "Well, well, maybe I forfeit my life today.";','mes "Bueno, bueno, quizás pierda mi vida hoy.";'),
("mes \"Don't look at me like that. Everything is as planned.\";","mes \"No me mires así. Todo está según lo planeado.\";"),
('mes "My master wishes for Shnaim and I to put you to the test.";','mes "Mi maestro desea que Shnaim y yo te pongamos a prueba.";'),
('mes "To see if you deserve to be our guests.";','mes "Para ver si mereces ser nuestro invitado.";'),
("mes \"If you think you've come this far on your own,\";","mes \"Si crees que has llegado hasta aquí por tu cuenta,\";"),
("mes \"you're mistaken.\";","mes \"estás equivocado.\";"),
('mes "Everything is as the Master has planned.";','mes "Todo es como el Maestro lo planeó.";'),
("mes \"For now, let's see if you can open this door.\";","mes \"Por ahora, veamos si puedes abrir esta puerta.\";"),
# npctalk Ahat
("Ahat: So, you've come.","Ahat: Así que viniste."),
("Ahat: Why don't I introduce myself officially? I'm Ahat, the first servant of the Demon God.","Ahat: ¿Por qué no me presento oficialmente? Soy Ahat, el primer sirviente del Dios Demonio."),
("Ahat: Well, well, maybe I forfeit my life today. Don't look at me like that. Everything is as planned.","Ahat: Bueno, bueno, quizás pierda mi vida hoy. No me mires así. Todo está según lo planeado."),
("Ahat: My master wishes for Shnaim and I to put you to the test. To see if you deserve to be our guests.","Ahat: Mi maestro desea que Shnaim y yo te pongamos a prueba. Para ver si mereces ser nuestro invitado."),
("Ahat: If you think you've come this far on your own, you're mistaken.","Ahat: Si crees que has llegado hasta aquí por tu cuenta, estás equivocado."),
("Ahat: Everything is as the Master has planned. For now, let's see if you can open this door.","Ahat: Todo es como el Maestro lo planeó. Por ahora, veamos si puedes abrir esta puerta."),
# Door mobmaster announces
('"Eliminate the Demon God\'s Apostles, Ahat and Shnaim, and collect their souls."','"Eliminen a los Apóstoles del Dios Demonio, Ahat y Shnaim, y recojan sus almas."'),
("\"The Apostles' souls are the key to opening the Temple of the Demon God.\"","\"Las almas de los Apóstoles son la clave para abrir el Templo del Dios Demonio.\""),
('"Activated the Soul Globes used to open the Temple of the Demon God."','"Se activaron los Globos de Alma usados para abrir el Templo del Dios Demonio."'),
# Soul Globe
('mes "Only party leaders can perform this event.";','mes "Solo los líderes de grupo pueden realizar este evento.";'),
("mes \"If you want to activate the soul globes, you need Shnaim's soul.\";","mes \"Si quieres activar los globos de alma, necesitas el alma de Shnaim.\";"),
("mes \"Inject \" + .@visible_npc_name$ + \"'s soul into the empty soul globe.\";","mes \"Inyectar el alma de \" + .@visible_npc_name$ + \" en el globo de alma vacío.\";"),
('mes "Successfully activated " + .@visible_npc_name$ + "\'s soul globe.";','mes "Se activó exitosamente el globo de alma de " + .@visible_npc_name$ + ".";'),
# Strange Boy / Morroc
('mes "You insignificant creature.";','mes "Criatura insignificante.";'),
('mes "How dare you lay a hand on a god-in-waiting?!";','mes "¡¿Cómo te atreves a ponerle la mano encima a un futuro dios?!";'),
("mes \"First, let me applaud you for coming this far.\";","mes \"Primero, déjame aplaudirte por haber llegado hasta aquí.\";"),
("mes \"You've been a good pawn.\";","mes \"Has sido un buen peón.\";"),
('select("What are you talking about?");','select("¿De qué estás hablando?");'),
("mes \"I've been waiting for this day.\";","mes \"He estado esperando este día.\";"),
('mes "To get out of that corner of the demon world and rule the entire universe.";','mes "Para salir de ese rincón del mundo demoníaco y gobernar todo el universo.";'),
('mes "To achieve that, I realized I must abandon my old body.";','mes "Para lograrlo, me di cuenta de que debía abandonar mi viejo cuerpo.";'),
('mes "So I died--well, I let you kill me.";','mes "Así que morí--bueno, dejé que me mataran.";'),
('mes "Death is an inevitable step to take before rebirth.";','mes "La muerte es un paso inevitable antes del renacimiento.";'),
("mes \"So I'm reborn--again, you brought me back.\";","mes \"Así que renací--de nuevo, ustedes me trajeron de vuelta.\";"),
('mes "All this has been arranged so that I could be reborn as God.";','mes "Todo esto fue arreglado para que pudiera renacer como Dios.";'),
("mes \"That's right, you foolish humans!\";","mes \"¡Así es, humanos tontos!\";"),
('mes "I died once, so that I could circle around the world and embrace it in my arms.";','mes "Morí una vez, para poder rodear el mundo y abrazarlo en mis brazos.";'),
("mes \"I've been reborn to engulf this world.\";","mes \"He renacido para engullir este mundo.\";"),
("mes \"I'll create a new world and become its Creator.\";","mes \"Crearé un nuevo mundo y me convertiré en su Creador.\";"),
('mes "Let me ask you, the first creatures that have stepped into my newborn land.";','mes "Déjame preguntarte, las primeras criaturas que pisaron mi tierra recién nacida.";'),
("mes \"How'd you like to follow me and watch the birth of a new world?\";","mes \"¿Qué tal si me siguen y presencian el nacimiento de un nuevo mundo?\";"),
# npctalk Morroc/Boy/Loki/Nidhogg center
("Boy: I've been waiting for this day. To get out of that corner of the demon world and rule the entire universe.","Boy: He estado esperando este día. Para salir de ese rincón del mundo demoníaco y gobernar todo el universo."),
("Boy: To achieve that, I realized I must abandon my old body. So I died--well, I let you kill me.","Boy: Para lograrlo, me di cuenta de que debía abandonar mi viejo cuerpo. Así que morí--bueno, dejé que me mataran."),
("Boy: Death is an inevitable step to take before rebirth. So I've been reborn--again, you've brought me back.","Boy: La muerte es un paso inevitable antes del renacimiento. Así que renací--de nuevo, ustedes me trajeron de vuelta."),
("Boy: All this has been arranged so that I could be reborn as God.","Boy: Todo esto fue arreglado para que pudiera renacer como Dios."),
("Morocc: I died once, so that I could circle around the world and embrace it in my arms. I've been reborn to engulf this world.","Morocc: Morí una vez, para poder rodear el mundo y abrazarlo. He renacido para engullir este mundo."),
("Morocc: I'll create a new world and become its Creator. Let me ask you, the first creatures that have stepped into my newborn land.","Morocc: Crearé un nuevo mundo y me convertiré en su Creador. Déjenme preguntarles, las primeras criaturas que pisaron mi tierra recién nacida."),
("Morocc: How'd you like to follow me and watch the birth of a new world?","Morocc: ¿Qué tal si me siguen y presencian el nacimiento de un nuevo mundo?"),
("Loki: Enough with your nonsense. Just say you like destroying things.","Loki: Basta de tonterías. Solo di que te gusta destruir cosas."),
("Loki: Create a new world and become its Creator? If this is the new world you're talking about, then I'm disappointed.","Loki: ¿Crear un nuevo mundo y convertirte en su Creador? Si este es el nuevo mundo del que hablas, estoy decepcionado."),
("Loki: Even if you burn your body, your power is not as potent as that of Ymir of the Genesis.","Loki: Incluso si quemas tu cuerpo, tu poder no es tan potente como el de Ymir del Génesis."),
("Loki: Just the fact that you had to steal Yggdrasil shows your lack of creativity.","Loki: El solo hecho de que tuvieras que robar Yggdrasil muestra tu falta de creatividad."),
("Loki: Take a good look at yourself. You're delusional if you think you look like a creator of any kind.","Loki: Mírate bien. Estás delirando si crees que pareces un creador de cualquier tipo."),
("Nidhogg: I second that. You're unnecessary to this world. You don't belong here.","Nidhogg: Concuerdo. Eres innecesario para este mundo. No perteneces aquí."),
("Nidhogg: Even Yggdrasil denies your existence!","Nidhogg: ¡Incluso Yggdrasil niega tu existencia!"),
("Nidhogg: As the Guardian of Yggdrasil, I have to remove you from this world.","Nidhogg: Como Guardiana de Yggdrasil, debo eliminarte de este mundo."),
("Morroc: Pah!","Morroc: ¡Bah!"),
("Morroc: Mortal, you must have a death wish to come at me like this.","Morroc: Mortal, debes tener deseos de morir para venir a mí así."),
("Morroc: I'll take your flesh and blood as housewarming gifts for my new world.","Morroc: Tomaré su carne y sangre como regalos de bienvenida para mi nuevo mundo."),
("Morroc: Have you beheld the darkness of the Genesis?","Morroc: ¿Han contemplado la oscuridad del Génesis?"),
("Morroc: Have you beheld frost, the beginning of life?","Morroc: ¿Han contemplado la escarcha, el comienzo de la vida?"),
("Morroc: Behold the Frost of Audhumla I brought back to life, into this world.","Morroc: Contemplen la Escarcha de Audhumla que traje de vuelta a la vida, a este mundo."),
("Loki: Are you running?","Loki: ¿Estás huyendo?"),
# Loki/Nidhogg
("mes \"You're helpless.\";","mes \"Eres un caso perdido.\";"),
('mes "And disgusting.";','mes "Y repugnante.";'),
("mes \"You're with a mercenary.\";","mes \"Estás con un mercenario.\";"),
('mes "Could you dismiss your current mercenary and hire me instead?";','mes "¿Podrías despedir a tu mercenario actual y contratarme a mí?";'),
('mes "I already assisted you once.";','mes "Ya te asistí una vez.";'),
('mes "Please be careful!";','mes "¡Por favor ten cuidado!";'),
('mes "allow me to aid you in this battle.";','mes "permíteme ayudarte en esta batalla.";'),
("Nidhogg: Allow me to aid you in this battle.","Nidhogg: Permíteme ayudarte en esta batalla."),
("mes \"My duty as the guardian isn't over yet.\";","mes \"Mi deber como guardiana aún no termina.\";"),
("Nidhogg: My duty as the guardian isn't over yet.","Nidhogg: Mi deber como guardiana aún no termina."),
('"^4d4dffGuardian Nidhogg has joined your party.^000000"','"^4d4dffLa Guardiana Nidhogg se ha unido a tu grupo.^000000"'),
("Nidhogg: Wait!","Nidhogg: ¡Espera!"),
# Brinaranea
("Brinaranea: Ooh, food walks into my lair.","Brinaranea: Ooh, la comida entra a mi guarida."),
("Brinaranea: My children will have a feast tonight. Ho ho ho!","Brinaranea: Mis hijos tendrán un festín esta noche. ¡Jo jo jo!"),
("Time to cook! *Giggle*","¡Hora de cocinar! *Risita*"),
("Come out, my children. An exquisite feast has delivered itself to us!","¡Salgan, mis hijos. Un exquisito festín se nos ha entregado!"),
("Children, it's time for dinner!","¡Hijos, es hora de cenar!"),
("Have all of you fed yet? Come out now!","¿Ya comieron todos? ¡Salgan ahora!"),
("A show time!","¡Hora del espectáculo!"),
("Ooh, game. It looks delicious!","Ooh, presa. ¡Se ve deliciosa!"),
("Wanna play?","¿Quieren jugar?"),
("Hah hah...","Ja ja..."),
("You're annoying! Don't mess with the Frost of Audhumla!","¡Son molestos! ¡No se metan con la Escarcha de Audhumla!"),
("You hellhounds, can you take this too?","Perros infernales, ¿pueden soportar esto también?"),
('"Nidhogg: No... She\'s regenerated herself perfectly."','"Nidhogg: No... Se regeneró perfectamente."'),
('"Nidhogg: Brinaranea\'s influence has dissipated, and a new warp gate has appeared."','"Nidhogg: La influencia de Brinaranea se disipó, y un nuevo portal ha aparecido."'),
# Nidhogg#eomnyd02
('mes "That was a tough battle.";','mes "Fue una batalla difícil.";'),
("mes \"This may not be good enough, but I hope it'll help your growth.\";","mes \"Puede que no sea suficiente, pero espero que ayude a tu crecimiento.\";"),
('"^4d4dffGuardian Nidhogg has rewarded you with a large amount of EXP for defeating Brinaranea.^000000"','"^4d4dffLa Guardiana Nidhogg te recompensó con una gran cantidad de EXP por derrotar a Brinaranea.^000000"'),
("mes \"Can this dreadful place compete with the Frost of the Genesis?\";","mes \"¿Puede este lugar espantoso competir con la Escarcha del Génesis?\";"),
("mes \"I can't say.\";","mes \"No puedo decirlo.\";"),
("mes \"He's created nothing on his own. How did he convince himself to think that he could be a creator?\";","mes \"No ha creado nada por su cuenta. ¿Cómo se convenció de que podría ser un creador?\";"),
# Morroc#mockid02 fire
("mes \"You're good.\";","mes \"Eres bueno.\";"),
('mes "Can you take on the wolf that swallowed the sun?";','mes "¿Puedes enfrentar al lobo que se tragó el sol?";'),
("mes \"If you can't handle him, then you can't handle a god now, can you?\";","mes \"Si no puedes con él, entonces no puedes con un dios, ¿verdad?\";"),
("mes \"I'll watch you. Mwa hah hah!\";","mes \"Los observaré. ¡Mua ja ja!\";"),
("Morroc: You're good. Can you taken on the wolf that swallowed the sun?","Morroc: Eres bueno. ¿Puedes enfrentar al lobo que se tragó el sol?"),
("Morroc: If you can't handle him, then you can't handle a god now, can you?","Morroc: Si no puedes con él, entonces no puedes con un dios, ¿verdad?"),
("Morroc: I'll watch you. Mwa hah hah!","Morroc: Los observaré. ¡Mua ja ja!"),
# Fire events
('"Grr..."','"Grr..."'),
('"I smell human... Grr..."','"Huelo humano... Grr..."'),
('"...BURN!"','"...¡ARDAN!"'),
("You're the ones... Grr... Good, I'll crush your bones! Grr...","Son ustedes... Grr... Bien, ¡les trituraré los huesos! Grr..."),
("Let's do this again. Come on!","¡Hagámoslo de nuevo. Vengan!"),
("I'm not going down without a fight!","¡No caeré sin pelear!"),
('"Nidhogg: Muspellskoll is trying to regenerate itself using the lava!"','"Nidhogg: ¡Muspellskoll está intentando regenerarse usando la lava!"'),
("Do I look easy to you? I'll burn you to ashes!","¿Les parezco fácil? ¡Los reduciré a cenizas!"),
('"Nidhogg: Muspellskoll\'s influence has dissipated, and a new warp gate has appeared."','"Nidhogg: La influencia de Muspellskoll se disipó, y un nuevo portal ha aparecido."'),
("Crash and burn!","¡Ardan y quémense!"),
("My fire will swallow you whole!","¡Mi fuego los tragará enteros!"),
('"Nidhogg: The Frost has melted. The lava is flowing again!"','"Nidhogg: La Escarcha se derritió. ¡La lava fluye de nuevo!"'),
('mes "It can be used to block the flow of lava using a Frost Crystal.";','mes "Se puede usar para bloquear el flujo de lava usando un Cristal de Escarcha.";'),
('"Use a Frost Crystal"','"Usar un Cristal de Escarcha"'),
('"Do not use a Frost Crystal"','"No usar un Cristal de Escarcha"'),
# Nidhogg phase 2
('mes "Good job, again.";','mes "Buen trabajo, otra vez.";'),
('"^4d4dffGuardian Nidhogg has rewarded you with a large amount of EXP for defeating Muspellskoll.^000000"','"^4d4dffLa Guardiana Nidhogg te recompensó con una gran cantidad de EXP por derrotar a Muspellskoll.^000000"'),
('mes "Skoll... Skoll and Haati...";','mes "Skoll... Skoll y Haati...";'),
('mes "Everything in here is a mere copy of that in the outside world.";','mes "Todo aquí es una mera copia del mundo exterior.";'),
("mes \"He's not a creator.\";","mes \"No es un creador.\";"),
# Strange Young Man / Morroc final
("You exceed my expectations.","Superan mis expectativas."),
("I'll accept your challenge.","Aceptaré su desafío."),
("I shall drench the land with your flowing blood and nourish it with your torn flesh.","Empaparé la tierra con su sangre y la nutriré con su carne desgarrada."),
("I'll show you the true depths of despair.","Les mostraré las verdaderas profundidades de la desesperación."),
("Morroc: You're already here, so let's not waste our time on talking.","Morroc: Ya están aquí, así que no perdamos tiempo hablando."),
("Morroc: Come on, mortals!","Morroc: ¡Vengan, mortales!"),
# Demigod battle
("You'll have to do better than this!","¡Tendrán que hacerlo mejor que esto!"),
("Stop being so persistent!","¡Dejen de ser tan persistentes!"),
("Mwah hah, dodge this if you can!","¡Mua ja, esquiven esto si pueden!"),
("A rhapsody for weak souls...","Una rapsodia para almas débiles..."),
("For whom the fugue is played? For whom the requiem is played?","¿Para quién se toca la fuga? ¿Para quién se toca el réquiem?"),
("Burn to ashes!","¡Ardan en cenizas!"),
('"Nidhogg: Wow, his regenerative power is unheard of! Don\'t let him regenerate again!"','"Nidhogg: ¡Wow, su poder regenerativo es inaudito! ¡No dejen que se regenere de nuevo!"'),
# Despair God
('"This is getting more interesting. *Snicker*"','"Esto se pone más interesante. *Risita*"'),
("\"Hey, you don't think this is over already, do you?\"","\"Oigan, no creerán que esto ya terminó, ¿verdad?\""),
('"What are you waiting for?!"','"¡¿Qué están esperando?!"'),
("\"I'll take your blood!\"","\"¡Tomaré su sangre!\""),
("I'll burn you slowly and painfully.","Los quemaré lenta y dolorosamente."),
("Can you hear the rhapsody? It's the sound of your soul writhing and screaming in pain!","¿Pueden oír la rapsodia? ¡Es el sonido de su alma retorciéndose y gritando de dolor!"),
("This is the thunderbolt of death!","¡Este es el rayo de la muerte!"),
("Burn and make beautiful flames!","¡Ardan y hagan hermosas llamas!"),
("I'll take your life.","Tomaré sus vidas."),
('"*Chuckle*"','"*Risita*"'),
("D-don't think... th-this... is over.. You're... already... time...","N-no crean... qu-que... esto... terminó.. Ustedes... ya... tiempo..."),
("\"---!!!\"","\"---!!!\""),
("I'll put you to rest. It's my mercy!!!","¡Los pondré a descansar. ¡Es mi misericordia!!!"),
# Nidhogg final
("mes \"I don't know what to say.\";","mes \"No sé qué decir.\";"),
('mes "We stopped the god-in-waiting.";','mes "Detuvimos al futuro dios.";'),
('mes "We accomplished our goal.";','mes "Cumplimos nuestro objetivo.";'),
("mes \"But I'm still unnerved.\";","mes \"Pero todavía estoy inquieta.\";"),
("mes \"This world is created in the mind of Morroc's.\";","mes \"Este mundo fue creado en la mente de Morroc.\";"),
("mes \"He'll live forever in this garden he couldn't finish.\";","mes \"Vivirá para siempre en este jardín que no pudo terminar.\";"),
("mes \"He probably doesn't know his body is destroyed forever.\";","mes \"Probablemente no sabe que su cuerpo fue destruido para siempre.\";"),
('mes "He was far too ambitious, even for him.";','mes "Era demasiado ambicioso, incluso para él.";'),
('mes "He wanted to create a new world and become its creator,";','mes "Quería crear un nuevo mundo y convertirse en su creador,";'),
("mes \"but he couldn't create anything on his own.\";","mes \"pero no pudo crear nada por su cuenta.\";"),
('mes "He abandoned his Demon body, just to become a mere facsimile of an existing god.";','mes "Abandonó su cuerpo de Demonio, solo para convertirse en una mera copia de un dios existente.";'),
('mes "He took the shape of a man.";','mes "Tomó la forma de un hombre.";'),
("mes \"He wasn't creative enough to reinvent the concept of God.\";","mes \"No fue lo suficientemente creativo para reinventar el concepto de Dios.\";"),
('mes "He was a paradox.";','mes "Era una paradoja.";'),
('mes "Now we need to get out of this trap in time and end; to reality.";','mes "Ahora necesitamos salir de esta trampa a tiempo y volver a la realidad.";'),
("mes \"This world only exists in the Demon God's mind. The same day repeats forever.\";","mes \"Este mundo solo existe en la mente del Dios Demonio. El mismo día se repite para siempre.\";"),
('mes "Everyone who enters this world will be dragged into the same loop.";','mes "Todos los que entren a este mundo serán arrastrados al mismo ciclo.";'),
('mes "In that sense, he succeeded in making his own world.";','mes "En ese sentido, tuvo éxito en crear su propio mundo.";'),
("mes \"Today's despair will repeat day after day.\";","mes \"La desesperación de hoy se repetirá día tras día.\";"),
("mes \"Even though we know this, we'll come back to walk the same path again. I hope I'll be able to fight by you every time...\";","mes \"Aunque lo sabemos, volveremos a recorrer el mismo camino. Espero poder luchar a tu lado cada vez...\";"),
("mes \"I've talked too much. The Commander must be waiting. Let me validate your feat, so you can report to him.\";","mes \"Hablé demasiado. El Comandante debe estar esperando. Déjame validar tu hazaña, para que puedas reportarle.\";"),
('mes "You did great today.";','mes "Lo hiciste genial hoy.";'),
("mes \"...It feels like things are not over yet,\";","mes \"...Siento que las cosas aún no terminan,\";"),
("mes \"This is very close to Morroc's spiritual world,\";","mes \"Esto está muy cerca del mundo espiritual de Morroc,\";"),
('mes "He should be here to keep thinking about the past!";','mes "¡Él debería estar aquí pensando en el pasado!";'),
('select("Exit.");','select("Salir.");'),
('mes "Of course. You must be exhausted.";','mes "Por supuesto. Debes estar agotado.";'),
('mes "Let me send you to the other members of your Expedition, free of charge.";','mes "Déjame enviarte con los otros miembros de tu Expedición, sin costo.";'),
# Little Helper (GM test NPC)
('mes "What?";','mes "¿Qué?";'),
('mes "Wrong.";','mes "Incorrecto.";'),
('mes "What Boss?";','mes "¿Qué Jefe?";'),
('mes "Brinaranea health was set to 2.000.000.";','mes "La vida de Brinaranea se estableció en 2.000.000.";'),
('mes "Muspellskoll health was set to 2.000.000.";','mes "La vida de Muspellskoll se estableció en 2.000.000.";'),
('mes "Demigod health was set to 2.000.000.";','mes "La vida del Semidiós se estableció en 2.000.000.";'),
('mes "Despair God health was set to 2.000.000.";','mes "La vida del Dios de la Desesperación se estableció en 2.000.000.";'),
]
n = 0
for o, r in R:
    if o in c:
        c = c.replace(o, r)
        n += 1
with open(fp, 'w', encoding='utf-8') as f:
    f.write(c)
print(f"TempleOfDemonGod.txt: {n}/{len(R)} applied")
