// rAthena login_msg_spn.conf
// Configuracion de mensajes del servidor de login (Espanol LATAM)
// -----------------------
0: ID no registrado.
1: Contrasena incorrecta.
2: Cuenta expirada.
3: Rechazado por el servidor.
4: Bloqueado por un GM.
5: No tienes la version mas reciente del juego.
6: Baneado.
7: Servidor lleno.
8: Limite de cuentas de la compania.
9: Baneado por DBA.
10: Correo electronico no confirmado.
11: Baneado por un GM.
12: Trabajando en la BD.
13: Bloqueo propio.
14: Grupo no permitido.
15: Grupo no permitido.
16: Cuenta eliminada.
17: La informacion de inicio de sesion permanece.
18: Investigacion por hackeo.
19: Investigacion de errores.
20: Eliminando personaje.
21: Eliminando personaje del conyugue.
22: Error desconocido.
