#!/usr/bin/env python3
"""
Translate academy.txt mes/select/announce/npctalk strings from English to LATAM Spanish.
Preserves all script logic, variables, functions, coordinates, color codes, NPC names in brackets, etc.
Uses informal 'tu' form. No double quotes inside mes strings (use single quotes).
No colons inside select() option text.
"""

import re
import sys

def translate_english(text):
    """Translate an English string to LATAM Spanish (LATAM, informal tu).
    Returns the translated string. Preserves color codes, NAVI tags, etc."""

    # If text is just a name in brackets, dots, or empty, return as-is
    if re.match(r'^\[.*\]$', text):
        return text
    if re.match(r'^[\.\s\*~\-]*$', text):
        return text
    # If it starts with a bracket name and rest is just dots
    if re.match(r'^\[.*\]\s*$', text):
        return text

    # Already Spanish? Check for strong Spanish indicators
    spanish_words = ['Puedes', 'boton', 'pantalla', 'ayudame', 'capitan', 'deberias',
                     'Informacion', 'tripulacion', 'equipar', 'habilidades', 'suerte',
                     'Muchas gracias', 'Consejo', 'teletransporte', 'herido', 'Questinfo',
                     'zarpar', 'Quieres', 'necesitas', 'aventureros', 'presionando',
                     'Todavia', 'reparaciones', 'Increible', 'Podrias', 'Deberia']
    for sw in spanish_words:
        if sw in text:
            return text

    # Large translation map
    t = {
        # === Captain Carocc at Izlude ===
        "Why are you here at the wharf?": "Por que estas aqui en el muelle?",
        "I guess you are doing well at the academy.": "Supongo que te va bien en la academia.",
        "I'm going to be docking and reparing the ship here for a while.": "Voy a estar atracando y reparando el barco aqui por un tiempo.",
        "I will be taking the same route I tried before.": "Tomare la misma ruta que intente antes.",
        "Hmm? You must be a student of the Criatura Academy?": "Hmm? Debes ser un estudiante de Criatura Academy?",
        "Were you on my ship?": "Estabas en mi barco?",
        "Hmm I can't remember.": "Hmm no puedo recordar.",
        "Well, anything is fine.": "Bueno, cualquier cosa esta bien.",
        "Shall I go easy on you since you said you were a student of the Academy?": "Deberia ser amable contigo ya que dijiste que eras estudiante de la Academia?",
        "I am still the captain of the ship, regardless.": "Sigo siendo el capitan del barco, de todos modos.",
        "I plan on taking off as soon as the repairs are complete.": "Planeo zarpar tan pronto como las reparaciones esten completas.",
        "The route will open with ^4d4dffPharos Lighthouse^000000 by then.": "La ruta se abrira con ^4d4dffPharos Lighthouse^000000 para entonces.",
        "This is Izlude.": "Esta es Izlude.",
        "The best city for you to take wings to your dreams.": "La mejor ciudad para que tus suenos tomen vuelo.",
        "Although I don't have any particular feelings for you,": "Aunque no tengo sentimientos particulares por ti,",
        "I've seen a lot of young people like you, while operating the ship.": "he visto a muchos jovenes como tu mientras operaba el barco.",
        "There were those among them who succeeded and failed and went back after being unable to adjust.": "Hubo entre ellos quienes tuvieron exito y quienes fracasaron y regresaron al no poder adaptarse.",
        "I want you to have a successful start with this place.": "Quiero que tengas un comienzo exitoso en este lugar.",
        "Did you know this?": "Sabias esto?",
        "Izlude has a new Institute for budding adventurers like you!": "Izlude tiene un nuevo Instituto para aventureros novatos como tu!",
        "Yes! It's called the ^4d4dffRoyal Criatura Academy^000000.": "Si! Se llama la ^4d4dffRoyal Criatura Academy^000000.",
        "Founded by the Rune-Midgarts lineage to help out new adventurers.": "Fundada por el linaje de Rune-Midgarts para ayudar a nuevos aventureros.",
        "A friend of mine works there, so I'll give you the introduction to him.": "Un amigo mio trabaja ahi, asi que te presentare con el.",
        "He could make a lot of things easier for you.": "El podria hacerte muchas cosas mas faciles.",
        "He usually talks to new adventurers near the entrance of the academy.": "Generalmente habla con nuevos aventureros cerca de la entrada de la academia.",
        "He ususally talks to new adventurers near the entrance of an academy.": "Generalmente habla con nuevos aventureros cerca de la entrada de la academia.",
        "He ususally talks to new adventurers near the entrance of the academy.": "Generalmente habla con nuevos aventureros cerca de la entrada de la academia.",
        "Go and meet him there.": "Ve a conocerlo ahi.",
        "Go and meet him personally.": "Ve a conocerlo personalmente.",
        "His name is ^4d4dffHun^000000": "Su nombre es ^4d4dffHun^000000",
        "I will mark his spot on the map so go to see him.": "Marcare su ubicacion en el mapa, ve a verlo.",
        "I will mark his location on the map so go to see him.": "Marcare su ubicacion en el mapa, ve a verlo.",
        "The ^4d4dffMini map can be seen on the right top of the screen.": "El ^4d4dffMini mapa se puede ver en la esquina superior derecha de la pantalla.",
        "^4d4dff Mini map can be seen on the right top of the screen.": "^4d4dffEl Mini mapa se puede ver en la esquina superior derecha de la pantalla.",
        "You can zoom in with +, zoom out with -. The waypoint from the NPC will be marked on it. ^000000": "Puedes acercar con +, alejar con -. El punto de referencia del NPC estara marcado en el. ^000000",
        "!- Information -!": "!- Informacion -!",
        "! - Information -!": "! - Informacion -!",
        "Received a Quest from ^4d4dffCaptain Carocc.": "Quest recibida de ^4d4dffCaptain Carocc.",
        "The quest content can be checked from the quest window.": "El contenido de la quest se puede revisar en la ventana de quests.",
        "Quest window can be opened by pressing ^4d4dffAlt + u^000000 keys together.": "La ventana de quests se puede abrir presionando ^4d4dffAlt + u^000000.",
        "Quest window can be opened by pressing the ^4d4dffAlt + u^000000 key.": "La ventana de quests se puede abrir presionando la tecla ^4d4dffAlt + u^000000.",
        "Contents of your Quest can be monitored on the Quest information window.": "El contenido de tu Quest se puede revisar en la ventana de informacion de Quests.",
        "If you need more help with the map, press <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> here": "Si necesitas mas ayuda con el mapa, presiona <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> aqui",
        "Yes, the part that says 'Hun'.": "Si, la parte que dice 'Hun'.",
        "Yes, the part that says [Hun].": "Si, la parte que dice [Hun].",
        "Yes, the part that says ''Hun''.": "Si, la parte que dice ''Hun''.",
        "^4d4dffThe icon during talk <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> means a link to navigation directions.": "^4d4dffEl icono durante la charla <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> significa un enlace a direcciones de navegacion.",
        "^4d4dff the icon during talk <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> means": "^4d4dffEl icono durante la charla <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> significa",
        "a link to navigation directions.": "un enlace a direcciones de navegacion.",
        "If you press info after selecting a task in the objectives^4d4dff,": "Si presionas info despues de seleccionar una tarea en los objetivos^4d4dff,",
        "an arrow pointing to the location of the objective will pop up along with the navigation help.": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion.",
        "an arrow pointing to the location of the objective will pop up along with navigation help": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion",
        "an arrow pointing to the location of the objective will pop up along with navigation help.": "aparecera una flecha apuntando a la ubicacion del objetivo junto con la ayuda de navegacion.",
        "Anyway, my friend will help you register with the academy": "De todos modos, mi amigo te ayudara a registrarte en la academia",
        "Anyway, my friend will help you register with the academy.": "De todos modos, mi amigo te ayudara a registrarte en la academia.",
        "I hope it can help you for your future.": "Espero que te ayude para tu futuro.",
        "I hope it will help you out in your journey": "Espero que te ayude en tu viaje",
        "I hope it will help you out in your journey.": "Espero que te ayude en tu viaje.",
        "Then there's no worry.": "Entonces no hay de que preocuparse.",
        "He'll introduce you to the academy.": "El te presentara en la academia.",
        "OK. I will show you the direction. You try it again.": "OK. Te mostrare la direccion. Intentalo de nuevo.",
        "By the way, did I tell you his name? His name is ^4d4dffHun^000000": "Por cierto, te dije su nombre? Su nombre es ^4d4dffHun^000000",
        "If you want, you can step forward to the world right away.": "Si quieres, puedes salir al mundo de inmediato.",
        "However, I recommend you visit the Academy first.": "Sin embargo, te recomiendo que visites la Academia primero.",
        "The world is a lonely place to be alone.": "El mundo es un lugar solitario para estar solo.",
        "The Academy has people you can make as lifetime companions.": "La Academia tiene personas que pueden ser companeros de por vida.",
        "The Academy has people you could make into lifetime companions.": "La Academia tiene personas que podrian ser companeros de por vida.",
        "My friend Hun will be around the academy entrance.": "Mi amigo Hun estara cerca de la entrada de la academia.",
        "If you don't know the way I'll point it out to you again.": "Si no conoces el camino te lo senalare de nuevo.",
        "My friend <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> will be around the academy entrance.": "Mi amigo <NAVI>[Hun]<INFO>izlude,122,207</INFO></NAVI> estara cerca de la entrada de la academia.",
        "then, Good luck!": "entonces, Buena suerte!",
        "Still being dilligent?": "Sigues siendo diligente?",
        "I've been busy, also.": "Yo tambien he estado ocupado.",
        "I was reparing the ship.": "Estaba reparando el barco.",
        "I'll be taking off as soon as the repairs are complete.": "Zarpare tan pronto como las reparaciones esten completas.",
        "At that time, the sailing route to ^4d4dffPharos lighthouse ^000000will be opened.": "En ese momento, la ruta de navegacion a ^4d4dffPharos Lighthouse^000000 sera abierta.",
        "Be excited for it.": "Emocionate por eso.",
        "Is it your first time on Izlude?": "Es tu primera vez en Izlude?",
        "You look strong and able!": "Te ves fuerte y capaz!",
        "I like able people like you!": "Me gusta la gente capaz como tu!",
        "Always be healthy and strong as you are now.": "Siempre se saludable y fuerte como lo eres ahora.",
        "I usually travel to ^4d4dffPharos Lighthouse^000000.": "Normalmente viajo a ^4d4dffPharos Lighthouse^000000.",
        "But I'm resting up due to some problems.": "Pero estoy descansando debido a algunos problemas.",
        "If it's Alberta or Byalan Island, talk to the next sailor.": "Si es Alberta o Byalan Island, habla con el siguiente marinero.",
        "Hmm? You said you didn't know what to do.": "Hmm? Dijiste que no sabias que hacer.",
        "Since you're at Izlude, why don't you visit ^4d4dffCriatura Academy^000000?": "Ya que estas en Izlude, por que no visitas ^4d4dffCriatura Academy^000000?",
        "Izlude has the Institute for budding adventurers like you": "Izlude tiene el Instituto para aventureros novatos como tu",
        "It's been a while!": "Ha pasado tiempo!",
        "Looking at your expression, you must be doing well.": "Por tu expresion, debes estar yendote bien.",
        "Do you want to go to Pharos Lighthouse on the southern coast of Morocc?": "Quieres ir a Pharos Lighthouse en la costa sur de Morocc?",
        "The fee is 2800 zeny. I have a crew that needs payment so this fee is non-negotiable.": "La tarifa es 2800 zeny. Tengo una tripulacion que necesita pago asi que no es negociable.",
        "Let us travel with the wing in our hair.": "Viajemos con el viento en nuestro cabello.",
        "Let us travel with the wind in our hair.": "Viajemos con el viento en nuestro cabello.",
        "Sorry but you are short of the boarding fee.": "Lo siento pero no tienes suficiente para la tarifa de abordaje.",
        "I need 2800z to operate.": "Necesito 2800z para operar.",
        "Do you know this, by the way?": "Por cierto, sabias esto?",
        "^4d4dffThere's a Rogue hideout at Pharos Lighthouse^000000.": "^4d4dffHay un escondite de Rogue en Pharos Lighthouse^000000.",
        "You already knew this?": "Ya lo sabias?",
        "I thought you knew that I only go to Pharos?": "Pense que sabias que solo voy a Pharos?",
        "Ask the sailor over there, he's the one that goes there frequently.": "Preguntale al marinero de alla, el es quien va ahi frecuentemente.",
        "There are plenty of other ships that travel to Alberta and Byalan Islands.": "Hay muchos otros barcos que viajan a Alberta y Byalan Islands.",
        "Hmm. I'm content with the well being of you and other adventurers who passed me by.": "Hmm. Estoy contento con el bienestar tuyo y de otros aventureros que pasaron por aqui.",
        "Lumin must be doing well too.": "Lumin debe estar bien tambien.",
        "I wonder why you feel like my own child even though we've only met from the sea.": "Me pregunto por que siento que eres como mi propio hijo aunque solo nos conocimos en el mar.",
        "I am Carocc, the caption of this ship.": "Soy Carocc, el capitan de este barco.",
        "Do you need a ship?": "Necesitas un barco?",
        "Then use it next time.": "Entonces usalo la proxima vez.",
        "Oh, We meet again.": "Oh, nos vemos de nuevo.",
        "Do you by any chance need a ship?": "De casualidad necesitas un barco?",
        "I usually travel to the port in Paros.": "Normalmente viajo al puerto en Paros.",
        "If you need to go to Paros later, come see me.": "Si necesitas ir a Paros despues, ven a verme.",
        "This guy has also decided to register at Criatura Academy.": "Este chico tambien ha decidido registrarse en Criatura Academy.",
        "This might be a good destiny for you. Hope you and him can be good friends.": "Esto podria ser un buen destino para ti. Espero que tu y el puedan ser buenos amigos.",

        # === Hun / Criatura Academy Staff ===
        "Quest cannot be continued due to the overfilled inventory.": "La quest no puede continuar debido al inventario lleno.",
        "Continue the quest after organizing the inventory.": "Continua la quest despues de organizar el inventario.",
        "Quest cannot be continued due to the invenory being full.": "La quest no puede continuar debido al inventario lleno.",
        "Please try it again after re-organizing your items.": "Por favor intentalo de nuevo despues de reorganizar tus items.",
        "Please try it again after organizing the items.": "Por favor intentalo de nuevo despues de reorganizar tus items.",
        "Oh.. you must be the adventurer Carocc was talking about.": "Oh.. debes ser el aventurero del que Carocc hablaba.",
        "I don't know where your homeland is but Midgard is a good place to start your life's journey.": "No se de donde vienes pero Midgard es un buen lugar para comenzar el viaje de tu vida.",
        "It's a good sight to see new adventurers start their journey.": "Es bueno ver a nuevos aventureros comenzar su viaje.",
        "You must be tired. Need a drink?": "Debes estar cansado. Necesitas algo de beber?",
        "It's joyous to see new adventurers starting out.": "Es un placer ver a nuevos aventureros empezar.",
        "You want something to drink while you are resting?": "Quieres algo de beber mientras descansas?",
        "You can open the Item window by clicking on the 'item' icon on top left portion of the screen.": "Puedes abrir la ventana de Items haciendo clic en el icono de 'item' en la parte superior izquierda de la pantalla.",
        "The items are automatically catagorized by 'consumables' 'equipment' 'etcetera' and 'personal' suitable for each use.": "Los items se categorizan automaticamente en 'consumibles', 'equipo', 'etcetera' y 'personal' segun su uso.",
        "It will do the automatic sorting per indiviaul useage to": "Hara la clasificacion automatica por uso individual",
        "Either ^4d4dffdouble click on the item^000000 you intend to use": "Ya sea ^4d4dffhaciendo doble clic en el item^000000 que deseas usar",
        "or drag it onto^4d4dff the equipment window and use it^000000": "o arrastralo a^4d4dff la ventana de equipo y usalo^000000",
        "^4d4dffItems can be used or equipped with simply double-clicking.": "^4d4dffLos items se pueden usar o equipar simplemente haciendo doble clic.",
        "Item window can be opened with shortcut key Alt+E": "La ventana de items se puede abrir con el atajo Alt+E",
        "^4d4dff Equipped items can be checked with Alt+ Q": "^4d4dffLos items equipados se pueden revisar con Alt+Q",
        "Items can also be dragged onto the location where you wish to equip it.": "Los items tambien se pueden arrastrar a la ubicacion donde deseas equiparlos.",
        "For detailed info on individual items^4d4dff, right click ^000000on that item.": "Para informacion detallada sobre items individuales^4d4dff, haz clic derecho ^000000en ese item.",
        "For detailed info on individual items^4d4dff, right-click ^000000on the item.": "Para informacion detallada sobre items individuales^4d4dff, haz clic derecho ^000000en el item.",
        "You can check the detailed info on the item.": "Puedes revisar la informacion detallada del item.",
        "^4d4dffRight-clicking on the item icon^4d4dff  brings up detailed info on the item.": "^4d4dffHacer clic derecho en el icono del item^4d4dff muestra informacion detallada del item.",
        "^4d4dffWhen you select other players, you can trade, party up with them with the community window that pops up.": "^4d4dffCuando seleccionas a otros jugadores, puedes comerciar o formar un party con ellos usando la ventana de comunidad que aparece.",
        "When you select on other players^4d4dff you can trade, party up with them with the community window that pops up.": "Cuando seleccionas a otros jugadores^4d4dff puedes comerciar o formar un party con ellos usando la ventana de comunidad que aparece.",
        "Ok now ^4d4dffdrink the apple juice that I gave you^000000.": "Ahora ^4d4dffbebe el jugo de manzana que te di^000000.",
        "Consume the apple juice that I gave you in your inventory.": "Consume el jugo de manzana que te di en tu inventario.",
        "Then we'll talk.": "Luego hablaremos.",
        "How's the taste?": "Que tal el sabor?",
        "Pretty good-taste of sweet and sour, right? It might not be much but it also has healing properties.": "Bastante bueno, dulce y acido, verdad? Puede que no sea mucho pero tambien tiene propiedades curativas.",
        "I want to give you more but that was the last of it": "Quisiera darte mas pero era el ultimo",
        "Anyways here's some potions. They'll come in handy when you start fighting.": "De todas formas aqui tienes unas pociones. Te seran utiles cuando empieces a pelear.",
        "Criatura Academy is a good place to build up experience for the future.": "Criatura Academy es un buen lugar para ganar experiencia para el futuro.",
        "And I'm not just saying this because I work here.": "Y no digo esto solo porque trabajo aqui.",
        "I'm not saying this just because I work here.": "No digo esto solo porque trabajo aqui.",
        "I'm for real... haha": "Lo digo en serio... jaja",
        "For real... hahahaha": "En serio... jajajaja",
        "What do you plan to do from now on?": "Que planeas hacer de ahora en adelante?",
        "Have you found a place to stay?": "Has encontrado un lugar donde quedarte?",
        "But still, though.": "Aun asi.",
        "It's tough to be out alone in a new place.": "Es dificil estar solo en un lugar nuevo.",
        "That's why Criatura Academy is there.": "Para eso esta Criatura Academy.",
        "Carocc sent you to me probably for the same reason.": "Carocc probablemente te envio a mi por la misma razon.",
        "Even though I'm just a work-hand here, I could show you around.": "Aunque solo soy un trabajador aqui, puedo mostrarte el lugar.",
        "If you follow this road up to north, you can see": "Si sigues este camino hacia el norte, puedes ver",
        "<NAVI>[the Academy building]<INFO>iz_ac01,100,39</INFO></NAVI>.": "<NAVI>[el edificio de la Academia]<INFO>iz_ac01,100,39</INFO></NAVI>.",
        "Anybody can enroll, so take advantage of it.": "Cualquiera puede inscribirse, asi que aprovechalo.",
        "Sorry to interrupt.": "Perdon por interrumpir.",
        "But ^4d4dffif you need location info, please ask me.^000000": "Pero ^4d4dffsi necesitas informacion de ubicaciones, preguntame.^000000",
        "Hun's information has limits": "La informacion de Hun tiene limites",
        "Hun's information has limits.": "La informacion de Hun tiene limites.",
        "How optimistic of you.": "Que optimista eres.",
        "If you need help, feel free to visit Criatura Academy any time.": "Si necesitas ayuda, visita Criatura Academy cuando quieras.",
        "There's no requirement or payment to enroll so it would be a great help to you.": "No hay requisitos ni pagos para inscribirse asi que seria de gran ayuda para ti.",
        "When you go through this way to the north, you'll find": "Si sigues este camino hacia el norte, encontraras",
        "<NAVI>[the academy building]<INFO>iz_ac01,100,39</INFO></NAVI>.": "<NAVI>[el edificio de la academia]<INFO>iz_ac01,100,39</INFO></NAVI>.",
        "If there are more adventurers like you, the future will be brighter.": "Si hay mas aventureros como tu, el futuro sera mas brillante.",
        "Hahahaha.": "Jajajaja.",
        "You already have a plan laid out?": "Ya tienes un plan preparado?",
        "Well prepared.": "Bien preparado.",
        "But just in case, if you are curious about the Criatura Academy, make a visit.": "Pero por si acaso, si tienes curiosidad sobre Criatura Academy, dale una visita.",
        "What is well, is well- isn't it?": "Lo que esta bien, esta bien, no?",
        "You are correct.": "Tienes razon.",
        "Preperation is the key.": "La preparacion es la clave.",
        "It's you..": "Eres tu..",
        "The Royal Criatura Academy was founded to help budding adventurers on their initial journey.": "La Royal Criatura Academy fue fundada para ayudar a aventureros novatos en su viaje inicial.",
        "Although I'm but a work-hand here, it makes me happy to see students graduate here and become fine members of society.": "Aunque solo soy un trabajador aqui, me hace feliz ver a estudiantes graduarse y convertirse en buenos miembros de la sociedad.",
        "Hey there.": "Hola.",
        "Rest up for a bit.": "Descansa un poco.",
        "Right clicking on the item icon ^4d4dffon the basic item window at the upper left corner brings up the detailed info on the item": "Hacer clic derecho en el icono del item ^4d4dffen la ventana basica de items en la esquina superior izquierda muestra la informacion detallada del item",
        "Right clicking on the item icon ^4d4dffbrings up the detailed info on the item": "Hacer clic derecho en el icono del item ^4d4dffmuestra la informacion detallada del item",

        # === Information Staff ===
        "Hi, how are you?": "Hola, como estas?",
        "I am in charge of navigation directions for Izlude's key locations": "Estoy a cargo de las direcciones de navegacion de las ubicaciones clave de Izlude",
        "I wish to propose a simple game along with the navigation, would that be ok?": "Quisiera proponerte un juego simple junto con la navegacion, te parece?",
        "First of all, how to check the mini-map.": "Primero que nada, como revisar el mini-mapa.",
        "You can check your location through the mini-map at the top right of the screen": "Puedes verificar tu ubicacion a traves del mini-mapa en la esquina superior derecha de la pantalla",
        "If you receive information on a town or a city, a waypoint ^4d4dff+^000000 can be marked on the map.": "Si recibes informacion de un pueblo o ciudad, un punto de referencia ^4d4dff+^000000 puede marcarse en el mapa.",
        "Press ^4d4dff[Ctrl] and [ ~ ] on your keyboard and you can see the world map^000000.": "Presiona ^4d4dff[Ctrl] y [ ~ ] en tu teclado y podras ver el mapa mundial^000000.",
        "Through the ^4d4dffworld map you can check the location of you, your party members and the level of monsters in the area.^000000": "A traves del ^4d4dffmapa mundial puedes verificar tu ubicacion, la de los miembros de tu party y el nivel de los monstruos en el area.^000000",
        "This is useful info to remember.": "Esta es informacion util para recordar.",
        "Now then, should we play a simple game?": "Entonces, jugamos un juego simple?",
        "I will ^4d4dffmark three specific locations on the mini-map.^000000": "Voy a ^4d4dffmarcar tres ubicaciones especificas en el mini-mapa.^000000",
        "Please ^4d4dffvisit those locations ^000000using the waypoints as reference.": "Por favor ^4d4dffvisita esas ubicaciones ^000000usando los puntos de referencia.",
        "Think of it as a treasure hunt and go.": "Piensalo como una busqueda del tesoro y ve.",
        "I've hidden some useful items there.": "Escondi algunos items utiles ahi.",
        "Vist me again after going by all three locations.": "Visitame de nuevo despues de ir a las tres ubicaciones.",
        "I will check up on it.": "Lo verificare.",
        "Ah, there' somebody who started out right before you!": "Ah, alguien empezo justo antes que tu!",
        "If you don't hurry that person will take all the items!": "Si no te apuras esa persona tomara todos los items!",
        "So, run!": "Asi que, corre!",
        "Do you need information on all the locations of Izlude?": "Necesitas informacion de todas las ubicaciones de Izlude?",
        "By clicking on the introduced ^B9062F[base camp name]^000000, I will offer you guidance so follow the ^B9062FRed Arrows^000000.": "Al hacer clic en el ^B9062F[nombre del lugar]^000000 introducido, te dare guia asi que sigue las ^B9062FFlechas Rojas^000000.",
        "If you click on the ^B9062F[area name]^000000, I can ^B9062Fnavigate^000000 a path for you to follow.": "Si haces clic en el ^B9062F[nombre del area]^000000, puedo ^B9062Fnavegar^000000 un camino para que sigas.",
        "If you are the first time adventurer,": "Si eres un aventurero primerizo,",
        "<NAVI>[Criatura Academy]<INFO>iz_ac01,100,39,</INFO></NAVI>": "<NAVI>[Criatura Academy]<INFO>iz_ac01,100,39,</INFO></NAVI>",
        "can offer a lot of info and help.": "puede ofrecerte mucha informacion y ayuda.",
        "Do you need additonal directions?": "Necesitas direcciones adicionales?",
        "Do you need additional directions?": "Necesitas direcciones adicionales?",
        "Through the <NAVI>[Wharf]<INFO>izlude,197,205,</INFO></NAVI> in the north east,": "A traves del <NAVI>[Wharf]<INFO>izlude,197,205,</INFO></NAVI> en el noreste,",
        "^8B4513Alberta^000000 or ^8B4513the Byalan Island^000000 can be visted.": "puedes visitar ^8B4513Alberta^000000 o ^8B4513Byalan Island^000000.",
        "you can go.": "puedes ir.",
        "Byalan Island is the scary place with ^8B4513Izlude dungeon^000000 in it.": "Byalan Island es el lugar aterrador con la ^8B4513mazmorra de Izlude^000000.",
        "To the southeast, the <NAVI>[Airship]<INFO>izlude,206,75,</INFO></NAVI>": "Al sureste, el <NAVI>[Airship]<INFO>izlude,206,75,</INFO></NAVI>",
        "will be connected with the Capital of the republic of Schwarzwald -^8B4513 Juno^000000, and": "esta conectado con la Capital de la republica de Schwarzwald -^8B4513 Juno^000000, y",
        "The capital of the Arunapeltsdom -^8B4513 Rachel ^000000.": "la capital de Arunafeltz -^8B4513 Rachel ^000000.",
        "The <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> located in the east": "La <NAVI>[Arena]<INFO>izlude,213,161,</INFO></NAVI> ubicada al este",
        "is for testing your battle ability.": "es para probar tu habilidad de batalla.",
        "It's an excellent place.": "Es un excelente lugar.",
        "I will mark the location on the mini map.": "Marcare la ubicacion en el mini mapa.",
        "I will mark the location of the": "Marcare la ubicacion de",
        "on the mini map.": "en el mini mapa.",
        "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> is the place to manage the job transfer to a swordman.": "<NAVI>[Swordman guild]<INFO>izlude,51,172,</INFO></NAVI> es el lugar para gestionar el cambio de trabajo a Swordman.",
        "I will mark the location of the swordman guild on the mini map.": "Marcare la ubicacion del gremio de Swordman en el mini mapa.",
        "If you want to visit ^8B4513Jawaii^000000 - the resort place for a couple,": "Si quieres visitar ^8B4513Jawaii^000000 - el lugar de descanso para parejas,",
        "talk to the <NAVI>[Wedding Secretary]<INFO>izlude,180,224,</INFO></NAVI>.": "habla con la <NAVI>[Wedding Secretary]<INFO>izlude,180,224,</INFO></NAVI>.",
        "Just ask the question about it.": "Solo pregunta al respecto.",
        "If you need to know about the Mercenary Guild, go west and speak to the": "Si necesitas saber sobre el Gremio de Mercenarios, ve al oeste y habla con el",
        "<NAVI>[Mercenary Guild Official]<INFO>izlude,47,170,</INFO></NAVI>.": "<NAVI>[Mercenary Guild Official]<INFO>izlude,47,170,</INFO></NAVI>.",
        "For now, I will mark the location of the": "Por ahora, marcare la ubicacion de",
        "I will erase the marks.": "Borrare las marcas.",
        "Have a wonderful adventure.": "Que tengas una maravillosa aventura.",
        "Good bye~~!": "Adios~~!",
        "What's with the long face?": "Por que esa cara larga?",
        "It looks like you found all the locations I marked.": "Parece que encontraste todas las ubicaciones que marque.",
        "Turtle...": "Tortuga...",
        "Because you are too slow.": "Porque eres muy lento.",
        "Yes, it is. I have been waiting for you for what seems like forever.": "Si. Te he estado esperando por lo que parece una eternidad.",
        ".......Shall I share with you?": ".......Deberia compartir contigo?",
        "Is that so?": "Es asi?",
        "Captain always told me to help the poor people.": "El capitan siempre me dijo que ayudara a los pobres.",
        "But you get rid of my chance to help.": "Pero eliminaste mi oportunidad de ayudar.",
        "Ahhh. Irritating.": "Ahhh. Irritante.",
        "Well, now we can divide 7 to 3?": "Bueno, ahora podemos dividir 7 a 3?",
        "I am OK with 6 to 4.": "Estoy bien con 6 a 4.",
        "This guy...": "Este tipo...",
        "Ahhh, you two calm down.": "Ahhh, ustedes dos calmense.",
        "Lumin took them all.": "Lumin se los llevo todos.",
        "Simple and fair decision.": "Decision simple y justa.",
        "OK. Now I am going.": "OK. Ya me voy.",
        "See you again, my friend.": "Nos vemos, amigo.",
        "Aren't you two friends?": "No son amigos ustedes dos?",
        "You guys both seemed friendly enough right?": "Los dos parecian bastante amigables, no?",
        "Well, this is my present for you.": "Bueno, este es mi regalo para ti.",
        "Hope it will be useful.": "Espero que sea util.",
        "Have a wonderful journey.": "Que tengas un maravilloso viaje.",
        "You have not found the treasure I hid.": "No has encontrado el tesoro que escondi.",
        "Here are the locations again.": "Aqui estan las ubicaciones de nuevo.",
        "Hurry up!": "Date prisa!",
        "This is Izlude - the satellite city of Prontera.": "Esta es Izlude - la ciudad satelite de Prontera.",
        "Do you need directions?": "Necesitas direcciones?",

        # === Airship / Arena / Bulletin Board ===
        "==== Airship Information====": "==== Informacion de Airship ====",
        "==== Airship Information ====": "==== Informacion de Airship ====",
        "Izlude - Juno - Rachel": "Izlude - Juno - Rachel",
        "Travellers bound for either the ^4d4dffSchwarzwalt Republic^000000 or ^4d4dffArunafeltz^000000 may board the airship here.": "Los viajeros con destino a la ^4d4dffRepublica de Schwarzwalt^000000 o ^4d4dffArunafeltz^000000 pueden abordar el airship aqui.",
        "Except the signboard of the free airship, nothing can be found.": "Excepto el letrero del airship gratuito, no se puede encontrar nada.",
        "Except for the signboard of the free airship, nothing particular was found.": "Excepto por el letrero del airship gratuito, no se encontro nada en particular.",
        "Yo.": "Oye.",
        "Sorry pal I got here first.": "Lo siento amigo, llegue primero.",
        "Should've used a Fly wing like I did.": "Deberias haber usado un Fly Wing como yo.",
        "Why do these wings teleport?": "Por que estas alas teletransportan?",
        "I guess because they're from Creamy monsters...": "Supongo que porque son de monstruos Creamy...",
        "As the captain said, seeing is believing. The world is full of mysteries.": "Como dijo el capitan, ver para creer. El mundo esta lleno de misterios.",
        "Seems like Lumin beat you again.": "Parece que Lumin te gano de nuevo.",
        "Better get to the next location before Lumin does.": "Mejor llega a la siguiente ubicacion antes que Lumin.",
        "Muahahahaha.": "Muajajajaja.",
        "Muahahaha.": "Muajajaja.",
        "No...": "No...",
        "Meeting three times in one day must be destiny.": "Encontrarnos tres veces en un dia debe ser destino.",
        "You and I can be friends.": "Tu y yo podemos ser amigos.",
        "Frene-what? Oh well I'm done with the mission.": "Frene-que? Bueno ya termine con la mision.",
        "Take care.": "Cuidate.",
        "Are you even listening to me?!": "Siquiera me estas escuchando?!",
        "^4d4dff...I have to report the result to the Information Staff...^000000.": "^4d4dff...Tengo que reportar el resultado al Personal de Informacion...^000000.",
        "^4d4dff...I have to report of the result to Information staff...^000000.": "^4d4dff...Tengo que reportar el resultado al Personal de Informacion...^000000.",
        "Ooo Butterfly Wings.": "Ooo Butterfly Wings.",
        "If I hand it over to you, you'll just waste 'em so I'll just keep them.": "Si te las doy, las desperdiciaras asi que me las quedare.",
        "If I hand them over to you, you'll just waste 'em so I think I'll keep them.": "Si te las doy, las desperdiciaras asi que creo que me las quedare.",
        "If I hand it over to you, you'll just waste 'em so I'll just keep them.": "Si te las doy, las desperdiciaras asi que me las quedare.",
        "Come on this is just friendly competition.": "Vamos, esto es solo competencia amistosa.",
        "I am doing this for you to make you stronger.": "Hago esto por ti para hacerte mas fuerte.",
        "Now, so long.": "Ahora, adios.",
        "Of course.": "Por supuesto.",
        "I already packed it in my bag.": "Ya lo guarde en mi bolsa.",
        "There were Butterfly Wings here.": "Habia Butterfly Wings aqui.",
        "That's not fair, I was here first so they're mine.": "Eso no es justo, yo llegue primero asi que son mias.",
        "You better get to the next stop faster if you want the prize.": "Mejor llega a la siguiente parada mas rapido si quieres el premio.",
        "Well, then.....": "Bueno, entonces.....",
        "Lumin disappeared with his long hair in the air.": "Lumin desaparecio con su largo cabello al aire.",
        "== Challenge! Arena! ==": "== Desafio! Arena! ==",
        "Breath taking battle with monsters!": "Batallas emocionantes contra monstruos!",
        "Where is your limit?": "Donde esta tu limite?",
        "PvE party with your comrad!": "Party PvE con tu camarada!",
        "All these at Arena!!": "Todo esto en la Arena!!",
        "Except for the Arena promtional board, nothing can be found here.": "Excepto por el tablero promocional de la Arena, no se puede encontrar nada aqui.",
        "Except for the Arena promotion signboard, nothing can be found.": "Excepto por el letrero promocional de la Arena, no se puede encontrar nada.",
        "Hmmm. Its not nothing....": "Hmmm. No es nada....",
        "There were potions here...": "Habia pociones aqui...",
        "I was tired of waiting for you so I took it too.": "Estaba cansado de esperarte asi que yo tambien las tome.",
        "But why does this potion never make me full?": "Pero por que esta pocion nunca me llena?",
        "*gulp*": "*trago*",
        "Oh well looks like it's all gone.": "Bueno parece que ya se acabaron.",
        "Lumin beat you again.": "Lumin te gano de nuevo.",
        "Better beat him to the last spot.": "Mejor ganale al ultimo lugar.",
        "Red potions.": "Pociones Rojas.",
        "If I hand it over to you, you'll just waste 'em so I'll just keep them.": "Si te las doy, las desperdiciaras asi que me las quedare.",
        "==== Information ====": "==== Informacion ====",
        "Prontera Field.": "Campo de Prontera.",
        "The city of Prontera is located to the north.": "La ciudad de Prontera esta ubicada al norte.",
        "Except for the simple signboard, nothing can be found here.": "Excepto por el simple letrero, no se puede encontrar nada aqui.",
        "Except for the simple signboard, nothing can be found.": "Excepto por el simple letrero, no se puede encontrar nada.",
        "Sorry but I am quicker than you.": "Lo siento pero soy mas rapido que tu.",
        "There were Fly Wings here..": "Habia Fly Wings aqui..",
        "In fact, I don't like Fly's wings.": "De hecho, no me gustan las alas de Fly.",
        "Flies are so dirty.": "Las moscas son tan sucias.",
        "By the way, why is one of the convenient transportations fly wing shaped?": "Por cierto, por que uno de los transportes convenientes tiene forma de ala de mosca?",
        "Perhaps you know?": "Tal vez tu sabes?",
        "...you don't know.": "...no sabes.",
        "Defeated by Lumin again.": "Derrotado por Lumin de nuevo.",
        "Keep calm and find the next location.": "Manten la calma y encuentra la siguiente ubicacion.",
        "...Hello": "...Hola",
        "Fly Wings.": "Fly Wings.",
        "Fly's wings were here so I already packed them in my bag.": "Las Fly Wings estaban aqui asi que ya las guarde en mi bolsa.",
        "This guy....": "Este tipo....",
        "......": "......",
        ".........": ".........",

        # === Therapist ===
        "Are you a student?": "Eres estudiante?",
        "Do you have any problem in your body?": "Tienes algun problema en tu cuerpo?",
        "This is the dispensary of the Royal Criatura Academy.": "Esta es la enfermeria de la Royal Criatura Academy.",
        "How can I help you?": "En que puedo ayudarte?",
        "Are you injured?": "Estas herido?",
        "Even the emergency treatment didn't work for you?": "Ni siquiera el tratamiento de emergencia te funciono?",
        "Is that good enough?": "Es suficiente?",
        "Have you recovered?": "Te has recuperado?",
        "If you are sane, go to bed and rest before you go.": "Si estas bien, ve a la cama y descansa antes de irte.",
        "I feel sorry for you but...": "Lo siento por ti pero...",
        "I can only give my free healing service to those under base level 20.": "Solo puedo dar mi servicio de curacion gratuito a los menores de nivel base 20.",
        "You don't look like you're going to die anyways.": "No parece que vayas a morir de todos modos.",
        "Just take a rest here until you've recovered.": "Solo descansa aqui hasta que te recuperes.",
        "There are lots of vacant beds!": "Hay muchas camas vacias!",
        "You already know about First Aid.": "Ya sabes sobre First Aid.",
        "We both are busy. Don't bother me.": "Ambos estamos ocupados. No me molestes.",
        "You are commendable!": "Eres admirable!",
        "First Aid is a skill that transfers SP to HP during emergency situations.": "First Aid es una habilidad que transfiere SP a HP durante situaciones de emergencia.",
        "Recovery ratio is very minimal...": "El ratio de recuperacion es muy minimo...",
        "It can help you avoid dying but won't give you much HP.": "Puede ayudarte a evitar morir pero no te dara mucho HP.",
        "Press ^4d4dffALT + S^000000 to open your Skill window to see your skills.": "Presiona ^4d4dffALT + S^000000 para abrir tu ventana de Skills y ver tus habilidades.",
        "If you press ^4d4dffF12^000000...": "Si presionas ^4d4dffF12^000000...",
        "The shortcut window will open up with nine small compartments to register your skills to.": "La ventana de atajos se abrira con nueve pequenos compartimentos para registrar tus habilidades.",
        "Dragging the right hand corner at the shortcut window, you can open up more skill shortcut pages.": "Arrastrando la esquina derecha de la ventana de atajos, puedes abrir mas paginas de atajos de habilidades.",
        "It is a simple use.. ^4d4dffEach slot responds to individual keys from F1 to F9^000000.": "Es de uso simple.. ^4d4dffCada ranura responde a teclas individuales de F1 a F9^000000.",
        "Needed skills or items can be immediately used after registering on the corresponding slots.": "Las habilidades o items necesarios se pueden usar inmediatamente al registrarlos en las ranuras correspondientes.",
        "You can register needed items or skills at ^4d4dffshortcut slots by dragging the icons.": "Puedes registrar items o habilidades necesarias en las ^4d4dffranuras de atajos arrastrando los iconos.",
        "^4d4dff The registered items and equipment at^4d4dff the slots can be immediately used or armed by pressing the reponding F1 - F9 keys.": "^4d4dffLos items y equipo registrados en^4d4dff las ranuras se pueden usar o equipar inmediatamente presionando las teclas F1 - F9 correspondientes.",
        "By setting the ^4d4dffshortcut keys as you want, you can use the responding shortcut key.": "Al configurar las ^4d4dffteclas de atajo como quieras, puedes usar la tecla de atajo correspondiente.",
        "^4d4dffyou may register the frequently using items and skills, and use them at your convenience.": "^4d4dffpuedes registrar los items y habilidades que uses frecuentemente, y usarlos cuando quieras.",
        "Now open the skill window and register [First Aid] as shortcut key, then use it.": "Ahora abre la ventana de habilidades y registra [First Aid] como tecla de atajo, luego usala.",
        "You will find it is more covenient to use this way.": "Encontraras que es mas conveniente usarla de esta forma.",
        "Have you investigated the growing plants in the field?": "Has investigado las plantas que crecen en el campo?",
        "^4d4dff Red Plant, Blue Plant, Green Plant, White Plant^000000etc..": "^4d4dff Red Plant, Blue Plant, Green Plant, White Plant^000000 etc..",
        "You can get different colored herbs from the various plants.": "Puedes obtener hierbas de diferentes colores de las varias plantas.",
        "Processing herbs turns to be a various useful potions.": "Procesar hierbas se convierte en varias pociones utiles.",
        "Now, shall we collect the Red Herb with your hands?": "Ahora, recolectamos la Red Herb con tus manos?",
        "A ^4d4dffRed Plant is growing near the academy building.^000000.": "Una ^4d4dffRed Plant esta creciendo cerca del edificio de la academia.^000000.",
        "I secretly planted it for today.": "La plante en secreto para hoy.",
        "Go and get ^4d4dff1 Red Herb^000000.": "Ve y consigue ^4d4dff1 Red Herb^000000.",
        "You got it.": "Lo conseguiste.",
        "^4d4dffYou could eat this herb and get the benefit of it immediately but it will be more efficient if you make it into a potion.^000000.": "^4d4dffPodrias comer esta hierba y obtener su beneficio inmediatamente pero sera mas eficiente si la conviertes en una pocion.^000000.",
        "Herbs vary their virtues according to their color.": "Las hierbas varian sus propiedades segun su color.",
        "^4d4dffGreen Herbs^000000 detox you.": "^4d4dffGreen Herbs^000000 te desintoxican.",
        "^4d4dffBlue Herbs^000000 recover your SP.": "^4d4dffBlue Herbs^000000 recuperan tu SP.",
        "Any other?": "Alguna otra?",
        "Well, HP is recovering like this red herb.": "Bueno, el HP se recupera como con esta hierba roja.",
        "This like this... Make a nectar and put it into a bottle....": "Asi como esto... Haz un nectar y ponlo en una botella...",
        "This becomes the recovering potion possible to take anywhere, anytime.": "Esto se convierte en la pocion de recuperacion que puedes llevar a cualquier parte, en cualquier momento.",
        "I will give it to you as souvenir.": "Te la dare como recuerdo.",
        "And also give you the recipe to make potions easily.": "Y tambien te dare la receta para hacer pociones facilmente.",
        "This is the book for the simple combination of potion use.": "Este es el libro para la combinacion simple de uso de pociones.",
        "You can make it easily by ^4d4dffusing the combination kit or cooking tool^000000.": "Puedes hacerlo facilmente ^4d4dffusando el kit de combinacion o herramienta de cocina^000000.",
        "Not only potions but also other easily attainable things can be turned to various tools. Please make use of them.": "No solo pociones sino tambien otras cosas faciles de obtener se pueden convertir en varias herramientas. Por favor aprovechalas.",
        "For your trial to make it, I gave you a Red Herb and one Apple,": "Para que pruebes hacerlo, te di una Red Herb y una Apple,",
        "How about making it with the combination kit?": "Que tal si lo haces con el kit de combinacion?",
        "Read the combination kit by ^4d4dffright-clicking^000000, and ^4d4dffclick the book shaped icon^000000 which will open up the explanation window.": "Lee el kit de combinacion haciendo ^4d4dffclic derecho^000000, y ^4d4dffhaz clic en el icono con forma de libro^000000 que abrira la ventana de explicacion.",
        "Why don't you learn about the virtues of herbs?": "Por que no aprendes sobre las propiedades de las hierbas?",
        "Bring one Red Herb by beating the growing Red Herb near the academy building.": "Trae una Red Herb golpeando la Red Plant que crece cerca del edificio de la academia.",
        "You can find it near the entrance of the academy.": "Puedes encontrarla cerca de la entrada de la academia.",
        "I already let you know about the basic medical botany.": "Ya te hable sobre la botanica medica basica.",
        "By the way, there is something called a ^4d4dffShining Plant^000000 here on Midgard.": "Por cierto, hay algo llamado ^4d4dffShining Plant^000000 aqui en Midgard.",
        "Nobody knows which herb comes out from this plant.": "Nadie sabe que hierba sale de esta planta.",
        "Once I got the fruit of Yggdrasil.": "Una vez obtuve el fruto de Yggdrasil.",
        "And, in the Alberta merchant guild, there is an old man making potions.": "Y en el gremio de mercaderes de Alberta, hay un viejo haciendo pociones.",
        "You can ask him for help.": "Puedes pedirle ayuda.",
        "^4d4dffAlchemist^000000 or ^4d4dffBiochemist^000000 or the higher class job ^4d4dffGeneticist^000000 are all good at creating potions.": "^4d4dffAlchemist^000000, ^4d4dffBiochemist^000000 o el trabajo de clase superior ^4d4dffGeneticist^000000 son todos buenos creando pociones.",
        "If you want to have a well-made potion, it may be a good idea to ask for a specialist.": "Si quieres una pocion bien hecha, puede ser buena idea pedirle a un especialista.",
        "I see...": "Ya veo...",
        "For emergency situations, in case you've fainted and want to be brought back here, I will save your current location.": "Para situaciones de emergencia, en caso de que te desmayes y quieras volver aqui, guardare tu ubicacion actual.",

        # === Academy Student / Red Herb Quest ===
        "Your inventory is too full so you can't continue this quest.": "Tu inventario esta muy lleno asi que no puedes continuar esta quest.",
        "Hey there Turtle": "Hola Tortuga",
        "You are really slow.": "Eres realmente lento.",
        "This Red Plant is no longer useful for you.": "Esta Red Plant ya no te sirve.",
        "You heard me.": "Me escuchaste.",
        "Aren't you here to collect the Red Plant for the Academy Therapist.": "No estas aqui para recolectar la Red Plant para el Terapeuta de la Academia.",
        "But, But something weird just happened.": "Pero, pero algo raro acaba de pasar.",
        "It happened right before my eyes.": "Paso justo frente a mis ojos.",
        "Did you lose your memory?": "Perdiste la memoria?",
        "If the captain hears about it, he'll cry.": "Si el capitan se entera, llorara.",
        "It is still ok as long as I remember you.": "Esta bien mientras yo te recuerde.",
        "Lumin.": "Lumin.",
        "How about being happy?": "Que tal estar feliz?",
        "Anyway, let me explain it to you, I have just cut all the leaves of this Red Plant.": "De todos modos, dejame explicarte, acabo de cortar todas las hojas de esta Red Plant.",
        "You can't collect the Red Plant anymore.": "Ya no puedes recolectar la Red Plant.",
        "OK... then...": "OK... entonces...",
        "I don't even need it anyways. I already know all about basic medical botany.": "De todos modos ni la necesito. Ya se todo sobre botanica medica basica.",
        "I didn't do it!": "Yo no lo hice!",
        "I was just standing here.": "Solo estaba parado aqui.",
        "Here take this Red Herb.": "Toma esta Red Herb.",
        "Ah... see it's growing back.": "Ah... mira esta volviendo a crecer.",
        "I guess you should go back to the Therapist.": "Creo que deberias volver con el Terapeuta.",
        "He's probably waiting for you..": "Probablemente te esta esperando..",
        "He seems to think of something deeply.": "Parece estar pensando en algo profundamente.",
        "Disregard it.": "Ignoralo.",
        "This student looks familiar...": "Este estudiante se ve familiar...",

        # === Instructor Argos (Trick Dead) ===
        "snoring... snoring...": "roncando... roncando...",
        "- ......": "- ......",
        "- A man is lying here": "- Un hombre esta tirado aqui",
        "- he's barely breathing.": "- apenas esta respirando.",
        "- Is this maybe...?!": "- Sera posible que...?!",
        "- an accident...": "- un accidente...",
        "- yes, this is a murder!": "- si, esto es un asesinato!",
        "- There's a murderer here!": "- Hay un asesino aqui!",
        "- I swear on some old person's grave": "- Juro por la tumba de alguien",
        "- I will solve this case!": "- que resolvere este caso!",
        "Yawn. Who are you making so much noise next to me...": "Bostezo. Quien eres tu haciendo tanto ruido a mi lado...",
        "Dead?! Who....?": "Muerto?! Quien....?",
        "me? Pu ha ha ha!!": "yo? Pu ja ja ja!!",
        "Sorry for laughing. Ha ha ha!": "Perdon por reirme. Ja ja ja!",
        "I was just taking a nap because the weather is good.": "Solo estaba tomando una siesta porque el clima esta bueno.",
        "Ahh...... that?": "Ahh...... eso?",
        "Right it makes sense that you misunderstood.": "Claro, tiene sentido que hayas malentendido.",
        "I used the skill<^ff0000Play Dead^000000> because I didn't want to be disturbed by monsters or someone else.": "Use la habilidad <^ff0000Play Dead^000000> porque no queria ser molestado por monstruos o alguien mas.",
        "I never thought someone would think of me as an actual dead body.": "Nunca pense que alguien me confundiria con un cadaver real.",
        "Oh, I see... you are a new novice who just has arrived here?": "Oh, ya veo... eres un novato nuevo que acaba de llegar aqui?",
        "I guess it is unexpected and surprising but do you want to learn <^ff0000Play Dead^000000>?": "Supongo que es inesperado y sorprendente pero quieres aprender <^ff0000Play Dead^000000>?",
        "I am sure that it will help you. How do you think about it?": "Estoy seguro de que te ayudara. Que piensas?",
        "Really ? If you are busy then fine by me.": "En serio? Si estas ocupado esta bien por mi.",
        "I should keep sleeping.": "Deberia seguir durmiendo.",
        "yawning...": "bostezando...",
        "You made a right decision!": "Tomaste la decision correcta!",
        "I want to teach you for good.": "Quiero ensenarte bien.",
        "A novice does not know the potential power of himself nor how strong the enemy is.": "Un novato no conoce el poder potencial de si mismo ni que tan fuerte es el enemigo.",
        "There is a studious type of novice who studies well..but i guess we are not.": "Hay un tipo de novato estudioso que estudia bien... pero supongo que nosotros no somos asi.",
        "Just take prompt action.": "Solo toma accion rapida.",
        "And sometimes you'll be defeated by stong enemies...": "Y a veces seras derrotado por enemigos fuertes...",
        "Huh? You're right this is my story.": "Eh? Tienes razon, esta es mi historia.",
        "I was getting sick of being defeated.": "Estaba harto de ser derrotado.",
        "One day, a good idea came to my mind. If I pretend to be dead when I find a strong enemy...": "Un dia, se me ocurrio una buena idea. Si finjo estar muerto cuando encuentro un enemigo fuerte...",
        "I was faced with the risk of death, because I was not good at pretending to be dead.": "Me enfrente al riesgo de muerte, porque no era bueno fingiendo estar muerto.",
        "Even when I look back at that time. it is still thrilling...": "Incluso cuando recuerdo esa epoca, sigue siendo emocionante...",
        "let's continue to talk": "sigamos hablando",
        "So ever since then, Playing Dead started working out for me!": "Asi que desde entonces, Hacerse el Muerto empezo a funcionarme!",
        "And then...": "Y luego...",
        "I could not hold a breath for a long time.": "No podia aguantar la respiracion por mucho tiempo.",
        "That was a problem!": "Eso era un problema!",
        "Clever monsters were checking out my breath!": "Los monstruos inteligentes revisaban mi respiracion!",
        "So I had to train myself to hold my breath for a long time.": "Asi que tuve que entrenarme para aguantar la respiracion por mucho tiempo.",
        "Sounds complicated.. but it is quite simple.": "Suena complicado.. pero es bastante simple.",
        "If you feel like you can not beat the enemy, when a strong one appears, just fall down on the ground and pretend to be dead.": "Si sientes que no puedes vencer al enemigo, cuando aparezca uno fuerte, solo tirate al suelo y finge estar muerto.",
        "I will put you on a brief test whether you hold you breathe or not.": "Te pondre una breve prueba de si puedes aguantar la respiracion o no.",
        "Hold a breath for 20 seconds, then talk to me later. I won't admit you if you talk to me before that time is over!": "Aguanta la respiracion por 20 segundos, luego hablame. No te aceptare si me hablas antes de que termine ese tiempo!",
        "Start!": "Empieza!",
        "What? You aren't able to hold your breath for even 20 seconds?": "Que? No puedes aguantar la respiracion ni 20 segundos?",
        "You can't learn this skill until you are able to hold it!": "No puedes aprender esta habilidad hasta que puedas aguantarla!",
        "Hold breath for 20 seconds again!": "Aguanta la respiracion por 20 segundos de nuevo!",
        "Then talk to me.": "Luego hablame.",
        "- Learned the <^ff0000Play Dead^000000>skill.": "- Aprendiste la habilidad <^ff0000Play Dead^000000>.",
        "Okay, good job.": "Bien, buen trabajo.",
        "If you have strong patience like that, it will save you. There will be no monsters that can hurt you.": "Si tienes una paciencia fuerte como esa, te salvara. No habra monstruos que puedan danarte.",
        "The <^ff0000Play Dead^000000> skill is in your skill list which you can open by pressing <Alt + S>, Please do not forget to use it, it will save you when you are in a danger.": "La habilidad <^ff0000Play Dead^000000> esta en tu lista de habilidades que puedes abrir presionando <Alt + S>. Por favor no olvides usarla, te salvara cuando estes en peligro.",
        "If you grow up and get another job, then you do not need this skill so do not spare it! Wse it when you need to and don't hesitate.": "Si creces y consigues otro trabajo, entonces no necesitaras esta habilidad asi que no la ahorres! Usala cuando la necesites y no dudes.",
        "I need to get some sleep, do not wake me up. Yawn.": "Necesito dormir un poco, no me despiertes. Bostezo.",

        # === Academy Receptionist ===
        "How are you today?": "Como estas hoy?",
        "I am in charge guiding you here in the Academy.": "Estoy a cargo de guiarte aqui en la Academia.",
        "Welcome to our Academy. I am in charge with the guide and registration for Novice education courses.": "Bienvenido a nuestra Academia. Estoy a cargo de la guia y registro de los cursos de educacion para Novices.",
        "What can I do for you?": "Que puedo hacer por ti?",
        "- As you are overloaded with too many items, quest can't be continued.-": "- Como tienes demasiados items, la quest no puede continuar. -",
        "I will make a new registration for you.": "Hare un nuevo registro para ti.",
        "You can choose the course freely and each course has individual features.": "Puedes elegir el curso libremente y cada curso tiene caracteristicas individuales.",
        "And this is the basic equipment for the educational course.": "Y este es el equipo basico para el curso educativo.",
        "Please make a good use of it.": "Por favor aprovechalo.",
        "Be careful with it as it won't be provided again.": "Ten cuidado con el ya que no se proporcionara de nuevo.",
        "It is your first step to be an adventurer that you have made a visit to us.": "Es tu primer paso para ser aventurero al habernos visitado.",
        "On our next meeting, I anticipate you will grow up a bit more.": "En nuestro proximo encuentro, espero que habras crecido un poco mas.",
        "One who is not a Novice can't attend the educational course.": "Quien no sea un Novice no puede asistir al curso educativo.",
        "However, a part of the educational course except the character cultivation can be freely attended. So, you may look around the Academy and neighboring places.": "Sin embargo, una parte del curso educativo excepto el cultivo de personaje puede ser asistida libremente. Asi que puedes explorar la Academia y los lugares cercanos.",
        "The first floor is equipped with instructors that give you lessons on how the world works here in Midgard.": "El primer piso cuenta con instructores que te dan lecciones sobre como funciona el mundo aqui en Midgard.",
        "First of all, at the dispensary, you can learn how to recover your physical strength and learn a skill to heal your HP": "Primero, en la enfermeria, puedes aprender como recuperar tu fuerza fisica y aprender una habilidad para curar tu HP",
        "At the armory, you can get simple training about battling monsters in Midgard.": "En la armeria, puedes recibir entrenamiento simple sobre combatir monstruos en Midgard.",
        "At the cafeteria, you can practice cooking and and will learn its many benefits.": "En la cafeteria, puedes practicar cocina y aprender sus muchos beneficios.",
        "At the 2nd floor, there are trainers that will teach you about the different job classes in the world.": "En el 2do piso, hay entrenadores que te ensenaran sobre las diferentes clases de trabajo en el mundo.",
        "Listen to the trainers and decide for yourself which job suits your personal style.": "Escucha a los entrenadores y decide por ti mismo que trabajo se adapta a tu estilo personal.",
        "This town is called 'Izlude' the satellite and port city of the Capital City of the Rune-Midgarts Kingdom Prontera.": "Esta ciudad se llama 'Izlude', la ciudad satelite y portuaria de la Capital del Rune-Midgarts Kingdom, Prontera.",
        "This town was re-organized to suit the education of Novices.": "Esta ciudad fue reorganizada para la educacion de Novices.",
        "Please find me, if you need anything else.": "Buscame si necesitas algo mas.",
        "Left-Click your mouse on the name of the trainer you are looking for and I will give guide you to them.": "Haz clic izquierdo con el mouse en el nombre del entrenador que buscas y te guiare hacia ellos.",
        "Is that helpful?": "Eso fue util?",
        "I believe you'll become nicer on our next meeting. Try your best~~~": "Creo que seras mejor en nuestro proximo encuentro. Da tu mejor esfuerzo~~~",
        "I believe you'll become nicer on our next meeting. Try your best~~~": "Creo que seras mejor en nuestro proximo encuentro. Da tu mejor esfuerzo~~~",

        # === Trainer Mainz ===
        "Ha ah....": "Ja ah....",
        "What should I do with this lunchbox?": "Que hago con este almuerzo?",
        "- Here, just moment!! -": "- Aqui, un momento!! -",
        "- As you are overloaded with too many items in your inventory -": "- Como tienes demasiados items en tu inventario -",
        "- You can't receive the items anymore -": "- Ya no puedes recibir mas items -",
        "- Let yourself enlightened -": "- Libera espacio -",
        "- and please try again -": "- y por favor intentalo de nuevo -",
        "Are you ready to learn about abnormal statuses? I promise that I won't trick you anymore. I am a ''trainer'' after all right?": "Estas listo para aprender sobre estados anormales? Prometo que no te enganare mas. Soy un ''entrenador'' despues de todo, verdad?",
        "First of all, I'll tell you about <^FF0000Poison^000000>.": "Primero, te hablare sobre <^FF0000Poison^000000>.",
        "As you already experienced, when you are poisoned, your body turns purple and you lose a little HP every second.": "Como ya experimentaste, cuando estas envenenado, tu cuerpo se vuelve morado y pierdes un poco de HP cada segundo.",
        "You can't lose HP forever so you won't die from poison.": "No puedes perder HP para siempre asi que no moriras por veneno.",
        "Experiencing is believing! I will put you in a poisoned status.": "Experimentar es creer! Te pondre en estado de envenenamiento.",
        "See what happens to you in the poisoned status.": "Mira lo que te pasa en estado de envenenamiento.",
        "You are- <^FF0000Poisoned^000000>.": "Estas- <^FF0000Envenenado^000000>.",
        "Did you see what is the poisoned status? After a certain period of time, you could be detoxicated, but if you're being attached, it is dangerous to expect being detoxicated naturally.": "Viste lo que es el estado de envenenamiento? Despues de cierto tiempo, puedes ser desintoxicado, pero si te estan atacando, es peligroso esperar desintoxicarse naturalmente.",
        "Refer to the detoxicants such as <^0022FFGreen Herb^000000>, <^0022FFGreen Potion^000000>, <^0022FFPanacea^000000> and <^0022FFRoyal Jelly^000000>.": "Consulta los antidotos como <^0022FFGreen Herb^000000>, <^0022FFGreen Potion^000000>, <^0022FFPanacea^000000> y <^0022FFRoyal Jelly^000000>.",
        "Next, I'll tell you about<^FF0000 Stun^000000.": "Ahora te hablare sobre <^FF0000Stun^000000>.",
        "I'll tell you about <^FF0000Stun^000000>.": "Te hablare sobre <^FF0000Stun^000000>.",
        "I'll tell you about <^FF0000Poison^000000>.": "Te hablare sobre <^FF0000Poison^000000>.",
        "While in the Stun status, stars will circle around your head and you can't move basically you'll be ''defenseless''.": "En el estado de Stun, estrellas giraran alrededor de tu cabeza y no podras moverte, basicamente estaras ''indefenso''.",
        "As you are defenseless, you can't move, use skills, and use items.": "Como estas indefenso, no puedes moverte, usar habilidades ni usar items.",
        "So, it is impossible to recover from it by yourself.": "Asi que es imposible recuperarte por ti mismo.",
        "The exceptional case is you can recover from it by the skill called <^0022FFGentle Touch-Cure^000000> if you are a Sura.": "La excepcion es que puedes recuperarte con la habilidad llamada <^0022FFGentle Touch-Cure^000000> si eres un Sura.",
        "You can recover with skills such as the Priest's <^0022FFRecovery ^000000> or the Arch Bishop's <^0022FFLauda Ramus^000000>.": "Puedes recuperarte con habilidades como <^0022FFRecovery^000000> del Priest o <^0022FFLauda Ramus^000000> del Arch Bishop.",
        "Let me show you what will happen in the Stun status!": "Dejame mostrarte lo que pasara en el estado de Stun!",
        "<^FF0000 Stun ^000000>.": "<^FF0000 Stun ^000000>.",
        "How was it?": "Que tal estuvo?",
        "Didn't you feel oppressed since you couldn't move?": "No te sentiste oprimido al no poder moverte?",
        "Imagine that you are in that status and monsters are rushing to you...": "Imagina que estas en ese estado y los monstruos vienen hacia ti...",
        "Believe me it'll happen.": "Creeme, pasara.",
        "This time, I will teach you about <^FF0000Sleep^000000>.": "Esta vez, te ensenare sobre <^FF0000Sleep^000000>.",
        "I will teach you about <^FF0000Sleep^000000>.": "Te ensenare sobre <^FF0000Sleep^000000>.",
        "In Sleep status, you fall asleep with a <Zzz> popped up over your head.": "En estado de Sleep, te quedas dormido con un <Zzz> sobre tu cabeza.",
        "Same as the Stun status, you are defenseless, but the difference is you can recover from the enemy's attack.": "Igual que el estado de Stun, estas indefenso, pero la diferencia es que puedes recuperarte del ataque del enemigo.",
        "But in Sleep status, the possibility to be hit by ''Critical'' attacks from enemy's attack is increased, you are in danger and exposed a severe damage.": "Pero en estado de Sleep, la posibilidad de ser golpeado por ataques ''Critical'' del enemigo aumenta, estas en peligro y expuesto a dano severo.",
        "For your reference, recovery by yourself is impossible and is only possible with the <^0022FF Recovery ^000000>skill of a Priest.": "Para tu referencia, la recuperacion por ti mismo es imposible y solo es posible con la habilidad <^0022FFRecovery^000000> de un Priest.",
        "Let me show you what will happen in the Sleep status.": "Dejame mostrarte lo que pasara en el estado de Sleep.",
        "<^FF0000 Sleep ^000000>.": "<^FF0000 Sleep ^000000>.",
        "How was it? It isn't fun to imagine being asleep in front of a dangerous enemy is it?": "Que tal estuvo? No es divertido imaginar estar dormido frente a un enemigo peligroso, verdad?",
        "Sleep is good for recovery but not necessarily good while you're in the middle of a battle.": "Dormir es bueno para recuperarse pero no necesariamente bueno cuando estas en medio de una batalla.",
        "Lastly, I will teach you about  <^FF0000 Silence ^000000>.": "Por ultimo, te ensenare sobre <^FF0000Silence^000000>.",
        "I will teach you about  <^FF0000 Silence ^000000>.": "Te ensenare sobre <^FF0000Silence^000000>.",
        "In Silence status,  you can't use any magic skills and a <...> will appear above your head.": "En estado de Silence, no puedes usar habilidades magicas y un <...> aparecera sobre tu cabeza.",
        "But all attacks are not impossible. Normal attacks can still be done while silenced.": "Pero no todos los ataques son imposibles. Los ataques normales aun se pueden hacer mientras estas silenciado.",
        "In the silence status, you can merely still physically attack or recover by using potions.": "En el estado de silencio, solo puedes atacar fisicamente o recuperarte usando pociones.",
        "It's possible to recover with the items such as<^0022FF Green Herb^000000>, <^0022FFGreen Potion^000000>, <^0022FFPanacea^000000> and <^0022FFRoyal Jelly^000000>.": "Es posible recuperarse con items como <^0022FFGreen Herb^000000>, <^0022FFGreen Potion^000000>, <^0022FFPanacea^000000> y <^0022FFRoyal Jelly^000000>.",
        "Let me show you what will happen in Sleep status.": "Dejame mostrarte lo que pasara en el estado de Silence.",
        "<^FF0000Silence^000000>": "<^FF0000Silence^000000>",
        "It's frustrating to not be able to use your skills right?": "Es frustrante no poder usar tus habilidades, verdad?",
        "Especially, when you are a high class depending upon the skills rather than physical attacks or in Sleep status during the battle, you will be damaged severely.": "Especialmente cuando eres una clase alta que depende de habilidades en vez de ataques fisicos, o en estado de Sleep durante la batalla, recibiras dano severo.",
        "In addtion, there are other statuses like Darkness, Frozen, Curse, Stone, Confusion etc, but I can let you experience all of them.": "Ademas, hay otros estados como Darkness, Frozen, Curse, Stone, Confusion, etc., pero puedo dejarte experimentar todos.",
        "I hope this was helpful for you to experience some of the things that you will see out in the world.": "Espero que haya sido util experimentar algunas de las cosas que veras en el mundo.",
        "Whenever you want to experience an abnormal status, please come to me.": "Cuando quieras experimentar un estado anormal, ven a buscarme.",
        "As an apology for the lunchbox matter, I will give you a small gift.": "Como disculpa por lo del almuerzo, te dare un pequeno regalo.",
        "Wish you have good luck in your adventures!": "Te deseo buena suerte en tus aventuras!",
        "Hey, you there!": "Oye, tu!",
        "By any chance, are you a training beginner?": "Por casualidad, eres un principiante en entrenamiento?",
        "I'm Trainer Mainz; and I'm in charge of education at this Academy.": "Soy el Entrenador Mainz; estoy a cargo de la educacion en esta Academia.",
        "Which course?": "Cual curso?",
        "It is not important so I will let you know later.": "No es importante asi que te lo dire despues.",
        "You must be very exhausted after having to read and learn so much right?": "Debes estar muy agotado despues de tener que leer y aprender tanto, verdad?",
        "Of course, you are... Oh, you poor thing.": "Por supuesto que si... Oh, pobrecito.",
        "There's a person who can help you when you need it.": "Hay una persona que puede ayudarte cuando lo necesitas.",
        "Do you know who is it?": "Sabes quien es?",
        "That's me!": "Soy yo!",
        "What does that mean?": "Que significa eso?",
        "It means I have prepared a special gift just for your exhausted self!": "Significa que prepare un regalo especial para tu agotado ser!",
        "A lunchbox for you!!! Hahahaha!": "Un almuerzo para ti!!! Jajajaja!",
        "Since I'm not the one who made it don't worry.": "Como no soy yo quien lo preparo, no te preocupes.",
        "My beloved wife prepared it. So, just be my guest and enjoy!": "Mi querida esposa lo preparo. Asi que, se mi invitado y disfruta!",
        "You don't want to have this lunchbox? I guess it's your loss then.": "No quieres este almuerzo? Supongo que es tu perdida.",
        "Should I just take it for myself then?": "Deberia quedarmelo entonces?",
        "Yes... You made a right decision.": "Si... Tomaste la decision correcta.",
        "Please keep in mind that I really wanted to have it but since you look exhausted I offered it to you first!": "Ten en cuenta que realmente lo queria pero como te ves agotado te lo ofreci primero!",
        "- You open the lunchbox and there is some type of food inside -": "- Abres el almuerzo y hay algun tipo de comida adentro -",
        "Wahahahat! Don't hesitate and just take it!": "Wajajaja! No dudes y solo tomalo!",
        "It will refresh you from your fatigue!": "Te refrescara de tu fatiga!",
        "Eat it~~ Eat it~~": "Comelo~~ Comelo~~",
        "- Since you're tired and starved you're obliged to take the box -": "- Como estas cansado y hambriento te ves obligado a tomar la caja -",
        "- You eat the food and suddenly feel a sharp pain in your stomach. Your vision seems to be blurry too -": "- Comes la comida y de repente sientes un dolor agudo en el estomago. Tu vision parece borrosa tambien -",
        "Oh... what happened to you?": "Oh... que te paso?",
        "You don't look too good!": "No te ves muy bien!",
        "Oh, man...": "Oh, cielos...",
        "I think you've been poisoned.": "Creo que fuiste envenenado.",
        "I will give you an antidote. You might get better if you take it.": "Te dare un antidoto. Podrias mejorar si lo tomas.",
        "- You reluctantly take the antidote -": "- Tomas el antidoto a reganadientes -",
        "Well, how the heck were you poisoned?": "Bueno, como diablos fuiste envenenado?",
        "By the way, I heard that there's a ghost wandering around the Royal Criatura Academy.": "Por cierto, escuche que hay un fantasma rondando la Royal Criatura Academy.",
        "I think the ghost must have poisoned you.": "Creo que el fantasma debe haberte envenenado.",
        "- You roll your eyes at Mainz -": "- Le pones los ojos en blanco a Mainz -",
        "- Mainz turns his head as if he doesn't notice -": "- Mainz voltea la cabeza como si no se diera cuenta -",
        "Ehem! Anyway, I am sorry.": "Ejem! De todos modos, lo siento.",
        "Please understand there is no malice.": "Por favor entiende que no hay mala intencion.",
        "All of these are for you...": "Todo esto es por ti...",
        "Want to know what I mean?": "Quieres saber a que me refiero?",
        "There are various kinds of monsters on the Midgard continent. And some of them can poison you or put you in abnormal conditions.": "Hay varios tipos de monstruos en el continente Midgard. Y algunos de ellos pueden envenenarte o ponerte en condiciones anormales.",
        "Usually, anybody is too embarrassed to admit being poisoned without knowing.  I just did it on purpose to let you have the experience in case it happens out in the real world.": "Normalmente, cualquiera siente verguenza de admitir ser envenenado sin saberlo. Lo hice a proposito para que tengas la experiencia en caso de que pase en el mundo real.",
        "Understand that I didn't intend to pass my wife's lunchbox as if it was a present. It was just another lesson from the Criatura Academy.": "Entiende que no pretendia pasar el almuerzo de mi esposa como si fuera un regalo. Fue solo otra leccion de Criatura Academy.",
        "As an apology, I would like to inform you of several abnormal statuses you might experience in the Midgard Continent.": "Como disculpa, me gustaria informarte sobre varios estados anormales que podrias experimentar en el Continente Midgard.",
        "Don't decline it! Being ready to learn so speak to me again.": "No lo rechaces! Preparate para aprender y hablame de nuevo.",
        "Are you here for an explanation about the abnormal statuses? What makes you anxious?": "Estas aqui para una explicacion sobre los estados anormales? Que te preocupa?",
        "What else are you anxious about?": "Que mas te preocupa?",
        "Do you have any more questions?": "Tienes mas preguntas?",
        "If you don't have any more questions, would you please have my lunchbox on behalf of me?": "Si no tienes mas preguntas, podrias llevarte mi almuerzo por mi?",
        "No?": "No?",
        "Haaaaa...": "Jaaaaa...",

        # Common phrases used throughout
        "End Conversation": "Terminar conversacion",
        "End Conversation.": "Terminar conversacion.",
        "End Coversation.": "Terminar conversacion.",
        "Coversation finished": "Conversacion terminada",
        "Go back to the previous menu": "Volver al menu anterior",
        "Cancel.": "Cancelar.",
        "Stop.": "Detener.",
        "Stop": "Detener",
        "Hello?": "Hola?",
        "Yes": "Si",
        "No": "No",
        "close": "cerrar",
        "Mini map marking removal": "Remover marcas del mini mapa",
        "I already know them all.": "Ya las conozco todas.",
        "Sure, let's play!": "Claro, juguemos!",
        "What'd you call me?": "Como me llamaste?",
        "I don't need your sympathy.": "No necesito tu lastima.",
        "!!!!!": "!!!!!",
        "Or Frenemies!": "O Frenemigos!",
        "Are you kidding me?!": "Me estas tomando el pelo?!",
        "Where's the treasure?": "Donde esta el tesoro?",
        "Where's the hidden treasure?": "Donde esta el tesoro escondido?",
        "Nothing again?": "Nada de nuevo?",
        "Why is there nothing here?": "Por que no hay nada aqui?",
        "Why is there nothing?": "Por que no hay nada?",
        "So can I have some?": "Puedo tener algunas?",
        "What are you talking about?": "De que estas hablando?",
        "Who're you?": "Quien eres?",
        "Ok so give me a ^ff0000Red Herb^000000": "Ok entonces dame una ^ff0000Red Herb^000000",
        "Then, why did you do it?": "Entonces, por que lo hiciste?",
        "You aren't dead?": "No estas muerto?",
        "But you weren't breathing...": "Pero no estabas respirando...",
        "I am sorry but I am busy.": "Lo siento pero estoy ocupado.",
        "I want to learn it!": "Quiero aprenderlo!",
        "Don't take it.": "No lo tomes.",
        "Take it.": "Tomalo.",
        "I need help with that": "Necesito ayuda con eso",
        "Anything will do really.": "Cualquier cosa esta bien realmente.",
        "Don't worry.": "No te preocupes.",
        "Help me!": "Ayudame!",
        "Teach me the First Aid Skill": "Ensenami la Habilidad First Aid",
        "^ff0000Red Herb Quest^000000": "^ff0000Quest de Red Herb^000000",
        "Save Location": "Guardar Ubicacion",
        "First Aid Skill": "Habilidad First Aid",
        "I want to rest.": "Quiero descansar.",
        "What's inside and outside the Academy.": "Que hay dentro y fuera de la Academia.",
        "Trainer location guide.": "Guia de ubicacion de Entrenadores.",
        "Register for the Academy": "Registrarse en la Academia",
        "Explanation about the Academy": "Explicacion sobre la Academia",
        "Location for trainers": "Ubicacion de entrenadores",
        "What's on the 1st floor": "Que hay en el 1er piso",
        "What's on the 2nd floor": "Que hay en el 2do piso",
        "Explanation about towns": "Explicacion sobre ciudades",
        "Game Mechanic Tutorial Instructors": "Instructores de Tutoriales de Mecanicas",
        "1st job trainers": "Entrenadores de 1er trabajo",
        "Return to the previous menu": "Volver al menu anterior",
        "Just a moment.": "Un momento.",
        "I have to leave.": "Tengo que irme.",
        "What are attributes?": "Que son los atributos?",
        "Harmony of attributes": "Armonia de atributos",
        "Experience of attribute": "Experiencia de atributo",
        "I already know": "Ya lo se",
        "Water": "Water",
        "Fire": "Fire",
        "Earth": "Earth",
        "Wind": "Wind",
        "Etc...": "Etc...",
        "Taming a monster": "Domar un monstruo",
        "Hatching the egg": "Incubar el huevo",
        "Monitoring pet's status": "Monitorear estado de mascota",
        "Feeding": "Alimentacion",
        "Performances": "Actuaciones",
        "Removing the accessory": "Quitar el accesorio",
        "Transforming back to egg": "Transformar de vuelta a huevo",
        "End Conversation": "Terminar conversacion",
        "A talking monster!": "Un monstruo que habla!",
        "Ignore it.": "Ignoralo.",
        "What is a pet?": "Que es una mascota?",
        "Does it help you fight?": "Te ayuda a pelear?",
        "How do I get a pet?": "Como consigo una mascota?",
        "Send me now!": "Enviame ahora!",
        "Stay": "Quedarme",
        "Check requests": "Ver solicitudes",
        "Warp me to the Field": "Teletransportame al Campo",
        "Take quest.": "Tomar quest.",
        "Give up on the quest.": "Rendirse en la quest.",
        "Give up for sure.": "Rendirse seguro.",
        "End Conversation": "Terminar conversacion",
        "Yes, give up.": "Si, rendirme.",
        "I will do it.": "Lo hare.",
        "Question about the shop.": "Pregunta sobre la tienda.",
        "I'm doing fine myself!": "Estoy bien por mi cuenta!",
        "Ok I'll listen!": "Ok escuchare!",
        "I don't want to do it.": "No quiero hacerlo.",
        "Buy": "Comprar",
        "Don't buy.": "No comprar.",
        "Shop types": "Tipos de tienda",
        "Currency types": "Tipos de moneda",
        "Cash Shop": "Cash Shop",
        "Experience training.": "Entrenamiento practico.",
        "No, I know enough.": "No, ya se suficiente.",
        "That's too tedious.": "Eso es muy tedioso.",
        "I'm not interested, excuse me...": "No me interesa, disculpa...",
        "Wow! I want to know more!": "Wow! Quiero saber mas!",
        "Cooking Benefits": "Beneficios de Cocina",
        "Cooking Methods": "Metodos de Cocina",
        "Actually, I have to go...": "En realidad, tengo que irme...",
        "How can I cook?": "Como puedo cocinar?",
        "I want to cook!": "Quiero cocinar!",
        "Yes! I did!": "Si! Lo hice!",
        "No, I gave up.": "No, me rendi.",
        "Fragrant Herb Mix": "Mezcla de Hierbas Fragantes",
        "Crunchy Salad": "Ensalada Crujiente",
        "Mixed Shabu Shabu": "Shabu Shabu Mixto",
        "Golden Apple Roast": "Manzana Dorada Asada",
        "Newfangled?": "Novedoso?",
        "Who are you..?": "Quien eres..?",
        "Why are you here?": "Por que estas aqui?",
        "Novice Combination Book": "Libro de Combinacion Novice",
        "Combination Kit": "Kit de Combinacion",
        "Ah... is that so?": "Ah... es asi?",
        "I lost it.": "Lo perdi.",
        "Neutral": "Neutral",
        "Poison": "Poison",
        "Holy": "Holy",
        "Dark": "Dark",
        "Angel": "Angel",
        "Undead": "Undead",
        "I want to quit.": "Quiero dejarlo.",
    }

    # Check exact match
    if text in t:
        return t[text]

    # For strings that contain dynamic content (like strcharinfo), we need pattern matching
    # Handle "Oh, "+strcharinfo(0)+"!" pattern - these remain as code, don't translate
    if 'strcharinfo' in text or '"+' in text or '+"' in text:
        return text

    # Return original if no translation found
    return text


def process_file(input_path, output_path):
    """Process the entire file, translating mes, select, announce, npctalk strings."""

    with open(input_path, 'r', encoding='cp949', errors='replace') as f:
        content = f.read()
        lines = content.split('\n')

    total_translated = 0
    new_lines = []

    for i, line in enumerate(lines):
        new_line = line

        # Skip first ~393 lines (already translated)
        if i < 393:
            new_lines.append(line)
            continue

        stripped = line.lstrip()

        # Skip comments
        if stripped.startswith('//'):
            new_lines.append(line)
            continue

        # Process mes "..."; lines
        mes_match = re.match(r'^(\s*mes\s+)"(.*)";\s*$', line)
        if mes_match:
            indent = mes_match.group(1)
            content = mes_match.group(2)
            translated = translate_english(content)
            if translated != content:
                total_translated += 1
            # Replace any double quotes in translated text with single quotes
            translated = translated.replace('"', "'")
            new_line = f'{indent}"{translated}";'

        # Process select("...") lines - more complex due to multiple options
        select_match = re.search(r'select\("([^"]*)"', line)
        if select_match and 'select(.@menu$)' not in line and 'select(.@' not in line:
            # Handle select with colons as separators
            full_select_match = re.search(r'select\("([^"]*)"\)', line)
            if full_select_match:
                select_content = full_select_match.group(1)
                # Split by : for colon-separated options or translate whole
                if ':' in select_content:
                    options = select_content.split(':')
                    translated_options = []
                    for opt in options:
                        t_opt = translate_english(opt.strip())
                        # Remove colons from translated text
                        t_opt = t_opt.replace(':', ' -')
                        translated_options.append(t_opt)
                    translated_select = ':'.join(translated_options)
                else:
                    translated_select = translate_english(select_content)
                    translated_select = translated_select.replace(':', ' -')

                if translated_select != select_content:
                    total_translated += 1
                # Replace double quotes with single quotes in the translated text
                translated_select = translated_select.replace('"', "'")
                new_line = line.replace(f'select("{select_content}")', f'select("{translated_select}")')

            # Handle select with comma-separated strings
            multi_select_match = re.search(r'select\("([^"]*)",\s*"([^"]*)"(?:,\s*"([^"]*)")?(?:,\s*"([^"]*)")?\)', line)
            if multi_select_match and not full_select_match:
                groups = [g for g in multi_select_match.groups() if g is not None]
                translated_groups = []
                for g in groups:
                    tg = translate_english(g)
                    tg = tg.replace(':', ' -').replace('"', "'")
                    translated_groups.append(tg)
                old_select = multi_select_match.group(0)
                new_select = 'select(' + ', '.join(f'"{g}"' for g in translated_groups) + ')'
                if old_select != new_select:
                    total_translated += 1
                new_line = line.replace(old_select, new_select)

        # Process npctalk "..." lines
        npctalk_match = re.search(r'npctalk\s+"([^"]*)"', line)
        if npctalk_match:
            content = npctalk_match.group(1)
            translated = translate_english(content)
            if translated != content:
                total_translated += 1
                translated = translated.replace('"', "'")
                new_line = line.replace(f'npctalk "{content}"', f'npctalk "{translated}"')

        # Process mapannounce strnpcinfo(4), "...", lines
        announce_match = re.search(r'(mapannounce\s+[^,]+,\s*)"([^"]*)"', line)
        if announce_match:
            content = announce_match.group(2)
            translated = translate_english(content)
            if translated != content:
                total_translated += 1
                translated = translated.replace('"', "'")
                new_line = line.replace(f'"{content}"', f'"{translated}"')

        new_lines.append(new_line)

    print(f"Total lines processed: {len(new_lines)}")
    print(f"Total translated: {total_translated}")

    with open(output_path, 'w', encoding='cp949', errors='replace') as f:
        f.write('\n'.join(new_lines))

    print(f"Output written to: {output_path}")


if __name__ == '__main__':
    input_path = r"D:\Xponzy Network\Ragnarok-Server\rathena\npc\re\jobs\novice\academy.txt.bak"
    output_path = r"D:\Xponzy Network\Ragnarok-Server\rathena\npc\re\jobs\novice\academy.txt"
    process_file(input_path, output_path)
