#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
English -> LATAM Spanish translator for rAthena NPC quest dialogue.
Translates ALL mes "..." and select("...") strings.
Preserves code logic, variables, color codes ^RRGGBB, [NPC Names].
Uses informal 'tu' form (LATAM Spanish).
"""
import re
import os
import sys

# =============================================================================
# COMPREHENSIVE SELECT OPTION TRANSLATIONS
# =============================================================================
SELECT_OPTIONS = {
    # Common UI options
    "Cancel.": "Cancelar.",
    "Cancel": "Cancelar",
    "Pass.": "Pasar.",
    "Yes.": "Si.",
    "Yes": "Si",
    "No.": "No.",
    "No": "No",
    "Ignore": "Ignorar",
    "Ignore him.": "Ignorarlo.",
    "Ignore Him.": "Ignorarlo.",
    "Ignore her.": "Ignorarla.",
    "Skills": "Habilidades",
    "Tools": "Herramientas",
    "Heart": "Corazon",
    "Ingredients": "Ingredientes",
    "Sure.": "Claro.",
    "Sure~": "Claro~",
    "Sure~!": "Claro~!",
    "Sure, why not?": "Claro, por que no?",
    "Sure thing.": "Por supuesto.",
    "Nothing.": "Nada.",
    "Not yet.": "Todavia no.",
    "Not yet...": "Todavia no...",
    "No, thanks.": "No, gracias.",
    "I see.": "Ya veo.",
    "Well...": "Bueno...",
    "Okay.": "Esta bien.",
    "Quit": "Salir",
    "Quit.": "Salir.",

    # the_sign_quest select options
    "I've been following these signs and...": "He estado siguiendo estos letreros y...",
    "I was just passing by...": "Solo estaba pasando...",
    "Nothing.": "Nada.",
    "I'm here to see Metz.": "Vine a ver a Metz.",
    "Gimmie your cash!": "Dame tu dinero!",
    "Who is Arian?": "Quien es Arian?",
    "What is Metz doing?": "Que esta haciendo Metz?",
    "How is Elle?": "Como esta Elle?",
    "You wanna have coffee sometime?": "Quieres tomar un cafe algun dia?",
    "Tell me about Metz.": "Cuentame sobre Metz.",
    "You have nice skin, Miss Elle.": "Tienes una piel bonita, Srta. Elle.",
    "Who are you talking about?": "De quien estas hablando?",
    "You're freaking me out!": "Me estas asustando!",
    "I'd like to meet this Daewoon.": "Me gustaria conocer a este Daewoon.",
    "Metz sent me here.": "Metz me envio aqui.",
    "Who are you then?": "Entonces quien eres tu?",
    "Kind of?": "Mas o menos?",
    "How the hell would I know?": "Como diablos voy a saberlo?",
    "No, but would you tell me?": "No, pero me lo dirias?",
    "It's handy.": "Es util.",
    "I actually don't know...": "En realidad no lo se...",
    "I'M READY! YEEAH!": "ESTOY LISTO! SIIII!",
    "I'll do my best!": "Dare lo mejor de mi!",
    "To hell with this!": "Al diablo con esto!",
    "Fine. Let's get it over with.": "Bien. Terminemos con esto.",
    "Yes, I do.": "Si, los tengo.",
    "I prefer soloing.": "Prefiero ir solo.",
    "I am lonely.": "Estoy solo.",
    "Awesome~!": "Genial~!",
    "I hate people who do that.": "Odio a la gente que hace eso.",
    "I do it sometimes...": "A veces lo hago...",
    "Destroy it!": "Destruirlo!",
    "I can't destroy such beauty...": "No puedo destruir tal belleza...",
    "I'd close my eyes, then destroy it.": "Cerraria los ojos y luego lo destruiria.",
    "Yes, of course!": "Si, por supuesto!",
    "I'd pretend not to hear anything.": "Fingiria no escuchar nada.",
    "I'd make fun of him, then run off.": "Me burlaria de el y luego me iria.",
    "Daewoon sent me.": "Daewoon me envio.",
    "Oops, sorry. Later~": "Ups, perdon. Luego~",
    "Speak to him.": "Hablarle.",
    "Ignore him.": "Ignorarlo.",
    "Try again.": "Intentar de nuevo.",
    "I've never heard of you.": "Nunca he escuchado de ti.",
    "Oh gosh, it's Jesqurienne!": "Oh cielos, es Jesqurienne!",
    "You got me, you got me.": "Me atrapaste, me atrapaste.",
    "Nope. Doesn't ring a bell.": "No. No me suena.",
    "^333333Stuck-up chick.^000000": "^333333Chica presumida.^000000",
    "Take it easy on the drinks...": "No tomes tanto...",
    "I can't let you win!": "No puedo dejarte ganar!",
    "Darn it...": "Rayos...",
    "Excuse me...": "Disculpa...",
    "Just pass by.": "Solo pasar.",
    "Oh, nothing.": "Ah, nada.",
    "I'm here for Metz...?": "Estoy aqui por Metz...?",
    "Here you are...": "Aqui tienes...",
    "Not yet...": "Todavia no...",
    "Who is Frank?": "Quien es Frank?",
    "Where is he?": "Donde esta?",
    "Speak to her.": "Hablarle.",
    "Leave her alone": "Dejarla sola",
    "Leave her sleep": "Dejarla dormir",
    "Wake her up": "Despertarla",
    "Roar~!": "Roar~!",
    "Excuse me.": "Disculpa.",
    "Ask about Stone of Sage": "Preguntar sobre la Piedra del Sabio",
    "Ask about Alchemy": "Preguntar sobre Alquimia",
    "I need your help.": "Necesito tu ayuda.",
    "Here is a letter for you.": "Aqui hay una carta para ti.",
    "I am leaving, leaving.": "Me voy, me voy.",
    "Please look at this.": "Por favor mira esto.",
    "I need your help again.": "Necesito tu ayuda de nuevo.",
    "What's up?": "Que hay?",
    "What happened?": "Que paso?",
    "What's wrong?": "Que sucede?",
    "Why don't you take this?": "Por que no tomas esto?",
    "What are you drawing by the way?": "Por cierto, que estas dibujando?",
    "Apprentices?": "Aprendices?",
    "Don't you miss your dad?": "No extranas a tu papa?",
    "He also misses you a lot.": "El tambien te extrana mucho.",
    "I'll bring this to him.": "Se lo llevare.",
    "Give Serin the symbol.": "Darle a Serin el simbolo.",
    "But why...?": "Pero por que...?",
    "But if Dark Lord comes to Midgard...": "Pero si el Dark Lord llega a Midgard...",
    "Alright. I'll let you go.": "De acuerdo. Te dejare ir.",
    "No, you have to be stopped.": "No, debo detenerte.",
    "I changed my mind for Midgard.": "Cambie de parecer por Midgard.",
    "I do, and it's alright...": "Lo se, y esta bien...",
    "I can't let you do this!": "No puedo dejarte hacer esto!",
    "Okay, have it your way.": "Esta bien, haz lo que quieras.",
    "I'm busy, sorry.": "Estoy ocupado, perdon.",
    "Sure, go ahead.": "Claro, adelante.",
    "Er, I'm busy, now that I think about it.": "Eh, estoy ocupado, ahora que lo pienso.",
    "Sure, let's do it.": "Claro, hagamoslo.",
    "Why should I help them?": "Por que deberia ayudarlos?",
    "About the Queen of the Dead...": "Sobre la Reina de los Muertos...",
    "About the Symbol of Nine Realms": "Sobre el Simbolo de los Nueve Reinos",
    "About Angrboda": "Sobre Angrboda",
    "I was told by the Witch that you're...": "La Bruja me dijo que tu...",
    "W-what should I do?": "Q-que deberia hacer?",
    "I can't believe this!": "No puedo creerlo!",
    "What do you mean??": "Que quieres decir??",
    "Don't worry, it won't.": "No te preocupes, no pasara.",
    "Then what should I do?": "Entonces que deberia hacer?",
    "Thanks for the concern, but I'm not worried.": "Gracias por la preocupacion, pero no estoy preocupado.",
    "I'll think about it.": "Lo pensare.",
    "Test...?": "Prueba...?",
    "I'm here for Metz Brayde.": "Estoy aqui por Metz Brayde.",
    "My apologies.": "Mis disculpas.",
    "Would you look at this?": "Podrias ver esto?",
    "Wait, I've got a pair of glasses...": "Espera, tengo unos lentes...",
    "Pass on by.": "Pasar de largo.",
    "About Geffen's Hidden Power": "Sobre el Poder Oculto de Geffen",
    "About Sobbing Starlight": "Sobre el Sobbing Starlight",
    "Interpret Ancient Document": "Interpretar Documento Antiguo",
    "Tell her your story.": "Contarle tu historia.",
    "Is that why you want Dark Lord...?": "Es por eso que quieres al Dark Lord...?",
    "Why are you doing this...": "Por que estas haciendo esto...",
    "I want to take Part Two again.": "Quiero hacer la Parte Dos de nuevo.",
    "Okay.": "Esta bien.",
    "Yes.": "Si.",
    "No.": "No.",
    "I can't do it.": "No puedo hacerlo.",
    "Let me think about it.": "Dejame pensarlo.",
    "Sure, why not?": "Claro, por que no?",
    "Um, I'm still thinking.": "Um, sigo pensandolo.",
    "Ignore her.": "Ignorarla.",
    "Excuse me, but Mahatra sent me...": "Disculpa, pero Mahatra me envio...",
    "Actually, he wants me to help you.": "De hecho, quiere que te ayude.",
    "Give me a minute...": "Dame un minuto...",
    "Here...": "Aqui...",
    "I'd like to see Mr. Bakerlan.": "Me gustaria ver al Sr. Bakerlan.",
    "Have a nice day.": "Que tengas un buen dia.",
    "Alchesh family?": "La familia Alchesh?",
    "Do you know where Mr. Bakerlan is?": "Sabes donde esta el Sr. Bakerlan?",
    "Mr. Metz sent me.": "El Sr. Metz me envio.",
    "No, I'm not.": "No, no lo soy.",
    "They must be busy.": "Deben estar ocupados.",
    "Yes, I have your order.": "Si, tengo tu pedido.",
    "I put it somewhere.": "Lo puse en algun lugar.",
    "Sorry, I lost it.": "Lo siento, lo perdi.",
    "No. I'm not joking.": "No. No estoy bromeando.",
    "Okay, you got me~": "Esta bien, me atrapaste~",
    "You have another assignment for me.": "Tienes otra tarea para mi.",
    "Vigorgra?": "Vigorgra?",
    "Oh, I'm sorry.": "Ah, lo siento.",
    "No, I don't want it!": "No, no lo quiero!",
    "I need Vigorgra for... a friend.": "Necesito Vigorgra para... un amigo.",
    "So what are you studying?": "Que estas estudiando?",
    "Um, I'm a dude...": "Eh, soy hombre...",
    "Why, thank you~": "Oh, gracias~",
    "Look for fresh water.": "Buscar agua fresca.",
    "Just wait for rescue.": "Solo esperar rescate.",
    "Forage for food.": "Buscar comida.",
    "Explore the island.": "Explorar la isla.",
    "Scream for help.": "Gritar por ayuda.",
    "Stay quiet.": "Quedarse callado.",
    "Wait for death to come.": "Esperar a que llegue la muerte.",
    "Find a way out.": "Encontrar una salida.",
    "Try to find my friends.": "Intentar encontrar a mis amigos.",
    "Stay put.": "Quedarme donde estoy.",
    "Continue exploring the dungeon.": "Seguir explorando la mazmorra.",
    "Wait for the case to get solved.": "Esperar a que se resuelva el caso.",
    "Try to find my friends first.": "Intentar encontrar a mis amigos primero.",
    "Solve the murder case on my own.": "Resolver el caso de asesinato por mi cuenta.",
    "Kill the others before they kill me.": "Matar a los demas antes de que me maten.",
    "Wait to see the end.": "Esperar a ver el final.",
    "Plant an apple tree.": "Plantar un manzano.",
    "Look to move to a different world.": "Buscar mudarme a un mundo diferente.",
    "What else? Save the world.": "Que mas? Salvar el mundo.",
    "What else? Go on a crime spree.": "Que mas? Ir de crimen en crimen.",

    # quests_ein select options
    "Give him materials.": "Darle materiales.",
    "Huh.": "Huh.",
    "'What are you talking about?'": "'De que estas hablando?'",
    "Talk about Einbroch.": "Hablar sobre Einbroch.",
    "Ask him to forge a Weapon.": "Pedirle que forje un Arma.",
    "What is that?": "Que es eso?",
    "How am I supposed to get the symbol?": "Como se supone que obtenga el simbolo?",
    "Don't pay him.": "No pagarle.",
    "Pay him.": "Pagarle.",
    "I can help you.": "Puedo ayudarte.",
    "I want to quit.": "Quiero renunciar.",
    "Um, isn't this a forge?": "Um, esto no es una fragua?",
    "Ask about Cooking.": "Preguntar sobre Cocina.",
    "Ask about Einbroch.": "Preguntar sobre Einbroch.",
    "But I like the city life~": "Pero me gusta la vida de ciudad~",
    "Master, I want to learn cooking.": "Maestro, quiero aprender a cocinar.",
    "Then why are you here?": "Entonces por que estas aqui?",
    "Gather them.": "Reunirlos.",

    # quests_hugel select options
    "What was I supposed to gather?": "Que se suponia que debia reunir?",
    "Don't worry, I'm leaving.": "No te preocupes, ya me voy.",
    "Alright.": "De acuerdo.",
    "Whoa, that's too much!": "Oye, eso es demasiado!",
    "It's candy.": "Es un dulce.",
    "It's a book.": "Es un libro.",
    "It's a place.": "Es un lugar.",
    "Ymir was a giant...": "Ymir era un gigante...",
    "Catch them.": "Atraparlos.",
    "Catch them": "Atraparlos",
    "Speak to Euslan": "Hablar con Euslan",
    "Offer to find Thierry": "Ofrecer buscar a Thierry",
    "Ooh, cooking!": "Ooh, cocina!",
    "So what did you": "Entonces que querias",
    "want to ask me...?": "preguntarme...?",
    "I won't. Thanks for the advice.": "No lo hare. Gracias por el consejo.",
    "Yeah, yeah, whatever.": "Si, si, lo que sea.",

    # More common ones
    "About Metz.": "Sobre Metz.",
    "Water": "Agua",
    "Earth": "Tierra",
    "Fire": "Fuego",
    "Wind": "Viento",
    "I see": "Ya veo",
    "Farewell": "Adios",
}


# =============================================================================
# COMPREHENSIVE MES LINE TRANSLATIONS (most frequent + critical)
# =============================================================================
MES_MAP = {
    # UI/System strings
    "^3355FFNext^000000": "^3355FFSiguiente^000000",
    "^3355FFClose^000000": "^3355FFCerrar^000000",
    "^3355FFWait a second! Right now,": "^3355FFEspera un momento! Ahora mismo,",
    "you have too many items in your inventory. Please come back after you've freed up more inventory space.^000000": "tienes demasiados objetos en tu inventario. Por favor vuelve cuando hayas liberado espacio en tu inventario.^000000",
    "you have too many items in your inventory. Please come back after you've made more available inventory space.^000000": "tienes demasiados objetos en tu inventario. Por favor vuelve cuando hayas liberado mas espacio.^000000",

    # Hugel cooking quest repeated strings
    "- *Snip Snip* -": "- *Snip Snip* -",
    "- *Whizz Whizz*-": "- *Whizz Whizz*-",
    "Well, that was": "Bueno, fue una",
    "a fun talk. Come": "charla divertida. Ven",
    "back and visit, 'kay?": "a visitarme, si?",
    "I'll miss you until": "Te extranare hasta",
    "the next time~": "la proxima vez~",
    "Oh, I was going to give": "Oh, iba a darte",
    "you a little something,": "un regalito,",
    "but you've carrying too": "pero estas cargando",
    "many things. Why don't": "demasiadas cosas. Por que",
    "you put some of it away": "no guardas algo de eso",
    "in your Kafra Storage?": "en tu Almacen Kafra?",
    "Well, feel": "Bueno, sientete",
    "free to visit": "libre de visitarme",
    "me whenever": "cuando",
    "you want, 'kay?": "quieras, si?",
    "- You decided to pass by them. -": "- Decidiste pasar de largo. -",
    "^333333*Sigh...*^000000": "^333333*Suspiro...*^000000",
    "^333333*Sigh*^000000": "^333333*Suspiro*^000000",
    "^333333*Ahem*^000000": "^333333*Ejem*^000000",
    "^333333*Ahem!*^000000": "^333333*Ejem!*^000000",
    "^333333*Sob*^000000": "^333333*Sollozo*^000000",
    "^333333*Cries*^000000": "^333333*Llora*^000000",
    "^333333*Pout*^000000": "^333333*Puchero*^000000",
    "^333333*Yawn...*": "^333333*Bostezo...*",
    "Date: **month **day": "Fecha: **mes **dia",
    "Check out the": "Mira las",
    "Now for beginners,": "Ahora para principiantes,",
    "learning to select": "aprender a seleccionar",
    "and use ingredients": "y usar ingredientes",
    "is one of the most": "es uno de los fundamentos",
    "important fundamentals.": "mas importantes.",
    "Cooking is like forging": "Cocinar es como forjar",
    "since specific ingredients": "ya que se necesitan ingredientes",
    "are needed to make specialty": "especificos para hacer",
    "items or dishes. You can't just": "objetos o platillos especiales. No puedes",
    "skip them if you really need": "omitirlos si realmente los",
    "them, right? Right!": "necesitas, verdad? Verdad!",
    "Once you make up your": "Una vez que te decidas",
    "mind to do something,": "a hacer algo,",
    "focus on finishing it, 'kay?": "enfocate en terminarlo, si?",
    "Never cut corners and always": "Nunca tomes atajos y siempre",
    "dedicate yourself to make the": "dedicate a hacer el",
    "very best finished product~": "mejor producto terminado~",
    "Cooking is a little": "Cocinar es un poco",
    "easier if you have": "mas facil si tienes",
    "nicer tools to use,": "mejores herramientas,",
    "but that's it. Tools by": "pero eso es todo. Las herramientas por",

    # Common dialogue lines
    "What...?": "Que...?",
    "Huh...?": "Eh...?",
    "Hmm...": "Hmm...",
    "Hm...?": "Hm...?",
    "Oh...?": "Oh...?",
    "Eh...?": "Eh...?",
    "......": "......",
    "...": "...",
    ".........": ".........",
    "..........": "..........",
    "Farewell.": "Adios.",
    "Welcome.": "Bienvenido.",
    "Greetings.": "Saludos.",
    "*Pout*": "*Puchero*",
}


# =============================================================================
# COMPREHENSIVE PHRASE PATTERNS FOR CONTEXTUAL TRANSLATION
# =============================================================================
def get_phrase_patterns():
    """Return (english, spanish) pairs for phrase-level replacement."""
    return [
        # ---- Long common phrases ----
        ("Please come back after", "Por favor vuelve despues de que"),
        ("I don't think you", "no creo que"),
        ("I don't know what", "no se que"),
        ("I don't know if", "no se si"),
        ("I don't know why", "no se por que"),
        ("I don't know how", "no se como"),
        ("I don't know where", "no se donde"),
        ("I don't know", "no lo se"),
        ("I don't have", "no tengo"),
        ("I don't want to", "no quiero"),
        ("I don't want", "no quiero"),
        ("I don't care", "no me importa"),
        ("I don't understand", "no entiendo"),
        ("I don't believe it", "no lo puedo creer"),
        ("I don't believe", "no creo"),
        ("I don't remember", "no recuerdo"),
        ("I don't mind", "no me molesta"),
        ("you don't have", "no tienes"),
        ("you don't know", "no sabes"),
        ("you don't understand", "no entiendes"),
        ("you don't need", "no necesitas"),
        ("he doesn't", "el no"),
        ("she doesn't", "ella no"),
        ("it doesn't", "no"),
        ("we don't", "no"),
        ("they don't", "ellos no"),
        ("I can't believe", "no puedo creer"),
        ("I can't help", "no puedo evitar"),
        ("I can't stop", "no puedo parar"),
        ("I can't wait", "no puedo esperar"),
        ("I can't do", "no puedo hacer"),
        ("I can't say", "no puedo decir"),
        ("I can't even", "ni siquiera puedo"),
        ("you can't just", "no puedes solo"),
        ("you can't", "no puedes"),
        ("we can't", "no podemos"),
        ("he can't", "el no puede"),
        ("she can't", "ella no puede"),
        ("they can't", "ellos no pueden"),
        ("I couldn't", "no pude"),
        ("you couldn't", "no pudiste"),
        ("I wouldn't", "no lo haria"),
        ("you wouldn't", "no lo harias"),
        ("I shouldn't", "no deberia"),
        ("you shouldn't", "no deberias"),
        ("I won't", "no voy a"),
        ("you won't", "no vas a"),
        ("he won't", "el no va a"),
        ("she won't", "ella no va a"),
        ("they won't", "ellos no van a"),
        ("I haven't", "no he"),
        ("you haven't", "no has"),
        ("I wasn't", "no estaba"),
        ("you weren't", "no estabas"),
        ("it wasn't", "no era"),
        ("that wasn't", "eso no era"),
        ("isn't it", "no es asi"),
        ("aren't you", "no estas"),
        ("I'm sorry, but", "lo siento, pero"),
        ("I'm sorry that", "lamento que"),
        ("I'm sorry.", "lo siento."),
        ("I'm sorry,", "lo siento,"),
        ("I'm sorry", "lo siento"),
        ("I'm afraid", "me temo"),
        ("I'm glad", "me alegro"),
        ("I'm happy", "estoy feliz"),
        ("I'm sure", "estoy seguro"),
        ("I'm not sure", "no estoy seguro"),
        ("I'm not", "no estoy"),
        ("I'm going to", "voy a"),
        ("I'm looking for", "estoy buscando"),
        ("I'm telling you", "te digo"),
        ("I'm trying to", "estoy tratando de"),
        ("I'm waiting for", "estoy esperando"),
        ("I'm worried", "estoy preocupado"),
        ("I'm impressed", "estoy impresionado"),
        ("I'm interested", "estoy interesado"),
        ("I'm so tired", "estoy tan cansado"),
        ("I'm pretty busy", "estoy bastante ocupado"),
        ("I'm just", "solo estoy"),
        ("I'm here", "estoy aqui"),
        ("I'm back", "estoy de vuelta"),
        ("I'm fine", "estoy bien"),
        ("you're here", "estas aqui"),
        ("you're right", "tienes razon"),
        ("you're wrong", "estas equivocado"),
        ("you're not", "no eres"),
        ("you're the one", "tu eres el"),
        ("you're welcome", "de nada"),
        ("you're a", "eres un"),
        ("you're looking", "estas buscando"),
        ("you're going", "vas a"),
        ("he's not", "el no esta"),
        ("he's a", "es un"),
        ("he's the", "es el"),
        ("she's not", "ella no esta"),
        ("she's a", "es una"),
        ("she's the", "es la"),
        ("it's not", "no es"),
        ("it's a", "es un"),
        ("it's the", "es el"),
        ("it's been", "ha sido"),
        ("it's time", "es hora"),
        ("it's too", "es demasiado"),
        ("it's very", "es muy"),
        ("it's just", "es solo"),
        ("it's true", "es verdad"),
        ("that's right", "asi es"),
        ("that's all", "eso es todo"),
        ("that's why", "por eso"),
        ("that's not", "eso no es"),
        ("that's how", "asi es como"),
        ("that's it", "eso es"),
        ("that's good", "eso esta bien"),
        ("that's great", "eso es genial"),
        ("that's fine", "esta bien"),
        ("there's no", "no hay"),
        ("there's a", "hay un"),
        ("there's nothing", "no hay nada"),
        ("there's something", "hay algo"),
        ("there are", "hay"),
        ("There are", "Hay"),
        ("what's going on", "que esta pasando"),
        ("what's wrong", "que pasa"),
        ("what's the", "cual es el"),
        ("what's this", "que es esto"),
        ("what's that", "que es eso"),
        ("who's that", "quien es ese"),
        ("where's the", "donde esta el"),
        ("how's it going", "como va todo"),
        ("we've been", "hemos estado"),
        ("we've got", "tenemos"),
        ("we'll have", "tendremos"),
        ("we'll be", "estaremos"),
        ("we'll see", "veremos"),
        ("I'll be", "estare"),
        ("I'll do", "lo hare"),
        ("I'll have", "tendre"),
        ("I'll give", "te dare"),
        ("I'll take", "tomare"),
        ("I'll try", "intentare"),
        ("I'll wait", "esperare"),
        ("I'll see", "vere"),
        ("I'll come", "vendre"),
        ("I'll go", "ire"),
        ("I'll tell", "te dire"),
        ("I'll send", "enviare"),
        ("I'll make", "hare"),
        ("I'll get", "conseguire"),
        ("I'll let", "dejare"),
        ("I'll keep", "mantendre"),
        ("I'll bring", "traere"),
        ("I'll never", "nunca"),
        ("you'll have", "tendras"),
        ("you'll be", "estaras"),
        ("you'll need", "necesitaras"),
        ("you'll find", "encontraras"),
        ("you'll see", "veras"),
        ("you'll get", "obtendras"),
        ("he'll", "el va a"),
        ("she'll", "ella va a"),
        ("they'll", "ellos van a"),
        ("I've been", "he estado"),
        ("I've heard", "he escuchado"),
        ("I've got", "tengo"),
        ("I've never", "nunca he"),
        ("I've already", "ya he"),
        ("I've done", "he hecho"),
        ("I've found", "he encontrado"),
        ("you've been", "has estado"),
        ("you've got", "tienes"),
        ("you've done", "has hecho"),
        ("Let me see", "Dejame ver"),
        ("let me see", "dejame ver"),
        ("Let me think", "Dejame pensar"),
        ("let me think", "dejame pensar"),
        ("Let me know", "Avisame"),
        ("let me know", "avisame"),
        ("Let me tell", "Dejame contarte"),
        ("let me tell", "dejame contarte"),
        ("Let me explain", "Dejame explicar"),
        ("Let me check", "Dejame revisar"),
        ("Let me give", "Dejame darte"),
        ("Let me help", "Dejame ayudarte"),
        ("Let's see", "Veamos"),
        ("let's see", "veamos"),
        ("Let's go", "Vamos"),
        ("let's go", "vamos"),
        ("Thank you so much!", "Muchas gracias!"),
        ("Thank you so much", "Muchas gracias"),
        ("Thank you very much", "Muchas gracias"),
        ("Thank you for", "Gracias por"),
        ("thank you for", "gracias por"),
        ("Thank you.", "Gracias."),
        ("Thank you~", "Gracias~"),
        ("Thank you", "Gracias"),
        ("thank you", "gracias"),
        ("Thanks for", "Gracias por"),
        ("thanks for", "gracias por"),
        ("Thanks so much", "Muchas gracias"),
        ("Thanks~", "Gracias~"),
        ("Thanks.", "Gracias."),
        ("Thanks,", "Gracias,"),
        ("Thanks", "Gracias"),
        ("thanks", "gracias"),
        ("Don't worry about", "No te preocupes por"),
        ("Don't worry,", "No te preocupes,"),
        ("Don't worry", "No te preocupes"),
        ("don't worry", "no te preocupes"),
        ("Don't forget", "No olvides"),
        ("don't forget", "no olvides"),
        ("Don't you think", "No crees"),
        ("don't you think", "no crees"),
        ("Welcome to the", "Bienvenido al"),
        ("Welcome to", "Bienvenido a"),
        ("Welcome back", "Bienvenido de vuelta"),
        ("Welcome,", "Bienvenido,"),
        ("Welcome.", "Bienvenido."),
        ("Welcome", "Bienvenido"),
        ("Good luck~", "Buena suerte~"),
        ("Good luck.", "Buena suerte."),
        ("Good luck,", "Buena suerte,"),
        ("Good luck on your", "Buena suerte en tus"),
        ("Good luck in", "Buena suerte en"),
        ("Good luck", "Buena suerte"),
        ("good luck", "buena suerte"),
        ("Good work", "Buen trabajo"),
        ("Good morning", "Buenos dias"),
        ("Good evening", "Buenas noches"),
        ("Good night", "Buenas noches"),
        ("Good day", "Buen dia"),
        ("Take care.", "Cuidate."),
        ("Take care,", "Cuidate,"),
        ("Take care~", "Cuidate~"),
        ("Take care now", "Cuidate"),
        ("Take care", "Cuidate"),
        ("take care", "cuidate"),
        ("Take your time", "Tomate tu tiempo"),
        ("take your time", "tomate tu tiempo"),
        ("Come back", "Vuelve"),
        ("come back", "vuelve"),
        ("Excuse me...", "Disculpa..."),
        ("Excuse me.", "Disculpa."),
        ("Excuse me,", "Disculpa,"),
        ("Excuse me", "Disculpa"),
        ("EXCUSE ME!", "DISCULPA!"),
        ("Of course,", "Por supuesto,"),
        ("Of course.", "Por supuesto."),
        ("Of course", "Por supuesto"),
        ("of course", "por supuesto"),
        ("In any case", "En todo caso"),
        ("in any case", "en todo caso"),
        ("In the end", "Al final"),
        ("in the end", "al final"),
        ("After all,", "Despues de todo,"),
        ("After all", "Despues de todo"),
        ("after all", "despues de todo"),
        ("In fact,", "De hecho,"),
        ("In fact", "De hecho"),
        ("in fact", "de hecho"),
        ("By the way,", "Por cierto,"),
        ("By the way", "Por cierto"),
        ("by the way", "por cierto"),
        ("For now,", "Por ahora,"),
        ("For now", "Por ahora"),
        ("for now", "por ahora"),
        ("right now", "ahora mismo"),
        ("Right now", "Ahora mismo"),
        ("right away", "de inmediato"),
        ("Right away", "De inmediato"),
        ("right here", "aqui mismo"),
        ("However,", "Sin embargo,"),
        ("however,", "sin embargo,"),
        ("However.", "Sin embargo."),
        ("However", "Sin embargo"),
        ("however", "sin embargo"),
        ("Although ", "Aunque "),
        ("although ", "aunque "),
        ("Unfortunately,", "Desafortunadamente,"),
        ("Unfortunately", "Desafortunadamente"),
        ("unfortunately", "desafortunadamente"),
        ("Apparently,", "Al parecer,"),
        ("Apparently", "Al parecer"),
        ("apparently", "al parecer"),
        ("Actually,", "En realidad,"),
        ("Actually", "En realidad"),
        ("actually", "en realidad"),
        ("Congratulations", "Felicidades"),
        ("congratulations", "felicidades"),
        ("Please come back", "Por favor vuelve"),
        ("please come back", "por favor vuelve"),
        ("Please bring", "Por favor trae"),
        ("please bring", "por favor trae"),
        ("Please wait", "Por favor espera"),
        ("please wait", "por favor espera"),
        ("Please leave", "Por favor vete"),
        ("please leave", "por favor vete"),
        ("Please don't", "Por favor no"),
        ("please don't", "por favor no"),
        ("Please do", "Por favor"),
        ("Please talk", "Por favor habla"),
        ("Please take", "Por favor toma"),
        ("Please go", "Por favor ve"),
        ("Please try", "Por favor intenta"),
        ("Please visit", "Por favor visita"),
        ("Please give", "Por favor dale"),
        ("Please come", "Por favor ven"),
        ("Please tell", "Por favor dile"),
        ("Please be", "Por favor se"),
        ("Please understand", "Por favor entiende"),
        ("Please", "Por favor"),
        ("please", "por favor"),
        ("Would you like to", "Te gustaria"),
        ("would you like to", "te gustaria"),
        ("Would you mind", "Te importaria"),
        ("Would you please", "Podrias por favor"),
        ("Would you", "Podrias"),
        ("would you", "podrias"),
        ("Could you please", "Podrias por favor"),
        ("Could you", "Podrias"),
        ("could you", "podrias"),
        ("What are you doing", "Que estas haciendo"),
        ("what are you doing", "que estas haciendo"),
        ("What are you talking about", "De que estas hablando"),
        ("What are you", "Que estas"),
        ("What do you think", "Que piensas"),
        ("What do you mean", "Que quieres decir"),
        ("What do you want", "Que quieres"),
        ("What do you need", "Que necesitas"),
        ("What do you know", "Que sabes"),
        ("What did you", "Que"),
        ("What happened", "Que paso"),
        ("What is this", "Que es esto"),
        ("What is that", "Que es eso"),
        ("What is the", "Cual es el"),
        ("What is it", "Que es"),
        ("What is", "Que es"),
        ("Where is", "Donde esta"),
        ("Where are", "Donde estan"),
        ("Who are you", "Quien eres"),
        ("who are you", "quien eres"),
        ("Who is this", "Quien es este"),
        ("Who is that", "Quien es ese"),
        ("Who is", "Quien es"),
        ("How are you", "Como estas"),
        ("how are you", "como estas"),
        ("How did you", "Como"),
        ("How is it", "Como esta"),
        ("How is", "Como esta"),
        ("How can I", "Como puedo"),
        ("How can you", "Como puedes"),
        ("Are you sure", "Estas seguro"),
        ("Are you ready", "Estas listo"),
        ("Are you okay", "Estas bien"),
        ("Are you", "Estas"),
        ("are you", "estas"),
        ("Do you have", "Tienes"),
        ("do you have", "tienes"),
        ("Do you know", "Sabes"),
        ("do you know", "sabes"),
        ("Do you think", "Crees"),
        ("do you think", "crees"),
        ("Do you want", "Quieres"),
        ("do you want", "quieres"),
        ("Do you remember", "Recuerdas"),
        ("do you remember", "recuerdas"),
        ("Do you understand", "Entiendes"),
        ("Have you heard", "Has escuchado"),
        ("have you heard", "has escuchado"),
        ("Have you ever", "Alguna vez has"),
        ("Have you been", "Has estado"),
        ("have you been", "has estado"),
        ("Have you finished", "Has terminado"),
        ("Did you know", "Sabias"),
        ("did you know", "sabias"),
        ("I wonder", "Me pregunto"),
        ("I suppose", "Supongo"),
        ("I guess", "Supongo"),
        ("I wish", "Deseo"),
        ("I heard", "Escuche"),
        ("I hope", "Espero"),
        ("I believe", "Creo"),
        ("I think", "Creo"),
        ("I know", "Se"),
        ("I feel", "Siento"),
        ("I need", "Necesito"),
        ("I want", "Quiero"),
        ("I have", "Tengo"),
        ("I had", "Tenia"),
        ("I was", "Estaba"),
        ("I am", "Soy"),
        ("I will", "Voy a"),
        ("I would", "Me gustaria"),
        ("I could", "Podria"),
        ("I should", "Deberia"),
        ("I must", "Debo"),
        ("I might", "Podria"),
        ("I may", "Podria"),
        ("I used to", "Solia"),
        ("I really", "Realmente"),
        ("I just", "Solo"),
        ("you know", "sabes"),
        ("You know", "Sabes"),
        ("you see", "veras"),
        ("You see", "Veras"),
        ("you should", "deberias"),
        ("You should", "Deberias"),
        ("you must", "debes"),
        ("You must", "Debes"),
        ("you need", "necesitas"),
        ("You need", "Necesitas"),
        ("you want", "quieres"),
        ("You want", "Quieres"),
        ("you can", "puedes"),
        ("You can", "Puedes"),
        ("you have", "tienes"),
        ("You have", "Tienes"),
        ("you are", "eres"),
        ("You are", "Eres"),
        ("you were", "estabas"),
        ("You were", "Estabas"),
        ("you will", "vas a"),
        ("You will", "Vas a"),
        ("you may", "puedes"),
        ("You may", "Puedes"),
        ("you might", "podrias"),
        ("You might", "Podrias"),
        ("He is", "El es"),
        ("he is", "el es"),
        ("She is", "Ella es"),
        ("she is", "ella es"),
        ("It is", "Es"),
        ("it is", "es"),
        ("We are", "Estamos"),
        ("we are", "estamos"),
        ("They are", "Ellos son"),
        ("they are", "ellos son"),
        ("it seems", "parece"),
        ("It seems", "Parece"),
        ("it looks", "parece"),
        ("It looks", "Parece"),
        ("my friend", "mi amigo"),
        ("my friends", "mis amigos"),
        ("your friend", "tu amigo"),
        ("your friends", "tus amigos"),
        ("a long time", "mucho tiempo"),
        ("long time", "mucho tiempo"),
        ("this time", "esta vez"),
        ("next time", "la proxima vez"),
        ("last time", "la ultima vez"),
        ("first time", "la primera vez"),
        ("every time", "cada vez"),
        ("some time", "algo de tiempo"),
        ("at this moment", "en este momento"),
        ("at the moment", "por el momento"),
        ("at least", "al menos"),
        ("at all", "en absoluto"),
        ("so long as", "siempre y cuando"),
        ("as well as", "asi como"),
        ("as well", "tambien"),
        ("as soon as", "tan pronto como"),
        ("as much as", "tanto como"),
        ("as far as", "en lo que"),
        ("once again", "una vez mas"),
        ("Once again", "Una vez mas"),
        ("instead of", "en lugar de"),
        ("Instead of", "En lugar de"),
        ("because of", "debido a"),
        ("Because of", "Debido a"),
        ("on your own", "por tu cuenta"),
        ("on my own", "por mi cuenta"),
        ("on our own", "por nuestra cuenta"),
        ("each other", "entre si"),
        ("no one", "nadie"),
        ("No one", "Nadie"),
        ("nothing but", "nada mas que"),
        ("nothing more", "nada mas"),
        ("nothing less", "nada menos"),
        ("nothing else", "nada mas"),
        ("never mind", "no importa"),
        ("Never mind", "No importa"),
        ("what if", "que pasaria si"),
        ("What if", "Que pasaria si"),
        ("even if", "incluso si"),
        ("Even if", "Incluso si"),
        ("even though", "aunque"),
        ("Even though", "Aunque"),
        ("as if", "como si"),
        ("Farewell~", "Adios~"),
        ("Farewell,", "Adios,"),
        ("Farewell.", "Adios."),
        ("Farewell", "Adios"),
        ("farewell", "adios"),
        ("Nothing.", "Nada."),
        ("nothing", "nada"),
        ("something", "algo"),
        ("Something", "Algo"),
        ("everything", "todo"),
        ("Everything", "Todo"),
        ("someone", "alguien"),
        ("Someone", "Alguien"),
        ("anyone", "alguien"),
        ("Anyone", "Alguien"),
        ("everyone", "todos"),
        ("Everyone", "Todos"),
        ("nobody", "nadie"),
        ("Nobody", "Nadie"),
        ("never", "nunca"),
        ("Never", "Nunca"),
        ("always", "siempre"),
        ("Always", "Siempre"),
        ("sometimes", "a veces"),
        ("Sometimes", "A veces"),
        ("usually", "usualmente"),
        ("recently", "recientemente"),
        ("Recently", "Recientemente"),
        ("lately", "ultimamente"),
        ("Lately", "Ultimamente"),
        ("enough", "suficiente"),
        ("dangerous", "peligroso"),
        ("Dangerous", "Peligroso"),
        ("adventurer", "aventurero"),
        ("adventurers", "aventureros"),
        ("Adventurer", "Aventurero"),
        ("warrior", "guerrero"),
        ("warriors", "guerreros"),
        ("Warrior", "Guerrero"),
        ("Blacksmith", "Herrero"),
        ("blacksmith", "herrero"),
        ("Alchemist", "Alquimista"),
        ("alchemist", "alquimista"),
        ("Alchemists", "Alquimistas"),
        ("Wizard", "Mago"),
        ("wizard", "mago"),
        ("Wizards", "Magos"),
        ("Priestess", "Sacerdotisa"),
        ("Priest", "Sacerdote"),
        ("Hunter", "Cazador"),
        ("Hunters", "Cazadores"),
        ("Knight", "Caballero"),
        ("Merchants", "Mercaderes"),
        ("Merchant", "Mercader"),
        ("merchant", "mercader"),
        ("Swordman", "Espadachin"),
        ("Novice", "Aprendiz"),
        ("sir.", "senor."),
        ("madam.", "senora."),
        ("monsters", "monstruos"),
        ("monster", "monstruo"),
        ("Monsters", "Monstruos"),
        ("Monster", "Monstruo"),
        ("birthday", "cumpleanos"),
        ("treasure", "tesoro"),
        ("brother", "hermano"),
        ("sister", "hermana"),
        ("father", "padre"),
        ("Father", "Padre"),
        ("mother", "madre"),
        ("Mother", "Madre"),
        ("daughter", "hija"),
        ("husband", "esposo"),
        ("family", "familia"),
        ("friend", "amigo"),
        ("friends", "amigos"),
        ("master", "maestro"),
        ("Master", "Maestro"),
        ("deliver", "entregar"),
        ("delivery", "entrega"),
        ("message", "mensaje"),
        ("letter", "carta"),
        ("weapon", "arma"),
        ("weapons", "armas"),
        ("armor", "armadura"),
        ("research", "investigacion"),
        ("Research", "Investigacion"),
        ("ancient", "antiguo"),
        ("Ancient", "Antiguo"),
        ("secret", "secreto"),
        ("Secret", "Secreto"),
        ("courage", "coraje"),
        ("honor", "honor"),
        ("experience", "experiencia"),
        ("knowledge", "conocimiento"),
    ]


# =============================================================================
# MAIN TRANSLATION LOGIC
# =============================================================================

def translate_content(content):
    """Translate mes content or select option to LATAM Spanish."""
    if not content:
        return content

    # Check exact matches in MES_MAP
    if content in MES_MAP:
        return MES_MAP[content]

    # Check exact matches in SELECT_OPTIONS (for select options)
    if content in SELECT_OPTIONS:
        return SELECT_OPTIONS[content]

    # Check if content is mostly non-text
    clean = re.sub(r'\^[0-9a-fA-F]{6}', '', content)
    alpha = sum(1 for c in clean if c.isalpha())
    if alpha < 3:
        return content

    # Apply phrase-level translation
    return apply_phrase_translation(content)


def apply_phrase_translation(text):
    """Apply phrase patterns to translate English text."""
    if not text:
        return text

    # Protect color codes and variables
    protected = {}
    counter = [0]

    def protect(m):
        key = f"@@{counter[0]}@@"
        counter[0] += 1
        protected[key] = m.group(0)
        return key

    result = text
    # Protect color codes
    result = re.sub(r'\^[0-9a-fA-F]{6}', protect, result)
    # Protect variable concatenations
    result = re.sub(r'"\s*\+[^"]+\+\s*"', protect, result)
    result = re.sub(r'\+\s*strcharinfo\([^)]+\)\s*\+', protect, result)
    result = re.sub(r'\+\s*\.\@\w+\$?\s*\+', protect, result)

    # Apply phrase patterns
    for eng, esp in get_phrase_patterns():
        if eng in result:
            result = result.replace(eng, esp, 1)

    # Restore protected tokens
    for key, val in protected.items():
        result = result.replace(key, val)

    return result


def process_line(line):
    """Process a single script line."""
    stripped = line.strip()
    if stripped.startswith('//') or not stripped:
        return line

    # Handle mes "..." lines
    mes_match = re.match(r'^(\s*mes\s+)"(.*)"\s*;(.*)$', line)
    if mes_match:
        prefix = mes_match.group(1)
        content = mes_match.group(2)
        suffix = mes_match.group(3)

        if re.match(r'^\[.*\]$', content.strip()):
            return line

        translated = translate_content(content)
        result = f'{prefix}"{translated}";'
        if suffix and suffix.strip():
            result += suffix
        return result + '\n'

    # Handle select("...")
    select_match = re.search(r'(select\()"([^"]+)"\)', line)
    if select_match:
        full_match = select_match.group(0)
        prefix_sel = select_match.group(1)
        content = select_match.group(2)

        options = content.split(':')
        translated_options = []
        for opt in options:
            if opt in SELECT_OPTIONS:
                translated_options.append(SELECT_OPTIONS[opt])
            else:
                translated_options.append(translate_content(opt))
        new_content = ':'.join(translated_options)
        new_select = f'{prefix_sel}"{new_content}")'
        return line.replace(full_match, new_select)

    # Handle mapannounce strings
    ann_match = re.search(r'(mapannounce\s+"[^"]+"\s*,\s*)"([^"]+)"', line)
    if ann_match:
        full = ann_match.group(0)
        pfx = ann_match.group(1)
        content = ann_match.group(2)
        translated = translate_content(content)
        return line.replace(full, f'{pfx}"{translated}"')

    return line


def process_file(filepath):
    """Process a complete quest file."""
    print(f"Processing: {filepath}")

    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        original = f.readlines()

    output = [process_line(line) for line in original]

    assert len(output) == len(original), f"Line count mismatch: {len(output)} vs {len(original)}"

    with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
        f.writelines(output)

    # Count changes
    changed = sum(1 for o, n in zip(original, output) if o != n)
    print(f"  Done: {len(original)} lines, {changed} lines translated, line count preserved")


if __name__ == '__main__':
    base = "D:/Xponzy Network/Ragnarok-Server/rathena/npc/quests"
    for fname in ["the_sign_quest.txt", "quests_ein.txt", "quests_hugel.txt"]:
        process_file(os.path.join(base, fname))

    # Clean up
    print("\nTranslation complete!")
