<?php
/**
 * KunaiRO — YAML to SQL converter for rAthena item_db and mob_db
 * Usage: php yaml2sql_php.php
 */

$rathenaRoot = realpath(__DIR__ . '/..');
$dbPath      = $rathenaRoot . '/db/pre-re';
$sqlPath     = $rathenaRoot . '/sql-files';

echo "=== KunaiRO yaml2sql converter ===\n\n";

// =====================================================================
// ITEM DATABASE
// =====================================================================
$itemFiles = ['item_db_equip.yml', 'item_db_usable.yml', 'item_db_etc.yml'];

$jobMap = [
	'All' => 'job_all', 'Acolyte' => 'job_acolyte', 'Alchemist' => 'job_alchemist',
	'Archer' => 'job_archer', 'Assassin' => 'job_assassin', 'BardDancer' => 'job_barddancer',
	'Blacksmith' => 'job_blacksmith', 'Crusader' => 'job_crusader', 'Gunslinger' => 'job_gunslinger',
	'Hunter' => 'job_hunter', 'Knight' => 'job_knight', 'Mage' => 'job_mage',
	'Merchant' => 'job_merchant', 'Monk' => 'job_monk', 'Ninja' => 'job_ninja',
	'Novice' => 'job_novice', 'Priest' => 'job_priest', 'Rogue' => 'job_rogue',
	'Sage' => 'job_sage', 'SoulLinker' => 'job_soullinker', 'StarGladiator' => 'job_stargladiator',
	'SuperNovice' => 'job_supernovice', 'Swordman' => 'job_swordman',
	'Taekwon' => 'job_taekwon', 'Thief' => 'job_thief', 'Wizard' => 'job_wizard',
];

$locationMap = [
	'Head_Top' => 'location_head_top', 'Head_Mid' => 'location_head_mid',
	'Head_Low' => 'location_head_low', 'Armor' => 'location_armor',
	'Right_Hand' => 'location_right_hand', 'Left_Hand' => 'location_left_hand',
	'Garment' => 'location_garment', 'Shoes' => 'location_shoes',
	'Right_Accessory' => 'location_right_accessory', 'Left_Accessory' => 'location_left_accessory',
	'Costume_Head_Top' => 'location_costume_head_top', 'Costume_Head_Mid' => 'location_costume_head_mid',
	'Costume_Head_Low' => 'location_costume_head_low', 'Costume_Garment' => 'location_costume_garment',
	'Ammo' => 'location_ammo', 'Shadow_Armor' => 'location_shadow_armor',
	'Shadow_Weapon' => 'location_shadow_weapon', 'Shadow_Shield' => 'location_shadow_shield',
	'Shadow_Shoes' => 'location_shadow_shoes',
	'Shadow_Right_Accessory' => 'location_shadow_right_accessory',
	'Shadow_Left_Accessory' => 'location_shadow_left_accessory',
];

$allItems = [];
foreach ($itemFiles as $file) {
	$fullPath = "$dbPath/$file";
	if (!file_exists($fullPath)) { echo "SKIP: $file\n"; continue; }
	echo "Parsing $file...\n";
	$items = parseItemYaml($fullPath);
	echo "  Found " . count($items) . " items\n";
	$allItems = array_merge($allItems, $items);
}

$sqlOut = "-- Generated by yaml2sql_php.php\n-- Items: " . count($allItems) . "\n\nTRUNCATE TABLE `item_db`;\n\n";

foreach ($allItems as $item) {
	$v = function($k, $default = 'NULL') use ($item) {
		if (!isset($item[$k])) return $default;
		$val = $item[$k];
		if ($val === true) return '1';
		if ($val === false) return '0';
		if (is_numeric($val)) return $val;
		return "'" . addslashes($val) . "'";
	};

	$cols = ['id', 'name_aegis', 'name_english', 'type', 'subtype', 'price_buy', 'price_sell',
		'weight', 'attack', 'defense', '`range`', 'slots', 'refineable', 'view',
		'weapon_level', 'armor_level', 'equip_level_min', 'equip_level_max',
		'script', 'equip_script', 'unequip_script'];
	$vals = [$v('Id'), $v('AegisName', "''"), $v('Name', "''"), $v('Type', "''"), $v('SubType'),
		$v('Buy'), $v('Sell'), $v('Weight'), $v('Attack'), $v('Defense'), $v('Range'),
		$v('Slots'), $v('Refineable'), $v('View'), $v('WeaponLevel'), $v('ArmorLevel'),
		$v('EquipLevelMin'), $v('EquipLevelMax'), $v('Script'), $v('EquipScript'), $v('UnEquipScript')];

	// Jobs
	$jobs = $item['Jobs'] ?? [];
	foreach ($jobMap as $yk => $col) {
		$cols[] = $col;
		$vals[] = isset($jobs[$yk]) ? (($jobs[$yk]) ? '1' : '0') : 'NULL';
	}
	// Locations
	$locs = $item['Locations'] ?? [];
	foreach ($locationMap as $yk => $col) {
		$cols[] = $col;
		$vals[] = isset($locs[$yk]) ? (($locs[$yk]) ? '1' : '0') : 'NULL';
	}

	$sqlOut .= "INSERT INTO `item_db` (" . implode(',', $cols) . ") VALUES (" . implode(',', $vals) . ");\n";
}
file_put_contents("$sqlPath/item_db_data.sql", $sqlOut);
echo "\nWrote " . count($allItems) . " items to item_db_data.sql\n\n";

// =====================================================================
// MOB DATABASE
// =====================================================================
$modeMap = [
	'CanMove' => 'mode_canmove', 'Looter' => 'mode_looter', 'Aggressive' => 'mode_aggressive',
	'Assist' => 'mode_assist', 'CastSensorIdle' => 'mode_castsensoridle',
	'NoRandomWalk' => 'mode_norandomwalk', 'NoCast' => 'mode_nocast',
	'CanAttack' => 'mode_canattack', 'CastSensorChase' => 'mode_castsensorchase',
	'ChangeChase' => 'mode_changechase', 'Angry' => 'mode_angry',
	'ChangeTargetMelee' => 'mode_changetargetmelee', 'ChangeTargetChase' => 'mode_changetargetchase',
	'TargetWeak' => 'mode_targetweak', 'RandomTarget' => 'mode_randomtarget',
	'IgnoreMelee' => 'mode_ignoremelee', 'IgnoreMagic' => 'mode_ignoremagic',
	'IgnoreRanged' => 'mode_ignoreranged', 'Mvp' => 'mode_mvp',
	'IgnoreMisc' => 'mode_ignoremisc', 'KnockbackImmune' => 'mode_knockbackimmune',
	'TeleportBlock' => 'mode_teleportblock', 'FixedItemDrop' => 'mode_fixeditemdrop',
	'Detector' => 'mode_detector', 'StatusImmune' => 'mode_statusimmune',
	'SkillImmune' => 'mode_skillimmune',
];

echo "Parsing mob_db.yml...\n";
$mobs = parseMobYaml("$dbPath/mob_db.yml");
echo "  Found " . count($mobs) . " mobs\n";

$mobSql = "-- Generated by yaml2sql_php.php\n-- Mobs: " . count($mobs) . "\n\nTRUNCATE TABLE `mob_db`;\n\n";

foreach ($mobs as $mob) {
	$v = function($k, $default = 'NULL') use ($mob) {
		if (!isset($mob[$k])) return $default;
		$val = $mob[$k];
		if ($val === true) return '1';
		if ($val === false) return '0';
		if (is_numeric($val)) return $val;
		return "'" . addslashes($val) . "'";
	};

	$cols = ['id','name_aegis','name_english','name_japanese','level','hp','sp',
		'base_exp','job_exp','mvp_exp','attack','attack2','defense','magic_defense',
		'str','agi','vit','`int`','dex','luk','attack_range','skill_range','chase_range',
		'size','race','element','element_level','walk_speed','attack_delay',
		'attack_motion','damage_motion','ai','class'];
	$jname = isset($mob['JapaneseName']) ? $v('JapaneseName') : $v('Name', "''");
	$vals = [$v('Id'), $v('AegisName',"''"), $v('Name',"''"), $jname,
		$v('Level'), $v('Hp'), $v('Sp'), $v('BaseExp'), $v('JobExp'), $v('MvpExp'),
		$v('Attack'), $v('Attack2'), $v('Defense'), $v('MagicDefense'),
		$v('Str'), $v('Agi'), $v('Vit'), $v('Int'), $v('Dex'), $v('Luk'),
		$v('AttackRange'), $v('SkillRange'), $v('ChaseRange'),
		$v('Size'), $v('Race'), $v('Element'), $v('ElementLevel'),
		$v('WalkSpeed'), $v('AttackDelay'), $v('AttackMotion'), $v('DamageMotion'),
		$v('Ai'), $v('Class')];

	// Modes
	$modes = $mob['Modes'] ?? [];
	foreach ($modeMap as $yk => $col) {
		$cols[] = $col;
		$vals[] = isset($modes[$yk]) ? (($modes[$yk]) ? '1' : '0') : 'NULL';
	}

	// MVP Drops (max 3)
	$mvpDrops = $mob['MvpDrops'] ?? [];
	for ($i = 1; $i <= 3; $i++) {
		$d = $mvpDrops[$i-1] ?? null;
		$cols[] = "mvpdrop{$i}_item";
		$cols[] = "mvpdrop{$i}_rate";
		$vals[] = $d ? "'" . addslashes($d['Item']) . "'" : 'NULL';
		$vals[] = $d ? intval($d['Rate']) : 'NULL';
	}

	// Regular Drops (max 10)
	$drops = $mob['Drops'] ?? [];
	for ($i = 1; $i <= 10; $i++) {
		$d = $drops[$i-1] ?? null;
		$cols[] = "drop{$i}_item";
		$cols[] = "drop{$i}_rate";
		$cols[] = "drop{$i}_nosteal";
		$vals[] = $d ? "'" . addslashes($d['Item']) . "'" : 'NULL';
		$vals[] = $d ? intval($d['Rate']) : 'NULL';
		$vals[] = ($d && !empty($d['StealProtected'])) ? '1' : 'NULL';
	}

	$mobSql .= "INSERT INTO `mob_db` (" . implode(',', $cols) . ") VALUES (" . implode(',', $vals) . ");\n";
}

file_put_contents("$sqlPath/mob_db_data.sql", $mobSql);
echo "Wrote " . count($mobs) . " mobs to mob_db_data.sql\n\n";
echo "=== DONE ===\nImport into MySQL:\n  item_db_data.sql\n  mob_db_data.sql\n";

// =====================================================================
// PARSERS
// =====================================================================
function parseItemYaml($file) {
	$items = [];
	$lines = file($file, FILE_IGNORE_NEW_LINES);
	$current = null;
	$inSection = null;
	$scriptBuffer = '';

	for ($i = 0; $i < count($lines); $i++) {
		$line = $lines[$i];
		$trimmed = ltrim($line);
		if ($trimmed === '' || $trimmed[0] === '#') continue;

		if (preg_match('/^  - Id:\s*(\d+)/', $line, $m)) {
			if ($current !== null) {
				if ($scriptBuffer && $inSection) { $current[$inSection] = trim($scriptBuffer); $scriptBuffer = ''; }
				$items[] = $current;
			}
			$current = ['Id' => intval($m[1])];
			$inSection = null; $scriptBuffer = '';
			continue;
		}
		if ($current === null) continue;

		if (preg_match('/^    (Script|EquipScript|UnEquipScript):\s*\|/', $line, $m)) {
			$inSection = $m[1]; $scriptBuffer = ''; continue;
		}
		if ($inSection && in_array($inSection, ['Script','EquipScript','UnEquipScript'])) {
			if (preg_match('/^      /', $line)) { $scriptBuffer .= trim($line) . ' '; continue; }
			else { $current[$inSection] = trim($scriptBuffer); $scriptBuffer = ''; $inSection = null; }
		}
		if (preg_match('/^    Jobs:\s*$/', $line)) { $inSection = 'Jobs'; $current['Jobs'] = []; continue; }
		if (preg_match('/^    Locations:\s*$/', $line)) { $inSection = 'Locations'; $current['Locations'] = []; continue; }
		if (preg_match('/^    (Classes|Flags|Trade|Delay|Stack|NoUse):\s*$/', $line)) { $inSection = 'skip'; continue; }

		if ($inSection === 'Jobs' && preg_match('/^\s+(\w+):\s*(true|false)/', $trimmed, $m)) {
			$current['Jobs'][$m[1]] = ($m[2] === 'true'); continue;
		}
		if ($inSection === 'Locations' && preg_match('/^\s+(\w+):\s*(true|false)/', $trimmed, $m)) {
			$current['Locations'][$m[1]] = ($m[2] === 'true'); continue;
		}
		if ($inSection === 'skip' && preg_match('/^\s{6,}/', $line)) continue;

		if (preg_match('/^    (\w+):\s*(.+)$/', $line, $m)) {
			$key = $m[1]; $val = trim($m[2]);
			if ($val === 'true') $val = true; elseif ($val === 'false') $val = false;
			elseif (is_numeric($val)) $val = intval($val);
			$current[$key] = $val; $inSection = null;
		}
	}
	if ($current !== null) {
		if ($scriptBuffer && $inSection) $current[$inSection] = trim($scriptBuffer);
		$items[] = $current;
	}
	return $items;
}

function parseMobYaml($file) {
	$mobs = [];
	$lines = file($file, FILE_IGNORE_NEW_LINES);
	$current = null;
	$inSection = null;
	$currentDrop = null;

	for ($i = 0; $i < count($lines); $i++) {
		$line = $lines[$i];
		if (trim($line) === '' || trim($line)[0] === '#') continue;

		// New mob entry (2-space indent)
		if (preg_match('/^  - Id:\s*(\d+)/', $line, $m)) {
			if ($currentDrop && $current && $inSection) {
				$current[$inSection][] = $currentDrop; $currentDrop = null;
			}
			if ($current !== null) $mobs[] = $current;
			$current = ['Id' => intval($m[1])]; $inSection = null; $currentDrop = null;
			continue;
		}
		if ($current === null) continue;

		// Section headers (4-space indent, no value)
		if (preg_match('/^    (Modes|Drops|MvpDrops|RaceGroups|MvpModes):\s*$/', $line, $m)) {
			if ($currentDrop && $inSection) { $current[$inSection][] = $currentDrop; $currentDrop = null; }
			$inSection = $m[1];
			if (!isset($current[$inSection]) && in_array($inSection, ['Modes','Drops','MvpDrops'])) {
				$current[$inSection] = [];
			}
			continue;
		}

		// Inside Modes section (6-space indent)
		if ($inSection === 'Modes' && preg_match('/^      (\w+):\s*(true|false)/', $line, $m)) {
			$current['Modes'][$m[1]] = ($m[2] === 'true'); continue;
		}

		// Inside RaceGroups (6-space indent) — skip
		if ($inSection === 'RaceGroups' && preg_match('/^      /', $line)) { continue; }

		// Inside Drops/MvpDrops — new drop item (6-space indent with -)
		if (($inSection === 'Drops' || $inSection === 'MvpDrops') && preg_match('/^      - Item:\s*(.+)/', $line, $m)) {
			if ($currentDrop) { $current[$inSection][] = $currentDrop; }
			$currentDrop = ['Item' => trim($m[1])]; continue;
		}
		// Drop sub-fields (8-space indent)
		if ($currentDrop && preg_match('/^        Rate:\s*(\d+)/', $line, $m)) {
			$currentDrop['Rate'] = intval($m[1]); continue;
		}
		if ($currentDrop && preg_match('/^        StealProtected:\s*(true|false)/', $line, $m)) {
			$currentDrop['StealProtected'] = ($m[1] === 'true'); continue;
		}
		if ($currentDrop && preg_match('/^        /', $line)) { continue; } // skip other drop fields

		// Regular top-level key:value (4-space indent)
		if (preg_match('/^    (\w+):\s*(.+)$/', $line, $m)) {
			if ($currentDrop && $inSection) { $current[$inSection][] = $currentDrop; $currentDrop = null; }
			$inSection = null;
			$key = $m[1]; $val = trim($m[2]);
			if ($val === 'true') $val = true; elseif ($val === 'false') $val = false;
			elseif (is_numeric($val)) $val = intval($val);
			$current[$key] = $val;
		}
	}
	if ($currentDrop && $current && $inSection) $current[$inSection][] = $currentDrop;
	if ($current !== null) $mobs[] = $current;
	return $mobs;
}
