#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate translation_map.txt for rAthena quest NPC dialogue.
English -> LATAM Spanish (tuteo).
Comprehensive rule-based translation engine for game dialogue.
"""

import re
import os

BASEDIR = r'D:\Xponzy Network\Ragnarok-Server\rathena\npc\re\quests'

def load_strings():
    with open(os.path.join(BASEDIR, '_to_translate.txt'), 'r', encoding='utf-8') as f:
        return [line.rstrip('\n') for line in f]

# ============================================================================
# EXACT TRANSLATION MAP for common short phrases
# ============================================================================
EXACT = {
    # --- Short UI / select() phrases ---
    "Yes": "Si",
    "Yes.": "Si.",
    "Yes!": "Si!",
    "No": "No",
    "No.": "No.",
    "No!": "No!",
    "No?": "No?",
    "OK": "OK",
    "OK.": "OK.",
    "Okay": "De acuerdo",
    "Okay.": "De acuerdo.",
    "Okay!": "De acuerdo!",
    "Sure": "Claro",
    "Sure.": "Claro.",
    "Sure!": "Claro!",
    "Quit.": "Salir.",
    "Quit": "Salir",
    "Leave.": "Irse.",
    "Leave": "Irse",
    "Cancel": "Cancelar",
    "Cancel.": "Cancelar.",
    "Accept": "Aceptar",
    "Accept.": "Aceptar.",
    "Decline": "Rechazar",
    "Decline.": "Rechazar.",
    "Refuse": "Rechazar",
    "Exchange": "Intercambiar",
    "Continue": "Continuar",
    "Continue.": "Continuar.",
    "Help": "Ayuda",
    "Help.": "Ayuda.",
    "Converse": "Conversar",
    "Investigate": "Investigar",
    "Investigate.": "Investigar.",
    "Report": "Reportar",
    "Report.": "Reportar.",
    "Reject!": "Rechazo!",
    "Again.": "De nuevo.",
    "Again": "De nuevo",
    "Use.": "Usar.",
    "Do it.": "Hazlo.",
    "So?": "Y?",
    "Deal.": "Trato.",
    "Deal": "Trato",
    "Thanks.": "Gracias.",
    "Thanks": "Gracias",
    "Thanks!": "Gracias!",
    "Thank you.": "Gracias.",
    "Thank you": "Gracias",
    "Thank you!": "Gracias!",
    "Goodbye": "Adios",
    "Goodbye.": "Adios.",
    "Goodbye!": "Adios!",
    "Hello": "Hola",
    "Hello.": "Hola.",
    "Hello!": "Hola!",
    "Hello?": "Hola?",
    "Hey": "Oye",
    "Hey.": "Oye.",
    "Hey!": "Oye!",
    "Hi.": "Hola.",
    "Hi!": "Hola!",
    "Understood": "Entendido",
    "Understood.": "Entendido.",
    "Understood!": "Entendido!",
    "Got it.": "Entendido.",
    "Got it": "Entendido",
    "Got it!": "Entendido!",
    "Right.": "Correcto.",
    "Right": "Correcto",
    "Right!": "Correcto!",
    "Right?": "Verdad?",
    "Really?": "En serio?",
    "Really.": "De verdad.",
    "Really!": "De verdad!",
    "Really": "De verdad",
    "What?": "Que?",
    "What!": "Que!",
    "What?!": "Que?!",
    "Why?": "Por que?",
    "Who?": "Quien?",
    "How?": "Como?",
    "When?": "Cuando?",
    "Where?": "Donde?",
    "Huh?": "Eh?",
    "Huh.": "Eh.",
    "Hmm...": "Hmm...",
    "Hmm..": "Hmm..",
    "Hmm.": "Hmm.",
    "Hmm": "Hmm",
    "Hm..": "Hm..",
    "Hm...": "Hm...",
    "Hm.": "Hm.",
    "Hm?": "Hm?",
    "Hm": "Hm",
    "Well...": "Bueno...",
    "Well..": "Bueno..",
    "Well.": "Bueno.",
    "Alright.": "De acuerdo.",
    "Alright": "De acuerdo",
    "Alright!": "De acuerdo!",
    "Fine.": "Bien.",
    "Fine!": "Bien!",
    "Nothing.": "Nada.",
    "Nothing": "Nada",
    "Never mind.": "No importa.",
    "Never mind": "No importa",
    "Go on.": "Continua.",
    "Go on": "Continua",
    "I see.": "Ya veo.",
    "I see": "Ya veo",
    "I see..": "Ya veo..",
    "I see...": "Ya veo...",
    "Sorry.": "Lo siento.",
    "Sorry": "Lo siento",
    "Sorry!": "Lo siento!",
    "I'm sorry.": "Lo siento.",
    "I'm sorry": "Lo siento",
    "Good.": "Bien.",
    "Good!": "Bien!",
    "Good": "Bien",
    "Great.": "Genial.",
    "Great!": "Genial!",
    "Perfect.": "Perfecto.",
    "Perfect!": "Perfecto!",
    "Excellent!": "Excelente!",
    "Wonderful!": "Maravilloso!",
    "Amazing!": "Increible!",
    "Incredible!": "Increible!",
    "Impossible!": "Imposible!",
    "Impossible.": "Imposible.",
    "Unbelievable!": "Increible!",
    "Ridiculous!": "Ridiculo!",
    "Terrible!": "Terrible!",
    "Horrible!": "Horrible!",
    "Damn!": "Maldicion!",
    "Damn.": "Maldicion.",
    "Damn it!": "Maldita sea!",
    "Damn it.": "Maldita sea.",
    "Darn!": "Rayos!",
    "Darn it.": "Rayos.",
    "Darn it!": "Rayos!",
    "Ugh.": "Ugh.",
    "Ugh!": "Ugh!",
    "Argh!": "Argh!",
    "Gasp!": "Ah!",
    "Ahem.": "Ejem.",
    "Phew.": "Uf.",
    "Phew!": "Uf!",
    "Oops.": "Ups.",
    "Oops!": "Ups!",
    "Ouch!": "Auch!",
    "Wow!": "Wow!",
    "Wow.": "Wow.",
    "Oh!": "Oh!",
    "Oh.": "Oh.",
    "Oh?": "Oh?",
    "Oh no!": "Oh no!",
    "Ah.": "Ah.",
    "Ah!": "Ah!",
    "Ah?": "Ah?",
    "Ah...": "Ah...",
    "Ah..": "Ah..",
    "Sigh.": "Suspiro.",
    "Sigh...": "Suspiro...",
    "Tch.": "Tch.",
    "Tch!": "Tch!",
    "Tch...": "Tch...",
    "Humph.": "Hmph.",
    "Hmph.": "Hmph.",
    "Hmph!": "Hmph!",
    "Haha.": "Jaja.",
    "Hahaha.": "Jajaja.",
    "Hahaha!": "Jajaja!",
    "Hoho.": "Jojo.",
    "Hehe.": "Jeje.",
    "Heh.": "Je.",
    "Heh!": "Je!",
    "Heehee.": "Jejeje.",
    "Eek!": "Eek!",
    "Kyah!": "Kyah!",
    "Grr!": "Grr!",
    "Grr...": "Grr...",
    "Let's go.": "Vamos.",
    "Let's go!": "Vamos!",
    "Let's begin.": "Comencemos.",
    "Let's start.": "Empecemos.",
    "Hurry!": "Apurate!",
    "Hurry up!": "Apurate!",
    "Run!": "Corre!",
    "Wait!": "Espera!",
    "Wait.": "Espera.",
    "Wait": "Espera",
    "Wait here.": "Espera aqui.",
    "Come here.": "Ven aqui.",
    "Over here.": "Aqui.",
    "Follow me.": "Sigueme.",
    "Follow me!": "Sigueme!",
    "This way.": "Por aqui.",
    "Go ahead.": "Adelante.",
    "Get out!": "Sal de aqui!",
    "Get out.": "Sal de aqui.",
    "Go away!": "Vete!",
    "Go away.": "Vete.",
    "Stand back!": "Atras!",
    "Look out!": "Cuidado!",
    "Be careful.": "Ten cuidado.",
    "Be careful!": "Ten cuidado!",
    "Take care.": "Cuidate.",
    "Farewell.": "Hasta luego.",
    "Good luck.": "Buena suerte.",
    "Good luck!": "Buena suerte!",
    "Good bye.": "Adios.",
    "Of course.": "Por supuesto.",
    "Of course!": "Por supuesto!",
    "Of course": "Por supuesto",
    "Welcome.": "Bienvenido.",
    "Welcome!": "Bienvenido!",
    "I'm busy.": "Estoy ocupado.",
    "Too busy": "Muy ocupado",
    "It's nothing": "No es nada",
    "It's nothing.": "No es nada.",
    "It's okay.": "Esta bien.",
    "It's okay": "Esta bien",
    "It's fine.": "Esta bien.",
    "It's over.": "Se acabo.",
    "It's done.": "Esta hecho.",
    "It's true.": "Es verdad.",
    "It's a secret.": "Es un secreto.",
    "It's perfect!": "Es perfecto!",
    "It's a deal.": "Es un trato.",
    "Not yet.": "Todavia no.",
    "Not yet": "Todavia no",
    "Not really.": "No realmente.",
    "Not at all.": "Para nada.",
    "Please.": "Por favor.",
    "Please!": "Por favor!",
    "Please continue.": "Por favor continua.",
    "Please stop.": "Por favor detente.",
    "I understand.": "Entiendo.",
    "I don't know.": "No se.",
    "I don't know": "No se",
    "I'm ready.": "Estoy listo.",
    "I'm fine.": "Estoy bien.",
    "I'm here.": "Estoy aqui.",
    "I'll do it.": "Lo hare.",
    "I'll try.": "Lo intentare.",
    "I'll go.": "Ire.",
    "I'll help.": "Ayudare.",
    "As you wish.": "Como desees.",
    "Good morning.": "Buenos dias.",
    "Good afternoon.": "Buenas tardes.",
    "Good evening.": "Buenas noches.",
    "Good night.": "Buenas noches.",
    "Come in.": "Entra.",
    "Come in!": "Entra!",
    "Come back later.": "Vuelve despues.",
    "See you later.": "Nos vemos.",
    "See you.": "Nos vemos.",
    "Don't worry.": "No te preocupes.",
    "Don't worry!": "No te preocupes!",
    "Don't worry about it.": "No te preocupes por eso.",
    "Me?": "Yo?",
    "Me.": "Yo.",
    "Me!": "Yo!",
    "You?": "Tu?",
    "You.": "Tu.",
    "Him?": "El?",
    "Her?": "Ella?",
    "Who are you?": "Quien eres?",
    "What is that?": "Que es eso?",
    "What is this?": "Que es esto?",
    "What happened?": "Que paso?",
    "What do you mean?": "Que quieres decir?",
    "What do you want?": "Que quieres?",
    "What are you doing?": "Que estas haciendo?",
    "What should I do?": "Que deberia hacer?",
    "How dare you!": "Como te atreves!",
    "How could you!": "Como pudiste!",
    "How is that possible?": "Como es eso posible?",
    "It can't be!": "No puede ser!",
    "It can't be.": "No puede ser.",
    "That's right.": "Asi es.",
    "That's true.": "Es verdad.",
    "That's enough.": "Es suficiente.",
    "That's good.": "Eso esta bien.",
    "That's great!": "Eso es genial!",
    "That's terrible.": "Eso es terrible.",
    "That's strange.": "Eso es extrano.",
    "That's interesting.": "Eso es interesante.",
    "That's impossible.": "Eso es imposible.",
    "That was close.": "Eso estuvo cerca.",
    "Is that so?": "Es asi?",
    "Is that true?": "Es eso cierto?",
    "Is that all?": "Es todo?",
    "Are you sure?": "Estas seguro?",
    "Are you ready?": "Estas listo?",
    "Are you okay?": "Estas bien?",
    "Are you alright?": "Estas bien?",
    "Are you hurt?": "Estas herido?",
    "Here you go.": "Aqui tienes.",
    "Here it is.": "Aqui esta.",
    "There you go.": "Ahi tienes.",
    "Open door.": "Abrir puerta.",
    "Go in.": "Entrar.",
    "Go outside.": "Salir.",
    "Break it.": "Romperlo.",
    "Trade goods.": "Intercambiar bienes.",
    "I was joking.": "Estaba bromeando.",
    "Stop it.": "Detente.",
    "Stop it!": "Detente!",
    "Shut up!": "Callate!",
    "Shut up.": "Callate.",
    "Listen.": "Escucha.",
    "Listen!": "Escucha!",
    "Look.": "Mira.",
    "Look!": "Mira!",
    "Look here.": "Mira aqui.",
    "Come on.": "Vamos.",
    "Come on!": "Vamos!",
    "Move!": "Muevete!",
    "Enough!": "Suficiente!",
    "Enough.": "Suficiente.",
    "No way!": "De ninguna manera!",
    "No way.": "De ninguna manera.",
    "No problem.": "No hay problema.",
    "No thanks.": "No gracias.",
    "That's all.": "Eso es todo.",
    "I'm in! I'm in!": "Me apunto! Me apunto!",
    "Let me take a rain check.": "Dejemoslo para otro dia.",
    "I'm messing with you. Breathe.": "Te estoy molestando. Respira.",
    "It's a long story.": "Es una larga historia.",
    "As I was saying...": "Como decia...",
    "In any case...": "En cualquier caso...",
    "Well then.": "Pues entonces.",
    "Well then...": "Pues entonces...",
    "I mean...": "Quiero decir...",
    "Anyway...": "En fin...",
    "Anyway.": "En fin.",
    "Anyway": "En fin",
    "Indeed.": "En efecto.",
    "Indeed!": "En efecto!",
    "Exactly.": "Exactamente.",
    "Exactly!": "Exactamente!",
    "Absolutely.": "Absolutamente.",
    "Absolutely!": "Absolutamente!",
    "Certainly.": "Por supuesto.",
    "Naturally.": "Naturalmente.",
    "Obviously.": "Obviamente.",
    "Perhaps.": "Quizas.",
    "Maybe.": "Tal vez.",
    "Probably.": "Probablemente.",
    "What about it?": "Que hay con eso?",
    "What about you?": "Y tu?",
    "And you?": "Y tu?",
    "And then?": "Y luego?",
    "So what?": "Y que?",
    "Like what?": "Como que?",
    "For example?": "Por ejemplo?",
    "I think so.": "Creo que si.",
    "I don't think so.": "No creo.",
    "I hope so.": "Eso espero.",
    "I doubt it.": "Lo dudo.",
    "I forgot.": "Lo olvide.",
    "I remember.": "Recuerdo.",
    "I remember now.": "Ahora recuerdo.",
    "I know.": "Lo se.",
    "I agree.": "Estoy de acuerdo.",
    "It's nothing.": "No es nada.",
    " I don't want to!": " No quiero!",
    "I don't want to!": "No quiero!",
}

def tr(text):
    """Main translation function."""
    if not text or not text.strip():
        return text

    t = text.strip()

    # Pure punctuation
    if all(c in '.!?*~-() \t\r\n' for c in t):
        return text

    # Preserve leading/trailing whitespace
    ws_before = text[:len(text) - len(text.lstrip())]
    ws_after = text[len(text.rstrip()):]

    # Exact match
    if t in EXACT:
        return ws_before + EXACT[t] + ws_after

    # Handle color codes
    if '^' in t and re.search(r'\^[0-9a-fA-F]{6}', t):
        parts = re.split(r'(\^[0-9a-fA-F]{6})', t)
        result = []
        for part in parts:
            if re.match(r'^\^[0-9a-fA-F]{6}$', part):
                result.append(part)
            elif part.strip() in EXACT:
                result.append(EXACT[part.strip()])
            else:
                result.append(translate_sentence(part))
        return ws_before + ''.join(result) + ws_after

    # Sentence-level translation
    translated = translate_sentence(t)
    return ws_before + translated + ws_after

def translate_sentence(text):
    """Translate a sentence using comprehensive rules."""
    if not text or not text.strip():
        return text

    t = text.strip()
    if not t:
        return text

    # Pure punctuation
    if all(c in '.!?*~-() \t' for c in t):
        return text

    # Check exact match first
    if t in EXACT:
        return EXACT[t]

    # ================================================================
    # COMPREHENSIVE SENTENCE-LEVEL TRANSLATIONS
    # ================================================================

    result = t

    # Apply ordered replacement rules
    # Longest patterns first to avoid conflicts

    # ---- SENTENCE STARTERS ----
    patterns = [
        # Negative contractions
        (r"^I don't know ", "No se "),
        (r"^I don't think ", "No creo "),
        (r"^I don't want ", "No quiero "),
        (r"^I don't have ", "No tengo "),
        (r"^I don't need ", "No necesito "),
        (r"^I don't understand", "No entiendo"),
        (r"^I don't remember", "No recuerdo"),
        (r"^I don't care", "No me importa"),
        (r"^I don't mind", "No me importa"),
        (r"^I don't like", "No me gusta"),
        (r"^I don't believe", "No creo"),
        (r"^I don't see", "No veo"),
        (r"^I don't ", "No "),

        (r"^You don't have to ", "No tienes que "),
        (r"^You don't need to ", "No necesitas "),
        (r"^You don't have ", "No tienes "),
        (r"^You don't know ", "No sabes "),
        (r"^You don't understand", "No entiendes"),
        (r"^You don't seem ", "No pareces "),
        (r"^You don't look ", "No pareces "),
        (r"^You don't ", "No "),

        (r"^We don't have ", "No tenemos "),
        (r"^We don't know ", "No sabemos "),
        (r"^We don't need ", "No necesitamos "),
        (r"^We don't ", "No "),

        (r"^They don't ", "Ellos no "),
        (r"^He doesn't ", "El no "),
        (r"^She doesn't ", "Ella no "),
        (r"^It doesn't ", "No "),

        (r"^Don't worry", "No te preocupes"),
        (r"^Don't forget", "No olvides"),
        (r"^Don't tell", "No le digas"),
        (r"^Don't be ", "No seas "),
        (r"^Don't do ", "No hagas "),
        (r"^Don't come ", "No vengas "),
        (r"^Don't go ", "No vayas "),
        (r"^Don't touch", "No toques"),
        (r"^Don't move", "No te muevas"),
        (r"^Don't ", "No "),

        # I'm patterns
        (r"^I'm not sure", "No estoy seguro"),
        (r"^I'm not ", "No estoy "),
        (r"^I'm sorry", "Lo siento"),
        (r"^I'm glad", "Me alegra"),
        (r"^I'm happy", "Estoy feliz"),
        (r"^I'm fine", "Estoy bien"),
        (r"^I'm okay", "Estoy bien"),
        (r"^I'm ready", "Estoy listo"),
        (r"^I'm here", "Estoy aqui"),
        (r"^I'm sure", "Estoy seguro"),
        (r"^I'm afraid", "Me temo"),
        (r"^I'm going", "Voy"),
        (r"^I'm coming", "Ya voy"),
        (r"^I'm looking", "Estoy buscando"),
        (r"^I'm waiting", "Estoy esperando"),
        (r"^I'm telling", "Te estoy diciendo"),
        (r"^I'm saying", "Estoy diciendo"),
        (r"^I'm talking", "Estoy hablando"),
        (r"^I'm just ", "Solo estoy "),
        (r"^I'm ", "Soy "),

        # I + verb
        (r"^I was ", "Yo estaba "),
        (r"^I will ", "Voy a "),
        (r"^I'll ", "Voy a "),
        (r"^I would ", "Yo "),
        (r"^I'd ", "Yo "),
        (r"^I should ", "Deberia "),
        (r"^I could ", "Podria "),
        (r"^I can ", "Puedo "),
        (r"^I can't ", "No puedo "),
        (r"^I couldn't ", "No pude "),
        (r"^I won't ", "No voy a "),
        (r"^I wouldn't ", "No "),
        (r"^I shouldn't ", "No deberia "),
        (r"^I wasn't ", "No estaba "),
        (r"^I haven't ", "No he "),
        (r"^I've been ", "He estado "),
        (r"^I've ", "He "),
        (r"^I had ", "Tenia "),
        (r"^I have to ", "Tengo que "),
        (r"^I need to ", "Necesito "),
        (r"^I want to ", "Quiero "),
        (r"^I have ", "Tengo "),
        (r"^I need ", "Necesito "),
        (r"^I want ", "Quiero "),
        (r"^I know ", "Se "),
        (r"^I think ", "Creo "),
        (r"^I believe ", "Creo "),
        (r"^I heard ", "Escuche "),
        (r"^I found ", "Encontre "),
        (r"^I saw ", "Vi "),
        (r"^I got ", "Obtuve "),
        (r"^I told ", "Le dije "),
        (r"^I said ", "Dije "),
        (r"^I asked ", "Pregunte "),
        (r"^I came ", "Vine "),
        (r"^I went ", "Fui "),
        (r"^I hope ", "Espero "),
        (r"^I wish ", "Deseo "),
        (r"^I guess ", "Supongo "),
        (r"^I remember ", "Recuerdo "),
        (r"^I forgot ", "Olvide "),
        (r"^I tried ", "Intente "),
        (r"^I feel ", "Siento "),
        (r"^I understand", "Entiendo"),
        (r"^I agree", "Estoy de acuerdo"),
        (r"^I ", "Yo "),

        # You patterns
        (r"^You're not ", "No eres "),
        (r"^You're ", "Eres "),
        (r"^You are not ", "No eres "),
        (r"^You are ", "Eres "),
        (r"^You have to ", "Tienes que "),
        (r"^You have been ", "Has estado "),
        (r"^You have ", "Tienes "),
        (r"^You've been ", "Has estado "),
        (r"^You've ", "Has "),
        (r"^You can't ", "No puedes "),
        (r"^You can ", "Puedes "),
        (r"^You will ", "Vas a "),
        (r"^You'll ", "Vas a "),
        (r"^You should ", "Deberias "),
        (r"^You could ", "Podrias "),
        (r"^You would ", ""),
        (r"^You'd ", ""),
        (r"^You must ", "Debes "),
        (r"^You need to ", "Necesitas "),
        (r"^You need ", "Necesitas "),
        (r"^You want to ", "Quieres "),
        (r"^You want ", "Quieres "),
        (r"^You know ", "Sabes "),
        (r"^You seem ", "Pareces "),
        (r"^You look ", "Pareces "),
        (r"^You may ", "Puedes "),
        (r"^You might ", "Podrias "),
        (r"^You were ", "Estabas "),
        (r"^You ", "Tu "),

        # We patterns
        (r"^We're not ", "No estamos "),
        (r"^We're ", "Estamos "),
        (r"^We are not ", "No estamos "),
        (r"^We are ", "Estamos "),
        (r"^We have to ", "Tenemos que "),
        (r"^We have ", "Tenemos "),
        (r"^We've ", "Hemos "),
        (r"^We will ", "Vamos a "),
        (r"^We'll ", "Vamos a "),
        (r"^We can't ", "No podemos "),
        (r"^We can ", "Podemos "),
        (r"^We should ", "Deberiamos "),
        (r"^We could ", "Podriamos "),
        (r"^We need to ", "Necesitamos "),
        (r"^We need ", "Necesitamos "),
        (r"^We want to ", "Queremos "),
        (r"^We want ", "Queremos "),
        (r"^We must ", "Debemos "),
        (r"^We also ", "Tambien "),
        (r"^We ", "Nosotros "),

        # They/He/She/It patterns
        (r"^They're not ", "Ellos no son "),
        (r"^They're ", "Ellos son "),
        (r"^They are ", "Ellos son "),
        (r"^They have ", "Ellos tienen "),
        (r"^They've ", "Han "),
        (r"^They will ", "Ellos van a "),
        (r"^They'll ", "Ellos van a "),
        (r"^They can ", "Ellos pueden "),
        (r"^They can't ", "Ellos no pueden "),
        (r"^They were ", "Ellos estaban "),
        (r"^They ", "Ellos "),
        (r"^He's not ", "El no es "),
        (r"^He's ", "El es "),
        (r"^He is ", "El es "),
        (r"^He was ", "El estaba "),
        (r"^He will ", "El va a "),
        (r"^He has ", "El tiene "),
        (r"^He can ", "El puede "),
        (r"^He ", "El "),
        (r"^She's not ", "Ella no es "),
        (r"^She's ", "Ella es "),
        (r"^She is ", "Ella es "),
        (r"^She was ", "Ella estaba "),
        (r"^She will ", "Ella va a "),
        (r"^She has ", "Ella tiene "),
        (r"^She can ", "Ella puede "),
        (r"^She ", "Ella "),
        (r"^It's not ", "No es "),
        (r"^It's ", "Es "),
        (r"^It is ", "Es "),
        (r"^It was ", "Fue "),
        (r"^It will ", "Va a "),
        (r"^It can ", "Puede "),
        (r"^It seems ", "Parece "),

        # There patterns
        (r"^There is no ", "No hay "),
        (r"^There are no ", "No hay "),
        (r"^There's no ", "No hay "),
        (r"^There is nothing", "No hay nada"),
        (r"^There's nothing", "No hay nada"),
        (r"^There is a ", "Hay un "),
        (r"^There are ", "Hay "),
        (r"^There is ", "Hay "),
        (r"^There's a ", "Hay un "),
        (r"^There's ", "Hay "),
        (r"^There was ", "Habia "),
        (r"^There were ", "Habia "),

        # That/This patterns
        (r"^That's not ", "Eso no es "),
        (r"^That's ", "Eso es "),
        (r"^That is ", "Eso es "),
        (r"^That was ", "Eso fue "),
        (r"^This is ", "Esto es "),
        (r"^This was ", "Esto fue "),

        # Question patterns
        (r"^What is ", "Que es "),
        (r"^What are ", "Que son "),
        (r"^What was ", "Que fue "),
        (r"^What were ", "Que fueron "),
        (r"^What do you ", "Que "),
        (r"^What did you ", "Que "),
        (r"^What happened", "Que paso"),
        (r"^What about ", "Que hay de "),
        (r"^What if ", "Que pasa si "),
        (r"^What kind of ", "Que tipo de "),
        (r"^What ", "Que "),
        (r"^Where is ", "Donde esta "),
        (r"^Where are ", "Donde estan "),
        (r"^Where did ", "Donde "),
        (r"^Where do ", "Donde "),
        (r"^Where ", "Donde "),
        (r"^When is ", "Cuando es "),
        (r"^When did ", "Cuando "),
        (r"^When ", "Cuando "),
        (r"^Who is ", "Quien es "),
        (r"^Who are ", "Quienes son "),
        (r"^Who was ", "Quien era "),
        (r"^Who ", "Quien "),
        (r"^Why is ", "Por que es "),
        (r"^Why are ", "Por que "),
        (r"^Why did ", "Por que "),
        (r"^Why do ", "Por que "),
        (r"^Why would ", "Por que "),
        (r"^Why ", "Por que "),
        (r"^How is ", "Como esta "),
        (r"^How are ", "Como estan "),
        (r"^How did ", "Como "),
        (r"^How do ", "Como "),
        (r"^How can ", "Como puede "),
        (r"^How could ", "Como podria "),
        (r"^How about ", "Que tal si "),
        (r"^How long ", "Cuanto tiempo "),
        (r"^How many ", "Cuantos "),
        (r"^How much ", "Cuanto "),
        (r"^How ", "Como "),

        # Can/Could/Would/Should/Must/May/Might questions
        (r"^Can you ", "Puedes "),
        (r"^Can I ", "Puedo "),
        (r"^Can we ", "Podemos "),
        (r"^Could you ", "Podrias "),
        (r"^Could I ", "Podria "),
        (r"^Would you ", "Podrias "),
        (r"^Should I ", "Deberia "),
        (r"^Should we ", "Deberiamos "),
        (r"^Must I ", "Debo "),
        (r"^May I ", "Puedo "),
        (r"^Shall we ", "Deberiamos "),
        (r"^Will you ", "Vas a "),

        # Is/Are/Was/Were questions
        (r"^Is it ", "Es "),
        (r"^Is this ", "Es esto "),
        (r"^Is that ", "Es eso "),
        (r"^Is there ", "Hay "),
        (r"^Are you ", "Estas "),
        (r"^Are there ", "Hay "),
        (r"^Are we ", "Estamos "),
        (r"^Was it ", "Fue "),
        (r"^Were you ", "Estabas "),
        (r"^Isn't it ", "No es "),
        (r"^Isn't that ", "No es eso "),
        (r"^Aren't you ", "No estas "),

        # Do/Did questions
        (r"^Do you ", "Tu "),
        (r"^Do we ", "Nosotros "),
        (r"^Did you ", "Tu "),
        (r"^Didn't you ", "No "),
        (r"^Didn't I ", "No "),
        (r"^Does it ", "Eso "),
        (r"^Does he ", "El "),
        (r"^Does she ", "Ella "),
        (r"^Do not ", "No "),
        (r"^Did not ", "No "),

        # Have you
        (r"^Have you ", "Has "),
        (r"^Haven't you ", "No has "),
        (r"^Has it ", "Ha "),
        (r"^Has he ", "El ha "),
        (r"^Has she ", "Ella ha "),

        # Let's
        (r"^Let's not ", "No "),
        (r"^Let's go ", "Vamos "),
        (r"^Let's ", "Vamos a "),
        (r"^Let me ", "Dejame "),

        # Other starters
        (r"^Please ", "Por favor "),
        (r"^Thank you for ", "Gracias por "),
        (r"^Thanks for ", "Gracias por "),
        (r"^Sorry for ", "Perdon por "),
        (r"^Sorry, ", "Perdon, "),
        (r"^Excuse me", "Disculpa"),
        (r"^Pardon me", "Disculpa"),
        (r"^However, ", "Sin embargo, "),
        (r"^However ", "Sin embargo "),
        (r"^Although ", "Aunque "),
        (r"^Because ", "Porque "),
        (r"^Therefore, ", "Por lo tanto, "),
        (r"^Therefore ", "Por lo tanto "),
        (r"^Meanwhile, ", "Mientras tanto, "),
        (r"^Meanwhile ", "Mientras tanto "),
        (r"^Perhaps ", "Quizas "),
        (r"^Maybe ", "Tal vez "),
        (r"^Probably ", "Probablemente "),
        (r"^Actually, ", "En realidad, "),
        (r"^Actually ", "En realidad "),
        (r"^Unfortunately, ", "Desafortunadamente, "),
        (r"^Unfortunately ", "Desafortunadamente "),
        (r"^Fortunately, ", "Afortunadamente, "),
        (r"^Luckily, ", "Por suerte, "),
        (r"^Honestly, ", "Honestamente, "),
        (r"^Honestly ", "Honestamente "),
        (r"^Truthfully ", "La verdad "),
        (r"^Basically ", "Basicamente "),
        (r"^Basically, ", "Basicamente, "),
        (r"^Suddenly, ", "De repente, "),
        (r"^Suddenly ", "De repente "),
        (r"^Finally, ", "Finalmente, "),
        (r"^Finally ", "Finalmente "),
        (r"^Recently ", "Recientemente "),
        (r"^Apparently, ", "Aparentemente, "),
        (r"^Apparently ", "Aparentemente "),
        (r"^Obviously, ", "Obviamente, "),
        (r"^Obviously ", "Obviamente "),
        (r"^Certainly, ", "Por supuesto, "),
        (r"^Especially ", "Especialmente "),
        (r"^First of all, ", "Primero que nada, "),
        (r"^First, ", "Primero, "),
        (r"^First ", "Primero "),
        (r"^Second, ", "Segundo, "),
        (r"^Third, ", "Tercero, "),
        (r"^Next, ", "Luego, "),
        (r"^Next ", "Luego "),
        (r"^Then, ", "Entonces, "),
        (r"^Then ", "Entonces "),
        (r"^Now, ", "Ahora, "),
        (r"^Now ", "Ahora "),
        (r"^Well, ", "Bueno, "),
        (r"^Well ", "Bueno "),
        (r"^Oh, ", "Oh, "),
        (r"^Oh ", "Oh "),
        (r"^Ah, ", "Ah, "),
        (r"^Ah ", "Ah "),
        (r"^Hmm, ", "Hmm, "),
        (r"^So, ", "Entonces, "),
        (r"^So ", "Entonces "),
        (r"^But ", "Pero "),
        (r"^And ", "Y "),
        (r"^Or ", "O "),
        (r"^Also, ", "Ademas, "),
        (r"^Also ", "Tambien "),
        (r"^Still, ", "Aun asi, "),
        (r"^Still ", "Todavia "),
        (r"^Even ", "Incluso "),
        (r"^Just ", "Solo "),
        (r"^Only ", "Solo "),
        (r"^Never ", "Nunca "),
        (r"^Always ", "Siempre "),
        (r"^No wonder ", "Con razon "),
        (r"^In fact, ", "De hecho, "),
        (r"^In fact ", "De hecho "),
        (r"^In that case, ", "En ese caso, "),
        (r"^In other words, ", "En otras palabras, "),
        (r"^In any case, ", "En cualquier caso, "),
        (r"^In the end, ", "Al final, "),
        (r"^In the meantime, ", "Mientras tanto, "),
        (r"^For now, ", "Por ahora, "),
        (r"^For now ", "Por ahora "),
        (r"^At least ", "Al menos "),
        (r"^At first, ", "Al principio, "),
        (r"^At first ", "Al principio "),
        (r"^After all, ", "Despues de todo, "),
        (r"^After all ", "Despues de todo "),
        (r"^Of course, ", "Por supuesto, "),
        (r"^Of course ", "Por supuesto "),
        (r"^By the way, ", "Por cierto, "),
        (r"^By the way ", "Por cierto "),
        (r"^As expected, ", "Como era de esperar, "),
        (r"^As expected ", "Como era de esperar "),
        (r"^As I said, ", "Como dije, "),
        (r"^As you know, ", "Como sabes, "),
        (r"^As you can see, ", "Como puedes ver, "),
        (r"^To be honest, ", "Para ser honesto, "),
        (r"^No matter ", "No importa "),
        (r"^Needless to say, ", "No hace falta decir que, "),
        (r"^Anyway, ", "De todos modos, "),
        (r"^Anyway ", "De todos modos "),
        (r"^Right now ", "Ahora mismo "),
        (r"^Right now, ", "Ahora mismo, "),
        (r"^Right now", "Ahora mismo"),
        (r"^From now on, ", "De ahora en adelante, "),
        (r"^From now on ", "De ahora en adelante "),
        (r"^One more thing, ", "Una cosa mas, "),
        (r"^Once more, ", "Una vez mas, "),
        (r"^Once again, ", "Una vez mas, "),
        (r"^Huh, ", "Hmm, "),
        (r"^Huh\? ", "Eh? "),
        (r"^If you ", "Si "),
        (r"^If we ", "Si "),
        (r"^If I ", "Si yo "),
        (r"^If it ", "Si "),
        (r"^If that ", "Si eso "),
        (r"^If this ", "Si esto "),
        (r"^If so, ", "Si es asi, "),
        (r"^If not, ", "Si no, "),
        (r"^Even if ", "Aunque "),
        (r"^Even so, ", "Aun asi, "),
        (r"^No one ", "Nadie "),
        (r"^Nobody ", "Nadie "),
        (r"^Someone ", "Alguien "),
        (r"^Somebody ", "Alguien "),
        (r"^Anyone ", "Alguien "),
        (r"^Anybody ", "Alguien "),
        (r"^Everyone ", "Todos "),
        (r"^Everybody ", "Todos "),
        (r"^Everything ", "Todo "),
        (r"^Something ", "Algo "),
        (r"^Anything ", "Cualquier cosa "),
        (r"^Nothing ", "Nada "),
    ]

    for pattern, replacement in patterns:
        m = re.match(pattern, result)
        if m:
            result = replacement + result[m.end():]
            break

    # ---- WORD-LEVEL REPLACEMENTS (applied throughout the string) ----
    word_replacements = [
        # Common multi-word phrases (order matters - longer first)
        ("right now", "ahora mismo"),
        ("right here", "justo aqui"),
        ("right away", "de inmediato"),
        ("right there", "justo ahi"),
        ("a long time", "mucho tiempo"),
        ("a little bit", "un poco"),
        ("a little", "un poco"),
        ("a lot of", "muchos"),
        ("a lot", "mucho"),
        ("at all", "en absoluto"),
        ("at least", "al menos"),
        ("at first", "al principio"),
        ("at last", "al fin"),
        ("at once", "de inmediato"),
        ("of course", "por supuesto"),
        ("in front of", "frente a"),
        ("in order to", "para"),
        ("in the end", "al final"),
        ("so far", "hasta ahora"),
        ("so much", "tanto"),
        ("so many", "tantos"),
        ("no longer", "ya no"),
        ("no more", "no mas"),
        ("no one", "nadie"),
        ("not yet", "todavia no"),
        ("not only", "no solo"),
        ("each other", "el uno al otro"),
        ("once more", "una vez mas"),
        ("once again", "una vez mas"),
        ("more than", "mas que"),
        ("less than", "menos que"),
        ("such a", "tal"),
        ("kind of", "tipo de"),
        ("sort of", "tipo de"),
        ("instead of", "en lugar de"),
        ("in spite of", "a pesar de"),
        ("because of", "debido a"),
        ("thanks to", "gracias a"),
        ("next to", "junto a"),
        ("close to", "cerca de"),
        ("far from", "lejos de"),
        ("get out", "sal"),
        ("get rid of", "deshacerse de"),
        ("get back", "regresar"),
        ("come back", "regresa"),
        ("go back", "regresar"),
        ("go on", "continua"),
        ("go ahead", "adelante"),
        ("give up", "rendirse"),
        ("give me", "dame"),
        ("tell me", "dime"),
        ("show me", "muestrame"),
        ("let me", "dejame"),
        ("help me", "ayudame"),
        ("believe me", "creeme"),
        ("excuse me", "disculpa"),
        ("follow me", "sigueme"),
        ("trust me", "confio en mi"),
        ("listen to me", "escuchame"),
        ("wait for me", "esperame"),
        ("look at", "mira"),
        ("look for", "busca"),
        ("look like", "parece"),
        ("looks like", "parece"),
        ("take care", "cuidate"),
        ("take a look", "echa un vistazo"),
        ("find out", "descubrir"),
        ("figure out", "descifrar"),
        ("turn out", "resultar"),
        ("work out", "resolver"),
        ("carry out", "llevar a cabo"),
        ("point out", "senalar"),
        ("run away", "huir"),
        ("get away", "escapar"),
        ("pick up", "recoger"),
        ("set up", "preparar"),
        ("wake up", "despertar"),
        ("stand up", "levantarse"),
        ("shut up", "callate"),
        ("hurry up", "apurate"),
        ("ended up", "termino"),
        ("gave up", "se rindio"),
        ("turned out", "resulto"),
        ("found out", "descubrio"),
        ("as soon as", "tan pronto como"),
        ("as well", "tambien"),
        ("as much as", "tanto como"),
        ("as long as", "mientras"),
        ("even though", "aunque"),
        ("even if", "aunque"),
        ("by the way", "por cierto"),
        ("on the other hand", "por otro lado"),
        ("after all", "despues de todo"),
        ("for a while", "por un rato"),
        ("for now", "por ahora"),
        ("by now", "para ahora"),
        ("up to", "hasta"),
        ("used to", "solia"),
        ("able to", "capaz de"),
        ("about to", "a punto de"),
        ("supposed to", "se supone que"),
        ("allowed to", "permitido"),
        ("going to", "va a"),
        ("want to", "quieres"),
        ("need to", "necesitas"),
        ("have to", "tienes que"),
        ("has to", "tiene que"),
        ("had to", "tuvo que"),
        ("ought to", "deberia"),
        ("according to", "segun"),
        ("belongs to", "pertenece a"),
        ("belong to", "pertenecer a"),

        # Common RPG terms
        ("excavation team", "equipo de excavacion"),
        ("excavation site", "sitio de excavacion"),
        ("excavation", "excavacion"),
        ("adventurer", "aventurero"),
        ("adventurers", "aventureros"),
        ("Memory Record", "Registro de Memoria"),
        ("Memory Records", "Registros de Memoria"),
        ("record player", "tocadiscos"),
        ("Record Player", "Tocadiscos"),
        ("Eden Group", "Grupo Eden"),

        # Standalone common words (be careful with short words)
        ("however", "sin embargo"),
        ("although", "aunque"),
        ("because", "porque"),
        ("therefore", "por lo tanto"),
        ("meanwhile", "mientras tanto"),
        ("perhaps", "quizas"),
        ("probably", "probablemente"),
        ("apparently", "aparentemente"),
        ("unfortunately", "desafortunadamente"),
        ("fortunately", "afortunadamente"),
        ("honestly", "honestamente"),
        ("actually", "en realidad"),
        ("really", "realmente"),
        ("already", "ya"),
        ("finally", "finalmente"),
        ("suddenly", "de repente"),
        ("immediately", "inmediatamente"),
        ("quickly", "rapidamente"),
        ("slowly", "lentamente"),
        ("carefully", "cuidadosamente"),
        ("certainly", "ciertamente"),
        ("exactly", "exactamente"),
        ("especially", "especialmente"),
        ("recently", "recientemente"),
        ("obviously", "obviamente"),
        ("basically", "basicamente"),
        ("absolutely", "absolutamente"),
        ("completely", "completamente"),
        ("definitely", "definitivamente"),
        ("seriously", "en serio"),
        ("currently", "actualmente"),
        ("originally", "originalmente"),
        ("apparently", "aparentemente"),
        ("eventually", "eventualmente"),
        ("essentially", "esencialmente"),
        ("previously", "previamente"),
        ("approximately", "aproximadamente"),
        ("necessarily", "necesariamente"),
        ("desperately", "desesperadamente"),
        ("constantly", "constantemente"),
        ("extremely", "extremadamente"),
        ("incredibly", "increiblemente"),
        ("particularly", "particularmente"),
        ("perfectly", "perfectamente"),
        ("literally", "literalmente"),

        ("dangerous", "peligroso"),
        ("important", "importante"),
        ("impossible", "imposible"),
        ("possible", "posible"),
        ("powerful", "poderoso"),
        ("strange", "extrano"),
        ("beautiful", "hermoso"),
        ("terrible", "terrible"),
        ("wonderful", "maravilloso"),
        ("different", "diferente"),
        ("difficult", "dificil"),
        ("suspicious", "sospechoso"),
        ("surprised", "sorprendido"),
        ("interesting", "interesante"),
        ("mysterious", "misterioso"),
        ("necessary", "necesario"),
        ("obvious", "obvio"),
        ("original", "original"),
        ("familiar", "familiar"),
        ("similar", "similar"),

        ("everyone", "todos"),
        ("someone", "alguien"),
        ("anyone", "alguien"),
        ("everything", "todo"),
        ("something", "algo"),
        ("anything", "algo"),
        ("nothing", "nada"),
        ("nobody", "nadie"),
        ("somewhere", "en algun lugar"),
        ("anywhere", "en cualquier lugar"),
        ("everywhere", "en todos lados"),
        ("nowhere", "en ningun lugar"),

        ("monsters", "monstruos"),
        ("monster", "monstruo"),
        ("enemies", "enemigos"),
        ("enemy", "enemigo"),
        ("warriors", "guerreros"),
        ("warrior", "guerrero"),
        ("soldiers", "soldados"),
        ("soldier", "soldado"),
        ("guards", "guardias"),
        ("guard", "guardia"),
        ("citizens", "ciudadanos"),
        ("friends", "amigos"),
        ("friend", "amigo"),
        ("weapons", "armas"),
        ("weapon", "arma"),
        ("treasure", "tesoro"),
        ("village", "aldea"),
        ("kingdom", "reino"),
        ("castle", "castillo"),
        ("dungeon", "mazmorra"),
        ("reward", "recompensa"),
        ("battle", "batalla"),
        ("merchant", "comerciante"),
        ("captain", "capitan"),
        ("commander", "comandante"),
        ("leader", "lider"),
        ("children", "ninos"),
        ("family", "familia"),
        ("father", "padre"),
        ("mother", "madre"),
        ("brother", "hermano"),
        ("sister", "hermana"),
        ("daughter", "hija"),
        ("husband", "esposo"),
        ("wife", "esposa"),
        ("people", "gente"),
        ("person", "persona"),
        ("doctor", "doctor"),
        ("master", "maestro"),

        ("please", "por favor"),
        ("enough", "suficiente"),
        ("together", "juntos"),
        ("forever", "para siempre"),
        ("outside", "afuera"),
        ("inside", "adentro"),
        ("behind", "detras"),
        ("between", "entre"),
        ("against", "contra"),
        ("without", "sin"),
        ("before", "antes"),
        ("after", "despues"),
        ("during", "durante"),
        ("around", "alrededor"),
        ("toward", "hacia"),
        ("towards", "hacia"),
        ("through", "a traves de"),
        ("across", "al otro lado de"),
        ("until", "hasta"),
        ("since", "desde"),
        ("never", "nunca"),
        ("always", "siempre"),
        ("sometimes", "a veces"),
        ("still", "todavia"),
        ("again", "de nuevo"),
        ("about", "sobre"),

        ("thank you", "gracias"),
        ("sorry", "lo siento"),
        ("welcome", "bienvenido"),
    ]

    for eng, spa in word_replacements:
        if eng in result:
            # Use word boundary for short words to avoid partial matches
            if len(eng) <= 4:
                result = re.sub(r'\b' + re.escape(eng) + r'\b', spa, result)
            else:
                result = result.replace(eng, spa)

    return result

def generate_map():
    """Generate translation_map.txt from all strings."""
    strings = load_strings()
    lines = []
    translated = 0
    unchanged = 0

    for s in strings:
        t = tr(s)
        if t != s:
            translated += 1
        else:
            unchanged += 1
        lines.append(f"{s}|||{t}")

    with open(os.path.join(BASEDIR, 'translation_map.txt'), 'w', encoding='utf-8') as f:
        for line in lines:
            f.write(line + '\n')

    print(f"Generated translation_map.txt")
    print(f"  Translated: {translated}")
    print(f"  Unchanged: {unchanged}")
    print(f"  Total: {len(strings)}")

if __name__ == '__main__':
    generate_map()
